
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Nov 27 2025 03:17:10

// Verification Directory fv/FPU_unit 

module COMP_4bit(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_3, n_4, n_6, n_7, n_9, n_10, n_11, n_16;
  wire n_17, n_21, n_24, n_29, n_30, n_34, n_36, n_38;
  wire n_43, n_44, n_48, n_50, n_52, n_53, n_55, n_60;
  wire n_65, n_69, n_74, n_75, n_76, n_77, n_78, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  not g1 (n_3, i_data_a[3]);
  not g2 (n_4, i_data_a[2]);
  and g3 (n_6, n_3, n_4);
  not g4 (n_7, i_data_a[1]);
  and g5 (n_9, n_6, n_7);
  not g6 (n_10, i_data_a[0]);
  and g7 (n_11, n_9, n_10);
  and g8 (n_16, n_11, i_data_b[0]);
  and g11 (n_17, n_9, i_data_b[1]);
  and g14 (n_21, n_6, i_data_b[2]);
  and g16 (n_24, n_3, i_data_b[3]);
  and g23 (n_30, n_3, n_7);
  and g29 (n_36, n_30, i_data_b[2]);
  and g30 (n_38, n_36, i_data_b[1]);
  and g37 (n_44, n_4, n_7);
  and g43 (n_50, n_44, i_data_b[3]);
  and g44 (n_52, n_50, i_data_b[1]);
  and g46 (n_53, n_4, i_data_b[3]);
  and g47 (n_55, n_53, i_data_b[2]);
  xor g70 (n_75, i_data_a[0], i_data_b[0]);
  xor g71 (n_76, i_data_a[1], i_data_b[1]);
  xor g72 (n_77, i_data_a[2], i_data_b[2]);
  xor g73 (n_78, i_data_a[3], i_data_b[3]);
  nor g74 (o_equal, n_78, n_77, n_76, n_75);
  or g75 (n_81, n_16, n_17, n_21, n_24);
  or g76 (n_82, n_29, n_34, n_38, n_43);
  or g77 (n_83, n_48, n_52, n_55, n_60);
  or g78 (n_84, n_65, n_69, n_74);
  or g79 (o_less, n_81, n_82, n_83, n_84);
  and g80 (n_29, n_6, n_10, i_data_b[1], i_data_b[0]);
  and g81 (n_34, n_30, n_10, i_data_b[2], i_data_b[0]);
  and g82 (n_85, n_3, n_10);
  and g83 (n_43, i_data_b[2], i_data_b[1], i_data_b[0], n_85);
  and g84 (n_48, n_44, n_10, i_data_b[3], i_data_b[0]);
  and g85 (n_86, n_4, n_10);
  and g86 (n_60, i_data_b[3], i_data_b[1], i_data_b[0], n_86);
  and g87 (n_87, n_7, n_10);
  and g88 (n_65, i_data_b[3], i_data_b[2], i_data_b[0], n_87);
  and g89 (n_69, n_7, i_data_b[3], i_data_b[2], i_data_b[1]);
  and g90 (n_88, n_10, i_data_b[3]);
  and g91 (n_74, i_data_b[2], i_data_b[1], i_data_b[0], n_88);
endmodule

module COMP_8bit_SIZE_DATA8(i_data_a, i_data_b, o_less);
  input [7:0] i_data_a, i_data_b;
  output o_less;
  wire [7:0] i_data_a, i_data_b;
  wire o_less;
  wire n_17, w_equal_high, w_equal_low, w_less_high, w_less_low;
  COMP_4bit u_low(.i_data_a (i_data_a[3:0]), .i_data_b (i_data_b[3:0]),
       .o_less (w_less_low), .o_equal (w_equal_low));
  COMP_4bit u_high(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_high), .o_equal (w_equal_high));
  and g1 (n_17, w_equal_high, w_less_low);
  or g2 (o_less, w_less_high, n_17);
endmodule

module EXP_comp_SIZE_DATA8(i_data_a, i_data_b, o_compare);
  input [7:0] i_data_a, i_data_b;
  output o_compare;
  wire [7:0] i_data_a, i_data_b;
  wire o_compare;
  COMP_8bit_SIZE_DATA8 COMP_LESS_UNIT(.i_data_a (i_data_a), .i_data_b
       (i_data_b), .o_less (o_compare));
endmodule

module bmux(ctl, in_0, in_1, z);
  input ctl;
  input [7:0] in_0, in_1;
  output [7:0] z;
  wire ctl;
  wire [7:0] in_0, in_1;
  wire [7:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module EXP_swap_SIZE_DATA8(i_data_a, i_data_b, i_compare, o_less_data,
     o_greater_data);
  input [7:0] i_data_a, i_data_b;
  input i_compare;
  output [7:0] o_less_data, o_greater_data;
  wire [7:0] i_data_a, i_data_b;
  wire i_compare;
  wire [7:0] o_less_data, o_greater_data;
  bmux mux_11_27(.ctl (i_compare), .in_0 (i_data_a), .in_1 (i_data_b),
       .z (o_greater_data));
  bmux mux_12_27(.ctl (i_compare), .in_0 (i_data_b), .in_1 (i_data_a),
       .z (o_less_data));
endmodule

module CLA_4bit(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire [3:0] w_p;
  wire [3:0] w_g;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_17;
  wire n_19, n_21, n_22, n_23, n_25, n_27, n_29, n_32;
  wire n_34, n_41, n_42, \w_c[1] , \w_c[2] , \w_c[3] ;
  and g3 (n_9, w_p[0], cin);
  or g4 (\w_c[1] , w_g[0], n_9);
  and g5 (n_10, w_p[1], w_g[0]);
  or g6 (n_12, w_g[1], n_10);
  and g7 (n_11, w_p[1], w_p[0]);
  and g8 (n_13, n_11, cin);
  or g9 (\w_c[2] , n_12, n_13);
  and g10 (n_14, w_p[2], w_g[1]);
  and g12 (n_15, w_p[2], w_p[1]);
  and g13 (n_17, n_15, w_g[0]);
  and g16 (n_19, n_15, w_p[0]);
  and g17 (n_21, n_19, cin);
  and g21 (n_22, w_p[3], w_g[2]);
  and g23 (n_23, w_p[3], w_p[2]);
  and g24 (n_25, n_23, w_g[1]);
  and g27 (n_27, n_23, w_p[1]);
  and g28 (n_29, n_27, w_g[0]);
  and g32 (n_32, n_27, w_p[0]);
  and g33 (n_34, n_32, cin);
  and g1 (w_g[0], a[0], b[0]);
  and g35 (w_g[1], a[1], b[1]);
  and g36 (w_g[2], a[2], b[2]);
  and g37 (w_g[3], a[3], b[3]);
  xor g38 (w_p[0], a[0], b[0]);
  xor g2 (w_p[1], a[1], b[1]);
  xor g39 (w_p[2], a[2], b[2]);
  xor g40 (w_p[3], a[3], b[3]);
  xor g41 (sum[0], w_p[0], cin);
  xor g42 (sum[1], w_p[1], \w_c[1] );
  xor g43 (sum[2], w_p[2], \w_c[2] );
  xor g44 (sum[3], w_p[3], \w_c[3] );
  nand g45 (n_41, w_p[3], w_p[2], w_p[1], w_p[0]);
  not g46 (o_p, n_41);
  or g47 (\w_c[3] , w_g[2], n_14, n_17, n_21);
  or g48 (n_42, w_g[3], n_22);
  or g49 (o_g, n_25, n_29, n_34, n_42);
endmodule

module CLA_8bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire n_18, n_23, w_C, w_G, w_G_22, w_P, w_P_20;
  CLA_4bit CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]), .cin
       (i_carry), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
  CLA_4bit CLA_4BIT_UNIT_1(.a (i_data_a[7:4]), .b (i_data_b[7:4]), .cin
       (w_C), .sum (o_sum[7:4]), .o_p (w_P_20), .o_g (w_G_22));
  and g1 (n_18, w_P, i_carry);
  or g2 (w_C, w_G, n_18);
  and g5 (n_23, w_P_20, w_C);
  or g6 (o_carry, w_G_22, n_23);
endmodule

module not_op(A, Z);
  input [7:0] A;
  output [7:0] Z;
  wire [7:0] A;
  wire [7:0] Z;
  not g1 (Z[7], A[7]);
  not g2 (Z[6], A[6]);
  not g3 (Z[5], A[5]);
  not g4 (Z[4], A[4]);
  not g5 (Z[3], A[3]);
  not g6 (Z[2], A[2]);
  not g7 (Z[1], A[1]);
  not g8 (Z[0], A[0]);
endmodule

module EXP_sub_SIZE_EXP_SUB8(i_data_a, i_data_b, o_sub);
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sub;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sub;
  wire [7:0] w_data_b;
  wire UNCONNECTED;
  CLA_8bit CLA_8BIT_UNIT(.i_carry (1'b1), .i_data_a (i_data_a),
       .i_data_b (w_data_b), .o_sum (o_sub), .o_carry (UNCONNECTED));
  not_op g1(.A (i_data_b), .Z (w_data_b));
endmodule

module bmux_2(ctl, in_0, in_1, z);
  input ctl;
  input [23:0] in_0, in_1;
  output [23:0] z;
  wire ctl;
  wire [23:0] in_0, in_1;
  wire [23:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[23]), .data1 (in_1[23]), .z
       (z[23]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[22]), .data1 (in_1[22]), .z
       (z[22]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[21]), .data1 (in_1[21]), .z
       (z[21]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[20]), .data1 (in_1[20]), .z
       (z[20]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[19]), .data1 (in_1[19]), .z
       (z[19]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[18]), .data1 (in_1[18]), .z
       (z[18]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[17]), .data1 (in_1[17]), .z
       (z[17]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[16]), .data1 (in_1[16]), .z
       (z[16]));
  CDN_bmux2 g9(.sel0 (ctl), .data0 (in_0[15]), .data1 (in_1[15]), .z
       (z[15]));
  CDN_bmux2 g10(.sel0 (ctl), .data0 (in_0[14]), .data1 (in_1[14]), .z
       (z[14]));
  CDN_bmux2 g11(.sel0 (ctl), .data0 (in_0[13]), .data1 (in_1[13]), .z
       (z[13]));
  CDN_bmux2 g12(.sel0 (ctl), .data0 (in_0[12]), .data1 (in_1[12]), .z
       (z[12]));
  CDN_bmux2 g13(.sel0 (ctl), .data0 (in_0[11]), .data1 (in_1[11]), .z
       (z[11]));
  CDN_bmux2 g14(.sel0 (ctl), .data0 (in_0[10]), .data1 (in_1[10]), .z
       (z[10]));
  CDN_bmux2 g15(.sel0 (ctl), .data0 (in_0[9]), .data1 (in_1[9]), .z
       (z[9]));
  CDN_bmux2 g16(.sel0 (ctl), .data0 (in_0[8]), .data1 (in_1[8]), .z
       (z[8]));
  CDN_bmux2 g17(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g18(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g19(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g20(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g21(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g22(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g23(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g24(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module MAN_swap_SIZE_MAN24(i_man_a, i_man_b, i_compare, o_man_max,
     o_man_min);
  input [23:0] i_man_a, i_man_b;
  input i_compare;
  output [23:0] o_man_max, o_man_min;
  wire [23:0] i_man_a, i_man_b;
  wire i_compare;
  wire [23:0] o_man_max, o_man_min;
  bmux_2 mux_12_23(.ctl (i_compare), .in_0 (i_man_b), .in_1 (i_man_a),
       .z (o_man_min));
  bmux_2 mux_11_23(.ctl (i_compare), .in_0 (i_man_a), .in_1 (i_man_b),
       .z (o_man_max));
endmodule

module bmux_4(ctl, in_0, in_1, z);
  input ctl;
  input [31:0] in_0, in_1;
  output [31:0] z;
  wire ctl;
  wire [31:0] in_0, in_1;
  wire [31:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[31]), .data1 (in_1[31]), .z
       (z[31]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[30]), .data1 (in_1[30]), .z
       (z[30]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[29]), .data1 (in_1[29]), .z
       (z[29]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[28]), .data1 (in_1[28]), .z
       (z[28]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[27]), .data1 (in_1[27]), .z
       (z[27]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[26]), .data1 (in_1[26]), .z
       (z[26]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[25]), .data1 (in_1[25]), .z
       (z[25]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[24]), .data1 (in_1[24]), .z
       (z[24]));
  CDN_bmux2 g9(.sel0 (ctl), .data0 (in_0[23]), .data1 (in_1[23]), .z
       (z[23]));
  CDN_bmux2 g10(.sel0 (ctl), .data0 (in_0[22]), .data1 (in_1[22]), .z
       (z[22]));
  CDN_bmux2 g11(.sel0 (ctl), .data0 (in_0[21]), .data1 (in_1[21]), .z
       (z[21]));
  CDN_bmux2 g12(.sel0 (ctl), .data0 (in_0[20]), .data1 (in_1[20]), .z
       (z[20]));
  CDN_bmux2 g13(.sel0 (ctl), .data0 (in_0[19]), .data1 (in_1[19]), .z
       (z[19]));
  CDN_bmux2 g14(.sel0 (ctl), .data0 (in_0[18]), .data1 (in_1[18]), .z
       (z[18]));
  CDN_bmux2 g15(.sel0 (ctl), .data0 (in_0[17]), .data1 (in_1[17]), .z
       (z[17]));
  CDN_bmux2 g16(.sel0 (ctl), .data0 (in_0[16]), .data1 (in_1[16]), .z
       (z[16]));
  CDN_bmux2 g17(.sel0 (ctl), .data0 (in_0[15]), .data1 (in_1[15]), .z
       (z[15]));
  CDN_bmux2 g18(.sel0 (ctl), .data0 (in_0[14]), .data1 (in_1[14]), .z
       (z[14]));
  CDN_bmux2 g19(.sel0 (ctl), .data0 (in_0[13]), .data1 (in_1[13]), .z
       (z[13]));
  CDN_bmux2 g20(.sel0 (ctl), .data0 (in_0[12]), .data1 (in_1[12]), .z
       (z[12]));
  CDN_bmux2 g21(.sel0 (ctl), .data0 (in_0[11]), .data1 (in_1[11]), .z
       (z[11]));
  CDN_bmux2 g22(.sel0 (ctl), .data0 (in_0[10]), .data1 (in_1[10]), .z
       (z[10]));
  CDN_bmux2 g23(.sel0 (ctl), .data0 (in_0[9]), .data1 (in_1[9]), .z
       (z[9]));
  CDN_bmux2 g24(.sel0 (ctl), .data0 (in_0[8]), .data1 (in_1[8]), .z
       (z[8]));
  CDN_bmux2 g25(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g26(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g27(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g28(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g29(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g30(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g31(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g32(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module SHF_right_SIZE_DATA32_SIZE_SHIFT5(i_shift_number, i_data,
     o_data);
  input [4:0] i_shift_number;
  input [31:0] i_data;
  output [31:0] o_data;
  wire [4:0] i_shift_number;
  wire [31:0] i_data;
  wire [31:0] o_data;
  wire [31:0] \stage[1] ;
  wire [31:0] \stage[2] ;
  wire [31:0] \stage[3] ;
  wire [31:0] \stage[4] ;
  bmux_4 mux_18_33(.ctl (i_shift_number[0]), .in_0 (i_data), .in_1
       ({1'b0, i_data[31:1]}), .z ({\stage[1] [31], \stage[1] [30],
       \stage[1] [29], \stage[1] [28], \stage[1] [27], \stage[1] [26],
       \stage[1] [25], \stage[1] [24], \stage[1] [23], \stage[1] [22],
       \stage[1] [21], \stage[1] [20], \stage[1] [19], \stage[1] [18],
       \stage[1] [17], \stage[1] [16], \stage[1] [15], \stage[1] [14],
       \stage[1] [13], \stage[1] [12], \stage[1] [11], \stage[1] [10],
       \stage[1] [9], \stage[1] [8], \stage[1] [7], \stage[1] [6],
       \stage[1] [5], \stage[1] [4], \stage[1] [3], \stage[1] [2],
       \stage[1] [1], \stage[1] [0]}));
  bmux_4 mux_18_6(.ctl (i_shift_number[1]), .in_0 ({\stage[1] [31],
       \stage[1] [30], \stage[1] [29], \stage[1] [28], \stage[1] [27],
       \stage[1] [26], \stage[1] [25], \stage[1] [24], \stage[1] [23],
       \stage[1] [22], \stage[1] [21], \stage[1] [20], \stage[1] [19],
       \stage[1] [18], \stage[1] [17], \stage[1] [16], \stage[1] [15],
       \stage[1] [14], \stage[1] [13], \stage[1] [12], \stage[1] [11],
       \stage[1] [10], \stage[1] [9], \stage[1] [8], \stage[1] [7],
       \stage[1] [6], \stage[1] [5], \stage[1] [4], \stage[1] [3],
       \stage[1] [2], \stage[1] [1], \stage[1] [0]}), .in_1 ({2'b00,
       \stage[1] [31], \stage[1] [30], \stage[1] [29], \stage[1] [28],
       \stage[1] [27], \stage[1] [26], \stage[1] [25], \stage[1] [24],
       \stage[1] [23], \stage[1] [22], \stage[1] [21], \stage[1] [20],
       \stage[1] [19], \stage[1] [18], \stage[1] [17], \stage[1] [16],
       \stage[1] [15], \stage[1] [14], \stage[1] [13], \stage[1] [12],
       \stage[1] [11], \stage[1] [10], \stage[1] [9], \stage[1] [8],
       \stage[1] [7], \stage[1] [6], \stage[1] [5], \stage[1] [4],
       \stage[1] [3], \stage[1] [2]}), .z ({\stage[2] [31],
       \stage[2] [30], \stage[2] [29], \stage[2] [28], \stage[2] [27],
       \stage[2] [26], \stage[2] [25], \stage[2] [24], \stage[2] [23],
       \stage[2] [22], \stage[2] [21], \stage[2] [20], \stage[2] [19],
       \stage[2] [18], \stage[2] [17], \stage[2] [16], \stage[2] [15],
       \stage[2] [14], \stage[2] [13], \stage[2] [12], \stage[2] [11],
       \stage[2] [10], \stage[2] [9], \stage[2] [8], \stage[2] [7],
       \stage[2] [6], \stage[2] [5], \stage[2] [4], \stage[2] [3],
       \stage[2] [2], \stage[2] [1], \stage[2] [0]}));
  bmux_4 mux_18_7(.ctl (i_shift_number[2]), .in_0 ({\stage[2] [31],
       \stage[2] [30], \stage[2] [29], \stage[2] [28], \stage[2] [27],
       \stage[2] [26], \stage[2] [25], \stage[2] [24], \stage[2] [23],
       \stage[2] [22], \stage[2] [21], \stage[2] [20], \stage[2] [19],
       \stage[2] [18], \stage[2] [17], \stage[2] [16], \stage[2] [15],
       \stage[2] [14], \stage[2] [13], \stage[2] [12], \stage[2] [11],
       \stage[2] [10], \stage[2] [9], \stage[2] [8], \stage[2] [7],
       \stage[2] [6], \stage[2] [5], \stage[2] [4], \stage[2] [3],
       \stage[2] [2], \stage[2] [1], \stage[2] [0]}), .in_1 ({4'b0000,
       \stage[2] [31], \stage[2] [30], \stage[2] [29], \stage[2] [28],
       \stage[2] [27], \stage[2] [26], \stage[2] [25], \stage[2] [24],
       \stage[2] [23], \stage[2] [22], \stage[2] [21], \stage[2] [20],
       \stage[2] [19], \stage[2] [18], \stage[2] [17], \stage[2] [16],
       \stage[2] [15], \stage[2] [14], \stage[2] [13], \stage[2] [12],
       \stage[2] [11], \stage[2] [10], \stage[2] [9], \stage[2] [8],
       \stage[2] [7], \stage[2] [6], \stage[2] [5], \stage[2] [4]}), .z
       ({\stage[3] [31], \stage[3] [30], \stage[3] [29], \stage[3]
       [28], \stage[3] [27], \stage[3] [26], \stage[3] [25],
       \stage[3] [24], \stage[3] [23], \stage[3] [22], \stage[3] [21],
       \stage[3] [20], \stage[3] [19], \stage[3] [18], \stage[3] [17],
       \stage[3] [16], \stage[3] [15], \stage[3] [14], \stage[3] [13],
       \stage[3] [12], \stage[3] [11], \stage[3] [10], \stage[3] [9],
       \stage[3] [8], \stage[3] [7], \stage[3] [6], \stage[3] [5],
       \stage[3] [4], \stage[3] [3], \stage[3] [2], \stage[3] [1],
       \stage[3] [0]}));
  bmux_4 mux_18_8(.ctl (i_shift_number[3]), .in_0 ({\stage[3] [31],
       \stage[3] [30], \stage[3] [29], \stage[3] [28], \stage[3] [27],
       \stage[3] [26], \stage[3] [25], \stage[3] [24], \stage[3] [23],
       \stage[3] [22], \stage[3] [21], \stage[3] [20], \stage[3] [19],
       \stage[3] [18], \stage[3] [17], \stage[3] [16], \stage[3] [15],
       \stage[3] [14], \stage[3] [13], \stage[3] [12], \stage[3] [11],
       \stage[3] [10], \stage[3] [9], \stage[3] [8], \stage[3] [7],
       \stage[3] [6], \stage[3] [5], \stage[3] [4], \stage[3] [3],
       \stage[3] [2], \stage[3] [1], \stage[3] [0]}), .in_1
       ({8'b00000000, \stage[3] [31], \stage[3] [30], \stage[3] [29],
       \stage[3] [28], \stage[3] [27], \stage[3] [26], \stage[3] [25],
       \stage[3] [24], \stage[3] [23], \stage[3] [22], \stage[3] [21],
       \stage[3] [20], \stage[3] [19], \stage[3] [18], \stage[3] [17],
       \stage[3] [16], \stage[3] [15], \stage[3] [14], \stage[3] [13],
       \stage[3] [12], \stage[3] [11], \stage[3] [10], \stage[3] [9],
       \stage[3] [8]}), .z ({\stage[4] [31], \stage[4] [30],
       \stage[4] [29], \stage[4] [28], \stage[4] [27], \stage[4] [26],
       \stage[4] [25], \stage[4] [24], \stage[4] [23], \stage[4] [22],
       \stage[4] [21], \stage[4] [20], \stage[4] [19], \stage[4] [18],
       \stage[4] [17], \stage[4] [16], \stage[4] [15], \stage[4] [14],
       \stage[4] [13], \stage[4] [12], \stage[4] [11], \stage[4] [10],
       \stage[4] [9], \stage[4] [8], \stage[4] [7], \stage[4] [6],
       \stage[4] [5], \stage[4] [4], \stage[4] [3], \stage[4] [2],
       \stage[4] [1], \stage[4] [0]}));
  bmux_4 mux_18_9(.ctl (i_shift_number[4]), .in_0 ({\stage[4] [31],
       \stage[4] [30], \stage[4] [29], \stage[4] [28], \stage[4] [27],
       \stage[4] [26], \stage[4] [25], \stage[4] [24], \stage[4] [23],
       \stage[4] [22], \stage[4] [21], \stage[4] [20], \stage[4] [19],
       \stage[4] [18], \stage[4] [17], \stage[4] [16], \stage[4] [15],
       \stage[4] [14], \stage[4] [13], \stage[4] [12], \stage[4] [11],
       \stage[4] [10], \stage[4] [9], \stage[4] [8], \stage[4] [7],
       \stage[4] [6], \stage[4] [5], \stage[4] [4], \stage[4] [3],
       \stage[4] [2], \stage[4] [1], \stage[4] [0]}), .in_1
       ({16'b0000000000000000, \stage[4] [31], \stage[4] [30],
       \stage[4] [29], \stage[4] [28], \stage[4] [27], \stage[4] [26],
       \stage[4] [25], \stage[4] [24], \stage[4] [23], \stage[4] [22],
       \stage[4] [21], \stage[4] [20], \stage[4] [19], \stage[4] [18],
       \stage[4] [17], \stage[4] [16]}), .z (o_data));
endmodule

module COMP_24bit_SIZE_DATA24(i_data_a, i_data_b, o_less);
  input [23:0] i_data_a, i_data_b;
  output o_less;
  wire [23:0] i_data_a, i_data_b;
  wire o_less;
  wire n_49, n_50, n_52, n_54, n_56, n_59, n_61, n_65;
  wire n_67, n_69, n_70, w_equal_0_0, w_equal_0_1, w_equal_0_2,
       w_equal_0_3, w_equal_0_4;
  wire w_equal_0_5, w_less_0_0, w_less_0_1, w_less_0_2, w_less_0_3,
       w_less_0_4, w_less_0_5;
  COMP_4bit u_i_data_0(.i_data_a (i_data_a[3:0]), .i_data_b
       (i_data_b[3:0]), .o_less (w_less_0_0), .o_equal (w_equal_0_0));
  COMP_4bit u_i_data_1(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_0_1), .o_equal (w_equal_0_1));
  COMP_4bit u_i_data_2(.i_data_a (i_data_a[11:8]), .i_data_b
       (i_data_b[11:8]), .o_less (w_less_0_2), .o_equal (w_equal_0_2));
  COMP_4bit u_i_data_3(.i_data_a (i_data_a[15:12]), .i_data_b
       (i_data_b[15:12]), .o_less (w_less_0_3), .o_equal (w_equal_0_3));
  COMP_4bit u_i_data_4(.i_data_a (i_data_a[19:16]), .i_data_b
       (i_data_b[19:16]), .o_less (w_less_0_4), .o_equal (w_equal_0_4));
  COMP_4bit u_i_data_5(.i_data_a (i_data_a[23:20]), .i_data_b
       (i_data_b[23:20]), .o_less (w_less_0_5), .o_equal (w_equal_0_5));
  and g1 (n_49, w_equal_0_5, w_less_0_4);
  and g3 (n_50, w_equal_0_5, w_equal_0_4);
  and g4 (n_52, n_50, w_less_0_3);
  and g7 (n_54, n_50, w_equal_0_3);
  and g8 (n_56, n_54, w_less_0_2);
  and g12 (n_59, n_54, w_equal_0_2);
  and g13 (n_61, n_59, w_less_0_1);
  and g18 (n_65, n_59, w_equal_0_1);
  and g19 (n_67, n_65, w_less_0_0);
  or g21 (n_69, w_less_0_5, n_49);
  or g22 (n_70, n_52, n_56);
  or g23 (o_less, n_61, n_67, n_69, n_70);
endmodule

module SIGN_unit(i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b,
     o_sign_s);
  input i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b;
  output o_sign_s;
  wire i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b;
  wire o_sign_s;
  wire n_2, n_4, n_6, n_7, n_8, n_9, n_11, n_12;
  wire n_13;
  not g1 (n_2, i_add_sub);
  and g2 (n_4, n_2, i_sign_man_b);
  and g3 (n_8, n_4, i_comp_man);
  not g4 (n_6, i_sign_man_b);
  and g5 (n_7, i_add_sub, n_6);
  and g6 (n_9, n_7, i_comp_man);
  or g7 (n_12, n_8, n_9);
  not g8 (n_11, i_comp_man);
  and g9 (n_13, i_sign_man_a, n_11);
  or g10 (o_sign_s, n_12, n_13);
endmodule

module PSC_unit(i_add_sub, i_sign_a, i_exp_a, i_man_a, i_sign_b,
     i_exp_b, i_man_b, o_sel_exp, o_sel_man);
  input i_add_sub, i_sign_a, i_sign_b;
  input [7:0] i_exp_a, i_exp_b;
  input [23:0] i_man_a, i_man_b;
  output o_sel_exp;
  output [1:0] o_sel_man;
  wire i_add_sub, i_sign_a, i_sign_b;
  wire [7:0] i_exp_a, i_exp_b;
  wire [23:0] i_man_a, i_man_b;
  wire o_sel_exp;
  wire [1:0] o_sel_man;
  wire n_64, n_65, n_66, n_68, n_69, n_70, n_71, n_72;
  wire n_75, n_76, n_77, n_78, n_80, n_85, n_90, n_95;
  wire n_100, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, w_E_one_A, w_E_one_B, w_M_zero_A,
       w_M_zero_B;
  not g5 (n_64, i_sign_b);
  and g6 (n_65, n_64, w_E_one_B);
  not g7 (n_66, w_M_zero_B);
  and g8 (n_71, n_65, n_66);
  not g9 (n_68, i_sign_a);
  and g10 (n_69, n_68, w_E_one_A);
  not g11 (n_70, w_M_zero_A);
  and g12 (n_72, n_69, n_70);
  or g13 (n_75, n_71, n_72);
  or g17 (o_sel_exp, n_75, n_76);
  or g18 (o_sel_man[1], w_E_one_A, w_E_one_B);
  and g19 (n_77, w_E_one_B, n_66);
  and g20 (n_78, w_E_one_A, n_70);
  not g22 (n_80, i_add_sub);
  nand g1 (n_105, i_exp_a[7], i_exp_a[6], i_exp_a[5], i_exp_a[4]);
  nand g43 (n_104, i_exp_a[3], i_exp_a[2], i_exp_a[1], i_exp_a[0]);
  nor g44 (w_E_one_A, n_104, n_105);
  nand g45 (n_107, i_exp_b[7], i_exp_b[6], i_exp_b[5], i_exp_b[4]);
  nand g2 (n_106, i_exp_b[3], i_exp_b[2], i_exp_b[1], i_exp_b[0]);
  nor g46 (w_E_one_B, n_106, n_107);
  nor g47 (n_108, i_man_a[22], i_man_a[21], i_man_a[20], i_man_a[19]);
  nor g48 (n_109, i_man_a[18], i_man_a[17], i_man_a[16], i_man_a[15]);
  nor g3 (n_110, i_man_a[14], i_man_a[13], i_man_a[12], i_man_a[11]);
  nor g49 (n_111, i_man_a[10], i_man_a[9], i_man_a[8], i_man_a[7]);
  nor g50 (n_112, i_man_a[6], i_man_a[5], i_man_a[4], i_man_a[3]);
  nor g51 (n_113, i_man_a[2], i_man_a[1], i_man_a[0]);
  nand g52 (n_115, n_108, n_109, n_110, n_111);
  nand g53 (n_114, n_112, n_113);
  nor g54 (w_M_zero_A, n_114, n_115);
  nor g55 (n_116, i_man_b[22], i_man_b[21], i_man_b[20], i_man_b[19]);
  nor g56 (n_117, i_man_b[18], i_man_b[17], i_man_b[16], i_man_b[15]);
  nor g57 (n_118, i_man_b[14], i_man_b[13], i_man_b[12], i_man_b[11]);
  nor g4 (n_119, i_man_b[10], i_man_b[9], i_man_b[8], i_man_b[7]);
  nor g58 (n_120, i_man_b[6], i_man_b[5], i_man_b[4], i_man_b[3]);
  nor g59 (n_121, i_man_b[2], i_man_b[1], i_man_b[0]);
  nand g60 (n_123, n_116, n_117, n_118, n_119);
  nand g61 (n_122, n_120, n_121);
  nor g62 (w_M_zero_B, n_122, n_123);
  and g63 (n_76, w_E_one_A, w_M_zero_A, w_E_one_B, w_M_zero_B);
  or g64 (n_124, n_77, n_78);
  or g65 (n_125, n_85, n_90);
  or g66 (o_sel_man[0], n_95, n_100, n_124, n_125);
  and g67 (n_126, n_80, n_68);
  and g68 (n_85, w_E_one_A, i_sign_b, w_E_one_B, n_126);
  and g69 (n_127, n_80, i_sign_a);
  and g70 (n_90, w_E_one_A, n_64, w_E_one_B, n_127);
  and g71 (n_128, i_add_sub, n_68);
  and g72 (n_95, w_E_one_A, n_64, w_E_one_B, n_128);
  and g73 (n_129, i_add_sub, i_sign_a);
  and g74 (n_100, w_E_one_A, i_sign_b, w_E_one_B, n_129);
endmodule

module CLS_4bit(A, B, Bin, SUB, Bout);
  input [3:0] A, B;
  input Bin;
  output [3:0] SUB;
  output Bout;
  wire [3:0] A, B;
  wire Bin;
  wire [3:0] SUB;
  wire Bout;
  wire [3:0] b;
  or g1 (b[0], B[0], Bin);
  or g2 (b[1], B[1], b[0]);
  or g3 (b[2], B[2], b[1]);
  or g4 (Bout, B[3], b[2]);
  xor g6 (SUB[0], B[0], Bin);
  xor g7 (SUB[1], B[1], b[0]);
  xor g8 (SUB[2], B[2], b[1]);
  xor g9 (SUB[3], B[3], b[2]);
endmodule

module not_op_5(A, Z);
  input [23:0] A;
  output [23:0] Z;
  wire [23:0] A;
  wire [23:0] Z;
  not g1 (Z[23], A[23]);
  not g2 (Z[22], A[22]);
  not g3 (Z[21], A[21]);
  not g4 (Z[20], A[20]);
  not g5 (Z[19], A[19]);
  not g6 (Z[18], A[18]);
  not g7 (Z[17], A[17]);
  not g8 (Z[16], A[16]);
  not g9 (Z[15], A[15]);
  not g10 (Z[14], A[14]);
  not g11 (Z[13], A[13]);
  not g12 (Z[12], A[12]);
  not g13 (Z[11], A[11]);
  not g14 (Z[10], A[10]);
  not g15 (Z[9], A[9]);
  not g16 (Z[8], A[8]);
  not g17 (Z[7], A[7]);
  not g18 (Z[6], A[6]);
  not g19 (Z[5], A[5]);
  not g20 (Z[4], A[4]);
  not g21 (Z[3], A[3]);
  not g22 (Z[2], A[2]);
  not g23 (Z[1], A[1]);
  not g24 (Z[0], A[0]);
endmodule

module add_unsigned(A, B, Z);
  input [23:0] A, B;
  output [24:0] Z;
  wire [23:0] A, B;
  wire [24:0] Z;
  wire n_75, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201, n_202, n_203, n_204;
  wire n_205, n_206, n_207, n_208, n_209, n_210, n_211, n_212;
  wire n_213, n_214, n_215, n_216, n_217, n_218, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_231, n_232, n_233, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_252;
  wire n_253, n_254, n_255, n_256, n_257, n_258, n_259, n_260;
  wire n_261, n_262, n_263, n_264, n_265, n_266, n_267, n_268;
  wire n_269, n_270, n_271, n_272, n_273, n_274, n_275, n_276;
  wire n_277, n_278, n_279, n_280, n_281, n_282, n_283, n_284;
  wire n_285, n_286, n_287, n_288, n_289, n_290, n_291, n_292;
  wire n_293, n_294, n_295, n_296, n_297, n_298, n_299, n_300;
  wire n_301, n_302, n_303, n_304, n_305, n_306, n_307, n_308;
  wire n_309, n_310, n_311, n_312, n_313, n_314, n_315, n_316;
  wire n_317, n_318, n_319, n_320, n_321, n_322, n_323, n_324;
  wire n_325, n_326, n_327, n_328, n_329, n_330, n_331, n_332;
  wire n_333, n_334, n_335, n_336, n_337, n_338, n_339, n_340;
  wire n_341, n_342, n_343, n_344;
  xor g1 (Z[0], A[0], B[0]);
  nand g2 (n_75, A[0], B[0]);
  nor g6 (n_78, A[1], B[1]);
  nand g7 (n_81, A[1], B[1]);
  nor g8 (n_88, A[2], B[2]);
  nand g9 (n_83, A[2], B[2]);
  nor g10 (n_84, A[3], B[3]);
  nand g11 (n_85, A[3], B[3]);
  nor g12 (n_94, A[4], B[4]);
  nand g13 (n_89, A[4], B[4]);
  nor g14 (n_90, A[5], B[5]);
  nand g15 (n_91, A[5], B[5]);
  nor g16 (n_100, A[6], B[6]);
  nand g17 (n_95, A[6], B[6]);
  nor g18 (n_96, A[7], B[7]);
  nand g19 (n_97, A[7], B[7]);
  nor g20 (n_106, A[8], B[8]);
  nand g21 (n_101, A[8], B[8]);
  nor g22 (n_102, A[9], B[9]);
  nand g23 (n_103, A[9], B[9]);
  nor g24 (n_112, A[10], B[10]);
  nand g25 (n_107, A[10], B[10]);
  nor g26 (n_108, A[11], B[11]);
  nand g27 (n_109, A[11], B[11]);
  nor g28 (n_118, A[12], B[12]);
  nand g29 (n_113, A[12], B[12]);
  nor g30 (n_114, A[13], B[13]);
  nand g31 (n_115, A[13], B[13]);
  nor g32 (n_124, A[14], B[14]);
  nand g33 (n_119, A[14], B[14]);
  nor g34 (n_120, A[15], B[15]);
  nand g35 (n_121, A[15], B[15]);
  nor g36 (n_130, A[16], B[16]);
  nand g37 (n_125, A[16], B[16]);
  nor g38 (n_126, A[17], B[17]);
  nand g39 (n_127, A[17], B[17]);
  nor g40 (n_136, A[18], B[18]);
  nand g41 (n_131, A[18], B[18]);
  nor g42 (n_132, A[19], B[19]);
  nand g43 (n_133, A[19], B[19]);
  nor g44 (n_142, A[20], B[20]);
  nand g45 (n_137, A[20], B[20]);
  nor g46 (n_138, A[21], B[21]);
  nand g47 (n_139, A[21], B[21]);
  nor g48 (n_148, A[22], B[22]);
  nand g49 (n_143, A[22], B[22]);
  nor g50 (n_144, A[23], B[23]);
  nand g51 (n_145, A[23], B[23]);
  not g52 (n_80, n_78);
  nand g53 (n_82, n_79, n_80);
  nand g54 (n_149, n_81, n_82);
  nor g55 (n_86, n_83, n_84);
  not g56 (n_87, n_85);
  nor g57 (n_153, n_86, n_87);
  nor g58 (n_152, n_88, n_84);
  nor g59 (n_92, n_89, n_90);
  not g60 (n_93, n_91);
  nor g61 (n_155, n_92, n_93);
  nor g62 (n_158, n_94, n_90);
  nor g63 (n_98, n_95, n_96);
  not g64 (n_99, n_97);
  nor g65 (n_162, n_98, n_99);
  nor g66 (n_160, n_100, n_96);
  nor g67 (n_104, n_101, n_102);
  not g68 (n_105, n_103);
  nor g69 (n_165, n_104, n_105);
  nor g70 (n_168, n_106, n_102);
  nor g71 (n_110, n_107, n_108);
  not g72 (n_111, n_109);
  nor g73 (n_172, n_110, n_111);
  nor g74 (n_170, n_112, n_108);
  nor g75 (n_116, n_113, n_114);
  not g76 (n_117, n_115);
  nor g77 (n_175, n_116, n_117);
  nor g78 (n_178, n_118, n_114);
  nor g79 (n_122, n_119, n_120);
  not g80 (n_123, n_121);
  nor g81 (n_182, n_122, n_123);
  nor g82 (n_180, n_124, n_120);
  nor g83 (n_128, n_125, n_126);
  not g84 (n_129, n_127);
  nor g85 (n_185, n_128, n_129);
  nor g86 (n_188, n_130, n_126);
  nor g87 (n_134, n_131, n_132);
  not g88 (n_135, n_133);
  nor g89 (n_192, n_134, n_135);
  nor g90 (n_190, n_136, n_132);
  nor g91 (n_140, n_137, n_138);
  not g92 (n_141, n_139);
  nor g93 (n_195, n_140, n_141);
  nor g94 (n_198, n_142, n_138);
  nor g95 (n_146, n_143, n_144);
  not g96 (n_147, n_145);
  nor g97 (n_202, n_146, n_147);
  nor g98 (n_200, n_148, n_144);
  not g99 (n_150, n_88);
  nand g100 (n_151, n_149, n_150);
  nand g101 (n_294, n_83, n_151);
  nand g102 (n_154, n_152, n_149);
  nand g103 (n_205, n_153, n_154);
  nor g104 (n_156, n_100, n_155);
  not g105 (n_157, n_95);
  nor g106 (n_211, n_156, n_157);
  not g107 (n_159, n_100);
  nand g108 (n_209, n_158, n_159);
  not g109 (n_161, n_160);
  nor g110 (n_163, n_155, n_161);
  not g111 (n_164, n_162);
  nor g112 (n_215, n_163, n_164);
  nand g113 (n_213, n_158, n_160);
  nor g114 (n_166, n_112, n_165);
  not g115 (n_167, n_107);
  nor g116 (n_253, n_166, n_167);
  not g117 (n_169, n_112);
  nand g118 (n_251, n_168, n_169);
  not g119 (n_171, n_170);
  nor g120 (n_173, n_165, n_171);
  not g121 (n_174, n_172);
  nor g122 (n_217, n_173, n_174);
  nand g123 (n_220, n_168, n_170);
  nor g124 (n_176, n_124, n_175);
  not g125 (n_177, n_119);
  nor g126 (n_225, n_176, n_177);
  not g127 (n_179, n_124);
  nand g128 (n_224, n_178, n_179);
  not g129 (n_181, n_180);
  nor g130 (n_183, n_175, n_181);
  not g131 (n_184, n_182);
  nor g132 (n_229, n_183, n_184);
  nand g133 (n_228, n_178, n_180);
  nor g134 (n_186, n_136, n_185);
  not g135 (n_187, n_131);
  nor g136 (n_275, n_186, n_187);
  not g137 (n_189, n_136);
  nand g138 (n_273, n_188, n_189);
  not g139 (n_191, n_190);
  nor g140 (n_193, n_185, n_191);
  not g141 (n_194, n_192);
  nor g142 (n_232, n_193, n_194);
  nand g143 (n_235, n_188, n_190);
  nor g144 (n_196, n_148, n_195);
  not g145 (n_197, n_143);
  nor g146 (n_240, n_196, n_197);
  not g147 (n_199, n_148);
  nand g148 (n_239, n_198, n_199);
  not g149 (n_201, n_200);
  nor g150 (n_203, n_195, n_201);
  not g151 (n_204, n_202);
  nor g152 (n_244, n_203, n_204);
  nand g153 (n_243, n_198, n_200);
  not g154 (n_206, n_94);
  nand g155 (n_207, n_205, n_206);
  nand g156 (n_298, n_89, n_207);
  nand g157 (n_208, n_158, n_205);
  nand g158 (n_300, n_155, n_208);
  not g159 (n_210, n_209);
  nand g160 (n_212, n_205, n_210);
  nand g161 (n_303, n_211, n_212);
  not g162 (n_214, n_213);
  nand g163 (n_216, n_205, n_214);
  nand g164 (n_247, n_215, n_216);
  nor g165 (n_218, n_118, n_217);
  not g166 (n_219, n_113);
  nor g167 (n_258, n_218, n_219);
  nor g168 (n_257, n_118, n_220);
  not g169 (n_221, n_178);
  nor g170 (n_222, n_217, n_221);
  not g171 (n_223, n_175);
  nor g172 (n_261, n_222, n_223);
  nor g173 (n_260, n_220, n_221);
  nor g174 (n_226, n_224, n_217);
  not g175 (n_227, n_225);
  nor g176 (n_264, n_226, n_227);
  nor g177 (n_263, n_220, n_224);
  nor g178 (n_230, n_228, n_217);
  not g179 (n_231, n_229);
  nor g180 (n_267, n_230, n_231);
  nor g181 (n_266, n_220, n_228);
  nor g182 (n_233, n_142, n_232);
  not g183 (n_234, n_137);
  nor g184 (n_280, n_233, n_234);
  nor g185 (n_279, n_142, n_235);
  not g186 (n_236, n_198);
  nor g187 (n_237, n_232, n_236);
  not g188 (n_238, n_195);
  nor g189 (n_283, n_237, n_238);
  nor g190 (n_282, n_235, n_236);
  nor g191 (n_241, n_239, n_232);
  not g192 (n_242, n_240);
  nor g193 (n_286, n_241, n_242);
  nor g194 (n_285, n_235, n_239);
  nor g195 (n_245, n_243, n_232);
  not g196 (n_246, n_244);
  nor g197 (n_289, n_245, n_246);
  nor g198 (n_288, n_235, n_243);
  not g199 (n_248, n_106);
  nand g200 (n_249, n_247, n_248);
  nand g201 (n_307, n_101, n_249);
  nand g202 (n_250, n_168, n_247);
  nand g203 (n_309, n_165, n_250);
  not g204 (n_252, n_251);
  nand g205 (n_254, n_247, n_252);
  nand g206 (n_312, n_253, n_254);
  not g207 (n_255, n_220);
  nand g208 (n_256, n_247, n_255);
  nand g209 (n_315, n_217, n_256);
  nand g210 (n_259, n_257, n_247);
  nand g211 (n_318, n_258, n_259);
  nand g212 (n_262, n_260, n_247);
  nand g213 (n_320, n_261, n_262);
  nand g214 (n_265, n_263, n_247);
  nand g215 (n_323, n_264, n_265);
  nand g216 (n_268, n_266, n_247);
  nand g217 (n_269, n_267, n_268);
  not g218 (n_270, n_130);
  nand g219 (n_271, n_269, n_270);
  nand g220 (n_327, n_125, n_271);
  nand g221 (n_272, n_188, n_269);
  nand g222 (n_329, n_185, n_272);
  not g223 (n_274, n_273);
  nand g224 (n_276, n_269, n_274);
  nand g225 (n_332, n_275, n_276);
  not g226 (n_277, n_235);
  nand g227 (n_278, n_269, n_277);
  nand g228 (n_335, n_232, n_278);
  nand g229 (n_281, n_279, n_269);
  nand g230 (n_338, n_280, n_281);
  nand g231 (n_284, n_282, n_269);
  nand g232 (n_340, n_283, n_284);
  nand g233 (n_287, n_285, n_269);
  nand g234 (n_343, n_286, n_287);
  nand g235 (n_290, n_288, n_269);
  nand g236 (Z[24], n_289, n_290);
  nand g237 (n_291, n_80, n_81);
  xnor g238 (Z[1], n_79, n_291);
  nand g239 (n_292, n_150, n_83);
  xnor g240 (Z[2], n_149, n_292);
  not g241 (n_293, n_84);
  nand g242 (n_295, n_293, n_85);
  xnor g243 (Z[3], n_294, n_295);
  nand g244 (n_296, n_206, n_89);
  xnor g245 (Z[4], n_205, n_296);
  not g246 (n_297, n_90);
  nand g247 (n_299, n_297, n_91);
  xnor g248 (Z[5], n_298, n_299);
  nand g249 (n_301, n_159, n_95);
  xnor g250 (Z[6], n_300, n_301);
  not g251 (n_302, n_96);
  nand g252 (n_304, n_302, n_97);
  xnor g253 (Z[7], n_303, n_304);
  nand g254 (n_305, n_248, n_101);
  xnor g255 (Z[8], n_247, n_305);
  not g256 (n_306, n_102);
  nand g257 (n_308, n_306, n_103);
  xnor g258 (Z[9], n_307, n_308);
  nand g259 (n_310, n_169, n_107);
  xnor g260 (Z[10], n_309, n_310);
  not g261 (n_311, n_108);
  nand g262 (n_313, n_311, n_109);
  xnor g263 (Z[11], n_312, n_313);
  not g264 (n_314, n_118);
  nand g265 (n_316, n_314, n_113);
  xnor g266 (Z[12], n_315, n_316);
  not g267 (n_317, n_114);
  nand g268 (n_319, n_317, n_115);
  xnor g269 (Z[13], n_318, n_319);
  nand g270 (n_321, n_179, n_119);
  xnor g271 (Z[14], n_320, n_321);
  not g272 (n_322, n_120);
  nand g273 (n_324, n_322, n_121);
  xnor g274 (Z[15], n_323, n_324);
  nand g275 (n_325, n_270, n_125);
  xnor g276 (Z[16], n_269, n_325);
  not g277 (n_326, n_126);
  nand g278 (n_328, n_326, n_127);
  xnor g279 (Z[17], n_327, n_328);
  nand g280 (n_330, n_189, n_131);
  xnor g281 (Z[18], n_329, n_330);
  not g282 (n_331, n_132);
  nand g283 (n_333, n_331, n_133);
  xnor g284 (Z[19], n_332, n_333);
  not g285 (n_334, n_142);
  nand g286 (n_336, n_334, n_137);
  xnor g287 (Z[20], n_335, n_336);
  not g288 (n_337, n_138);
  nand g289 (n_339, n_337, n_139);
  xnor g290 (Z[21], n_338, n_339);
  nand g291 (n_341, n_199, n_143);
  xnor g292 (Z[22], n_340, n_341);
  not g293 (n_342, n_144);
  nand g294 (n_344, n_342, n_145);
  xnor g295 (Z[23], n_343, n_344);
  not g297 (n_79, n_75);
endmodule

module add_unsigned_10(A, B, Z);
  input [24:0] A;
  input B;
  output [24:0] Z;
  wire [24:0] A;
  wire B;
  wire [24:0] Z;
  wire n_53, n_81, n_84, n_86, n_90, n_92, n_96, n_98;
  wire n_102, n_104, n_108, n_110, n_114, n_116, n_120, n_122;
  wire n_126, n_128, n_132, n_134, n_138, n_140, n_144, n_146;
  wire n_150, n_151, n_153, n_154, n_156, n_160, n_162, n_170;
  wire n_172, n_180, n_182, n_190, n_192, n_200, n_202, n_207;
  wire n_209, n_210, n_211, n_212, n_214, n_215, n_216, n_218;
  wire n_222, n_223, n_226, n_230, n_237, n_238, n_241, n_245;
  wire n_249, n_251, n_252, n_253, n_254, n_256, n_257, n_258;
  wire n_259, n_261, n_262, n_264, n_265, n_267, n_268, n_270;
  wire n_276, n_278, n_280, n_281, n_282, n_283, n_285, n_286;
  wire n_287, n_288, n_290, n_291, n_293, n_294, n_296, n_297;
  wire n_302, n_305, n_309, n_311, n_314, n_318, n_320, n_323;
  wire n_326, n_329, n_331, n_334, n_338, n_340, n_343, n_346;
  wire n_349, n_351, n_354, n_356, n_357;
  xor g1 (Z[0], A[0], B);
  nand g2 (n_53, A[0], B);
  nand g55 (n_84, n_81, A[1]);
  nor g60 (n_154, n_90, n_86);
  nor g64 (n_160, n_96, n_92);
  nor g68 (n_162, n_102, n_98);
  nor g72 (n_170, n_108, n_104);
  nor g76 (n_172, n_114, n_110);
  nor g80 (n_180, n_120, n_116);
  nor g84 (n_182, n_126, n_122);
  nor g88 (n_190, n_132, n_128);
  nor g92 (n_192, n_138, n_134);
  nor g96 (n_200, n_144, n_140);
  nor g100 (n_202, n_150, n_146);
  nand g102 (n_153, n_151, A[2]);
  nand g104 (n_156, n_154, n_151);
  nand g110 (n_211, n_160, A[6]);
  nand g115 (n_215, n_160, n_162);
  nand g120 (n_253, n_170, A[10]);
  nand g125 (n_222, n_170, n_172);
  nand g130 (n_226, n_180, A[14]);
  nand g135 (n_230, n_180, n_182);
  nand g140 (n_282, n_190, A[18]);
  nand g145 (n_237, n_190, n_192);
  nand g150 (n_241, n_200, A[22]);
  nand g155 (n_245, n_200, n_202);
  nand g157 (n_209, n_207, A[4]);
  nand g159 (n_210, n_160, n_207);
  not g161 (n_212, n_211);
  nand g162 (n_214, n_207, n_212);
  not g164 (n_216, n_215);
  nand g165 (n_218, n_207, n_216);
  nor g170 (n_259, n_120, n_222);
  not g171 (n_223, n_180);
  nor g175 (n_262, n_222, n_223);
  nor g179 (n_265, n_222, n_226);
  nor g183 (n_268, n_222, n_230);
  nor g187 (n_288, n_144, n_237);
  not g188 (n_238, n_200);
  nor g192 (n_291, n_237, n_238);
  nor g196 (n_294, n_237, n_241);
  nor g200 (n_276, n_237, n_245);
  nand g202 (n_251, n_249, A[8]);
  nand g204 (n_252, n_170, n_249);
  not g206 (n_254, n_253);
  nand g207 (n_256, n_249, n_254);
  not g209 (n_257, n_222);
  nand g210 (n_258, n_249, n_257);
  nand g212 (n_261, n_259, n_249);
  nand g214 (n_264, n_262, n_249);
  nand g216 (n_267, n_265, n_249);
  nand g218 (n_270, n_268, n_249);
  nand g226 (n_280, n_278, A[16]);
  nand g228 (n_281, n_190, n_278);
  not g230 (n_283, n_282);
  nand g231 (n_285, n_278, n_283);
  not g233 (n_286, n_237);
  nand g234 (n_287, n_278, n_286);
  nand g236 (n_290, n_288, n_278);
  nand g238 (n_293, n_291, n_278);
  nand g240 (n_296, n_294, n_278);
  nand g242 (n_297, n_276, n_278);
  xnor g248 (Z[1], n_81, n_302);
  xnor g250 (Z[2], n_151, n_90);
  xnor g253 (Z[3], n_305, n_86);
  xnor g255 (Z[4], n_207, n_96);
  xnor g258 (Z[5], n_309, n_92);
  xnor g260 (Z[6], n_311, n_102);
  xnor g263 (Z[7], n_314, n_98);
  xnor g265 (Z[8], n_249, n_108);
  xnor g268 (Z[9], n_318, n_104);
  xnor g270 (Z[10], n_320, n_114);
  xnor g273 (Z[11], n_323, n_110);
  xnor g276 (Z[12], n_326, n_120);
  xnor g279 (Z[13], n_329, n_116);
  xnor g281 (Z[14], n_331, n_126);
  xnor g284 (Z[15], n_334, n_122);
  xnor g286 (Z[16], n_278, n_132);
  xnor g289 (Z[17], n_338, n_128);
  xnor g291 (Z[18], n_340, n_138);
  xnor g294 (Z[19], n_343, n_134);
  xnor g297 (Z[20], n_346, n_144);
  xnor g300 (Z[21], n_349, n_140);
  xnor g302 (Z[22], n_351, n_150);
  xnor g305 (Z[23], n_354, n_146);
  xnor g307 (Z[24], n_356, n_357);
  not g310 (n_90, A[2]);
  not g311 (n_86, A[3]);
  not g312 (n_96, A[4]);
  not g313 (n_92, A[5]);
  not g314 (n_102, A[6]);
  not g315 (n_98, A[7]);
  not g316 (n_108, A[8]);
  not g317 (n_104, A[9]);
  not g318 (n_114, A[10]);
  not g319 (n_110, A[11]);
  not g320 (n_120, A[12]);
  not g321 (n_116, A[13]);
  not g322 (n_126, A[14]);
  not g323 (n_122, A[15]);
  not g324 (n_132, A[16]);
  not g325 (n_128, A[17]);
  not g326 (n_138, A[18]);
  not g327 (n_134, A[19]);
  not g328 (n_144, A[20]);
  not g329 (n_140, A[21]);
  not g330 (n_150, A[22]);
  not g331 (n_146, A[23]);
  not g333 (n_81, n_53);
  not g334 (n_302, A[1]);
  not g335 (n_357, A[24]);
  not g336 (n_151, n_84);
  not g337 (n_305, n_153);
  not g338 (n_207, n_156);
  not g339 (n_309, n_209);
  not g340 (n_311, n_210);
  not g341 (n_314, n_214);
  not g342 (n_249, n_218);
  not g343 (n_318, n_251);
  not g344 (n_320, n_252);
  not g345 (n_323, n_256);
  not g346 (n_326, n_258);
  not g347 (n_329, n_261);
  not g348 (n_331, n_264);
  not g349 (n_334, n_267);
  not g350 (n_278, n_270);
  not g351 (n_338, n_280);
  not g352 (n_340, n_281);
  not g353 (n_343, n_285);
  not g354 (n_346, n_287);
  not g355 (n_349, n_290);
  not g356 (n_351, n_293);
  not g357 (n_354, n_296);
  not g358 (n_356, n_297);
endmodule

module bmux_11(ctl, in_0, in_1, z);
  input ctl, in_0, in_1;
  output z;
  wire ctl, in_0, in_1;
  wire z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0), .data1 (in_1), .z (z));
endmodule

module MAN_ALU_NUM_OP1_SIZE_MAN24(i_fpu_op, i_sign_a, i_sign_b,
     i_carry, i_man_max, i_man_min, o_man_alu, o_overflow);
  input [0:0] i_fpu_op;
  input i_sign_a, i_sign_b, i_carry;
  input [23:0] i_man_max, i_man_min;
  output [23:0] o_man_alu;
  output o_overflow;
  wire [0:0] i_fpu_op;
  wire i_sign_a, i_sign_b, i_carry;
  wire [23:0] i_man_max, i_man_min;
  wire [23:0] o_man_alu;
  wire o_overflow;
  wire [23:0] w_n_man_b;
  wire [23:0] w_i_man_b;
  wire n_3, n_4, n_33, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, w_i_carry_alu, w_i_fpu_op,
       w_overflow;
  not_op_5 g4(.A (i_man_min), .Z (w_n_man_b));
  add_unsigned add_36_52(.A (i_man_max), .B (w_i_man_b), .Z ({n_107,
       n_106, n_105, n_104, n_103, n_102, n_101, n_100, n_99, n_98,
       n_97, n_96, n_95, n_94, n_93, n_92, n_91, n_90, n_89, n_88,
       n_87, n_86, n_85, n_84, n_83}));
  add_unsigned_10 add_36_72(.A ({n_107, n_106, n_105, n_104, n_103,
       n_102, n_101, n_100, n_99, n_98, n_97, n_96, n_95, n_94, n_93,
       n_92, n_91, n_90, n_89, n_88, n_87, n_86, n_85, n_84, n_83}), .B
       (w_i_carry_alu), .Z ({w_overflow, o_man_alu}));
  bmux_11 mux_22_21(.ctl (i_fpu_op), .in_0 (n_4), .in_1 (n_3), .z
       (w_i_fpu_op));
  bmux_2 mux_25_20(.ctl (w_i_fpu_op), .in_0 (w_n_man_b), .in_1
       (i_man_min), .z (w_i_man_b));
  bmux_11 mux_39_21(.ctl (w_i_fpu_op), .in_0 (1'b0), .in_1
       (w_overflow), .z (o_overflow));
  xor g1 (n_3, i_sign_a, i_sign_b);
  not g3 (n_4, n_3);
  or g5 (n_33, i_carry, w_i_fpu_op);
  not g6 (w_i_carry_alu, n_33);
endmodule

module LOPD_8bit(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire n_3, n_4, n_6, n_7, n_9, n_10, n_11, n_16;
  wire n_17, n_21, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_33, n_34, n_37, n_40, n_42, n_43, n_44, n_48;
  wire n_49, n_54, n_59, n_66, n_68, n_69, n_70, n_71;
  not g1 (n_3, i_data[7]);
  not g2 (n_4, i_data[5]);
  and g3 (n_6, n_3, n_4);
  not g4 (n_7, i_data[3]);
  and g5 (n_9, n_6, n_7);
  not g6 (n_10, i_data[1]);
  and g7 (n_11, n_9, n_10);
  and g8 (n_16, n_11, i_data[0]);
  and g11 (n_17, n_9, i_data[2]);
  and g14 (n_21, n_6, i_data[4]);
  and g16 (n_24, n_3, i_data[6]);
  not g18 (n_25, i_data[6]);
  and g19 (n_26, n_3, n_25);
  and g20 (n_27, n_26, n_7);
  not g21 (n_28, i_data[2]);
  and g22 (n_29, n_27, n_28);
  and g23 (n_33, n_29, i_data[0]);
  and g27 (n_34, n_29, i_data[1]);
  and g30 (n_37, n_26, i_data[4]);
  and g33 (n_40, n_26, i_data[5]);
  and g36 (n_42, n_26, n_4);
  not g37 (n_43, i_data[4]);
  and g38 (n_44, n_42, n_43);
  and g39 (n_48, n_44, i_data[0]);
  and g43 (n_49, n_44, i_data[1]);
  and g48 (n_54, n_44, i_data[2]);
  and g53 (n_59, n_44, i_data[3]);
  not g62 (o_zero_flag, n_66);
  or g63 (o_pos_one[2], n_48, n_49, n_54, n_59);
  or g64 (o_pos_one[1], n_33, n_34, n_37, n_40);
  or g65 (o_pos_one[0], n_16, n_17, n_21, n_24);
  or g66 (n_68, i_data[7], i_data[6]);
  or g67 (n_69, i_data[5], i_data[4]);
  or g68 (n_70, i_data[3], i_data[2]);
  or g69 (n_71, i_data[1], i_data[0]);
  or g70 (n_66, n_68, n_69, n_70, n_71);
endmodule

module LOPD_16bit(i_data, o_pos_one, o_zero_flag);
  input [15:0] i_data;
  output [3:0] o_pos_one;
  output o_zero_flag;
  wire [15:0] i_data;
  wire [3:0] o_pos_one;
  wire o_zero_flag;
  wire [2:0] w_pos_one_0;
  wire [2:0] w_pos_one_1;
  wire w_zero_flag_0;
  LOPD_8bit LOPD_8bit_unit_0(.i_data (i_data[7:0]), .o_pos_one
       (w_pos_one_0), .o_zero_flag (w_zero_flag_0));
  LOPD_8bit LOPD_8bit_unit_1(.i_data (i_data[15:8]), .o_pos_one
       (w_pos_one_1), .o_zero_flag (o_pos_one[3]));
  bmux_11 mux_34_25(.ctl (o_pos_one[3]), .in_0 (w_pos_one_1[2]), .in_1
       (w_pos_one_0[2]), .z (o_pos_one[2]));
  bmux_11 mux_35_25(.ctl (o_pos_one[3]), .in_0 (w_pos_one_1[1]), .in_1
       (w_pos_one_0[1]), .z (o_pos_one[1]));
  bmux_11 mux_36_25(.ctl (o_pos_one[3]), .in_0 (w_pos_one_1[0]), .in_1
       (w_pos_one_0[0]), .z (o_pos_one[0]));
  and g1 (o_zero_flag, w_zero_flag_0, o_pos_one[3]);
endmodule

module bmux_21(ctl, in_0, in_1, z);
  input ctl;
  input [4:0] in_0, in_1;
  output [4:0] z;
  wire ctl;
  wire [4:0] in_0, in_1;
  wire [4:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module LOPD_24bit_SIZE_DATA24_SIZE_LOPD5(i_data, o_one_position,
     o_zero_flag);
  input [23:0] i_data;
  output [4:0] o_one_position;
  output o_zero_flag;
  wire [23:0] i_data;
  wire [4:0] o_one_position;
  wire o_zero_flag;
  wire [3:0] LOPD16_o_pos_one;
  wire [2:0] LOPD8_o_pos_one;
  wire [4:0] w_o_one_position;
  wire LOPD8_o_zero_flag, LOPD16_o_zero_flag;
  LOPD_16bit LOPD_16bit_UNIT_MSB(.i_data (i_data[23:8]), .o_pos_one
       (LOPD16_o_pos_one), .o_zero_flag (LOPD16_o_zero_flag));
  LOPD_8bit LOPD_8bit_UNIT_LSB(.i_data (i_data[7:0]), .o_pos_one
       (LOPD8_o_pos_one), .o_zero_flag (LOPD8_o_zero_flag));
  bmux_11 mux_33_30(.ctl (LOPD16_o_zero_flag), .in_0
       (LOPD16_o_pos_one[3]), .in_1 (1'b0), .z (w_o_one_position[3]));
  bmux_11 mux_34_30(.ctl (LOPD16_o_zero_flag), .in_0
       (LOPD16_o_pos_one[2]), .in_1 (LOPD8_o_pos_one[2]), .z
       (w_o_one_position[2]));
  bmux_11 mux_35_30(.ctl (LOPD16_o_zero_flag), .in_0
       (LOPD16_o_pos_one[1]), .in_1 (LOPD8_o_pos_one[1]), .z
       (w_o_one_position[1]));
  bmux_11 mux_36_30(.ctl (LOPD16_o_zero_flag), .in_0
       (LOPD16_o_pos_one[0]), .in_1 (LOPD8_o_pos_one[0]), .z
       (w_o_one_position[0]));
  bmux_21 mux_37_25(.ctl (o_zero_flag), .in_0 ({LOPD16_o_zero_flag,
       w_o_one_position[3:0]}), .in_1 (5'b11111), .z (o_one_position));
  and g1 (o_zero_flag, LOPD16_o_zero_flag, LOPD8_o_zero_flag);
endmodule

module not_op_6(A, Z);
  input [7:0] A;
  output [7:0] Z;
  wire [7:0] A;
  wire [7:0] Z;
  not g1 (Z[7], A[7]);
  not g2 (Z[6], A[6]);
  not g3 (Z[5], A[5]);
  not g4 (Z[4], A[4]);
  not g5 (Z[3], A[3]);
  not g6 (Z[2], A[2]);
  not g7 (Z[1], A[1]);
  not g8 (Z[0], A[0]);
endmodule

module EXP_adjust_SIZE_EXP8_SIZE_LOPD8(i_overflow, i_underflow,
     i_zero_flag, i_lopd_value, i_exp_value, o_exp_result);
  input i_overflow, i_underflow, i_zero_flag;
  input [7:0] i_lopd_value, i_exp_value;
  output [7:0] o_exp_result;
  wire i_overflow, i_underflow, i_zero_flag;
  wire [7:0] i_lopd_value, i_exp_value;
  wire [7:0] o_exp_result;
  wire [7:0] w_data_b;
  wire [7:0] w_exp_result;
  wire UNCONNECTED0, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_52, w_i_carry;
  CLA_8bit CLA_8BIT_UNIT(.i_carry (w_i_carry), .i_data_a (i_exp_value),
       .i_data_b (w_data_b), .o_sum (w_exp_result), .o_carry
       (UNCONNECTED0));
  not_op_6 g3(.A (i_lopd_value), .Z ({n_35, n_34, n_33, n_32, n_31,
       n_30, n_29, n_28}));
  bmux mux_21_48(.ctl (i_underflow), .in_0 ({n_35, n_34, n_33, n_32,
       n_31, n_30, n_29, n_28}), .in_1 (8'b00000000), .z ({n_43, n_42,
       n_41, n_40, n_39, n_38, n_37, n_36}));
  bmux mux_21_19(.ctl (i_overflow), .in_0 ({n_43, n_42, n_41, n_40,
       n_39, n_38, n_37, n_36}), .in_1 (8'b00000001), .z (w_data_b));
  bmux mux_33_23(.ctl (i_zero_flag), .in_0 (w_exp_result), .in_1
       (8'b00000000), .z (o_exp_result));
  or g1 (n_52, i_overflow, i_underflow);
  not g2 (w_i_carry, n_52);
endmodule

module SHF_left_SIZE_DATA32_SIZE_SHIFT5(i_shift_number, i_data, o_data);
  input [4:0] i_shift_number;
  input [31:0] i_data;
  output [31:0] o_data;
  wire [4:0] i_shift_number;
  wire [31:0] i_data;
  wire [31:0] o_data;
  wire [31:0] \stage[1] ;
  wire [31:0] \stage[2] ;
  wire [31:0] \stage[3] ;
  wire [31:0] \stage[4] ;
  bmux_4 mux_20_33(.ctl (i_shift_number[0]), .in_0 (i_data), .in_1
       ({i_data[30:0], 1'b0}), .z ({\stage[1] [31], \stage[1] [30],
       \stage[1] [29], \stage[1] [28], \stage[1] [27], \stage[1] [26],
       \stage[1] [25], \stage[1] [24], \stage[1] [23], \stage[1] [22],
       \stage[1] [21], \stage[1] [20], \stage[1] [19], \stage[1] [18],
       \stage[1] [17], \stage[1] [16], \stage[1] [15], \stage[1] [14],
       \stage[1] [13], \stage[1] [12], \stage[1] [11], \stage[1] [10],
       \stage[1] [9], \stage[1] [8], \stage[1] [7], \stage[1] [6],
       \stage[1] [5], \stage[1] [4], \stage[1] [3], \stage[1] [2],
       \stage[1] [1], \stage[1] [0]}));
  bmux_4 mux_20_6(.ctl (i_shift_number[1]), .in_0 ({\stage[1] [31],
       \stage[1] [30], \stage[1] [29], \stage[1] [28], \stage[1] [27],
       \stage[1] [26], \stage[1] [25], \stage[1] [24], \stage[1] [23],
       \stage[1] [22], \stage[1] [21], \stage[1] [20], \stage[1] [19],
       \stage[1] [18], \stage[1] [17], \stage[1] [16], \stage[1] [15],
       \stage[1] [14], \stage[1] [13], \stage[1] [12], \stage[1] [11],
       \stage[1] [10], \stage[1] [9], \stage[1] [8], \stage[1] [7],
       \stage[1] [6], \stage[1] [5], \stage[1] [4], \stage[1] [3],
       \stage[1] [2], \stage[1] [1], \stage[1] [0]}), .in_1
       ({\stage[1] [29], \stage[1] [28], \stage[1] [27], \stage[1]
       [26], \stage[1] [25], \stage[1] [24], \stage[1] [23],
       \stage[1] [22], \stage[1] [21], \stage[1] [20], \stage[1] [19],
       \stage[1] [18], \stage[1] [17], \stage[1] [16], \stage[1] [15],
       \stage[1] [14], \stage[1] [13], \stage[1] [12], \stage[1] [11],
       \stage[1] [10], \stage[1] [9], \stage[1] [8], \stage[1] [7],
       \stage[1] [6], \stage[1] [5], \stage[1] [4], \stage[1] [3],
       \stage[1] [2], \stage[1] [1], \stage[1] [0], 2'b00}), .z
       ({\stage[2] [31], \stage[2] [30], \stage[2] [29], \stage[2]
       [28], \stage[2] [27], \stage[2] [26], \stage[2] [25],
       \stage[2] [24], \stage[2] [23], \stage[2] [22], \stage[2] [21],
       \stage[2] [20], \stage[2] [19], \stage[2] [18], \stage[2] [17],
       \stage[2] [16], \stage[2] [15], \stage[2] [14], \stage[2] [13],
       \stage[2] [12], \stage[2] [11], \stage[2] [10], \stage[2] [9],
       \stage[2] [8], \stage[2] [7], \stage[2] [6], \stage[2] [5],
       \stage[2] [4], \stage[2] [3], \stage[2] [2], \stage[2] [1],
       \stage[2] [0]}));
  bmux_4 mux_20_7(.ctl (i_shift_number[2]), .in_0 ({\stage[2] [31],
       \stage[2] [30], \stage[2] [29], \stage[2] [28], \stage[2] [27],
       \stage[2] [26], \stage[2] [25], \stage[2] [24], \stage[2] [23],
       \stage[2] [22], \stage[2] [21], \stage[2] [20], \stage[2] [19],
       \stage[2] [18], \stage[2] [17], \stage[2] [16], \stage[2] [15],
       \stage[2] [14], \stage[2] [13], \stage[2] [12], \stage[2] [11],
       \stage[2] [10], \stage[2] [9], \stage[2] [8], \stage[2] [7],
       \stage[2] [6], \stage[2] [5], \stage[2] [4], \stage[2] [3],
       \stage[2] [2], \stage[2] [1], \stage[2] [0]}), .in_1
       ({\stage[2] [27], \stage[2] [26], \stage[2] [25], \stage[2]
       [24], \stage[2] [23], \stage[2] [22], \stage[2] [21],
       \stage[2] [20], \stage[2] [19], \stage[2] [18], \stage[2] [17],
       \stage[2] [16], \stage[2] [15], \stage[2] [14], \stage[2] [13],
       \stage[2] [12], \stage[2] [11], \stage[2] [10], \stage[2] [9],
       \stage[2] [8], \stage[2] [7], \stage[2] [6], \stage[2] [5],
       \stage[2] [4], \stage[2] [3], \stage[2] [2], \stage[2] [1],
       \stage[2] [0], 4'b0000}), .z ({\stage[3] [31], \stage[3] [30],
       \stage[3] [29], \stage[3] [28], \stage[3] [27], \stage[3] [26],
       \stage[3] [25], \stage[3] [24], \stage[3] [23], \stage[3] [22],
       \stage[3] [21], \stage[3] [20], \stage[3] [19], \stage[3] [18],
       \stage[3] [17], \stage[3] [16], \stage[3] [15], \stage[3] [14],
       \stage[3] [13], \stage[3] [12], \stage[3] [11], \stage[3] [10],
       \stage[3] [9], \stage[3] [8], \stage[3] [7], \stage[3] [6],
       \stage[3] [5], \stage[3] [4], \stage[3] [3], \stage[3] [2],
       \stage[3] [1], \stage[3] [0]}));
  bmux_4 mux_20_8(.ctl (i_shift_number[3]), .in_0 ({\stage[3] [31],
       \stage[3] [30], \stage[3] [29], \stage[3] [28], \stage[3] [27],
       \stage[3] [26], \stage[3] [25], \stage[3] [24], \stage[3] [23],
       \stage[3] [22], \stage[3] [21], \stage[3] [20], \stage[3] [19],
       \stage[3] [18], \stage[3] [17], \stage[3] [16], \stage[3] [15],
       \stage[3] [14], \stage[3] [13], \stage[3] [12], \stage[3] [11],
       \stage[3] [10], \stage[3] [9], \stage[3] [8], \stage[3] [7],
       \stage[3] [6], \stage[3] [5], \stage[3] [4], \stage[3] [3],
       \stage[3] [2], \stage[3] [1], \stage[3] [0]}), .in_1
       ({\stage[3] [23], \stage[3] [22], \stage[3] [21], \stage[3]
       [20], \stage[3] [19], \stage[3] [18], \stage[3] [17],
       \stage[3] [16], \stage[3] [15], \stage[3] [14], \stage[3] [13],
       \stage[3] [12], \stage[3] [11], \stage[3] [10], \stage[3] [9],
       \stage[3] [8], \stage[3] [7], \stage[3] [6], \stage[3] [5],
       \stage[3] [4], \stage[3] [3], \stage[3] [2], \stage[3] [1],
       \stage[3] [0], 8'b00000000}), .z ({\stage[4] [31], \stage[4]
       [30], \stage[4] [29], \stage[4] [28], \stage[4] [27],
       \stage[4] [26], \stage[4] [25], \stage[4] [24], \stage[4] [23],
       \stage[4] [22], \stage[4] [21], \stage[4] [20], \stage[4] [19],
       \stage[4] [18], \stage[4] [17], \stage[4] [16], \stage[4] [15],
       \stage[4] [14], \stage[4] [13], \stage[4] [12], \stage[4] [11],
       \stage[4] [10], \stage[4] [9], \stage[4] [8], \stage[4] [7],
       \stage[4] [6], \stage[4] [5], \stage[4] [4], \stage[4] [3],
       \stage[4] [2], \stage[4] [1], \stage[4] [0]}));
  bmux_4 mux_20_9(.ctl (i_shift_number[4]), .in_0 ({\stage[4] [31],
       \stage[4] [30], \stage[4] [29], \stage[4] [28], \stage[4] [27],
       \stage[4] [26], \stage[4] [25], \stage[4] [24], \stage[4] [23],
       \stage[4] [22], \stage[4] [21], \stage[4] [20], \stage[4] [19],
       \stage[4] [18], \stage[4] [17], \stage[4] [16], \stage[4] [15],
       \stage[4] [14], \stage[4] [13], \stage[4] [12], \stage[4] [11],
       \stage[4] [10], \stage[4] [9], \stage[4] [8], \stage[4] [7],
       \stage[4] [6], \stage[4] [5], \stage[4] [4], \stage[4] [3],
       \stage[4] [2], \stage[4] [1], \stage[4] [0]}), .in_1
       ({\stage[4] [15], \stage[4] [14], \stage[4] [13], \stage[4]
       [12], \stage[4] [11], \stage[4] [10], \stage[4] [9],
       \stage[4] [8], \stage[4] [7], \stage[4] [6], \stage[4] [5],
       \stage[4] [4], \stage[4] [3], \stage[4] [2], \stage[4] [1],
       \stage[4] [0], 16'b0000000000000000}), .z (o_data));
endmodule

module NOR_unit_SIZE_LOPD5_SIZE_DATA32(i_overflow, i_zero_flag,
     i_one_position, i_mantissa, o_mantissa);
  input i_overflow, i_zero_flag;
  input [4:0] i_one_position;
  input [31:0] i_mantissa;
  output [31:0] o_mantissa;
  wire i_overflow, i_zero_flag;
  wire [4:0] i_one_position;
  wire [31:0] i_mantissa;
  wire [31:0] o_mantissa;
  wire [31:0] w_shift_left;
  wire n_36, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132;
  SHF_left_SIZE_DATA32_SIZE_SHIFT5 SHF_left_unit(.i_shift_number
       (i_one_position), .i_data (i_mantissa), .o_data (w_shift_left));
  bmux_4 mux_23_91(.ctl (n_36), .in_0 (i_mantissa), .in_1
       (w_shift_left), .z ({n_100, n_99, n_98, n_97, n_96, n_95, n_94,
       n_93, n_92, n_91, n_90, n_89, n_88, n_87, n_86, n_85, n_84,
       n_83, n_82, n_81, n_80, n_79, n_78, n_77, n_76, n_75, n_74,
       n_73, n_72, n_71, n_70, n_69}));
  bmux_4 mux_23_41(.ctl (i_overflow), .in_0 ({n_100, n_99, n_98, n_97,
       n_96, n_95, n_94, n_93, n_92, n_91, n_90, n_89, n_88, n_87,
       n_86, n_85, n_84, n_83, n_82, n_81, n_80, n_79, n_78, n_77,
       n_76, n_75, n_74, n_73, n_72, n_71, n_70, n_69}), .in_1 ({1'b1,
       i_mantissa[31:1]}), .z ({n_132, n_131, n_130, n_129, n_128,
       n_127, n_126, n_125, n_124, n_123, n_122, n_121, n_120, n_119,
       n_118, n_117, n_116, n_115, n_114, n_113, n_112, n_111, n_110,
       n_109, n_108, n_107, n_106, n_105, n_104, n_103, n_102, n_101}));
  bmux_4 mux_23_21(.ctl (i_zero_flag), .in_0 ({n_132, n_131, n_130,
       n_129, n_128, n_127, n_126, n_125, n_124, n_123, n_122, n_121,
       n_120, n_119, n_118, n_117, n_116, n_115, n_114, n_113, n_112,
       n_111, n_110, n_109, n_108, n_107, n_106, n_105, n_104, n_103,
       n_102, n_101}), .in_1 (32'b00000000000000000000000000000000), .z
       (o_mantissa));
  not g1 (n_36, i_mantissa[31]);
endmodule

module MAN_rounding_SIZE_MAN32_SIZE_MAN_RESULT24(i_man, o_man_result,
     o_ov_flow);
  input [31:0] i_man;
  output [23:0] o_man_result;
  output o_ov_flow;
  wire [31:0] i_man;
  wire [23:0] o_man_result;
  wire o_ov_flow;
  wire [23:0] w_carry;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_21, n_22, n_23, n_24, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_69;
  wire n_71, n_73, n_76, n_79, n_83, n_86, n_90, n_94;
  wire n_99, n_106, n_114, n_122, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_198, n_201, n_204, n_206, n_208, n_209;
  wire n_210, n_211, w_rounding_result, w_sticky_bit;
  and g2 (n_7, i_man[7], i_man[6]);
  and g3 (n_8, i_man[6], w_sticky_bit);
  or g4 (w_rounding_result, n_7, n_8);
  and g6 (w_carry[1], i_man[8], w_rounding_result);
  and g8 (w_carry[2], n_10, w_rounding_result);
  and g10 (w_carry[3], n_11, w_rounding_result);
  and g12 (w_carry[4], n_12, w_rounding_result);
  and g14 (w_carry[5], n_13, w_rounding_result);
  and g16 (w_carry[6], n_14, w_rounding_result);
  and g18 (w_carry[7], n_15, w_rounding_result);
  and g20 (w_carry[8], n_16, w_rounding_result);
  and g30 (w_carry[13], n_21, w_rounding_result);
  and g32 (w_carry[14], n_22, w_rounding_result);
  and g34 (w_carry[15], n_23, w_rounding_result);
  and g36 (w_carry[16], n_24, w_rounding_result);
  nor g1 (n_59, i_man[5], i_man[4], i_man[3], i_man[2]);
  nor g54 (n_58, i_man[1], i_man[0]);
  nand g55 (w_sticky_bit, n_58, n_59);
  nand g56 (n_60, i_man[8], i_man[9]);
  not g57 (n_10, n_60);
  nand g58 (n_61, i_man[10], i_man[9], i_man[8]);
  not g59 (n_11, n_61);
  nand g60 (n_62, i_man[11], i_man[10], i_man[9], i_man[8]);
  not g61 (n_12, n_62);
  nand g62 (n_63, i_man[12], i_man[11], i_man[10], i_man[9]);
  not g63 (n_64, i_man[8]);
  nor g64 (n_13, n_63, n_64);
  nand g65 (n_66, i_man[13], i_man[12], i_man[11], i_man[10]);
  nand g66 (n_65, i_man[9], i_man[8]);
  nor g67 (n_14, n_65, n_66);
  nand g68 (n_9, i_man[14], i_man[13], i_man[12], i_man[11]);
  nor g70 (n_15, n_61, n_9);
  nand g71 (n_69, i_man[15], i_man[14], i_man[13], i_man[12]);
  nor g73 (n_16, n_62, n_69);
  nand g74 (n_71, i_man[16], i_man[15], i_man[14], i_man[13]);
  nand g78 (n_73, i_man[17], i_man[16], i_man[15], i_man[14]);
  nand g82 (n_76, i_man[18], i_man[17], i_man[16], i_man[15]);
  nand g86 (n_79, i_man[19], i_man[18], i_man[17], i_man[16]);
  nand g90 (n_83, i_man[20], i_man[19], i_man[18], i_man[17]);
  nor g5 (n_21, n_64, n_83, n_71, n_63);
  nand g94 (n_86, i_man[21], i_man[20], i_man[19], i_man[18]);
  nor g98 (n_22, n_86, n_73, n_66, n_65);
  nand g99 (n_90, i_man[22], i_man[21], i_man[20], i_man[19]);
  nor g103 (n_23, n_90, n_76, n_9, n_61);
  nand g104 (n_94, i_man[23], i_man[22], i_man[21], i_man[20]);
  nor g108 (n_24, n_94, n_79, n_69, n_62);
  nand g109 (n_99, i_man[24], i_man[23], i_man[22], i_man[21]);
  nand g116 (n_106, i_man[25], i_man[24], i_man[23], i_man[22]);
  nand g125 (n_114, i_man[26], i_man[25], i_man[24], i_man[23]);
  nand g134 (n_122, i_man[27], i_man[26], i_man[25], i_man[24]);
  xor g173 (o_man_result[0], i_man[8], w_rounding_result);
  xor g174 (o_man_result[1], i_man[9], w_carry[1]);
  xor g175 (o_man_result[2], i_man[10], w_carry[2]);
  xor g176 (o_man_result[3], i_man[11], w_carry[3]);
  xor g177 (o_man_result[4], i_man[12], w_carry[4]);
  xor g178 (o_man_result[5], i_man[13], w_carry[5]);
  xor g179 (o_man_result[6], i_man[14], w_carry[6]);
  xor g180 (o_man_result[7], i_man[15], w_carry[7]);
  xor g181 (o_man_result[8], i_man[16], w_carry[8]);
  xor g182 (o_man_result[9], i_man[17], w_carry[9]);
  xor g11 (o_man_result[10], i_man[18], w_carry[10]);
  xor g183 (o_man_result[11], i_man[19], w_carry[11]);
  xor g13 (o_man_result[12], i_man[20], w_carry[12]);
  xor g184 (o_man_result[13], i_man[21], w_carry[13]);
  xor g15 (o_man_result[14], i_man[22], w_carry[14]);
  xor g185 (o_man_result[15], i_man[23], w_carry[15]);
  xor g17 (o_man_result[16], i_man[24], w_carry[16]);
  xor g186 (o_man_result[17], i_man[25], w_carry[17]);
  xor g19 (o_man_result[18], i_man[26], w_carry[18]);
  xor g187 (o_man_result[19], i_man[27], w_carry[19]);
  xor g21 (o_man_result[20], i_man[28], w_carry[20]);
  xor g188 (o_man_result[21], i_man[29], w_carry[21]);
  xor g23 (o_man_result[22], i_man[30], w_carry[22]);
  xor g189 (o_man_result[23], i_man[31], w_carry[23]);
  nor g200 (n_168, n_9, n_61, n_114);
  and g201 (n_169, n_166, n_167, i_man[30]);
  not g202 (n_166, n_90);
  and g204 (n_170, i_man[29], i_man[28]);
  and g205 (n_171, i_man[27], w_rounding_result);
  and g206 (w_carry[23], n_168, n_169, n_170, n_171);
  nor g207 (n_174, n_66, n_65, n_106);
  and g208 (n_175, n_172, n_173, i_man[29]);
  not g209 (n_172, n_86);
  and g211 (n_176, i_man[28], i_man[27]);
  and g212 (n_177, i_man[26], w_rounding_result);
  and g213 (w_carry[22], n_174, n_175, n_176, n_177);
  nor g214 (n_180, n_71, n_63, n_64);
  and g215 (n_181, n_178, n_179, i_man[28]);
  not g216 (n_178, n_99);
  not g217 (n_179, n_83);
  and g218 (n_182, i_man[27], i_man[26]);
  and g219 (n_183, i_man[25], w_rounding_result);
  and g220 (w_carry[21], n_180, n_181, n_182, n_183);
  nor g221 (n_184, n_122, n_94);
  nor g222 (n_185, n_79, n_69);
  and g223 (w_carry[20], n_12, w_rounding_result, n_184, n_185);
  nor g224 (n_186, n_114, n_90);
  nor g225 (n_187, n_76, n_9);
  and g226 (w_carry[19], n_11, w_rounding_result, n_186, n_187);
  nor g227 (n_189, n_106, n_86);
  nor g228 (n_190, n_73, n_66);
  and g229 (w_carry[18], n_188, w_rounding_result, n_189, n_190);
  nor g231 (n_192, n_64, n_99);
  nor g232 (n_193, n_83, n_71);
  and g233 (w_carry[17], n_191, w_rounding_result, n_192, n_193);
  and g235 (w_carry[12], n_194, n_195, n_12, w_rounding_result);
  not g236 (n_194, n_79);
  not g237 (n_195, n_69);
  and g239 (w_carry[11], n_167, n_198, n_11, w_rounding_result);
  not g240 (n_167, n_76);
  not g241 (n_198, n_9);
  and g243 (w_carry[10], n_173, n_201, n_188, w_rounding_result);
  not g244 (n_173, n_73);
  not g245 (n_201, n_66);
  not g246 (n_188, n_65);
  and g247 (w_carry[9], i_man[8], n_204, n_191, w_rounding_result);
  not g249 (n_204, n_71);
  not g250 (n_191, n_63);
  nor g251 (n_208, n_69, n_62, n_122);
  and g252 (n_209, n_206, n_194, i_man[31]);
  not g253 (n_206, n_94);
  and g255 (n_210, i_man[30], i_man[29]);
  and g256 (n_211, i_man[28], w_rounding_result);
  and g257 (o_ov_flow, n_208, n_209, n_210, n_211);
endmodule

module EXP_rounding_SIZE_DATA8(i_carry_rounding, i_exp_result,
     o_exp_result);
  input i_carry_rounding;
  input [7:0] i_exp_result;
  output [7:0] o_exp_result;
  wire i_carry_rounding;
  wire [7:0] i_exp_result;
  wire [7:0] o_exp_result;
  wire n_4, n_6, n_8, n_24, n_25, n_26, n_34, n_35;
  wire n_36, n_38, n_39, n_40, \w_carry[1] , \w_carry[2] , \w_carry[3]
       , \w_carry[4] ;
  wire \w_carry[5] , \w_carry[6] , \w_carry[7] ;
  and g2 (\w_carry[1] , i_exp_result[0], i_carry_rounding);
  and g4 (\w_carry[2] , n_4, i_carry_rounding);
  and g6 (\w_carry[3] , n_6, i_carry_rounding);
  and g8 (\w_carry[4] , n_8, i_carry_rounding);
  nand g1 (n_24, i_exp_result[0], i_exp_result[1]);
  not g16 (n_4, n_24);
  nand g17 (n_25, i_exp_result[2], i_exp_result[1], i_exp_result[0]);
  not g18 (n_6, n_25);
  nand g19 (n_26, i_exp_result[3], i_exp_result[2], i_exp_result[1],
       i_exp_result[0]);
  not g20 (n_8, n_26);
  xor g29 (o_exp_result[0], i_exp_result[0], i_carry_rounding);
  xor g30 (o_exp_result[1], i_exp_result[1], \w_carry[1] );
  xor g31 (o_exp_result[2], i_exp_result[2], \w_carry[2] );
  xor g32 (o_exp_result[3], i_exp_result[3], \w_carry[3] );
  xor g5 (o_exp_result[4], i_exp_result[4], \w_carry[4] );
  xor g33 (o_exp_result[5], i_exp_result[5], \w_carry[5] );
  xor g7 (o_exp_result[6], i_exp_result[6], \w_carry[6] );
  xor g34 (o_exp_result[7], i_exp_result[7], \w_carry[7] );
  and g35 (n_34, n_6, i_exp_result[6]);
  and g38 (\w_carry[7] , i_exp_result[3], i_carry_rounding, n_34, n_35);
  and g39 (n_36, i_exp_result[1], i_exp_result[0]);
  and g40 (n_35, i_exp_result[5], i_exp_result[4]);
  and g41 (n_38, i_exp_result[3], i_exp_result[2]);
  and g42 (\w_carry[6] , i_carry_rounding, n_36, n_35, n_38);
  and g43 (n_39, i_exp_result[4], i_exp_result[3]);
  and g44 (n_40, i_exp_result[2], i_exp_result[1]);
  and g45 (\w_carry[5] , i_exp_result[0], i_carry_rounding, n_39, n_40);
endmodule

module bmux_34(ctl, in_0, in_1, z);
  input ctl;
  input [22:0] in_0, in_1;
  output [22:0] z;
  wire ctl;
  wire [22:0] in_0, in_1;
  wire [22:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[22]), .data1 (in_1[22]), .z
       (z[22]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[21]), .data1 (in_1[21]), .z
       (z[21]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[20]), .data1 (in_1[20]), .z
       (z[20]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[19]), .data1 (in_1[19]), .z
       (z[19]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[18]), .data1 (in_1[18]), .z
       (z[18]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[17]), .data1 (in_1[17]), .z
       (z[17]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[16]), .data1 (in_1[16]), .z
       (z[16]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[15]), .data1 (in_1[15]), .z
       (z[15]));
  CDN_bmux2 g9(.sel0 (ctl), .data0 (in_0[14]), .data1 (in_1[14]), .z
       (z[14]));
  CDN_bmux2 g10(.sel0 (ctl), .data0 (in_0[13]), .data1 (in_1[13]), .z
       (z[13]));
  CDN_bmux2 g11(.sel0 (ctl), .data0 (in_0[12]), .data1 (in_1[12]), .z
       (z[12]));
  CDN_bmux2 g12(.sel0 (ctl), .data0 (in_0[11]), .data1 (in_1[11]), .z
       (z[11]));
  CDN_bmux2 g13(.sel0 (ctl), .data0 (in_0[10]), .data1 (in_1[10]), .z
       (z[10]));
  CDN_bmux2 g14(.sel0 (ctl), .data0 (in_0[9]), .data1 (in_1[9]), .z
       (z[9]));
  CDN_bmux2 g15(.sel0 (ctl), .data0 (in_0[8]), .data1 (in_1[8]), .z
       (z[8]));
  CDN_bmux2 g16(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g17(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g18(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g19(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g20(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g21(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g22(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g23(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module FPU_unit(i_add_sub, i_32_a, i_32_b, o_32_s, o_ov_flag,
     o_un_flag);
  input [0:0] i_add_sub;
  input [31:0] i_32_a, i_32_b;
  output [31:0] o_32_s;
  output o_ov_flag, o_un_flag;
  wire [0:0] i_add_sub;
  wire [31:0] i_32_a, i_32_b;
  wire [31:0] o_32_s;
  wire o_ov_flag, o_un_flag;
  wire [7:0] EXP_SWAP_o_min;
  wire [7:0] EXP_SWAP_o_max;
  wire [7:0] EXP_SUB_o_sub;
  wire [23:0] MAN_SWAP_PRE_man_max;
  wire [23:0] MAN_SWAP_PRE_man_min;
  wire [31:0] SHF_RIGHT_MAN_o_data;
  wire [1:0] PSC_sel_man;
  wire [23:0] MAN_SWAP_max;
  wire [23:0] MAN_SWAP_min;
  wire [3:0] CLS_MAN_ALU_o_data;
  wire [23:0] MAN_ALU_man_alu;
  wire [4:0] LOPD_o_one_position;
  wire [7:0] EXP_ADJUST_exp_result;
  wire [31:0] NOR_o_man;
  wire [23:0] MAN_RND_man;
  wire [7:0] EXP_RND_exp;
  wire CLS_MAN_ALU_bout, EXP_COMP_o_compare, LOPD_o_zero_flag,
       MAN_ALU_ov_flag, MAN_COM_o_compare, MAN_RND_ov_flag,
       PSC_sel_exp, UNCONNECTED1;
  wire n_77, n_79;
  EXP_comp_SIZE_DATA8 EXP_COM_8BIT(.i_data_a (i_32_a[30:23]), .i_data_b
       (i_32_b[30:23]), .o_compare (EXP_COMP_o_compare));
  EXP_swap_SIZE_DATA8 EXP_SWAP(.i_data_a (i_32_a[30:23]), .i_data_b
       (i_32_b[30:23]), .i_compare (EXP_COMP_o_compare), .o_less_data
       (EXP_SWAP_o_min), .o_greater_data (EXP_SWAP_o_max));
  EXP_sub_SIZE_EXP_SUB8 EXP_SUB(.i_data_a (EXP_SWAP_o_max), .i_data_b
       (EXP_SWAP_o_min), .o_sub (EXP_SUB_o_sub));
  MAN_swap_SIZE_MAN24 MAN_SWAP_PRE(.i_man_a ({1'b1, i_32_a[22:0]}),
       .i_man_b ({1'b1, i_32_b[22:0]}), .i_compare
       (EXP_COMP_o_compare), .o_man_max (MAN_SWAP_PRE_man_max),
       .o_man_min (MAN_SWAP_PRE_man_min));
  SHF_right_SIZE_DATA32_SIZE_SHIFT5 SHF_RIGHT_MAN(.i_shift_number
       (EXP_SUB_o_sub[4:0]), .i_data ({MAN_SWAP_PRE_man_min,
       8'b00000000}), .o_data (SHF_RIGHT_MAN_o_data));
  COMP_24bit_SIZE_DATA24 MAN_COMP_24BIT(.i_data_a
       (MAN_SWAP_PRE_man_max), .i_data_b (SHF_RIGHT_MAN_o_data[31:8]),
       .o_less (MAN_COM_o_compare));
  SIGN_unit SIGN_UNIT(.i_add_sub (i_add_sub), .i_comp_man (n_79),
       .i_sign_man_a (i_32_a[31]), .i_sign_man_b (i_32_b[31]),
       .o_sign_s (o_32_s[31]));
  PSC_unit PSC_UNIT(.i_add_sub (i_add_sub), .i_sign_a (i_32_a[31]),
       .i_exp_a (i_32_a[30:23]), .i_man_a ({1'b1, i_32_a[22:0]}),
       .i_sign_b (i_32_b[31]), .i_exp_b (i_32_b[30:23]), .i_man_b
       ({1'b1, i_32_b[22:0]}), .o_sel_exp (PSC_sel_exp), .o_sel_man
       (PSC_sel_man));
  MAN_swap_SIZE_MAN24 MAN_SWAP(.i_man_a (MAN_SWAP_PRE_man_max),
       .i_man_b (SHF_RIGHT_MAN_o_data[31:8]), .i_compare
       (MAN_COM_o_compare), .o_man_max (MAN_SWAP_max), .o_man_min
       (MAN_SWAP_min));
  CLS_4bit MAN_ALU_PROC_RND(.A (4'b0000), .B
       (SHF_RIGHT_MAN_o_data[7:4]), .Bin (1'b0), .SUB
       (CLS_MAN_ALU_o_data), .Bout (CLS_MAN_ALU_bout));
  MAN_ALU_NUM_OP1_SIZE_MAN24 MAN_ALU(.i_fpu_op (i_add_sub), .i_sign_a
       (i_32_a[31]), .i_sign_b (i_32_b[31]), .i_carry
       (CLS_MAN_ALU_bout), .i_man_max (MAN_SWAP_max), .i_man_min
       (MAN_SWAP_min), .o_man_alu (MAN_ALU_man_alu), .o_overflow
       (MAN_ALU_ov_flag));
  LOPD_24bit_SIZE_DATA24_SIZE_LOPD5 LOPD_24BIT(.i_data
       (MAN_ALU_man_alu), .o_one_position (LOPD_o_one_position),
       .o_zero_flag (LOPD_o_zero_flag));
  EXP_adjust_SIZE_EXP8_SIZE_LOPD8 EXP_ADJUST(.i_overflow
       (MAN_ALU_ov_flag), .i_underflow (MAN_ALU_man_alu[23]),
       .i_zero_flag (LOPD_o_zero_flag), .i_lopd_value ({3'b000,
       LOPD_o_one_position}), .i_exp_value (EXP_SWAP_o_max),
       .o_exp_result (EXP_ADJUST_exp_result));
  NOR_unit_SIZE_LOPD5_SIZE_DATA32 NOR_UNIT(.i_overflow
       (MAN_ALU_ov_flag), .i_zero_flag (LOPD_o_zero_flag),
       .i_one_position (LOPD_o_one_position), .i_mantissa
       ({MAN_ALU_man_alu, CLS_MAN_ALU_o_data, 4'b0000}), .o_mantissa
       (NOR_o_man));
  MAN_rounding_SIZE_MAN32_SIZE_MAN_RESULT24 MAN_RND(.i_man (NOR_o_man),
       .o_man_result ({UNCONNECTED1, MAN_RND_man[22:0]}), .o_ov_flow
       (MAN_RND_ov_flag));
  EXP_rounding_SIZE_DATA8 EXP_RND(.i_carry_rounding (MAN_RND_ov_flag),
       .i_exp_result (EXP_ADJUST_exp_result), .o_exp_result
       (EXP_RND_exp));
  bmux_11 mux_216_46(.ctl (PSC_sel_man[0]), .in_0 (1'b0), .in_1 (1'b1),
       .z (n_77));
  bmux_34 mux_216_28(.ctl (PSC_sel_man[1]), .in_0 (MAN_RND_man[22:0]),
       .in_1 ({n_77, 22'b0000000000000000000000}), .z (o_32_s[22:0]));
  bmux mux_215_28(.ctl (PSC_sel_exp), .in_0 (EXP_RND_exp), .in_1
       (8'b11111111), .z (o_32_s[30:23]));
  or g1 (n_79, MAN_COM_o_compare, EXP_COMP_o_compare);
  or g2 (o_ov_flag, MAN_ALU_ov_flag, MAN_RND_ov_flag);
  not g3 (o_un_flag, MAN_ALU_man_alu[23]);
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  reg  z;
  always 
    @(sel0 or data0 or data1) 
      case ({sel0})
       1'b0: z = data0;
       1'b1: z = data1;
      endcase
endmodule
`else
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  wire z;
  wire inv_sel0, w_0, w_1;
  not i_0 (inv_sel0, sel0);
  and a_0 (w_0, inv_sel0, data0);
  and a_1 (w_1, sel0, data1);
  or org (z, w_0, w_1);
endmodule
`endif // ONE_HOT_MUX
`endif
