/home/noname/Documents/project_tiny/Floating_point/02_rtl/FPU_32bit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/ALU/CLA/CLA_4bit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/ALU/CLA/CLA_8bit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/ALU/CLA/CLA_28bit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/ALU/SUM_unit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/EXP/EXP_adjust.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/EXP/EXP_diff_exponent.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/EXP/EXP_sub.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/EXP/EXP_swap.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/LOPD/LOPD_4bit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/LOPD/LOPD_8bit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/LOPD/LOPD_16bit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/LOPD/LOPD_32bit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/MANTISSA/ALU_unit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/MANTISSA/MANTISSA_shf_right.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/MANTISSA/MANTISSA_swap.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/SHF/SHF_shift_left.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/SHF/SHF_shift_right.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/EXP_unit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/FPU_normalization.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/FPU_rounding.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/MANTISSA_unit.sv
/home/noname/Documents/project_tiny/Floating_point/02_rtl/SHF_unit.sv