// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See Vtb_SHF_unit.h for the primary calling header

#include "Vtb_SHF_unit__pch.h"
#include "Vtb_SHF_unit__Syms.h"
#include "Vtb_SHF_unit___024root.h"

VL_ATTR_COLD void Vtb_SHF_unit___024root___eval_static__TOP(Vtb_SHF_unit___024root* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtb_SHF_unit__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_SHF_unit___024root___eval_static__TOP\n"); );
    // Body
    vlSelf->tb_SHF_unit__DOT__pass_count = 0U;
    ++(vlSymsp->__Vcoverage[77]);
    vlSelf->tb_SHF_unit__DOT__fail_count = 0U;
    ++(vlSymsp->__Vcoverage[78]);
}

VL_ATTR_COLD void Vtb_SHF_unit___024root___eval_initial__TOP(Vtb_SHF_unit___024root* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtb_SHF_unit__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_SHF_unit___024root___eval_initial__TOP\n"); );
    // Body
    ++(vlSymsp->__Vcoverage[235]);
    ++(vlSymsp->__Vcoverage[238]);
    ++(vlSymsp->__Vcoverage[241]);
    ++(vlSymsp->__Vcoverage[244]);
    ++(vlSymsp->__Vcoverage[247]);
}

#ifdef VL_DEBUG
VL_ATTR_COLD void Vtb_SHF_unit___024root___dump_triggers__stl(Vtb_SHF_unit___024root* vlSelf);
#endif  // VL_DEBUG

VL_ATTR_COLD void Vtb_SHF_unit___024root___eval_triggers__stl(Vtb_SHF_unit___024root* vlSelf) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtb_SHF_unit__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_SHF_unit___024root___eval_triggers__stl\n"); );
    // Body
    vlSelf->__VstlTriggered.set(0U, (IData)(vlSelf->__VstlFirstIteration));
    vlSelf->__VstlTriggered.set(1U, vlSelf->tb_SHF_unit__DOT__DUT__DOT__GEN_SHIFT_LEFT__DOT__SHF_SHIFT_LEFT__DOT__stage_data.neq(vlSelf->__Vtrigprevexpr___TOP__tb_SHF_unit__DOT__DUT__DOT__GEN_SHIFT_LEFT__DOT__SHF_SHIFT_LEFT__DOT__stage_data__0));
    vlSelf->__Vtrigprevexpr___TOP__tb_SHF_unit__DOT__DUT__DOT__GEN_SHIFT_LEFT__DOT__SHF_SHIFT_LEFT__DOT__stage_data__0.assign(vlSelf->tb_SHF_unit__DOT__DUT__DOT__GEN_SHIFT_LEFT__DOT__SHF_SHIFT_LEFT__DOT__stage_data);
    if (VL_UNLIKELY((1U & (~ (IData)(vlSelf->__VstlDidInit))))) {
        vlSelf->__VstlDidInit = 1U;
        vlSelf->__VstlTriggered.set(1U, 1U);
    }
#ifdef VL_DEBUG
    if (VL_UNLIKELY(vlSymsp->_vm_contextp__->debug())) {
        Vtb_SHF_unit___024root___dump_triggers__stl(vlSelf);
    }
#endif
}

VL_ATTR_COLD void Vtb_SHF_unit___024root___configure_coverage(Vtb_SHF_unit___024root* vlSelf, bool first) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtb_SHF_unit__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_SHF_unit___024root___configure_coverage\n"); );
    // Body
    (void)first;  // Prevent unused variable warning
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[0]), first, "SHF_unit/tb_SHF_unit.sv", 12, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_shift_number[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[1]), first, "SHF_unit/tb_SHF_unit.sv", 12, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_shift_number[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[2]), first, "SHF_unit/tb_SHF_unit.sv", 12, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_shift_number[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[3]), first, "SHF_unit/tb_SHF_unit.sv", 12, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_shift_number[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[4]), first, "SHF_unit/tb_SHF_unit.sv", 12, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_shift_number[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[6]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[7]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[8]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[9]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[10]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[11]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[12]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[13]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[14]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[15]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[16]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[17]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[18]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[19]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[20]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[21]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[22]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[23]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[24]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[25]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[26]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[27]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[28]), first, "SHF_unit/tb_SHF_unit.sv", 13, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "i_data[23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[29]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[30]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[31]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[32]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[33]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[34]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[35]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[36]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[37]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[38]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[39]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[40]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[41]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[42]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[43]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[44]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[45]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[46]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[47]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[48]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[49]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[50]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[51]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[52]), first, "SHF_unit/tb_SHF_unit.sv", 14, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "o_data[23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[53]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[54]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[55]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[56]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[57]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[58]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[59]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[60]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[61]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[62]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[63]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[64]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[65]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[66]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[67]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[68]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[69]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[70]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[71]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[72]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[73]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[74]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[75]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[76]), first, "SHF_unit/tb_SHF_unit.sv", 15, 28, ".tb_SHF_unit", "v_toggle/tb_SHF_unit", "expected_data[23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[77]), first, "SHF_unit/tb_SHF_unit.sv", 18, 26, ".tb_SHF_unit", "v_line/tb_SHF_unit", "block", "18");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[78]), first, "SHF_unit/tb_SHF_unit.sv", 19, 26, ".tb_SHF_unit", "v_line/tb_SHF_unit", "block", "19");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[79]), first, "SHF_unit/tb_SHF_unit.sv", 35, 9, ".tb_SHF_unit", "v_branch/tb_SHF_unit", "if", "35-36");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[80]), first, "SHF_unit/tb_SHF_unit.sv", 35, 10, ".tb_SHF_unit", "v_branch/tb_SHF_unit", "else", "38");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[81]), first, "SHF_unit/tb_SHF_unit.sv", 50, 13, ".tb_SHF_unit", "v_branch/tb_SHF_unit", "if", "50-51");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[82]), first, "SHF_unit/tb_SHF_unit.sv", 50, 14, ".tb_SHF_unit", "v_branch/tb_SHF_unit", "else", "53");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[83]), first, "SHF_unit/tb_SHF_unit.sv", 56, 13, ".tb_SHF_unit", "v_branch/tb_SHF_unit", "if", "56-59");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[84]), first, "SHF_unit/tb_SHF_unit.sv", 56, 14, ".tb_SHF_unit", "v_branch/tb_SHF_unit", "else", "60-63");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[85]), first, "SHF_unit/tb_SHF_unit.sv", 42, 9, ".tb_SHF_unit", "v_line/tb_SHF_unit", "block", "42,44-45,47");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[86]), first, "SHF_unit/tb_SHF_unit.sv", 74, 9, ".tb_SHF_unit", "v_branch/tb_SHF_unit", "if", "74-75");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[87]), first, "SHF_unit/tb_SHF_unit.sv", 74, 10, ".tb_SHF_unit", "v_branch/tb_SHF_unit", "else", "77");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[88]), first, "SHF_unit/tb_SHF_unit.sv", 33, 5, ".tb_SHF_unit", "v_line/tb_SHF_unit", "block", "33-34,39,42,68-72,79");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[0]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 6, 38, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_shift_number[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[1]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 6, 38, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_shift_number[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[2]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 6, 38, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_shift_number[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[3]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 6, 38, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_shift_number[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[4]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 6, 38, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_shift_number[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[6]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[7]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[8]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[9]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[10]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[11]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[12]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[13]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[14]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[15]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[16]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[17]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[18]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[19]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[20]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[21]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[22]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[23]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[24]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[25]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[26]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[27]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[28]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 7, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "i_data[23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[29]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[30]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[31]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[32]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[33]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[34]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[35]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[36]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[37]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[38]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[39]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[40]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[41]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[42]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[43]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[44]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[45]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[46]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[47]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[48]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[49]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[50]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[51]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[52]), first, "SHF_unit/../../../02_rtl/SHF_unit.sv", 8, 37, ".tb_SHF_unit.DUT", "v_toggle/SHF_unit__L0", "o_data[23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[0]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 5, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_shift_number[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[1]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 5, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_shift_number[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[2]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 5, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_shift_number[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[3]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 5, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_shift_number[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[4]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 5, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_shift_number[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[5]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[6]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[7]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[8]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[9]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[10]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[11]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[12]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[13]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[14]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[15]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[16]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[17]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[18]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[19]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[20]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[21]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[22]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[23]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[24]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[25]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[26]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[27]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[28]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 6, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "i_data[23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[29]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[30]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[31]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[32]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[33]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[34]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[35]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[36]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[37]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[38]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[39]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[40]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[41]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[42]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[43]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[44]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[45]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[46]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[47]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[48]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[49]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[50]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[51]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[52]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 7, 35, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "o_data[23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[89]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[90]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[91]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[92]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[93]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[94]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[95]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[96]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[97]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[98]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[99]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[100]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[101]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[102]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[103]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[104]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[105]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[106]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[107]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[108]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[109]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[110]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[111]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[112]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[0][23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[113]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[114]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[115]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[116]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[117]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[118]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[119]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[120]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[121]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[122]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[123]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[124]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[125]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[126]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[127]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[128]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[129]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[130]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[131]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[132]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[133]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[134]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[135]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[136]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[1][23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[137]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[138]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[139]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[140]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[141]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[142]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[143]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[144]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[145]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[146]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[147]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[148]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[149]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[150]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[151]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[152]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[153]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[154]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[155]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[156]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[157]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[158]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[159]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[160]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[2][23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[161]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[162]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[163]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[164]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[165]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[166]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[167]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[168]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[169]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[170]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[171]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[172]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[173]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[174]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[175]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[176]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[177]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[178]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[179]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[180]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[181]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[182]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[183]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[184]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[3][23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[185]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[186]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[187]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[188]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[189]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[190]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[191]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[192]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[193]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[194]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[195]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[196]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[197]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[198]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[199]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[200]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[201]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[202]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[203]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[204]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[205]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[206]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[207]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[208]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[4][23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[209]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][0]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[210]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][1]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[211]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][2]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[212]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][3]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[213]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][4]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[214]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][5]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[215]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][6]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[216]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][7]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[217]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][8]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[218]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][9]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[219]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][10]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[220]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][11]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[221]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][12]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[222]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][13]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[223]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][14]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[224]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][15]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[225]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][16]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[226]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][17]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[227]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][18]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[228]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][19]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[229]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][20]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[230]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][21]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[231]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][22]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[232]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 12, 27, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_toggle/SHF_shift_left__S18_SB5", "stage_data[5][23]", "");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[233]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 21, 17, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_branch/SHF_shift_left__S18_SB5", "if", "18,21-22");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[234]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 21, 18, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_branch/SHF_shift_left__S18_SB5", "else", "18,24");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[235]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 20, 13, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_line/SHF_shift_left__S18_SB5", "block", "20");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[236]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 21, 17, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_branch/SHF_shift_left__S18_SB5", "if", "18,21-22");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[237]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 21, 18, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_branch/SHF_shift_left__S18_SB5", "else", "18,24");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[238]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 20, 13, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_line/SHF_shift_left__S18_SB5", "block", "20");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[239]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 21, 17, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_branch/SHF_shift_left__S18_SB5", "if", "18,21-22");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[240]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 21, 18, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_branch/SHF_shift_left__S18_SB5", "else", "18,24");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[241]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 20, 13, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_line/SHF_shift_left__S18_SB5", "block", "20");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[242]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 21, 17, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_branch/SHF_shift_left__S18_SB5", "if", "18,21-22");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[243]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 21, 18, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_branch/SHF_shift_left__S18_SB5", "else", "18,24");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[244]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 20, 13, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_line/SHF_shift_left__S18_SB5", "block", "20");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[245]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 21, 17, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_branch/SHF_shift_left__S18_SB5", "if", "18,21-22");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[246]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 21, 18, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_branch/SHF_shift_left__S18_SB5", "else", "18,24");
    vlSelf->__vlCoverInsert(&(vlSymsp->__Vcoverage[247]), first, "SHF_unit/../../../02_rtl/SHF_shift_left.sv", 20, 13, ".tb_SHF_unit.DUT.GEN_SHIFT_LEFT.SHF_SHIFT_LEFT", "v_line/SHF_shift_left__S18_SB5", "block", "20");
}
