
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Nov 23 2025 23:11:37

// Verification Directory fv/FPU_unit 

module CLA_4bit_9(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_13, n_15;
  OAI21X1HVT g471(.A0 (n_6), .A1 (n_15), .B0 (n_1), .Y (o_g));
  XOR2XLHVT g472(.A (n_6), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g473(.A0 (n_7), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  XOR2XLHVT g474(.A (n_7), .B (n_13), .Y (sum[2]));
  OAI21X1HVT g475(.A0 (n_5), .A1 (n_10), .B0 (n_4), .Y (n_13));
  XNOR2X1HVT g476(.A (n_9), .B (n_10), .Y (sum[1]));
  XNOR2X1HVT g478(.A (cin), .B (n_8), .Y (sum[0]));
  AOI21X1HVT g479(.A0 (cin), .A1 (n_3), .B0 (n_2), .Y (n_10));
  NOR2BX1HVT g481(.AN (n_4), .B (n_5), .Y (n_9));
  NAND2BX1HVT g482(.AN (n_2), .B (n_3), .Y (n_8));
  XOR2XLHVT g483(.A (a[2]), .B (b[2]), .Y (n_7));
  XNOR2X1HVT g484(.A (a[3]), .B (b[3]), .Y (n_6));
  NOR2X1HVT g485(.A (a[1]), .B (b[1]), .Y (n_5));
  NAND2X1HVT g486(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2XLHVT g487(.A (a[3]), .B (b[3]), .Y (n_1));
  OR2XLHVT g488(.A (a[0]), .B (b[0]), .Y (n_3));
  AND2XLHVT g489(.A (a[0]), .B (b[0]), .Y (n_2));
  NOR4BBX1HVT g2(.AN (n_9), .BN (n_7), .C (n_6), .D (n_8), .Y (o_p));
endmodule

module CLA_4bit_10(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_8, n_10;
  wire n_11, n_12;
  assign o_g = 1'b0;
  assign o_p = 1'b0;
  XNOR2X1HVT g217(.A (n_5), .B (n_12), .Y (sum[3]));
  XNOR2X1HVT g218(.A (n_4), .B (n_11), .Y (sum[2]));
  OAI2BB1X1HVT g219(.A0N (n_4), .A1N (n_10), .B0 (n_6), .Y (n_12));
  AOI21X1HVT g220(.A0 (a[1]), .A1 (b[1]), .B0 (n_10), .Y (n_11));
  ADDHX1HVT g221(.A (n_2), .B (n_8), .CO (n_10), .S (sum[1]));
  AO22XLHVT g222(.A0 (n_3), .A1 (cin), .B0 (a[0]), .B1 (b[0]), .Y
       (n_8));
  XOR2XLHVT g223(.A (n_3), .B (cin), .Y (sum[0]));
  OAI21XLHVT g224(.A0 (a[1]), .A1 (a[2]), .B0 (b[1]), .Y (n_6));
  XNOR2X1HVT g225(.A (a[3]), .B (b[1]), .Y (n_5));
  MXI2XLHVT g226(.A (n_1), .B (b[1]), .S0 (a[2]), .Y (n_4));
  MXI2XLHVT g227(.A (n_1), .B (b[1]), .S0 (a[1]), .Y (n_2));
  XOR2XLHVT g228(.A (a[0]), .B (b[0]), .Y (n_3));
  INVX1HVT g229(.A (b[1]), .Y (n_1));
endmodule

module CLA_8bit_1(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire w_C, w_G, w_G_22, w_P, w_P_20;
  assign o_carry = 1'b0;
  CLA_4bit_9 CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]),
       .cin (i_data_b[5]), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
  CLA_4bit_10 CLA_4BIT_UNIT_1(.a (i_data_a[7:4]), .b ({2'b00,
       i_data_b[5:4]}), .cin (w_C), .sum (o_sum[7:4]), .o_p (w_P_20),
       .o_g (w_G_22));
  AO21XLHVT g20(.A0 (i_data_b[5]), .A1 (w_P), .B0 (w_G), .Y (w_C));
endmodule

module EXP_adjust_SIZE_EXP8_SIZE_LOPD8(i_overflow, i_underflow,
     i_zero_flag, i_lopd_value, i_exp_value, o_exp_result);
  input i_overflow, i_underflow, i_zero_flag;
  input [7:0] i_lopd_value, i_exp_value;
  output [7:0] o_exp_result;
  wire i_overflow, i_underflow, i_zero_flag;
  wire [7:0] i_lopd_value, i_exp_value;
  wire [7:0] o_exp_result;
  wire [7:0] w_data_b;
  wire [7:0] w_exp_result;
  wire UNCONNECTED, n_0, w_i_carry;
  CLA_8bit_1 CLA_8BIT_UNIT(.i_carry (1'b0), .i_data_a (i_exp_value),
       .i_data_b ({2'b00, w_i_carry, w_data_b[4:0]}), .o_sum
       (w_exp_result), .o_carry (UNCONNECTED));
  NOR2BX1HVT g150(.AN (w_i_carry), .B (i_lopd_value[4]), .Y
       (w_data_b[4]));
  NOR2BX1HVT g151(.AN (w_i_carry), .B (i_lopd_value[2]), .Y
       (w_data_b[2]));
  NOR2BX1HVT g152(.AN (w_i_carry), .B (i_lopd_value[1]), .Y
       (w_data_b[1]));
  NOR2BX1HVT g153(.AN (w_i_carry), .B (i_lopd_value[3]), .Y
       (w_data_b[3]));
  OAI21X1HVT g154(.A0 (i_underflow), .A1 (i_lopd_value[0]), .B0 (n_0),
       .Y (w_data_b[0]));
  NOR2X1HVT g155(.A (i_underflow), .B (i_overflow), .Y (w_i_carry));
  INVX1HVT g156(.A (i_overflow), .Y (n_0));
  NOR2BX1HVT g157(.AN (w_exp_result[4]), .B (i_zero_flag), .Y
       (o_exp_result[4]));
  NOR2BX1HVT g158(.AN (w_exp_result[6]), .B (i_zero_flag), .Y
       (o_exp_result[6]));
  NOR2BX1HVT g159(.AN (w_exp_result[7]), .B (i_zero_flag), .Y
       (o_exp_result[7]));
  NOR2BX1HVT g160(.AN (w_exp_result[0]), .B (i_zero_flag), .Y
       (o_exp_result[0]));
  NOR2BX1HVT g161(.AN (w_exp_result[2]), .B (i_zero_flag), .Y
       (o_exp_result[2]));
  NOR2BX1HVT g162(.AN (w_exp_result[5]), .B (i_zero_flag), .Y
       (o_exp_result[5]));
  NOR2BX1HVT g163(.AN (w_exp_result[3]), .B (i_zero_flag), .Y
       (o_exp_result[3]));
  NOR2BX1HVT g164(.AN (w_exp_result[1]), .B (i_zero_flag), .Y
       (o_exp_result[1]));
endmodule

module EXP_rounding_SIZE_DATA8(i_carry_rounding, i_exp_result,
     o_exp_result);
  input i_carry_rounding;
  input [7:0] i_exp_result;
  output [7:0] o_exp_result;
  wire i_carry_rounding;
  wire [7:0] i_exp_result;
  wire [7:0] o_exp_result;
  wire n_0, n_2, n_4, n_6, n_8, n_10, n_12;
  XNOR2X1HVT g173(.A (i_exp_result[7]), .B (n_12), .Y
       (o_exp_result[7]));
  XNOR2X1HVT g174(.A (i_exp_result[6]), .B (n_10), .Y
       (o_exp_result[6]));
  NAND2BXLHVT g175(.AN (n_10), .B (i_exp_result[6]), .Y (n_12));
  XNOR2X1HVT g176(.A (i_exp_result[5]), .B (n_8), .Y (o_exp_result[5]));
  NAND2BX1HVT g177(.AN (n_8), .B (i_exp_result[5]), .Y (n_10));
  XNOR2X1HVT g178(.A (i_exp_result[4]), .B (n_6), .Y (o_exp_result[4]));
  NAND2BX1HVT g179(.AN (n_6), .B (i_exp_result[4]), .Y (n_8));
  XNOR2X1HVT g180(.A (i_exp_result[3]), .B (n_4), .Y (o_exp_result[3]));
  NAND2BX1HVT g181(.AN (n_4), .B (i_exp_result[3]), .Y (n_6));
  XNOR2X1HVT g182(.A (i_exp_result[2]), .B (n_2), .Y (o_exp_result[2]));
  NAND2BX1HVT g183(.AN (n_2), .B (i_exp_result[2]), .Y (n_4));
  XNOR2X1HVT g184(.A (i_exp_result[1]), .B (n_0), .Y (o_exp_result[1]));
  NAND2BX1HVT g185(.AN (n_0), .B (i_exp_result[1]), .Y (n_2));
  XOR2XLHVT g186(.A (i_exp_result[0]), .B (i_carry_rounding), .Y
       (o_exp_result[0]));
  NAND2X1HVT g187(.A (i_exp_result[0]), .B (i_carry_rounding), .Y
       (n_0));
endmodule

module CLA_4bit(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_10, n_12, n_13, n_16;
  XNOR2X1HVT g263(.A (n_2), .B (n_16), .Y (sum[3]));
  AOI21X1HVT g264(.A0 (n_6), .A1 (n_12), .B0 (n_5), .Y (n_16));
  NAND2BX1HVT g265(.AN (o_p), .B (n_13), .Y (o_g));
  CLKXOR2X1HVT g266(.A (n_6), .B (n_12), .Y (sum[2]));
  AOI222X1HVT g267(.A0 (a[3]), .A1 (b[3]), .B0 (n_10), .B1 (n_8), .C0
       (n_5), .C1 (n_2), .Y (n_13));
  OAI21X1HVT g268(.A0 (n_7), .A1 (n_4), .B0 (n_0), .Y (n_12));
  NOR3BX1HVT g269(.AN (n_8), .B (n_7), .C (sum[0]), .Y (o_p));
  OAI2BB1X1HVT g270(.A0N (b[0]), .A1N (n_1), .B0 (n_0), .Y (n_10));
  XNOR2X1HVT g271(.A (n_1), .B (n_4), .Y (sum[1]));
  AND2XLHVT g272(.A (n_2), .B (n_6), .Y (n_8));
  INVX1HVT g273(.A (n_1), .Y (n_7));
  ADDHX1HVT g274(.A (a[2]), .B (b[2]), .CO (n_5), .S (n_6));
  NOR2BX1HVT g275(.AN (sum[0]), .B (b[0]), .Y (n_4));
  XNOR2X1HVT g276(.A (a[0]), .B (b[0]), .Y (sum[0]));
  XOR2XLHVT g277(.A (a[3]), .B (b[3]), .Y (n_2));
  XOR2XLHVT g278(.A (a[1]), .B (b[1]), .Y (n_1));
  NAND2X1HVT g279(.A (a[1]), .B (b[1]), .Y (n_0));
endmodule

module CLA_4bit_1(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1;
  assign o_g = 1'b0;
  assign o_p = 1'b0;
  assign sum[1] = 1'b0;
  assign sum[2] = 1'b0;
  assign sum[3] = 1'b0;
  XNOR2X1HVT g68(.A (n_1), .B (cin), .Y (sum[0]));
  XNOR2X1HVT g69(.A (a[0]), .B (b[0]), .Y (n_1));
endmodule

module CLA_8bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire n_6, n_7, n_9, w_C, w_G, w_G_22, w_P, w_P_20;
  assign o_carry = 1'b0;
  assign o_sum[5] = 1'b0;
  assign o_sum[6] = 1'b0;
  assign o_sum[7] = 1'b0;
  CLA_4bit CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]), .cin
       (1'b1), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
  CLA_4bit_1 CLA_4BIT_UNIT_1(.a ({3'b000, i_data_a[4]}), .b ({3'b000,
       i_data_b[4]}), .cin (w_C), .sum ({n_6, n_7, n_9, o_sum[4]}),
       .o_p (w_P_20), .o_g (w_G_22));
  OR2XLHVT g7(.A (w_P), .B (w_G), .Y (w_C));
endmodule

module EXP_sub_SIZE_EXP_SUB8(i_data_a, i_data_b, o_sub);
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sub;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sub;
  wire UNCONNECTED0, n_0, n_1, n_2, n_3, n_4, n_13, n_14;
  wire n_15;
  assign o_sub[5] = 1'b0;
  assign o_sub[6] = 1'b0;
  assign o_sub[7] = 1'b0;
  CLA_8bit CLA_8BIT_UNIT(.i_carry (1'b1), .i_data_a ({3'b000,
       i_data_a[4:0]}), .i_data_b ({3'b000, n_0, n_3, n_4, n_1, n_2}),
       .o_sum ({n_13, n_14, n_15, o_sub[4:0]}), .o_carry
       (UNCONNECTED0));
  INVX1HVT g10(.A (i_data_b[2]), .Y (n_4));
  INVX1HVT g11(.A (i_data_b[3]), .Y (n_3));
  INVX1HVT g13(.A (i_data_b[0]), .Y (n_2));
  INVX1HVT g12(.A (i_data_b[1]), .Y (n_1));
  INVX1HVT g9(.A (i_data_b[4]), .Y (n_0));
endmodule

module COMP_4bit_1(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12;
  OAI21X1HVT g329(.A0 (i_data_a[3]), .A1 (n_11), .B0 (n_12), .Y
       (o_less));
  OAI2BB1X1HVT g330(.A0N (i_data_a[3]), .A1N (n_11), .B0 (i_data_b[3]),
       .Y (n_12));
  AOI22X1HVT g331(.A0 (n_3), .A1 (n_10), .B0 (i_data_b[2]), .B1 (n_2),
       .Y (n_11));
  OAI32X1HVT g332(.A0 (i_data_a[0]), .A1 (n_1), .A2 (n_7), .B0
       (i_data_a[1]), .B1 (n_0), .Y (n_10));
  AND4XLHVT g333(.A (n_5), .B (n_8), .C (n_6), .D (n_4), .Y (o_equal));
  ADDHX1HVT g334(.A (i_data_a[1]), .B (n_0), .CO (n_7), .S (n_8));
  MXI2XLHVT g335(.A (i_data_b[0]), .B (n_1), .S0 (i_data_a[0]), .Y
       (n_6));
  MXI2XLHVT g336(.A (i_data_a[2]), .B (n_2), .S0 (i_data_b[2]), .Y
       (n_5));
  XNOR2X1HVT g337(.A (i_data_b[3]), .B (i_data_a[3]), .Y (n_4));
  NAND2BXLHVT g338(.AN (i_data_b[2]), .B (i_data_a[2]), .Y (n_3));
  INVX1HVT g339(.A (i_data_a[2]), .Y (n_2));
  INVX1HVT g340(.A (i_data_b[0]), .Y (n_1));
  INVX1HVT g341(.A (i_data_b[1]), .Y (n_0));
endmodule

module COMP_4bit(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  assign o_equal = 1'b0;
  OAI22X1HVT g229(.A0 (n_4), .A1 (n_8), .B0 (i_data_a[3]), .B1 (n_2),
       .Y (o_less));
  AOI22X1HVT g230(.A0 (n_5), .A1 (n_7), .B0 (i_data_b[2]), .B1 (n_0),
       .Y (n_8));
  OAI32X1HVT g231(.A0 (i_data_a[0]), .A1 (n_3), .A2 (n_6), .B0
       (i_data_a[1]), .B1 (n_1), .Y (n_7));
  NOR2BX1HVT g232(.AN (i_data_a[1]), .B (i_data_b[1]), .Y (n_6));
  NAND2BX1HVT g233(.AN (i_data_b[2]), .B (i_data_a[2]), .Y (n_5));
  NOR2BX1HVT g234(.AN (i_data_a[3]), .B (i_data_b[3]), .Y (n_4));
  INVX1HVT g235(.A (i_data_b[0]), .Y (n_3));
  INVX1HVT g236(.A (i_data_b[3]), .Y (n_2));
  INVX1HVT g237(.A (i_data_b[1]), .Y (n_1));
  INVX1HVT g238(.A (i_data_a[2]), .Y (n_0));
endmodule

module COMP_8bit_SIZE_DATA8(i_data_a, i_data_b, o_less);
  input [7:0] i_data_a, i_data_b;
  output o_less;
  wire [7:0] i_data_a, i_data_b;
  wire o_less;
  wire w_equal_high, w_equal_low, w_less_high, w_less_low;
  COMP_4bit_1 u_high(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_high), .o_equal (w_equal_high));
  COMP_4bit u_low(.i_data_a (i_data_a[3:0]), .i_data_b (i_data_b[3:0]),
       .o_less (w_less_low), .o_equal (w_equal_low));
  AO21X1HVT g16(.A0 (w_equal_high), .A1 (w_less_low), .B0
       (w_less_high), .Y (o_less));
endmodule

module EXP_swap_SIZE_DATA8(i_data_a, i_data_b, o_compare, o_less_data,
     o_greater_data);
  input [7:0] i_data_a, i_data_b;
  output o_compare;
  output [7:0] o_less_data, o_greater_data;
  wire [7:0] i_data_a, i_data_b;
  wire o_compare;
  wire [7:0] o_less_data, o_greater_data;
  assign o_less_data[5] = 1'b0;
  assign o_less_data[6] = 1'b0;
  assign o_less_data[7] = 1'b0;
  COMP_8bit_SIZE_DATA8 COMP_LESS_UNIT(.i_data_a (i_data_a), .i_data_b
       (i_data_b), .o_less (o_compare));
  MX2XLHVT g217(.A (i_data_b[4]), .B (i_data_a[4]), .S0 (o_compare), .Y
       (o_less_data[4]));
  MX2XLHVT g218(.A (i_data_b[1]), .B (i_data_a[1]), .S0 (o_compare), .Y
       (o_less_data[1]));
  MX2XLHVT g219(.A (i_data_a[6]), .B (i_data_b[6]), .S0 (o_compare), .Y
       (o_greater_data[6]));
  MX2X1HVT g220(.A (i_data_a[5]), .B (i_data_b[5]), .S0 (o_compare), .Y
       (o_greater_data[5]));
  MX2XLHVT g221(.A (i_data_b[0]), .B (i_data_a[0]), .S0 (o_compare), .Y
       (o_less_data[0]));
  MX2XLHVT g222(.A (i_data_a[4]), .B (i_data_b[4]), .S0 (o_compare), .Y
       (o_greater_data[4]));
  MX2XLHVT g223(.A (i_data_a[0]), .B (i_data_b[0]), .S0 (o_compare), .Y
       (o_greater_data[0]));
  MX2XLHVT g224(.A (i_data_b[3]), .B (i_data_a[3]), .S0 (o_compare), .Y
       (o_less_data[3]));
  MX2XLHVT g225(.A (i_data_b[2]), .B (i_data_a[2]), .S0 (o_compare), .Y
       (o_less_data[2]));
  MX2X1HVT g226(.A (i_data_a[2]), .B (i_data_b[2]), .S0 (o_compare), .Y
       (o_greater_data[2]));
  MX2X1HVT g227(.A (i_data_a[1]), .B (i_data_b[1]), .S0 (o_compare), .Y
       (o_greater_data[1]));
  MX2XLHVT g228(.A (i_data_a[7]), .B (i_data_b[7]), .S0 (o_compare), .Y
       (o_greater_data[7]));
  MX2X1HVT g229(.A (i_data_a[3]), .B (i_data_b[3]), .S0 (o_compare), .Y
       (o_greater_data[3]));
endmodule

module LOPD_8bit(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_12;
  AOI2BB1XLHVT g263(.A0N (n_12), .A1N (i_data[6]), .B0 (i_data[7]), .Y
       (o_pos_one[0]));
  AOI2BB1XLHVT g264(.A0N (n_7), .A1N (i_data[4]), .B0 (i_data[5]), .Y
       (n_12));
  AOI21X1HVT g265(.A0 (n_5), .A1 (n_1), .B0 (n_0), .Y (o_pos_one[1]));
  NOR2X1HVT g266(.A (n_8), .B (n_0), .Y (o_pos_one[2]));
  NOR3BX1HVT g267(.AN (n_1), .B (n_6), .C (n_0), .Y (o_zero_flag));
  NAND2X1HVT g268(.A (n_6), .B (n_1), .Y (n_8));
  AOI2BB1XLHVT g269(.A0N (n_3), .A1N (i_data[2]), .B0 (i_data[3]), .Y
       (n_7));
  NAND2X1HVT g270(.A (n_2), .B (n_4), .Y (n_6));
  NAND2BX1HVT g271(.AN (n_2), .B (n_4), .Y (n_5));
  NOR2BX1HVT g272(.AN (i_data[0]), .B (i_data[1]), .Y (n_3));
  NOR2X1HVT g273(.A (i_data[2]), .B (i_data[3]), .Y (n_4));
  NOR2X1HVT g274(.A (i_data[0]), .B (i_data[1]), .Y (n_2));
  NOR2X1HVT g275(.A (i_data[4]), .B (i_data[5]), .Y (n_1));
  OR2XLHVT g276(.A (i_data[6]), .B (i_data[7]), .Y (n_0));
endmodule

module LOPD_8bit_1(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_12;
  AOI2BB1XLHVT g263(.A0N (n_12), .A1N (i_data[6]), .B0 (i_data[7]), .Y
       (o_pos_one[0]));
  AOI2BB1XLHVT g264(.A0N (n_7), .A1N (i_data[4]), .B0 (i_data[5]), .Y
       (n_12));
  AOI21X1HVT g265(.A0 (n_5), .A1 (n_1), .B0 (n_0), .Y (o_pos_one[1]));
  NOR2X1HVT g266(.A (n_8), .B (n_0), .Y (o_pos_one[2]));
  NOR3BX1HVT g267(.AN (n_1), .B (n_6), .C (n_0), .Y (o_zero_flag));
  NAND2X1HVT g268(.A (n_6), .B (n_1), .Y (n_8));
  AOI2BB1XLHVT g269(.A0N (n_3), .A1N (i_data[2]), .B0 (i_data[3]), .Y
       (n_7));
  NAND2X1HVT g270(.A (n_2), .B (n_4), .Y (n_6));
  NAND2BX1HVT g271(.AN (n_2), .B (n_4), .Y (n_5));
  NOR2BX1HVT g272(.AN (i_data[0]), .B (i_data[1]), .Y (n_3));
  NOR2X1HVT g273(.A (i_data[2]), .B (i_data[3]), .Y (n_4));
  NOR2X1HVT g274(.A (i_data[0]), .B (i_data[1]), .Y (n_2));
  NOR2X1HVT g275(.A (i_data[4]), .B (i_data[5]), .Y (n_1));
  OR2XLHVT g276(.A (i_data[6]), .B (i_data[7]), .Y (n_0));
endmodule

module LOPD_16bit(i_data, o_pos_one, o_zero_flag);
  input [15:0] i_data;
  output [3:0] o_pos_one;
  output o_zero_flag;
  wire [15:0] i_data;
  wire [3:0] o_pos_one;
  wire o_zero_flag;
  wire [2:0] w_pos_one_0;
  wire [2:0] w_pos_one_1;
  wire w_zero_flag_0;
  LOPD_8bit LOPD_8bit_unit_0(.i_data (i_data[7:0]), .o_pos_one
       (w_pos_one_0), .o_zero_flag (w_zero_flag_0));
  LOPD_8bit_1 LOPD_8bit_unit_1(.i_data (i_data[15:8]), .o_pos_one
       (w_pos_one_1), .o_zero_flag (o_pos_one[3]));
  MX2XLHVT g62(.A (w_pos_one_1[2]), .B (w_pos_one_0[2]), .S0
       (o_pos_one[3]), .Y (o_pos_one[2]));
  MX2XLHVT g63(.A (w_pos_one_1[1]), .B (w_pos_one_0[1]), .S0
       (o_pos_one[3]), .Y (o_pos_one[1]));
  MX2XLHVT g64(.A (w_pos_one_1[0]), .B (w_pos_one_0[0]), .S0
       (o_pos_one[3]), .Y (o_pos_one[0]));
  AND2X1HVT g65(.A (o_pos_one[3]), .B (w_zero_flag_0), .Y
       (o_zero_flag));
endmodule

module LOPD_8bit_2(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_12;
  AOI2BB1X1HVT g263(.A0N (n_12), .A1N (i_data[6]), .B0 (i_data[7]), .Y
       (o_pos_one[0]));
  AOI2BB1XLHVT g264(.A0N (n_7), .A1N (i_data[4]), .B0 (i_data[5]), .Y
       (n_12));
  AOI21X1HVT g265(.A0 (n_5), .A1 (n_1), .B0 (n_0), .Y (o_pos_one[1]));
  NOR2X1HVT g266(.A (n_8), .B (n_0), .Y (o_pos_one[2]));
  NOR3BX1HVT g267(.AN (n_1), .B (n_6), .C (n_0), .Y (o_zero_flag));
  NAND2X1HVT g268(.A (n_6), .B (n_1), .Y (n_8));
  AOI2BB1XLHVT g269(.A0N (n_3), .A1N (i_data[2]), .B0 (i_data[3]), .Y
       (n_7));
  NAND2X1HVT g270(.A (n_2), .B (n_4), .Y (n_6));
  NAND2BX1HVT g271(.AN (n_2), .B (n_4), .Y (n_5));
  NOR2BX1HVT g272(.AN (i_data[0]), .B (i_data[1]), .Y (n_3));
  NOR2X1HVT g273(.A (i_data[2]), .B (i_data[3]), .Y (n_4));
  NOR2X1HVT g274(.A (i_data[0]), .B (i_data[1]), .Y (n_2));
  NOR2X1HVT g275(.A (i_data[4]), .B (i_data[5]), .Y (n_1));
  OR2X1HVT g276(.A (i_data[6]), .B (i_data[7]), .Y (n_0));
endmodule

module LOPD_24bit_SIZE_DATA24_SIZE_LOPD5(i_data, o_one_position,
     o_zero_flag);
  input [23:0] i_data;
  output [4:0] o_one_position;
  output o_zero_flag;
  wire [23:0] i_data;
  wire [4:0] o_one_position;
  wire o_zero_flag;
  wire [3:0] LOPD16_o_pos_one;
  wire [2:0] LOPD8_o_pos_one;
  wire LOPD8_o_zero_flag, n_0, n_1, n_2, n_3, n_4;
  LOPD_16bit LOPD_16bit_UNIT_MSB(.i_data (i_data[23:8]), .o_pos_one
       (LOPD16_o_pos_one), .o_zero_flag (o_one_position[4]));
  LOPD_8bit_2 LOPD_8bit_UNIT_LSB(.i_data (i_data[7:0]), .o_pos_one
       (LOPD8_o_pos_one), .o_zero_flag (LOPD8_o_zero_flag));
  NAND2X1HVT g124(.A (n_1), .B (n_4), .Y (o_one_position[2]));
  NAND2X1HVT g125(.A (n_1), .B (n_3), .Y (o_one_position[0]));
  NAND2X1HVT g126(.A (n_1), .B (n_2), .Y (o_one_position[1]));
  OAI2BB1X1HVT g127(.A0N (LOPD16_o_pos_one[3]), .A1N (n_0), .B0 (n_1),
       .Y (o_one_position[3]));
  AOI22X1HVT g128(.A0 (n_0), .A1 (LOPD16_o_pos_one[2]), .B0
       (LOPD8_o_pos_one[2]), .B1 (o_one_position[4]), .Y (n_4));
  AOI22X1HVT g129(.A0 (n_0), .A1 (LOPD16_o_pos_one[0]), .B0
       (LOPD8_o_pos_one[0]), .B1 (o_one_position[4]), .Y (n_3));
  AOI22X1HVT g130(.A0 (n_0), .A1 (LOPD16_o_pos_one[1]), .B0
       (LOPD8_o_pos_one[1]), .B1 (o_one_position[4]), .Y (n_2));
  INVX1HVT g131(.A (o_zero_flag), .Y (n_1));
  NOR2BX1HVT g132(.AN (LOPD8_o_zero_flag), .B (n_0), .Y (o_zero_flag));
  INVX1HVT g133(.A (o_one_position[4]), .Y (n_0));
endmodule

module CLA_4bit_2(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_11, n_12, n_14, n_16, n_18;
  XNOR2X1HVT g306(.A (n_2), .B (n_18), .Y (sum[3]));
  AOI21X1HVT g307(.A0 (n_7), .A1 (n_16), .B0 (n_6), .Y (n_18));
  CLKXOR2X1HVT g308(.A (n_7), .B (n_16), .Y (sum[2]));
  OAI21X1HVT g309(.A0 (n_5), .A1 (n_11), .B0 (n_0), .Y (n_16));
  OAI2BB1X1HVT g310(.A0N (cin), .A1N (o_p), .B0 (n_14), .Y (o_g));
  AOI22X1HVT g311(.A0 (n_2), .A1 (n_12), .B0 (a[3]), .B1 (b[3]), .Y
       (n_14));
  CLKXOR2X1HVT g312(.A (n_5), .B (n_11), .Y (sum[1]));
  AO21XLHVT g313(.A0 (n_7), .A1 (n_9), .B0 (n_6), .Y (n_12));
  AOI21X1HVT g314(.A0 (cin), .A1 (n_4), .B0 (n_3), .Y (n_11));
  AND4XLHVT g315(.A (n_4), .B (n_2), .C (n_1), .D (n_7), .Y (o_p));
  OAI2BB1X1HVT g316(.A0N (n_3), .A1N (n_1), .B0 (n_0), .Y (n_9));
  CLKXOR2X1HVT g317(.A (cin), .B (n_4), .Y (sum[0]));
  INVX1HVT g318(.A (n_1), .Y (n_5));
  ADDHX1HVT g319(.A (a[2]), .B (b[2]), .CO (n_6), .S (n_7));
  ADDHX1HVT g320(.A (a[0]), .B (b[0]), .CO (n_3), .S (n_4));
  CLKXOR2X1HVT g321(.A (a[3]), .B (b[3]), .Y (n_2));
  XOR2XLHVT g322(.A (a[1]), .B (b[1]), .Y (n_1));
  NAND2X1HVT g323(.A (a[1]), .B (b[1]), .Y (n_0));
endmodule

module CLA_4bit_3(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_13, n_15;
  OAI21X1HVT g441(.A0 (n_5), .A1 (n_15), .B0 (n_0), .Y (o_g));
  CLKXOR2X1HVT g442(.A (n_5), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g443(.A0 (n_6), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  CLKXOR2X1HVT g444(.A (n_6), .B (n_13), .Y (sum[2]));
  OAI2BB1X1HVT g445(.A0N (n_4), .A1N (n_9), .B0 (n_3), .Y (n_13));
  XNOR2X1HVT g446(.A (n_8), .B (n_9), .Y (sum[1]));
  NOR4BX1HVT g447(.AN (n_6), .B (n_8), .C (n_7), .D (n_5), .Y (o_p));
  XNOR2X1HVT g448(.A (n_7), .B (cin), .Y (sum[0]));
  OAI2BB1X1HVT g449(.A0N (n_2), .A1N (cin), .B0 (n_1), .Y (n_9));
  NAND2X1HVT g450(.A (n_3), .B (n_4), .Y (n_8));
  NAND2X1HVT g451(.A (n_1), .B (n_2), .Y (n_7));
  CLKXOR2X1HVT g452(.A (a[2]), .B (b[2]), .Y (n_6));
  XNOR2X1HVT g453(.A (a[3]), .B (b[3]), .Y (n_5));
  OR2X1HVT g454(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2X1HVT g455(.A (a[1]), .B (b[1]), .Y (n_3));
  NAND2X1HVT g456(.A (a[3]), .B (b[3]), .Y (n_0));
  OR2XLHVT g457(.A (a[0]), .B (b[0]), .Y (n_2));
  NAND2X1HVT g458(.A (a[0]), .B (b[0]), .Y (n_1));
endmodule

module CLA_4bit_4(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_13, n_15;
  OAI21X1HVT g437(.A0 (n_5), .A1 (n_15), .B0 (n_0), .Y (o_g));
  XOR2XLHVT g438(.A (n_5), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g439(.A0 (n_6), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  CLKXOR2X1HVT g440(.A (n_6), .B (n_13), .Y (sum[2]));
  OAI2BB1X1HVT g441(.A0N (n_4), .A1N (n_9), .B0 (n_3), .Y (n_13));
  XNOR2X1HVT g442(.A (n_8), .B (n_9), .Y (sum[1]));
  NOR4BX1HVT g443(.AN (n_6), .B (n_8), .C (n_7), .D (n_5), .Y (o_p));
  XNOR2X1HVT g444(.A (n_7), .B (cin), .Y (sum[0]));
  OAI2BB1X1HVT g445(.A0N (n_2), .A1N (cin), .B0 (n_1), .Y (n_9));
  NAND2X1HVT g446(.A (n_3), .B (n_4), .Y (n_8));
  NAND2X1HVT g447(.A (n_1), .B (n_2), .Y (n_7));
  CLKXOR2X1HVT g448(.A (a[2]), .B (b[2]), .Y (n_6));
  XNOR2X1HVT g449(.A (a[3]), .B (b[3]), .Y (n_5));
  OR2XLHVT g450(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2X1HVT g451(.A (a[1]), .B (b[1]), .Y (n_3));
  NAND2X1HVT g452(.A (a[3]), .B (b[3]), .Y (n_0));
  OR2XLHVT g453(.A (a[0]), .B (b[0]), .Y (n_2));
  NAND2X1HVT g454(.A (a[0]), .B (b[0]), .Y (n_1));
endmodule

module CLA_4bit_5(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_13, n_15;
  OAI21X1HVT g441(.A0 (n_6), .A1 (n_15), .B0 (n_1), .Y (o_g));
  CLKXOR2X1HVT g442(.A (n_6), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g443(.A0 (n_7), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  CLKXOR2X1HVT g444(.A (n_7), .B (n_13), .Y (sum[2]));
  OAI21X1HVT g445(.A0 (n_5), .A1 (n_10), .B0 (n_4), .Y (n_13));
  NOR4BX1HVT g447(.AN (n_7), .B (n_6), .C (n_9), .D (n_8), .Y (o_p));
  XNOR2X1HVT g448(.A (n_8), .B (cin), .Y (sum[0]));
  AOI21X1HVT g449(.A0 (n_3), .A1 (cin), .B0 (n_2), .Y (n_10));
  NAND2BX1HVT g451(.AN (n_5), .B (n_4), .Y (n_9));
  NAND2BX1HVT g452(.AN (n_2), .B (n_3), .Y (n_8));
  CLKXOR2X1HVT g453(.A (a[2]), .B (b[2]), .Y (n_7));
  XNOR2X1HVT g454(.A (a[3]), .B (b[3]), .Y (n_6));
  NOR2X1HVT g455(.A (a[1]), .B (b[1]), .Y (n_5));
  NAND2X1HVT g456(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2X1HVT g457(.A (a[3]), .B (b[3]), .Y (n_1));
  OR2XLHVT g458(.A (a[0]), .B (b[0]), .Y (n_3));
  AND2XLHVT g459(.A (a[0]), .B (b[0]), .Y (n_2));
  XOR2XLHVT g2(.A (n_9), .B (n_10), .Y (sum[1]));
endmodule

module CLA_4bit_6(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_13, n_15;
  OAI21X1HVT g441(.A0 (n_6), .A1 (n_15), .B0 (n_1), .Y (o_g));
  XOR2XLHVT g442(.A (n_6), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g443(.A0 (n_7), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  XOR2XLHVT g444(.A (n_7), .B (n_13), .Y (sum[2]));
  OAI21X1HVT g445(.A0 (n_5), .A1 (n_10), .B0 (n_4), .Y (n_13));
  NOR4BX1HVT g447(.AN (n_7), .B (n_6), .C (n_9), .D (n_8), .Y (o_p));
  XNOR2X1HVT g448(.A (n_8), .B (cin), .Y (sum[0]));
  AOI21X1HVT g449(.A0 (n_3), .A1 (cin), .B0 (n_2), .Y (n_10));
  NAND2BX1HVT g451(.AN (n_5), .B (n_4), .Y (n_9));
  NAND2BX1HVT g452(.AN (n_2), .B (n_3), .Y (n_8));
  CLKXOR2X1HVT g453(.A (a[2]), .B (b[2]), .Y (n_7));
  XNOR2X1HVT g454(.A (a[3]), .B (b[3]), .Y (n_6));
  NOR2X1HVT g455(.A (a[1]), .B (b[1]), .Y (n_5));
  NAND2X1HVT g456(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2X1HVT g457(.A (a[3]), .B (b[3]), .Y (n_1));
  OR2XLHVT g458(.A (a[0]), .B (b[0]), .Y (n_3));
  AND2XLHVT g459(.A (a[0]), .B (b[0]), .Y (n_2));
  XOR2XLHVT g2(.A (n_9), .B (n_10), .Y (sum[1]));
endmodule

module CLA_4bit_7(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_8, n_10;
  wire n_12;
  OAI21X1HVT g360(.A0 (n_4), .A1 (n_12), .B0 (n_1), .Y (o_g));
  CLKXOR2X1HVT g361(.A (n_4), .B (n_12), .Y (sum[3]));
  AOI22X1HVT g362(.A0 (n_3), .A1 (n_10), .B0 (a[2]), .B1 (b[2]), .Y
       (n_12));
  CLKXOR2X1HVT g363(.A (n_3), .B (n_10), .Y (sum[2]));
  OAI21X1HVT g364(.A0 (n_5), .A1 (n_8), .B0 (n_0), .Y (n_10));
  CLKXOR2X1HVT g365(.A (n_5), .B (n_8), .Y (sum[1]));
  AOI22X1HVT g366(.A0 (n_2), .A1 (cin), .B0 (a[0]), .B1 (b[0]), .Y
       (n_8));
  NOR4BBX1HVT g367(.AN (n_3), .BN (n_2), .C (n_5), .D (n_4), .Y (o_p));
  CLKXOR2X1HVT g368(.A (n_2), .B (cin), .Y (sum[0]));
  XNOR2X1HVT g369(.A (a[1]), .B (b[1]), .Y (n_5));
  XNOR2X1HVT g370(.A (a[3]), .B (b[3]), .Y (n_4));
  CLKXOR2X1HVT g371(.A (a[2]), .B (b[2]), .Y (n_3));
  XOR2XLHVT g372(.A (a[0]), .B (b[0]), .Y (n_2));
  NAND2X1HVT g373(.A (a[3]), .B (b[3]), .Y (n_1));
  NAND2X1HVT g374(.A (a[1]), .B (b[1]), .Y (n_0));
endmodule

module CLA_4bit_8(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_13, n_15;
  OAI21X1HVT g499(.A0 (n_5), .A1 (n_15), .B0 (n_0), .Y (o_g));
  CLKXOR2X1HVT g500(.A (n_5), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g501(.A0 (n_6), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  CLKXOR2X1HVT g502(.A (n_6), .B (n_13), .Y (sum[2]));
  OAI2BB1X1HVT g503(.A0N (n_4), .A1N (n_9), .B0 (n_3), .Y (n_13));
  XNOR2X1HVT g504(.A (n_8), .B (n_9), .Y (sum[1]));
  NOR4BX1HVT g505(.AN (n_6), .B (n_5), .C (n_8), .D (n_7), .Y (o_p));
  XNOR2X1HVT g506(.A (n_7), .B (cin), .Y (sum[0]));
  OAI2BB1X1HVT g507(.A0N (n_2), .A1N (cin), .B0 (n_1), .Y (n_9));
  NAND2X1HVT g508(.A (n_3), .B (n_4), .Y (n_8));
  NAND2X1HVT g509(.A (n_1), .B (n_2), .Y (n_7));
  XOR2XLHVT g510(.A (a[2]), .B (b[2]), .Y (n_6));
  XNOR2X1HVT g511(.A (a[3]), .B (b[3]), .Y (n_5));
  OR2XLHVT g512(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2X1HVT g513(.A (a[1]), .B (b[1]), .Y (n_3));
  NAND2XLHVT g514(.A (a[3]), .B (b[3]), .Y (n_0));
  OR2XLHVT g515(.A (a[0]), .B (b[0]), .Y (n_2));
  NAND2X1HVT g516(.A (a[0]), .B (b[0]), .Y (n_1));
endmodule

module CLA_28bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [27:0] i_data_a, i_data_b;
  output [27:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [27:0] i_data_a, i_data_b;
  wire [27:0] o_sum;
  wire o_carry;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, \w_c[1] , \w_c[2] , \w_c[3] , \w_c[4] ,
       \w_c[5] ;
  wire \w_c[6] , w_g, w_g_59, w_g_65, w_g_75, w_g_90, w_g_111, w_g_139;
  wire w_p, w_p_58, w_p_64, w_p_74, w_p_89, w_p_110, w_p_138;
  CLA_4bit_2 \CLA_BLOCK_GEN[0].CLA_4BIT_UNIT (.a (i_data_a[3:0]), .b
       (i_data_b[3:0]), .cin (i_carry), .sum (o_sum[3:0]), .o_p (w_p),
       .o_g (w_g));
  CLA_4bit_3 \CLA_BLOCK_GEN[1].CLA_4BIT_UNIT (.a (i_data_a[7:4]), .b
       (i_data_b[7:4]), .cin (\w_c[1] ), .sum (o_sum[7:4]), .o_p
       (w_p_58), .o_g (w_g_59));
  CLA_4bit_4 \CLA_BLOCK_GEN[2].CLA_4BIT_UNIT (.a (i_data_a[11:8]), .b
       (i_data_b[11:8]), .cin (\w_c[2] ), .sum (o_sum[11:8]), .o_p
       (w_p_64), .o_g (w_g_65));
  CLA_4bit_5 \CLA_BLOCK_GEN[3].CLA_4BIT_UNIT (.a (i_data_a[15:12]), .b
       (i_data_b[15:12]), .cin (\w_c[3] ), .sum (o_sum[15:12]), .o_p
       (w_p_74), .o_g (w_g_75));
  CLA_4bit_6 \CLA_BLOCK_GEN[4].CLA_4BIT_UNIT (.a (i_data_a[19:16]), .b
       (i_data_b[19:16]), .cin (\w_c[4] ), .sum (o_sum[19:16]), .o_p
       (w_p_89), .o_g (w_g_90));
  CLA_4bit_7 \CLA_BLOCK_GEN[5].CLA_4BIT_UNIT (.a (i_data_a[23:20]), .b
       (i_data_b[23:20]), .cin (\w_c[5] ), .sum (o_sum[23:20]), .o_p
       (w_p_110), .o_g (w_g_111));
  CLA_4bit_8 \CLA_BLOCK_GEN[6].CLA_4BIT_UNIT (.a (i_data_a[27:24]), .b
       (i_data_b[27:24]), .cin (\w_c[6] ), .sum (o_sum[27:24]), .o_p
       (w_p_138), .o_g (w_g_139));
  AO21X1HVT g141(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (\w_c[1] ));
  OR2XLHVT g159(.A (n_26), .B (w_g_59), .Y (\w_c[2] ));
  NOR2BX1HVT g160(.AN (w_p_58), .B (n_25), .Y (n_26));
  AOI21XLHVT g161(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_25));
  NAND2BX1HVT g186(.AN (w_g_65), .B (n_24), .Y (\w_c[3] ));
  OAI21X1HVT g187(.A0 (n_23), .A1 (w_g_59), .B0 (w_p_64), .Y (n_24));
  NOR2BX1HVT g188(.AN (w_p_58), .B (n_22), .Y (n_23));
  AOI21XLHVT g189(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_22));
  NAND2BX1HVT g224(.AN (w_g_75), .B (n_21), .Y (\w_c[4] ));
  OAI21X1HVT g225(.A0 (n_20), .A1 (w_g_65), .B0 (w_p_74), .Y (n_21));
  OA21X1HVT g226(.A0 (n_19), .A1 (w_g_59), .B0 (w_p_64), .Y (n_20));
  NOR2BX1HVT g227(.AN (w_p_58), .B (n_18), .Y (n_19));
  AOI21XLHVT g228(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_18));
  NAND2BXLHVT g287(.AN (w_g_139), .B (n_17), .Y (o_carry));
  OAI21X1HVT g288(.A0 (n_16), .A1 (w_g_111), .B0 (w_p_138), .Y (n_17));
  OA21X1HVT g289(.A0 (n_15), .A1 (w_g_90), .B0 (w_p_110), .Y (n_16));
  OA21X1HVT g290(.A0 (n_14), .A1 (w_g_75), .B0 (w_p_89), .Y (n_15));
  OA21X1HVT g291(.A0 (n_13), .A1 (w_g_65), .B0 (w_p_74), .Y (n_14));
  OA21X1HVT g292(.A0 (n_12), .A1 (w_g_59), .B0 (w_p_64), .Y (n_13));
  NOR2BX1HVT g293(.AN (w_p_58), .B (n_11), .Y (n_12));
  AOI21XLHVT g294(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_11));
  NAND2BX1HVT g253(.AN (w_g_90), .B (n_10), .Y (\w_c[5] ));
  OAI21X1HVT g254(.A0 (n_9), .A1 (w_g_75), .B0 (w_p_89), .Y (n_10));
  OA21X1HVT g255(.A0 (n_8), .A1 (w_g_65), .B0 (w_p_74), .Y (n_9));
  OA21X1HVT g256(.A0 (n_7), .A1 (w_g_59), .B0 (w_p_64), .Y (n_8));
  NOR2BX1HVT g257(.AN (w_p_58), .B (n_6), .Y (n_7));
  AOI21XLHVT g258(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_6));
  NAND2BX1HVT g295(.AN (w_g_111), .B (n_5), .Y (\w_c[6] ));
  OAI21X1HVT g296(.A0 (n_4), .A1 (w_g_90), .B0 (w_p_110), .Y (n_5));
  OA21X1HVT g297(.A0 (n_3), .A1 (w_g_75), .B0 (w_p_89), .Y (n_4));
  OA21X1HVT g298(.A0 (n_2), .A1 (w_g_65), .B0 (w_p_74), .Y (n_3));
  OA21X1HVT g259(.A0 (n_1), .A1 (w_g_59), .B0 (w_p_64), .Y (n_2));
  NOR2BX1HVT g260(.AN (w_p_58), .B (n_0), .Y (n_1));
  AOI21XLHVT g261(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_0));
endmodule

module MAN_ALU_NUM_OP1_SIZE_MAN28(i_fpu_op, i_sign_a, i_sign_b,
     i_man_max, i_man_min, o_man_alu, o_overflow);
  input [0:0] i_fpu_op;
  input i_sign_a, i_sign_b;
  input [27:0] i_man_max, i_man_min;
  output [27:0] o_man_alu;
  output o_overflow;
  wire [0:0] i_fpu_op;
  wire i_sign_a, i_sign_b;
  wire [27:0] i_man_max, i_man_min;
  wire [27:0] o_man_alu;
  wire o_overflow;
  wire [27:0] w_i_man_b;
  wire n_0, n_1, n_2, w_i_carry, w_overflow;
  CLA_28bit ALU_SUB_UNIT(.i_carry (w_i_carry), .i_data_a (i_man_max),
       .i_data_b (w_i_man_b), .o_sum (o_man_alu), .o_carry
       (w_overflow));
  MXI2XLHVT g117(.A (n_2), .B (w_i_carry), .S0 (i_man_min[3]), .Y
       (w_i_man_b[3]));
  MX2XLHVT g118(.A (w_i_carry), .B (n_2), .S0 (i_man_min[1]), .Y
       (w_i_man_b[1]));
  MXI2XLHVT g119(.A (n_2), .B (w_i_carry), .S0 (i_man_min[0]), .Y
       (w_i_man_b[0]));
  XNOR2X1HVT g120(.A (n_2), .B (i_man_min[2]), .Y (w_i_man_b[2]));
  INVX1HVT g121(.A (w_i_carry), .Y (n_2));
  XNOR2X1HVT g122(.A (i_fpu_op), .B (n_1), .Y (w_i_carry));
  XNOR2X1HVT g123(.A (i_sign_b), .B (i_sign_a), .Y (n_1));
  NOR2BX1HVT g69(.AN (w_overflow), .B (w_i_carry), .Y (o_overflow));
  MXI2XLHVT g255(.A (n_0), .B (w_i_carry), .S0 (i_man_min[18]), .Y
       (w_i_man_b[18]));
  MXI2XLHVT g256(.A (n_0), .B (w_i_carry), .S0 (i_man_min[25]), .Y
       (w_i_man_b[25]));
  MXI2XLHVT g257(.A (n_0), .B (w_i_carry), .S0 (i_man_min[23]), .Y
       (w_i_man_b[23]));
  MXI2XLHVT g258(.A (n_0), .B (w_i_carry), .S0 (i_man_min[19]), .Y
       (w_i_man_b[19]));
  MXI2XLHVT g259(.A (n_0), .B (w_i_carry), .S0 (i_man_min[11]), .Y
       (w_i_man_b[11]));
  MXI2XLHVT g260(.A (n_0), .B (w_i_carry), .S0 (i_man_min[10]), .Y
       (w_i_man_b[10]));
  MXI2XLHVT g261(.A (n_0), .B (w_i_carry), .S0 (i_man_min[27]), .Y
       (w_i_man_b[27]));
  MXI2XLHVT g262(.A (n_0), .B (w_i_carry), .S0 (i_man_min[9]), .Y
       (w_i_man_b[9]));
  MXI2XLHVT g263(.A (n_0), .B (w_i_carry), .S0 (i_man_min[8]), .Y
       (w_i_man_b[8]));
  MXI2XLHVT g264(.A (n_0), .B (w_i_carry), .S0 (i_man_min[22]), .Y
       (w_i_man_b[22]));
  MXI2XLHVT g265(.A (n_0), .B (w_i_carry), .S0 (i_man_min[17]), .Y
       (w_i_man_b[17]));
  MXI2XLHVT g266(.A (n_0), .B (w_i_carry), .S0 (i_man_min[7]), .Y
       (w_i_man_b[7]));
  MXI2XLHVT g267(.A (n_0), .B (w_i_carry), .S0 (i_man_min[15]), .Y
       (w_i_man_b[15]));
  MXI2XLHVT g268(.A (n_0), .B (w_i_carry), .S0 (i_man_min[16]), .Y
       (w_i_man_b[16]));
  MXI2XLHVT g269(.A (n_0), .B (w_i_carry), .S0 (i_man_min[5]), .Y
       (w_i_man_b[5]));
  MXI2XLHVT g270(.A (n_0), .B (w_i_carry), .S0 (i_man_min[4]), .Y
       (w_i_man_b[4]));
  MXI2XLHVT g271(.A (n_0), .B (w_i_carry), .S0 (i_man_min[26]), .Y
       (w_i_man_b[26]));
  MXI2XLHVT g272(.A (n_0), .B (w_i_carry), .S0 (i_man_min[21]), .Y
       (w_i_man_b[21]));
  MXI2XLHVT g273(.A (n_0), .B (w_i_carry), .S0 (i_man_min[6]), .Y
       (w_i_man_b[6]));
  MXI2XLHVT g274(.A (n_0), .B (w_i_carry), .S0 (i_man_min[14]), .Y
       (w_i_man_b[14]));
  MXI2XLHVT g275(.A (n_0), .B (w_i_carry), .S0 (i_man_min[24]), .Y
       (w_i_man_b[24]));
  XNOR2X1HVT g276(.A (n_0), .B (i_man_min[13]), .Y (w_i_man_b[13]));
  MXI2XLHVT g277(.A (n_0), .B (w_i_carry), .S0 (i_man_min[20]), .Y
       (w_i_man_b[20]));
  MXI2XLHVT g278(.A (n_0), .B (w_i_carry), .S0 (i_man_min[12]), .Y
       (w_i_man_b[12]));
  INVX2HVT g279(.A (w_i_carry), .Y (n_0));
endmodule

module COMP_4bit_2(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  assign o_equal = 1'b0;
  OR4X1HVT g114(.A (i_data_b[3]), .B (i_data_b[2]), .C (i_data_b[1]),
       .D (i_data_b[0]), .Y (o_less));
endmodule

module COMP_4bit_3(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12;
  OAI21X1HVT g320(.A0 (i_data_a[3]), .A1 (n_11), .B0 (n_12), .Y
       (o_less));
  OAI2BB1X1HVT g321(.A0N (i_data_a[3]), .A1N (n_11), .B0 (i_data_b[3]),
       .Y (n_12));
  AOI22X1HVT g322(.A0 (n_3), .A1 (n_10), .B0 (n_2), .B1 (i_data_b[2]),
       .Y (n_11));
  OAI32X1HVT g323(.A0 (i_data_a[0]), .A1 (n_1), .A2 (n_7), .B0
       (i_data_a[1]), .B1 (n_0), .Y (n_10));
  AND4XLHVT g324(.A (n_8), .B (n_4), .C (n_5), .D (n_6), .Y (o_equal));
  ADDHX1HVT g325(.A (i_data_a[1]), .B (n_0), .CO (n_7), .S (n_8));
  MXI2XLHVT g326(.A (i_data_b[0]), .B (n_1), .S0 (i_data_a[0]), .Y
       (n_6));
  MXI2XLHVT g327(.A (i_data_a[2]), .B (n_2), .S0 (i_data_b[2]), .Y
       (n_5));
  XNOR2X1HVT g328(.A (i_data_a[3]), .B (i_data_b[3]), .Y (n_4));
  OR2XLHVT g329(.A (n_2), .B (i_data_b[2]), .Y (n_3));
  INVX1HVT g330(.A (i_data_a[2]), .Y (n_2));
  INVX1HVT g331(.A (i_data_b[0]), .Y (n_1));
  INVX1HVT g332(.A (i_data_b[1]), .Y (n_0));
endmodule

module COMP_4bit_4(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12;
  OAI21X1HVT g320(.A0 (i_data_a[3]), .A1 (n_11), .B0 (n_12), .Y
       (o_less));
  OAI2BB1X1HVT g321(.A0N (i_data_a[3]), .A1N (n_11), .B0 (i_data_b[3]),
       .Y (n_12));
  AOI22X1HVT g322(.A0 (n_3), .A1 (n_10), .B0 (n_2), .B1 (i_data_b[2]),
       .Y (n_11));
  OAI32X1HVT g323(.A0 (i_data_a[0]), .A1 (n_7), .A2 (n_1), .B0
       (i_data_a[1]), .B1 (n_0), .Y (n_10));
  AND4XLHVT g324(.A (n_8), .B (n_5), .C (n_6), .D (n_4), .Y (o_equal));
  ADDHX1HVT g325(.A (i_data_a[1]), .B (n_0), .CO (n_7), .S (n_8));
  MXI2XLHVT g326(.A (i_data_b[0]), .B (n_1), .S0 (i_data_a[0]), .Y
       (n_6));
  MXI2XLHVT g327(.A (i_data_a[2]), .B (n_2), .S0 (i_data_b[2]), .Y
       (n_5));
  XNOR2X1HVT g328(.A (i_data_a[3]), .B (i_data_b[3]), .Y (n_4));
  OR2XLHVT g329(.A (n_2), .B (i_data_b[2]), .Y (n_3));
  INVX1HVT g330(.A (i_data_a[2]), .Y (n_2));
  INVX1HVT g331(.A (i_data_b[0]), .Y (n_1));
  INVX1HVT g332(.A (i_data_b[1]), .Y (n_0));
endmodule

module COMP_4bit_7(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12;
  OAI21X1HVT g320(.A0 (i_data_a[3]), .A1 (n_11), .B0 (n_12), .Y
       (o_less));
  OAI2BB1X1HVT g321(.A0N (i_data_a[3]), .A1N (n_11), .B0 (i_data_b[3]),
       .Y (n_12));
  AOI22X1HVT g322(.A0 (n_3), .A1 (n_10), .B0 (n_2), .B1 (i_data_b[2]),
       .Y (n_11));
  OAI32X1HVT g323(.A0 (i_data_a[0]), .A1 (n_1), .A2 (n_7), .B0
       (i_data_a[1]), .B1 (n_0), .Y (n_10));
  AND4XLHVT g324(.A (n_8), .B (n_6), .C (n_4), .D (n_5), .Y (o_equal));
  ADDHX1HVT g325(.A (i_data_a[1]), .B (n_0), .CO (n_7), .S (n_8));
  XNOR2X1HVT g326(.A (i_data_a[0]), .B (i_data_b[0]), .Y (n_6));
  MXI2XLHVT g327(.A (i_data_a[2]), .B (n_2), .S0 (i_data_b[2]), .Y
       (n_5));
  XNOR2X1HVT g328(.A (i_data_a[3]), .B (i_data_b[3]), .Y (n_4));
  OR2X1HVT g329(.A (n_2), .B (i_data_b[2]), .Y (n_3));
  INVX1HVT g330(.A (i_data_a[2]), .Y (n_2));
  INVX1HVT g331(.A (i_data_b[0]), .Y (n_1));
  INVX1HVT g332(.A (i_data_b[1]), .Y (n_0));
endmodule

module COMP_4bit_8(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11;
  OA21X1HVT g319(.A0 (n_7), .A1 (n_11), .B0 (i_data_b[3]), .Y (o_less));
  AOI22X1HVT g320(.A0 (n_4), .A1 (n_10), .B0 (i_data_a[2]), .B1 (n_1),
       .Y (n_11));
  OAI211X1HVT g321(.A0 (n_0), .A1 (i_data_b[1]), .B0 (n_3), .C0
       (i_data_b[0]), .Y (n_10));
  AND4XLHVT g322(.A (i_data_b[3]), .B (n_8), .C (n_5), .D (n_6), .Y
       (o_equal));
  ADDHX1HVT g323(.A (n_2), .B (i_data_b[2]), .CO (n_7), .S (n_8));
  MXI2XLHVT g324(.A (i_data_a[1]), .B (n_0), .S0 (i_data_b[1]), .Y
       (n_6));
  MXI2XLHVT g325(.A (i_data_a[0]), .B (n_3), .S0 (i_data_b[0]), .Y
       (n_5));
  NAND2XLHVT g326(.A (n_0), .B (i_data_b[1]), .Y (n_4));
  INVX1HVT g327(.A (i_data_a[0]), .Y (n_3));
  INVX1HVT g328(.A (i_data_a[2]), .Y (n_2));
  INVX1HVT g329(.A (i_data_b[2]), .Y (n_1));
  INVX1HVT g330(.A (i_data_a[1]), .Y (n_0));
endmodule

module COMP_28bit_SIZE_DATA28(i_data_a, i_data_b, o_less);
  input [27:0] i_data_a, i_data_b;
  output o_less;
  wire [27:0] i_data_a, i_data_b;
  wire o_less;
  wire n_0, n_1, n_2, n_3, n_4, n_5, w_equal_0_0, w_equal_0_1;
  wire w_equal_0_2, w_equal_0_3, w_equal_0_4, w_equal_0_5, w_equal_0_6,
       w_less_0_0, w_less_0_1, w_less_0_2;
  wire w_less_0_3, w_less_0_4, w_less_0_5, w_less_0_6;
  COMP_4bit_2 u_i_data_0(.i_data_a (4'b0000), .i_data_b
       (i_data_b[3:0]), .o_less (w_less_0_0), .o_equal (w_equal_0_0));
  COMP_4bit_3 u_i_data_1(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_0_1), .o_equal (w_equal_0_1));
  COMP_4bit_4 u_i_data_2(.i_data_a (i_data_a[11:8]), .i_data_b
       (i_data_b[11:8]), .o_less (w_less_0_2), .o_equal (w_equal_0_2));
  COMP_4bit_7 u_i_data_3(.i_data_a (i_data_a[15:12]), .i_data_b
       (i_data_b[15:12]), .o_less (w_less_0_3), .o_equal (w_equal_0_3));
  COMP_4bit_7 u_i_data_4(.i_data_a (i_data_a[19:16]), .i_data_b
       (i_data_b[19:16]), .o_less (w_less_0_4), .o_equal (w_equal_0_4));
  COMP_4bit_7 u_i_data_5(.i_data_a (i_data_a[23:20]), .i_data_b
       (i_data_b[23:20]), .o_less (w_less_0_5), .o_equal (w_equal_0_5));
  COMP_4bit_8 u_i_data_6(.i_data_a ({1'b1, i_data_a[26:24]}), .i_data_b
       (i_data_b[27:24]), .o_less (w_less_0_6), .o_equal (w_equal_0_6));
  AO21X1HVT g156(.A0 (w_equal_0_6), .A1 (n_5), .B0 (w_less_0_6), .Y
       (o_less));
  NAND2BX1HVT g157(.AN (w_less_0_5), .B (n_4), .Y (n_5));
  OAI21X1HVT g158(.A0 (w_less_0_4), .A1 (n_3), .B0 (w_equal_0_5), .Y
       (n_4));
  OA21X1HVT g159(.A0 (w_less_0_3), .A1 (n_2), .B0 (w_equal_0_4), .Y
       (n_3));
  OA21X1HVT g160(.A0 (w_less_0_2), .A1 (n_1), .B0 (w_equal_0_3), .Y
       (n_2));
  NOR2BX1HVT g161(.AN (w_equal_0_2), .B (n_0), .Y (n_1));
  AOI21X1HVT g162(.A0 (w_less_0_0), .A1 (w_equal_0_1), .B0
       (w_less_0_1), .Y (n_0));
endmodule

module MAN_swap_SIZE_MAN24(i_man_a, i_man_b, i_compare, o_man_max,
     o_man_min);
  input [23:0] i_man_a, i_man_b;
  input i_compare;
  output [23:0] o_man_max, o_man_min;
  wire [23:0] i_man_a, i_man_b;
  wire i_compare;
  wire [23:0] o_man_max, o_man_min;
  assign o_man_min[23] = 1'b1;
  assign o_man_max[23] = 1'b1;
  MX2X1HVT g761(.A (i_man_b[7]), .B (i_man_a[7]), .S0 (i_compare), .Y
       (o_man_min[7]));
  MX2XLHVT g762(.A (i_man_a[21]), .B (i_man_b[21]), .S0 (i_compare), .Y
       (o_man_max[21]));
  MX2XLHVT g763(.A (i_man_a[19]), .B (i_man_b[19]), .S0 (i_compare), .Y
       (o_man_max[19]));
  MX2XLHVT g764(.A (i_man_a[16]), .B (i_man_b[16]), .S0 (i_compare), .Y
       (o_man_max[16]));
  MX2XLHVT g765(.A (i_man_b[18]), .B (i_man_a[18]), .S0 (i_compare), .Y
       (o_man_min[18]));
  MX2X1HVT g766(.A (i_man_b[17]), .B (i_man_a[17]), .S0 (i_compare), .Y
       (o_man_min[17]));
  MX2XLHVT g767(.A (i_man_a[9]), .B (i_man_b[9]), .S0 (i_compare), .Y
       (o_man_max[9]));
  MX2XLHVT g768(.A (i_man_b[16]), .B (i_man_a[16]), .S0 (i_compare), .Y
       (o_man_min[16]));
  MX2X1HVT g769(.A (i_man_b[15]), .B (i_man_a[15]), .S0 (i_compare), .Y
       (o_man_min[15]));
  MX2XLHVT g770(.A (i_man_b[14]), .B (i_man_a[14]), .S0 (i_compare), .Y
       (o_man_min[14]));
  MX2XLHVT g771(.A (i_man_a[15]), .B (i_man_b[15]), .S0 (i_compare), .Y
       (o_man_max[15]));
  MX2XLHVT g772(.A (i_man_a[8]), .B (i_man_b[8]), .S0 (i_compare), .Y
       (o_man_max[8]));
  MX2X1HVT g773(.A (i_man_b[13]), .B (i_man_a[13]), .S0 (i_compare), .Y
       (o_man_min[13]));
  MX2XLHVT g774(.A (i_man_b[12]), .B (i_man_a[12]), .S0 (i_compare), .Y
       (o_man_min[12]));
  MX2X1HVT g775(.A (i_man_b[11]), .B (i_man_a[11]), .S0 (i_compare), .Y
       (o_man_min[11]));
  MX2XLHVT g776(.A (i_man_a[7]), .B (i_man_b[7]), .S0 (i_compare), .Y
       (o_man_max[7]));
  MX2XLHVT g777(.A (i_man_b[10]), .B (i_man_a[10]), .S0 (i_compare), .Y
       (o_man_min[10]));
  MX2X1HVT g778(.A (i_man_b[9]), .B (i_man_a[9]), .S0 (i_compare), .Y
       (o_man_min[9]));
  MX2X1HVT g779(.A (i_man_a[18]), .B (i_man_b[18]), .S0 (i_compare), .Y
       (o_man_max[18]));
  MX2X1HVT g780(.A (i_man_a[14]), .B (i_man_b[14]), .S0 (i_compare), .Y
       (o_man_max[14]));
  MX2X1HVT g781(.A (i_man_a[6]), .B (i_man_b[6]), .S0 (i_compare), .Y
       (o_man_max[6]));
  MX2X1HVT g782(.A (i_man_b[8]), .B (i_man_a[8]), .S0 (i_compare), .Y
       (o_man_min[8]));
  MX2X1HVT g783(.A (i_man_a[22]), .B (i_man_b[22]), .S0 (i_compare), .Y
       (o_man_max[22]));
  MX2X1HVT g784(.A (i_man_b[19]), .B (i_man_a[19]), .S0 (i_compare), .Y
       (o_man_min[19]));
  MX2X1HVT g785(.A (i_man_b[5]), .B (i_man_a[5]), .S0 (i_compare), .Y
       (o_man_min[5]));
  MX2X1HVT g786(.A (i_man_b[4]), .B (i_man_a[4]), .S0 (i_compare), .Y
       (o_man_min[4]));
  MX2X1HVT g787(.A (i_man_b[3]), .B (i_man_a[3]), .S0 (i_compare), .Y
       (o_man_min[3]));
  MX2XLHVT g788(.A (i_man_a[5]), .B (i_man_b[5]), .S0 (i_compare), .Y
       (o_man_max[5]));
  MX2XLHVT g789(.A (i_man_b[2]), .B (i_man_a[2]), .S0 (i_compare), .Y
       (o_man_min[2]));
  MX2X1HVT g790(.A (i_man_b[1]), .B (i_man_a[1]), .S0 (i_compare), .Y
       (o_man_min[1]));
  MX2XLHVT g791(.A (i_man_a[4]), .B (i_man_b[4]), .S0 (i_compare), .Y
       (o_man_max[4]));
  MX2XLHVT g792(.A (i_man_b[0]), .B (i_man_a[0]), .S0 (i_compare), .Y
       (o_man_min[0]));
  MX2X1HVT g793(.A (i_man_a[20]), .B (i_man_b[20]), .S0 (i_compare), .Y
       (o_man_max[20]));
  MX2XLHVT g794(.A (i_man_a[13]), .B (i_man_b[13]), .S0 (i_compare), .Y
       (o_man_max[13]));
  MX2XLHVT g795(.A (i_man_a[3]), .B (i_man_b[3]), .S0 (i_compare), .Y
       (o_man_max[3]));
  MX2X1HVT g796(.A (i_man_a[2]), .B (i_man_b[2]), .S0 (i_compare), .Y
       (o_man_max[2]));
  MX2XLHVT g797(.A (i_man_a[12]), .B (i_man_b[12]), .S0 (i_compare), .Y
       (o_man_max[12]));
  MX2X1HVT g798(.A (i_man_a[1]), .B (i_man_b[1]), .S0 (i_compare), .Y
       (o_man_max[1]));
  MX2XLHVT g799(.A (i_man_a[17]), .B (i_man_b[17]), .S0 (i_compare), .Y
       (o_man_max[17]));
  MX2XLHVT g800(.A (i_man_a[11]), .B (i_man_b[11]), .S0 (i_compare), .Y
       (o_man_max[11]));
  MX2XLHVT g801(.A (i_man_a[0]), .B (i_man_b[0]), .S0 (i_compare), .Y
       (o_man_max[0]));
  MX2XLHVT g802(.A (i_man_b[22]), .B (i_man_a[22]), .S0 (i_compare), .Y
       (o_man_min[22]));
  MX2X1HVT g803(.A (i_man_a[10]), .B (i_man_b[10]), .S0 (i_compare), .Y
       (o_man_max[10]));
  MX2X1HVT g804(.A (i_man_b[21]), .B (i_man_a[21]), .S0 (i_compare), .Y
       (o_man_min[21]));
  MX2X1HVT g805(.A (i_man_b[20]), .B (i_man_a[20]), .S0 (i_compare), .Y
       (o_man_min[20]));
  MX2XLHVT g806(.A (i_man_b[6]), .B (i_man_a[6]), .S0 (i_compare), .Y
       (o_man_min[6]));
endmodule

module MAN_swap_SIZE_MAN28(i_man_a, i_man_b, i_compare, o_man_max,
     o_man_min);
  input [27:0] i_man_a, i_man_b;
  input i_compare;
  output [27:0] o_man_max, o_man_min;
  wire [27:0] i_man_a, i_man_b;
  wire i_compare;
  wire [27:0] o_man_max, o_man_min;
  MX2XLHVT g828(.A (i_man_b[15]), .B (i_man_a[15]), .S0 (i_compare), .Y
       (o_man_min[15]));
  MX2XLHVT g829(.A (i_man_a[25]), .B (i_man_b[25]), .S0 (i_compare), .Y
       (o_man_max[25]));
  MX2XLHVT g830(.A (i_man_a[23]), .B (i_man_b[23]), .S0 (i_compare), .Y
       (o_man_max[23]));
  MX2XLHVT g831(.A (i_man_a[20]), .B (i_man_b[20]), .S0 (i_compare), .Y
       (o_man_max[20]));
  MX2XLHVT g832(.A (i_man_a[14]), .B (i_man_b[14]), .S0 (i_compare), .Y
       (o_man_max[14]));
  MX2XLHVT g833(.A (i_man_b[26]), .B (i_man_a[26]), .S0 (i_compare), .Y
       (o_man_min[26]));
  MX2XLHVT g834(.A (i_man_b[25]), .B (i_man_a[25]), .S0 (i_compare), .Y
       (o_man_min[25]));
  MX2XLHVT g835(.A (i_man_b[24]), .B (i_man_a[24]), .S0 (i_compare), .Y
       (o_man_min[24]));
  MX2X1HVT g836(.A (i_man_a[13]), .B (i_man_b[13]), .S0 (i_compare), .Y
       (o_man_max[13]));
  MX2XLHVT g837(.A (i_man_b[23]), .B (i_man_a[23]), .S0 (i_compare), .Y
       (o_man_min[23]));
  MX2XLHVT g838(.A (i_man_b[22]), .B (i_man_a[22]), .S0 (i_compare), .Y
       (o_man_min[22]));
  MX2XLHVT g839(.A (i_man_b[21]), .B (i_man_a[21]), .S0 (i_compare), .Y
       (o_man_min[21]));
  MX2XLHVT g840(.A (i_man_a[19]), .B (i_man_b[19]), .S0 (i_compare), .Y
       (o_man_max[19]));
  MX2XLHVT g841(.A (i_man_a[12]), .B (i_man_b[12]), .S0 (i_compare), .Y
       (o_man_max[12]));
  MX2XLHVT g842(.A (i_man_b[20]), .B (i_man_a[20]), .S0 (i_compare), .Y
       (o_man_min[20]));
  MX2XLHVT g843(.A (i_man_b[19]), .B (i_man_a[19]), .S0 (i_compare), .Y
       (o_man_min[19]));
  MX2XLHVT g844(.A (i_man_a[11]), .B (i_man_b[11]), .S0 (i_compare), .Y
       (o_man_max[11]));
  MX2XLHVT g845(.A (i_man_b[18]), .B (i_man_a[18]), .S0 (i_compare), .Y
       (o_man_min[18]));
  MX2XLHVT g846(.A (i_man_b[17]), .B (i_man_a[17]), .S0 (i_compare), .Y
       (o_man_min[17]));
  MX2XLHVT g847(.A (i_man_b[16]), .B (i_man_a[16]), .S0 (i_compare), .Y
       (o_man_min[16]));
  MX2XLHVT g848(.A (i_man_a[18]), .B (i_man_b[18]), .S0 (i_compare), .Y
       (o_man_max[18]));
  MX2XLHVT g849(.A (i_man_a[10]), .B (i_man_b[10]), .S0 (i_compare), .Y
       (o_man_max[10]));
  MX2XLHVT g850(.A (i_man_a[26]), .B (i_man_b[26]), .S0 (i_compare), .Y
       (o_man_max[26]));
  MX2XLHVT g851(.A (i_man_a[4]), .B (i_man_b[4]), .S0 (i_compare), .Y
       (o_man_max[4]));
  MX2XLHVT g852(.A (i_man_b[13]), .B (i_man_a[13]), .S0 (i_compare), .Y
       (o_man_min[13]));
  MX2XLHVT g853(.A (i_man_b[12]), .B (i_man_a[12]), .S0 (i_compare), .Y
       (o_man_min[12]));
  MX2XLHVT g854(.A (i_man_b[11]), .B (i_man_a[11]), .S0 (i_compare), .Y
       (o_man_min[11]));
  MX2XLHVT g855(.A (i_man_a[9]), .B (i_man_b[9]), .S0 (i_compare), .Y
       (o_man_max[9]));
  MX2XLHVT g856(.A (i_man_b[10]), .B (i_man_a[10]), .S0 (i_compare), .Y
       (o_man_min[10]));
  MX2XLHVT g857(.A (i_man_b[9]), .B (i_man_a[9]), .S0 (i_compare), .Y
       (o_man_min[9]));
  MX2XLHVT g858(.A (i_man_b[8]), .B (i_man_a[8]), .S0 (i_compare), .Y
       (o_man_min[8]));
  MX2XLHVT g859(.A (i_man_a[8]), .B (i_man_b[8]), .S0 (i_compare), .Y
       (o_man_max[8]));
  MX2XLHVT g860(.A (i_man_b[7]), .B (i_man_a[7]), .S0 (i_compare), .Y
       (o_man_min[7]));
  MX2XLHVT g861(.A (i_man_b[6]), .B (i_man_a[6]), .S0 (i_compare), .Y
       (o_man_min[6]));
  MX2XLHVT g862(.A (i_man_b[5]), .B (i_man_a[5]), .S0 (i_compare), .Y
       (o_man_min[5]));
  MX2XLHVT g863(.A (i_man_a[24]), .B (i_man_b[24]), .S0 (i_compare), .Y
       (o_man_max[24]));
  MX2XLHVT g864(.A (i_man_a[22]), .B (i_man_b[22]), .S0 (i_compare), .Y
       (o_man_max[22]));
  MX2XLHVT g865(.A (i_man_a[17]), .B (i_man_b[17]), .S0 (i_compare), .Y
       (o_man_max[17]));
  MX2XLHVT g866(.A (i_man_a[7]), .B (i_man_b[7]), .S0 (i_compare), .Y
       (o_man_max[7]));
  MX2XLHVT g867(.A (i_man_b[4]), .B (i_man_a[4]), .S0 (i_compare), .Y
       (o_man_min[4]));
  MX2XLHVT g868(.A (i_man_a[16]), .B (i_man_b[16]), .S0 (i_compare), .Y
       (o_man_max[16]));
  MX2XLHVT g869(.A (i_man_a[6]), .B (i_man_b[6]), .S0 (i_compare), .Y
       (o_man_max[6]));
  MX2XLHVT g870(.A (i_man_a[5]), .B (i_man_b[5]), .S0 (i_compare), .Y
       (o_man_max[5]));
  MX2XLHVT g871(.A (i_man_a[21]), .B (i_man_b[21]), .S0 (i_compare), .Y
       (o_man_max[21]));
  MX2XLHVT g872(.A (i_man_a[15]), .B (i_man_b[15]), .S0 (i_compare), .Y
       (o_man_max[15]));
  MX2XLHVT g873(.A (i_man_b[14]), .B (i_man_a[14]), .S0 (i_compare), .Y
       (o_man_min[14]));
  NOR2BX1HVT g874(.AN (i_man_b[3]), .B (i_compare), .Y (o_man_min[3]));
  NOR2BX1HVT g875(.AN (i_man_b[1]), .B (i_compare), .Y (o_man_min[1]));
  NOR2BX1HVT g876(.AN (i_man_b[0]), .B (i_compare), .Y (o_man_min[0]));
  AND2XLHVT g877(.A (i_man_b[2]), .B (i_compare), .Y (o_man_max[2]));
  NAND2BXLHVT g878(.AN (i_man_b[27]), .B (i_compare), .Y
       (o_man_max[27]));
  AND2XLHVT g879(.A (i_man_b[0]), .B (i_compare), .Y (o_man_max[0]));
  OR2XLHVT g880(.A (i_man_b[27]), .B (i_compare), .Y (o_man_min[27]));
  NOR2BX1HVT g881(.AN (i_man_b[2]), .B (i_compare), .Y (o_man_min[2]));
  AND2X1HVT g882(.A (i_compare), .B (i_man_b[1]), .Y (o_man_max[1]));
  AND2XLHVT g883(.A (i_man_b[3]), .B (i_compare), .Y (o_man_max[3]));
endmodule

module SHF_left_28bit_SIZE_DATA28_SIZE_SHIFT5(i_shift_number, i_data,
     o_data);
  input [4:0] i_shift_number;
  input [27:0] i_data;
  output [27:0] o_data;
  wire [4:0] i_shift_number;
  wire [27:0] i_data;
  wire [27:0] o_data;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_116, n_117, n_118, n_121, n_128, n_129, n_130, n_132;
  wire n_136, n_137;
  NAND2X1HVT g2847(.A (n_121), .B (n_137), .Y (o_data[27]));
  NAND2X1HVT g2848(.A (n_128), .B (n_136), .Y (o_data[26]));
  OAI221X1HVT g2849(.A0 (n_3), .A1 (n_118), .B0 (n_30), .B1 (n_63), .C0
       (n_130), .Y (o_data[25]));
  OAI211X1HVT g2850(.A0 (n_30), .A1 (n_48), .B0 (n_132), .C0 (n_129),
       .Y (o_data[24]));
  AOI32X1HVT g2851(.A0 (i_data[27]), .A1 (n_5), .A2 (n_28), .B0
       (i_shift_number[4]), .B1 (n_116), .Y (n_137));
  AOI32X1HVT g2852(.A0 (i_data[26]), .A1 (n_5), .A2 (n_28), .B0
       (i_shift_number[4]), .B1 (n_117), .Y (n_136));
  NOR2X1HVT g2853(.A (i_shift_number[4]), .B (n_118), .Y (o_data[9]));
  AND2XLHVT g2854(.A (n_3), .B (n_117), .Y (o_data[10]));
  AND2XLHVT g2855(.A (n_3), .B (n_110), .Y (o_data[8]));
  NAND2X1HVT g2856(.A (i_shift_number[4]), .B (n_110), .Y (n_132));
  AND2XLHVT g2857(.A (n_3), .B (n_116), .Y (o_data[11]));
  AOI31X1HVT g2858(.A0 (n_8), .A1 (n_6), .A2 (n_40), .B0 (n_111), .Y
       (n_130));
  AOI31X1HVT g2859(.A0 (n_8), .A1 (n_6), .A2 (n_42), .B0 (n_114), .Y
       (n_129));
  AOI221X1HVT g2860(.A0 (n_42), .A1 (n_44), .B0 (i_data[25]), .B1
       (n_79), .C0 (n_109), .Y (n_128));
  OAI222X1HVT g2861(.A0 (n_4), .A1 (n_93), .B0 (n_7), .B1 (n_89), .C0
       (n_33), .C1 (n_68), .Y (o_data[19]));
  OAI221X1HVT g2862(.A0 (n_4), .A1 (n_95), .B0 (n_30), .B1 (n_62), .C0
       (n_108), .Y (o_data[22]));
  OAI221X1HVT g2863(.A0 (n_4), .A1 (n_94), .B0 (n_30), .B1 (n_59), .C0
       (n_113), .Y (o_data[21]));
  OAI221X1HVT g2864(.A0 (n_4), .A1 (n_86), .B0 (n_30), .B1 (n_50), .C0
       (n_112), .Y (o_data[20]));
  OAI222X1HVT g2865(.A0 (n_4), .A1 (n_98), .B0 (n_7), .B1 (n_85), .C0
       (n_33), .C1 (n_31), .Y (o_data[16]));
  OAI222X1HVT g2866(.A0 (n_4), .A1 (n_96), .B0 (n_7), .B1 (n_88), .C0
       (n_33), .C1 (n_66), .Y (o_data[18]));
  AOI221X1HVT g2867(.A0 (n_40), .A1 (n_44), .B0 (i_data[26]), .B1
       (n_79), .C0 (n_106), .Y (n_121));
  OAI222X1HVT g2868(.A0 (n_4), .A1 (n_90), .B0 (n_7), .B1 (n_87), .C0
       (n_9), .C1 (n_46), .Y (o_data[17]));
  OAI221X1HVT g2869(.A0 (n_4), .A1 (n_97), .B0 (n_30), .B1 (n_56), .C0
       (n_107), .Y (o_data[23]));
  OAI22X1HVT g2870(.A0 (n_7), .A1 (n_97), .B0 (n_4), .B1 (n_91), .Y
       (o_data[15]));
  OAI22X1HVT g2871(.A0 (n_4), .A1 (n_85), .B0 (n_38), .B1 (n_45), .Y
       (n_114));
  OA22X1HVT g2872(.A0 (n_9), .A1 (n_84), .B0 (n_29), .B1 (n_63), .Y
       (n_113));
  OA22X1HVT g2873(.A0 (n_9), .A1 (n_92), .B0 (n_29), .B1 (n_48), .Y
       (n_112));
  OAI22X1HVT g2874(.A0 (n_4), .A1 (n_87), .B0 (n_25), .B1 (n_45), .Y
       (n_111));
  MX2XLHVT g2875(.A (n_90), .B (n_46), .S0 (i_shift_number[3]), .Y
       (n_118));
  OAI22X1HVT g2876(.A0 (i_shift_number[3]), .A1 (n_96), .B0 (n_11), .B1
       (n_66), .Y (n_117));
  OAI22X1HVT g2877(.A0 (i_shift_number[3]), .A1 (n_93), .B0 (n_11), .B1
       (n_68), .Y (n_116));
  OAI22X1HVT g2878(.A0 (n_4), .A1 (n_88), .B0 (n_30), .B1 (n_70), .Y
       (n_109));
  AOI22X1HVT g2879(.A0 (n_10), .A1 (n_82), .B0 (n_28), .B1 (n_69), .Y
       (n_108));
  OA22X1HVT g2880(.A0 (n_9), .A1 (n_91), .B0 (n_29), .B1 (n_71), .Y
       (n_107));
  OAI22X1HVT g2881(.A0 (n_4), .A1 (n_89), .B0 (n_30), .B1 (n_71), .Y
       (n_106));
  OAI22X1HVT g2882(.A0 (n_7), .A1 (n_86), .B0 (n_4), .B1 (n_92), .Y
       (o_data[12]));
  OAI22X1HVT g2883(.A0 (n_7), .A1 (n_95), .B0 (n_4), .B1 (n_83), .Y
       (o_data[14]));
  OAI22X1HVT g2884(.A0 (n_7), .A1 (n_94), .B0 (n_4), .B1 (n_84), .Y
       (o_data[13]));
  OAI22X1HVT g2885(.A0 (i_shift_number[3]), .A1 (n_98), .B0 (n_11), .B1
       (n_31), .Y (n_110));
  NOR2X1HVT g2886(.A (n_7), .B (n_91), .Y (o_data[7]));
  NOR2X1HVT g2887(.A (n_7), .B (n_84), .Y (o_data[5]));
  NOR2X1HVT g2888(.A (n_7), .B (n_92), .Y (o_data[4]));
  NOR2X1HVT g2889(.A (n_7), .B (n_83), .Y (o_data[6]));
  AOI22X1HVT g2890(.A0 (n_1), .A1 (n_75), .B0 (i_shift_number[2]), .B1
       (n_76), .Y (n_98));
  AOI22X1HVT g2891(.A0 (n_1), .A1 (n_54), .B0 (i_shift_number[2]), .B1
       (n_57), .Y (n_97));
  AOI22X1HVT g2892(.A0 (n_1), .A1 (n_72), .B0 (i_shift_number[2]), .B1
       (n_73), .Y (n_96));
  AOI22X1HVT g2893(.A0 (n_1), .A1 (n_78), .B0 (i_shift_number[2]), .B1
       (n_72), .Y (n_95));
  AOI22X1HVT g2894(.A0 (n_1), .A1 (n_60), .B0 (i_shift_number[2]), .B1
       (n_52), .Y (n_94));
  AOI22X1HVT g2895(.A0 (n_1), .A1 (n_57), .B0 (i_shift_number[2]), .B1
       (n_74), .Y (n_93));
  MX2XLHVT g2896(.A (n_77), .B (n_31), .S0 (i_shift_number[2]), .Y
       (n_92));
  AOI22X1HVT g2897(.A0 (n_1), .A1 (n_74), .B0 (i_shift_number[2]), .B1
       (n_67), .Y (n_91));
  INVX1HVT g2898(.A (n_83), .Y (n_82));
  AOI22X1HVT g2899(.A0 (n_1), .A1 (n_52), .B0 (i_shift_number[2]), .B1
       (n_53), .Y (n_90));
  AOI22X1HVT g2900(.A0 (n_1), .A1 (n_55), .B0 (i_shift_number[2]), .B1
       (n_54), .Y (n_89));
  AOI22X1HVT g2901(.A0 (n_1), .A1 (n_61), .B0 (i_shift_number[2]), .B1
       (n_78), .Y (n_88));
  AOI22X1HVT g2902(.A0 (n_1), .A1 (n_58), .B0 (i_shift_number[2]), .B1
       (n_60), .Y (n_87));
  AOI22X1HVT g2903(.A0 (n_1), .A1 (n_51), .B0 (i_shift_number[2]), .B1
       (n_75), .Y (n_86));
  AOI22X1HVT g2904(.A0 (n_1), .A1 (n_49), .B0 (i_shift_number[2]), .B1
       (n_51), .Y (n_85));
  AOI32X1HVT g2905(.A0 (i_shift_number[2]), .A1 (n_0), .A2 (n_32), .B0
       (n_1), .B1 (n_53), .Y (n_84));
  AOI22X1HVT g2906(.A0 (n_1), .A1 (n_73), .B0 (i_shift_number[2]), .B1
       (n_65), .Y (n_83));
  NOR2X1HVT g2907(.A (n_29), .B (n_66), .Y (o_data[2]));
  NOR2X1HVT g2908(.A (n_29), .B (n_68), .Y (o_data[3]));
  INVX1HVT g2909(.A (n_76), .Y (n_77));
  INVX1HVT g2910(.A (n_69), .Y (n_70));
  INVX1HVT g2911(.A (n_68), .Y (n_67));
  INVX1HVT g2912(.A (n_66), .Y (n_65));
  NOR2X1HVT g2913(.A (n_7), .B (n_46), .Y (o_data[1]));
  NOR3X1HVT g2914(.A (i_shift_number[1]), .B (n_2), .C (n_29), .Y
       (n_79));
  OAI22X1HVT g2915(.A0 (i_shift_number[1]), .A1 (n_24), .B0 (n_0), .B1
       (n_12), .Y (n_78));
  OAI22X1HVT g2916(.A0 (i_shift_number[1]), .A1 (n_37), .B0 (n_0), .B1
       (n_35), .Y (n_76));
  OAI22X1HVT g2917(.A0 (i_shift_number[1]), .A1 (n_41), .B0 (n_0), .B1
       (n_26), .Y (n_75));
  OAI22X1HVT g2918(.A0 (i_shift_number[1]), .A1 (n_34), .B0 (n_0), .B1
       (n_43), .Y (n_74));
  OAI22X1HVT g2919(.A0 (i_shift_number[1]), .A1 (n_26), .B0 (n_0), .B1
       (n_37), .Y (n_73));
  OAI22X1HVT g2920(.A0 (i_shift_number[1]), .A1 (n_16), .B0 (n_0), .B1
       (n_41), .Y (n_72));
  MX2XLHVT g2921(.A (n_25), .B (n_39), .S0 (i_shift_number[1]), .Y
       (n_71));
  OAI22X1HVT g2922(.A0 (i_shift_number[1]), .A1 (n_38), .B0 (n_0), .B1
       (n_20), .Y (n_69));
  AOI22X1HVT g2923(.A0 (n_0), .A1 (n_19), .B0 (i_shift_number[1]), .B1
       (n_32), .Y (n_68));
  AOI32X1HVT g2924(.A0 (i_data[0]), .A1 (i_shift_number[1]), .A2 (n_2),
       .B0 (n_0), .B1 (n_36), .Y (n_66));
  INVX1HVT g2925(.A (n_61), .Y (n_62));
  INVX1HVT g2926(.A (n_58), .Y (n_59));
  INVX1HVT g2927(.A (n_55), .Y (n_56));
  INVX1HVT g2928(.A (n_49), .Y (n_50));
  MX2XLHVT g2929(.A (n_39), .B (n_13), .S0 (i_shift_number[1]), .Y
       (n_63));
  OAI22X1HVT g2930(.A0 (i_shift_number[1]), .A1 (n_27), .B0 (n_0), .B1
       (n_23), .Y (n_61));
  OAI22X1HVT g2931(.A0 (i_shift_number[1]), .A1 (n_21), .B0 (n_0), .B1
       (n_14), .Y (n_60));
  OAI22X1HVT g2932(.A0 (i_shift_number[1]), .A1 (n_15), .B0 (n_0), .B1
       (n_22), .Y (n_58));
  OAI22X1HVT g2933(.A0 (i_shift_number[1]), .A1 (n_14), .B0 (n_0), .B1
       (n_17), .Y (n_57));
  OAI22X1HVT g2934(.A0 (i_shift_number[1]), .A1 (n_13), .B0 (n_0), .B1
       (n_15), .Y (n_55));
  OAI22X1HVT g2935(.A0 (i_shift_number[1]), .A1 (n_22), .B0 (n_0), .B1
       (n_21), .Y (n_54));
  OAI22X1HVT g2936(.A0 (i_shift_number[1]), .A1 (n_43), .B0 (n_0), .B1
       (n_18), .Y (n_53));
  OAI22X1HVT g2937(.A0 (i_shift_number[1]), .A1 (n_17), .B0 (n_0), .B1
       (n_34), .Y (n_52));
  OAI22X1HVT g2938(.A0 (i_shift_number[1]), .A1 (n_12), .B0 (n_0), .B1
       (n_16), .Y (n_51));
  OAI22X1HVT g2939(.A0 (i_shift_number[1]), .A1 (n_23), .B0 (n_0), .B1
       (n_24), .Y (n_49));
  MX2XLHVT g2940(.A (n_20), .B (n_27), .S0 (i_shift_number[1]), .Y
       (n_48));
  NOR2X1HVT g2941(.A (n_29), .B (n_31), .Y (o_data[0]));
  INVX1HVT g2942(.A (n_45), .Y (n_44));
  NAND2X1HVT g2943(.A (n_6), .B (n_32), .Y (n_46));
  NAND2X1HVT g2944(.A (i_shift_number[1]), .B (n_28), .Y (n_45));
  INVX1HVT g2945(.A (n_35), .Y (n_36));
  INVX1HVT g2946(.A (n_29), .Y (n_28));
  AOI22X1HVT g2947(.A0 (i_data[5]), .A1 (n_2), .B0 (i_data[4]), .B1
       (i_shift_number[0]), .Y (n_43));
  MX2X1HVT g2948(.A (i_data[24]), .B (i_data[23]), .S0
       (i_shift_number[0]), .Y (n_42));
  AOI22X1HVT g2949(.A0 (i_data[8]), .A1 (n_2), .B0 (i_data[7]), .B1
       (i_shift_number[0]), .Y (n_41));
  MX2X1HVT g2950(.A (i_data[25]), .B (i_data[24]), .S0
       (i_shift_number[0]), .Y (n_40));
  AOI22XLHVT g2951(.A0 (i_data[21]), .A1 (n_2), .B0 (i_data[20]), .B1
       (i_shift_number[0]), .Y (n_39));
  AOI22XLHVT g2952(.A0 (i_data[22]), .A1 (n_2), .B0 (i_data[21]), .B1
       (i_shift_number[0]), .Y (n_38));
  AOI22X1HVT g2953(.A0 (i_data[4]), .A1 (n_2), .B0 (i_data[3]), .B1
       (i_shift_number[0]), .Y (n_37));
  AOI22X1HVT g2954(.A0 (i_data[2]), .A1 (n_2), .B0 (i_data[1]), .B1
       (i_shift_number[0]), .Y (n_35));
  AOI22X1HVT g2955(.A0 (i_data[7]), .A1 (n_2), .B0 (i_data[6]), .B1
       (i_shift_number[0]), .Y (n_34));
  NAND2X1HVT g2956(.A (n_10), .B (n_1), .Y (n_33));
  MX2X1HVT g2957(.A (i_data[1]), .B (i_data[0]), .S0
       (i_shift_number[0]), .Y (n_32));
  NAND2X1HVT g2958(.A (i_data[0]), .B (n_5), .Y (n_31));
  NAND2X1HVT g2959(.A (i_shift_number[2]), .B (n_8), .Y (n_30));
  NAND2X1HVT g2960(.A (n_8), .B (n_1), .Y (n_29));
  INVX1HVT g2961(.A (n_18), .Y (n_19));
  AOI22XLHVT g2962(.A0 (i_data[18]), .A1 (n_2), .B0 (i_data[17]), .B1
       (i_shift_number[0]), .Y (n_27));
  AOI22X1HVT g2963(.A0 (i_data[6]), .A1 (n_2), .B0 (i_data[5]), .B1
       (i_shift_number[0]), .Y (n_26));
  AOI22XLHVT g2964(.A0 (i_data[23]), .A1 (n_2), .B0 (i_data[22]), .B1
       (i_shift_number[0]), .Y (n_25));
  AOI22XLHVT g2965(.A0 (i_data[14]), .A1 (n_2), .B0 (i_data[13]), .B1
       (i_shift_number[0]), .Y (n_24));
  AOI22XLHVT g2966(.A0 (i_data[16]), .A1 (n_2), .B0 (i_data[15]), .B1
       (i_shift_number[0]), .Y (n_23));
  AOI22XLHVT g2967(.A0 (i_data[15]), .A1 (n_2), .B0 (i_data[14]), .B1
       (i_shift_number[0]), .Y (n_22));
  AOI22XLHVT g2968(.A0 (i_data[13]), .A1 (n_2), .B0 (i_data[12]), .B1
       (i_shift_number[0]), .Y (n_21));
  AOI22XLHVT g2969(.A0 (i_data[20]), .A1 (n_2), .B0 (i_data[19]), .B1
       (i_shift_number[0]), .Y (n_20));
  AOI22X1HVT g2970(.A0 (i_data[3]), .A1 (n_2), .B0 (i_data[2]), .B1
       (i_shift_number[0]), .Y (n_18));
  AOI22X1HVT g2971(.A0 (i_data[9]), .A1 (n_2), .B0 (i_data[8]), .B1
       (i_shift_number[0]), .Y (n_17));
  AOI22XLHVT g2972(.A0 (i_data[10]), .A1 (n_2), .B0 (i_data[9]), .B1
       (i_shift_number[0]), .Y (n_16));
  AOI22XLHVT g2973(.A0 (i_data[17]), .A1 (n_2), .B0 (i_data[16]), .B1
       (i_shift_number[0]), .Y (n_15));
  AOI22XLHVT g2974(.A0 (i_data[11]), .A1 (n_2), .B0 (i_data[10]), .B1
       (i_shift_number[0]), .Y (n_14));
  AOI22XLHVT g2975(.A0 (i_data[19]), .A1 (n_2), .B0 (i_data[18]), .B1
       (i_shift_number[0]), .Y (n_13));
  AOI22XLHVT g2976(.A0 (i_data[12]), .A1 (n_2), .B0 (i_data[11]), .B1
       (i_shift_number[0]), .Y (n_12));
  INVX1HVT g2977(.A (n_10), .Y (n_9));
  INVX1HVT g2978(.A (n_8), .Y (n_7));
  NAND2X1HVT g2979(.A (i_shift_number[3]), .B (n_1), .Y (n_11));
  NOR2X1HVT g2980(.A (n_3), .B (i_shift_number[3]), .Y (n_10));
  NOR2X1HVT g2981(.A (i_shift_number[4]), .B (i_shift_number[3]), .Y
       (n_8));
  NOR2X1HVT g2982(.A (i_shift_number[2]), .B (i_shift_number[1]), .Y
       (n_6));
  NOR2X1HVT g2983(.A (i_shift_number[1]), .B (i_shift_number[0]), .Y
       (n_5));
  NAND2X1HVT g2984(.A (n_3), .B (i_shift_number[3]), .Y (n_4));
  INVX1HVT g2985(.A (i_shift_number[4]), .Y (n_3));
  INVX2HVT g2986(.A (i_shift_number[0]), .Y (n_2));
  INVX1HVT g2987(.A (i_shift_number[2]), .Y (n_1));
  INVX1HVT g2988(.A (i_shift_number[1]), .Y (n_0));
endmodule

module NORMALIZATION_unit_SIZE_LOPD5_SIZE_DATA28(i_overflow,
     i_zero_flag, i_one_position, i_mantissa, o_mantissa);
  input i_overflow, i_zero_flag;
  input [4:0] i_one_position;
  input [27:0] i_mantissa;
  output [27:0] o_mantissa;
  wire i_overflow, i_zero_flag;
  wire [4:0] i_one_position;
  wire [27:0] i_mantissa;
  wire [27:0] o_mantissa;
  wire [27:0] w_shift_left;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33;
  SHF_left_28bit_SIZE_DATA28_SIZE_SHIFT5
       SHF_left_28bit_unit(.i_shift_number (i_one_position), .i_data
       (i_mantissa), .o_data (w_shift_left));
  OAI2BB1X1HVT g1372(.A0N (i_mantissa[27]), .A1N (n_4), .B0 (n_15), .Y
       (o_mantissa[26]));
  OAI2BB1X1HVT g1373(.A0N (i_mantissa[25]), .A1N (n_6), .B0 (n_24), .Y
       (o_mantissa[25]));
  OAI2BB1X1HVT g1374(.A0N (n_5), .A1N (w_shift_left[23]), .B0 (n_27),
       .Y (o_mantissa[23]));
  OAI2BB1X1HVT g1375(.A0N (i_mantissa[18]), .A1N (n_6), .B0 (n_29), .Y
       (o_mantissa[18]));
  OAI2BB1X1HVT g1376(.A0N (n_5), .A1N (w_shift_left[9]), .B0 (n_32), .Y
       (o_mantissa[9]));
  OAI2BB1X1HVT g1377(.A0N (i_mantissa[8]), .A1N (n_6), .B0 (n_30), .Y
       (o_mantissa[8]));
  OAI2BB1X1HVT g1378(.A0N (n_5), .A1N (w_shift_left[17]), .B0 (n_26),
       .Y (o_mantissa[17]));
  OAI2BB1X1HVT g1379(.A0N (i_mantissa[7]), .A1N (n_6), .B0 (n_28), .Y
       (o_mantissa[7]));
  OAI2BB1X1HVT g1380(.A0N (i_mantissa[6]), .A1N (n_6), .B0 (n_25), .Y
       (o_mantissa[6]));
  OAI2BB1X1HVT g1381(.A0N (i_mantissa[22]), .A1N (n_6), .B0 (n_19), .Y
       (o_mantissa[22]));
  OAI2BB1X1HVT g1382(.A0N (n_5), .A1N (w_shift_left[16]), .B0 (n_21),
       .Y (o_mantissa[16]));
  OAI2BB1X1HVT g1383(.A0N (i_mantissa[5]), .A1N (n_6), .B0 (n_23), .Y
       (o_mantissa[5]));
  OAI2BB1X1HVT g1384(.A0N (i_mantissa[4]), .A1N (n_6), .B0 (n_22), .Y
       (o_mantissa[4]));
  OAI2BB1X1HVT g1385(.A0N (n_5), .A1N (w_shift_left[10]), .B0 (n_33),
       .Y (o_mantissa[10]));
  OAI2BB1X1HVT g1386(.A0N (i_mantissa[15]), .A1N (n_6), .B0 (n_17), .Y
       (o_mantissa[15]));
  OAI2BB1X1HVT g1387(.A0N (n_5), .A1N (w_shift_left[2]), .B0 (n_18), .Y
       (o_mantissa[2]));
  OAI2BB1X1HVT g1388(.A0N (n_5), .A1N (w_shift_left[1]), .B0 (n_16), .Y
       (o_mantissa[1]));
  OAI2BB1X1HVT g1389(.A0N (i_mantissa[24]), .A1N (n_6), .B0 (n_20), .Y
       (o_mantissa[24]));
  OAI2BB1X1HVT g1390(.A0N (i_mantissa[21]), .A1N (n_6), .B0 (n_13), .Y
       (o_mantissa[21]));
  OAI2BB1X1HVT g1391(.A0N (i_mantissa[14]), .A1N (n_6), .B0 (n_12), .Y
       (o_mantissa[14]));
  OAI2BB1X1HVT g1392(.A0N (n_5), .A1N (w_shift_left[0]), .B0 (n_14), .Y
       (o_mantissa[0]));
  OAI2BB1X1HVT g1393(.A0N (i_mantissa[20]), .A1N (n_6), .B0 (n_9), .Y
       (o_mantissa[20]));
  OAI2BB1X1HVT g1394(.A0N (n_5), .A1N (w_shift_left[13]), .B0 (n_11),
       .Y (o_mantissa[13]));
  OAI2BB1X1HVT g1395(.A0N (n_5), .A1N (w_shift_left[12]), .B0 (n_10),
       .Y (o_mantissa[12]));
  OAI2BB1X1HVT g1396(.A0N (i_mantissa[19]), .A1N (n_6), .B0 (n_31), .Y
       (o_mantissa[19]));
  OAI2BB1X1HVT g1397(.A0N (i_mantissa[11]), .A1N (n_6), .B0 (n_8), .Y
       (o_mantissa[11]));
  OAI2BB1X1HVT g1398(.A0N (n_5), .A1N (w_shift_left[3]), .B0 (n_7), .Y
       (o_mantissa[3]));
  AOI22XLHVT g1399(.A0 (i_mantissa[10]), .A1 (n_6), .B0
       (i_mantissa[11]), .B1 (n_4), .Y (n_33));
  AOI22XLHVT g1400(.A0 (i_mantissa[9]), .A1 (n_6), .B0
       (i_mantissa[10]), .B1 (n_4), .Y (n_32));
  AOI22X1HVT g1401(.A0 (n_5), .A1 (w_shift_left[19]), .B0
       (i_mantissa[20]), .B1 (n_4), .Y (n_31));
  AOI22X1HVT g1402(.A0 (n_5), .A1 (w_shift_left[8]), .B0
       (i_mantissa[9]), .B1 (n_4), .Y (n_30));
  AOI22X1HVT g1403(.A0 (n_5), .A1 (w_shift_left[18]), .B0
       (i_mantissa[19]), .B1 (n_4), .Y (n_29));
  AOI22X1HVT g1404(.A0 (n_5), .A1 (w_shift_left[7]), .B0
       (i_mantissa[8]), .B1 (n_4), .Y (n_28));
  AOI22XLHVT g1405(.A0 (i_mantissa[23]), .A1 (n_6), .B0
       (i_mantissa[24]), .B1 (n_4), .Y (n_27));
  AOI22XLHVT g1406(.A0 (i_mantissa[17]), .A1 (n_6), .B0
       (i_mantissa[18]), .B1 (n_4), .Y (n_26));
  AOI22X1HVT g1407(.A0 (n_5), .A1 (w_shift_left[6]), .B0
       (i_mantissa[7]), .B1 (n_4), .Y (n_25));
  AOI22X1HVT g1408(.A0 (n_5), .A1 (w_shift_left[25]), .B0
       (i_mantissa[26]), .B1 (n_4), .Y (n_24));
  AOI22X1HVT g1409(.A0 (n_5), .A1 (w_shift_left[5]), .B0
       (i_mantissa[6]), .B1 (n_4), .Y (n_23));
  AOI22X1HVT g1410(.A0 (n_5), .A1 (w_shift_left[4]), .B0
       (i_mantissa[5]), .B1 (n_4), .Y (n_22));
  AOI22XLHVT g1411(.A0 (i_mantissa[16]), .A1 (n_6), .B0
       (i_mantissa[17]), .B1 (n_4), .Y (n_21));
  AOI22X1HVT g1412(.A0 (n_5), .A1 (w_shift_left[24]), .B0
       (i_mantissa[25]), .B1 (n_4), .Y (n_20));
  AOI22X1HVT g1413(.A0 (n_5), .A1 (w_shift_left[22]), .B0
       (i_mantissa[23]), .B1 (n_4), .Y (n_19));
  AOI22XLHVT g1414(.A0 (i_mantissa[2]), .A1 (n_6), .B0 (i_mantissa[3]),
       .B1 (n_4), .Y (n_18));
  AOI22X1HVT g1415(.A0 (n_5), .A1 (w_shift_left[15]), .B0
       (i_mantissa[16]), .B1 (n_4), .Y (n_17));
  AOI22XLHVT g1416(.A0 (i_mantissa[1]), .A1 (n_6), .B0 (i_mantissa[2]),
       .B1 (n_4), .Y (n_16));
  AOI22X1HVT g1417(.A0 (n_5), .A1 (w_shift_left[26]), .B0
       (i_mantissa[26]), .B1 (n_1), .Y (n_15));
  AOI22XLHVT g1418(.A0 (i_mantissa[0]), .A1 (n_6), .B0 (i_mantissa[1]),
       .B1 (n_4), .Y (n_14));
  AOI22X1HVT g1419(.A0 (n_5), .A1 (w_shift_left[21]), .B0
       (i_mantissa[22]), .B1 (n_4), .Y (n_13));
  AOI22X1HVT g1420(.A0 (n_5), .A1 (w_shift_left[14]), .B0
       (i_mantissa[15]), .B1 (n_4), .Y (n_12));
  AOI22XLHVT g1421(.A0 (i_mantissa[13]), .A1 (n_6), .B0
       (i_mantissa[14]), .B1 (n_4), .Y (n_11));
  AOI22XLHVT g1422(.A0 (i_mantissa[12]), .A1 (n_6), .B0
       (i_mantissa[13]), .B1 (n_4), .Y (n_10));
  AOI22X1HVT g1423(.A0 (n_5), .A1 (w_shift_left[20]), .B0
       (i_mantissa[21]), .B1 (n_4), .Y (n_9));
  AOI22X1HVT g1424(.A0 (n_5), .A1 (w_shift_left[11]), .B0
       (i_mantissa[12]), .B1 (n_4), .Y (n_8));
  AOI22XLHVT g1425(.A0 (i_mantissa[3]), .A1 (n_6), .B0 (i_mantissa[4]),
       .B1 (n_4), .Y (n_7));
  OAI211X1HVT g1426(.A0 (i_zero_flag), .A1 (n_0), .B0 (n_2), .C0 (n_3),
       .Y (o_mantissa[27]));
  NOR2X1HVT g1427(.A (i_overflow), .B (n_2), .Y (n_6));
  NOR3X1HVT g1428(.A (i_mantissa[27]), .B (i_overflow), .C
       (i_zero_flag), .Y (n_5));
  INVX1HVT g1429(.A (n_4), .Y (n_3));
  NOR2BX1HVT g1430(.AN (i_overflow), .B (i_zero_flag), .Y (n_4));
  INVX1HVT g1431(.A (n_2), .Y (n_1));
  NAND2BX1HVT g1432(.AN (i_zero_flag), .B (i_mantissa[27]), .Y (n_2));
  INVX1HVT g1433(.A (w_shift_left[27]), .Y (n_0));
endmodule

module PSC_unit(i_add_sub, i_sign_a, i_exp_a, i_man_a, i_sign_b,
     i_exp_b, i_man_b, o_sel_exp, o_sel_man);
  input i_add_sub, i_sign_a, i_sign_b;
  input [7:0] i_exp_a, i_exp_b;
  input [23:0] i_man_a, i_man_b;
  output o_sel_exp;
  output [1:0] o_sel_man;
  wire i_add_sub, i_sign_a, i_sign_b;
  wire [7:0] i_exp_a, i_exp_b;
  wire [23:0] i_man_a, i_man_b;
  wire o_sel_exp;
  wire [1:0] o_sel_man;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_31;
  OAI2BB1X1HVT g625(.A0N (n_21), .A1N (n_31), .B0 (n_29), .Y
       (o_sel_exp));
  OAI32X1HVT g626(.A0 (n_19), .A1 (n_26), .A2 (n_24), .B0 (i_sign_b),
       .B1 (n_25), .Y (n_31));
  OAI2BB1X1HVT g627(.A0N (n_21), .A1N (n_27), .B0 (n_28), .Y
       (o_sel_man[0]));
  NAND3BXLHVT g628(.AN (i_sign_a), .B (n_20), .C (n_26), .Y (n_29));
  NAND2X1HVT g629(.A (n_20), .B (n_26), .Y (n_28));
  OAI2BB1X1HVT g630(.A0N (n_20), .A1N (n_22), .B0 (n_25), .Y (n_27));
  NAND4XLHVT g631(.A (n_3), .B (n_7), .C (n_16), .D (n_18), .Y (n_26));
  INVX1HVT g632(.A (n_24), .Y (n_25));
  NAND4XLHVT g633(.A (n_14), .B (n_6), .C (n_15), .D (n_17), .Y (n_24));
  OR2X1HVT g634(.A (n_21), .B (n_20), .Y (o_sel_man[1]));
  XNOR2X1HVT g635(.A (i_add_sub), .B (n_8), .Y (n_22));
  INVX1HVT g636(.A (n_20), .Y (n_19));
  AND2XLHVT g637(.A (n_5), .B (n_2), .Y (n_18));
  NOR2X1HVT g638(.A (n_10), .B (n_12), .Y (n_21));
  NOR2X1HVT g639(.A (n_13), .B (n_11), .Y (n_20));
  AND2XLHVT g640(.A (n_1), .B (n_0), .Y (n_17));
  NOR4X1HVT g641(.A (i_man_a[10]), .B (i_man_a[15]), .C (i_man_a[4]),
       .D (n_9), .Y (n_16));
  NOR4X1HVT g642(.A (i_man_b[3]), .B (i_man_b[18]), .C (i_man_b[13]),
       .D (n_4), .Y (n_15));
  NOR4X1HVT g643(.A (i_man_b[14]), .B (i_man_b[19]), .C (i_man_b[20]),
       .D (i_man_b[21]), .Y (n_14));
  NAND4XLHVT g644(.A (i_exp_a[4]), .B (i_exp_a[5]), .C (i_exp_a[6]), .D
       (i_exp_a[7]), .Y (n_13));
  NAND4XLHVT g645(.A (i_exp_b[0]), .B (i_exp_b[1]), .C (i_exp_b[2]), .D
       (i_exp_b[3]), .Y (n_12));
  NAND4XLHVT g646(.A (i_exp_a[0]), .B (i_exp_a[1]), .C (i_exp_a[2]), .D
       (i_exp_a[3]), .Y (n_11));
  NAND4XLHVT g647(.A (i_exp_b[4]), .B (i_exp_b[5]), .C (i_exp_b[6]), .D
       (i_exp_b[7]), .Y (n_10));
  OR4X1HVT g648(.A (i_man_a[8]), .B (i_man_a[9]), .C (i_man_a[11]), .D
       (i_man_a[18]), .Y (n_9));
  XNOR2X1HVT g649(.A (i_sign_b), .B (i_sign_a), .Y (n_8));
  NOR4X1HVT g650(.A (i_man_a[0]), .B (i_man_a[1]), .C (i_man_a[5]), .D
       (i_man_a[6]), .Y (n_7));
  NOR4X1HVT g651(.A (i_man_b[1]), .B (i_man_b[2]), .C (i_man_b[15]), .D
       (i_man_b[22]), .Y (n_6));
  NOR4X1HVT g652(.A (i_man_a[16]), .B (i_man_a[17]), .C (i_man_a[20]),
       .D (i_man_a[21]), .Y (n_5));
  OR4X1HVT g653(.A (i_man_b[4]), .B (i_man_b[5]), .C (i_man_b[16]), .D
       (i_man_b[17]), .Y (n_4));
  NOR4X1HVT g654(.A (i_man_a[2]), .B (i_man_a[7]), .C (i_man_a[12]), .D
       (i_man_a[13]), .Y (n_3));
  NOR4X1HVT g655(.A (i_man_a[3]), .B (i_man_a[22]), .C (i_man_a[14]),
       .D (i_man_a[19]), .Y (n_2));
  NOR4X1HVT g656(.A (i_man_b[7]), .B (i_man_b[8]), .C (i_man_b[9]), .D
       (i_man_b[10]), .Y (n_1));
  NOR4X1HVT g657(.A (i_man_b[0]), .B (i_man_b[6]), .C (i_man_b[11]), .D
       (i_man_b[12]), .Y (n_0));
endmodule

module RND_add_SIZE_DATA24(i_data, i_carry, o_data, o_carry);
  input [23:0] i_data;
  input i_carry;
  output [23:0] o_data;
  output o_carry;
  wire [23:0] i_data;
  wire i_carry;
  wire [23:0] o_data;
  wire o_carry;
  wire n_0, n_2, n_4, n_6, n_8, n_10, n_12, n_14;
  wire n_16, n_18, n_20, n_22, n_24, n_26, n_28, n_30;
  wire n_32, n_34, n_36, n_38, n_40, n_43;
  assign o_data[23] = 1'b0;
  AND3XLHVT g598(.A (i_data[22]), .B (i_data[23]), .C (n_43), .Y
       (o_carry));
  XOR2XLHVT g599(.A (i_data[22]), .B (n_43), .Y (o_data[22]));
  ADDHX1HVT g600(.A (i_data[21]), .B (n_40), .CO (n_43), .S
       (o_data[21]));
  ADDHX1HVT g601(.A (i_data[20]), .B (n_38), .CO (n_40), .S
       (o_data[20]));
  ADDHX1HVT g602(.A (i_data[19]), .B (n_36), .CO (n_38), .S
       (o_data[19]));
  ADDHX1HVT g603(.A (i_data[18]), .B (n_34), .CO (n_36), .S
       (o_data[18]));
  ADDHX1HVT g604(.A (i_data[17]), .B (n_32), .CO (n_34), .S
       (o_data[17]));
  ADDHX1HVT g605(.A (i_data[16]), .B (n_30), .CO (n_32), .S
       (o_data[16]));
  ADDHX1HVT g606(.A (i_data[15]), .B (n_28), .CO (n_30), .S
       (o_data[15]));
  ADDHX1HVT g607(.A (i_data[14]), .B (n_26), .CO (n_28), .S
       (o_data[14]));
  ADDHX1HVT g608(.A (i_data[13]), .B (n_24), .CO (n_26), .S
       (o_data[13]));
  ADDHX1HVT g609(.A (i_data[12]), .B (n_22), .CO (n_24), .S
       (o_data[12]));
  ADDHX1HVT g610(.A (i_data[11]), .B (n_20), .CO (n_22), .S
       (o_data[11]));
  ADDHX1HVT g611(.A (i_data[10]), .B (n_18), .CO (n_20), .S
       (o_data[10]));
  ADDHX1HVT g612(.A (i_data[9]), .B (n_16), .CO (n_18), .S (o_data[9]));
  ADDHX1HVT g613(.A (i_data[8]), .B (n_14), .CO (n_16), .S (o_data[8]));
  ADDHX1HVT g614(.A (i_data[7]), .B (n_12), .CO (n_14), .S (o_data[7]));
  ADDHX1HVT g615(.A (i_data[6]), .B (n_10), .CO (n_12), .S (o_data[6]));
  ADDHX1HVT g616(.A (i_data[5]), .B (n_8), .CO (n_10), .S (o_data[5]));
  ADDHX1HVT g617(.A (i_data[4]), .B (n_6), .CO (n_8), .S (o_data[4]));
  ADDHX1HVT g618(.A (i_data[3]), .B (n_4), .CO (n_6), .S (o_data[3]));
  ADDHX1HVT g619(.A (i_data[2]), .B (n_2), .CO (n_4), .S (o_data[2]));
  ADDHX1HVT g620(.A (i_data[1]), .B (n_0), .CO (n_2), .S (o_data[1]));
  ADDHX1HVT g621(.A (i_data[0]), .B (i_carry), .CO (n_0), .S
       (o_data[0]));
endmodule

module ROUNDING_unit_SIZE_MAN28_SIZE_MAN_RESULT24(i_man, o_man_result,
     o_ov_flow);
  input [27:0] i_man;
  output [23:0] o_man_result;
  output o_ov_flow;
  wire [27:0] i_man;
  wire [23:0] o_man_result;
  wire o_ov_flow;
  wire n_0, n_7, w_rounding_result;
  assign o_man_result[23] = 1'b0;
  RND_add_SIZE_DATA24 INCREASE_ROUNDING(.i_data (i_man[27:4]), .i_carry
       (w_rounding_result), .o_data ({n_7, o_man_result[22:0]}),
       .o_carry (o_ov_flow));
  NOR2BX1HVT g33(.AN (i_man[2]), .B (n_0), .Y (w_rounding_result));
  NOR3X1HVT g34(.A (i_man[0]), .B (i_man[1]), .C (i_man[3]), .Y (n_0));
endmodule

module Mux_4_to_1_SIZE_DATA24(i_sel, i_data_00, i_data_01, i_data_10,
     i_data_11, o_data);
  input [1:0] i_sel;
  input [23:0] i_data_00, i_data_01, i_data_10, i_data_11;
  output [23:0] o_data;
  wire [1:0] i_sel;
  wire [23:0] i_data_00, i_data_01, i_data_10, i_data_11;
  wire [23:0] o_data;
  assign o_data[23] = 1'b0;
  MX2XLHVT g241(.A (i_data_01[22]), .B (i_sel[0]), .S0 (i_sel[1]), .Y
       (o_data[22]));
  NOR2BX1HVT g242(.AN (i_data_01[16]), .B (i_sel[1]), .Y (o_data[16]));
  NOR2BX1HVT g243(.AN (i_data_01[17]), .B (i_sel[1]), .Y (o_data[17]));
  NOR2BX1HVT g244(.AN (i_data_01[9]), .B (i_sel[1]), .Y (o_data[9]));
  NOR2BX1HVT g245(.AN (i_data_01[1]), .B (i_sel[1]), .Y (o_data[1]));
  NOR2BX1HVT g246(.AN (i_data_01[8]), .B (i_sel[1]), .Y (o_data[8]));
  NOR2BX1HVT g247(.AN (i_data_01[21]), .B (i_sel[1]), .Y (o_data[21]));
  NOR2BX1HVT g248(.AN (i_data_01[7]), .B (i_sel[1]), .Y (o_data[7]));
  NOR2BX1HVT g249(.AN (i_data_01[6]), .B (i_sel[1]), .Y (o_data[6]));
  NOR2BX1HVT g250(.AN (i_data_01[20]), .B (i_sel[1]), .Y (o_data[20]));
  NOR2BX1HVT g251(.AN (i_data_01[15]), .B (i_sel[1]), .Y (o_data[15]));
  NOR2BX1HVT g252(.AN (i_data_01[5]), .B (i_sel[1]), .Y (o_data[5]));
  NOR2BX1HVT g253(.AN (i_data_01[13]), .B (i_sel[1]), .Y (o_data[13]));
  NOR2BX1HVT g254(.AN (i_data_01[14]), .B (i_sel[1]), .Y (o_data[14]));
  NOR2BX1HVT g255(.AN (i_data_01[3]), .B (i_sel[1]), .Y (o_data[3]));
  NOR2BX1HVT g256(.AN (i_data_01[2]), .B (i_sel[1]), .Y (o_data[2]));
  NOR2BX1HVT g257(.AN (i_data_01[19]), .B (i_sel[1]), .Y (o_data[19]));
  NOR2BX1HVT g258(.AN (i_data_01[4]), .B (i_sel[1]), .Y (o_data[4]));
  NOR2BX1HVT g259(.AN (i_data_01[0]), .B (i_sel[1]), .Y (o_data[0]));
  NOR2BX1HVT g260(.AN (i_data_01[12]), .B (i_sel[1]), .Y (o_data[12]));
  NOR2BX1HVT g261(.AN (i_data_01[18]), .B (i_sel[1]), .Y (o_data[18]));
  NOR2BX1HVT g262(.AN (i_data_01[11]), .B (i_sel[1]), .Y (o_data[11]));
  NOR2BX1HVT g263(.AN (i_data_01[10]), .B (i_sel[1]), .Y (o_data[10]));
endmodule

module SHF_right_28bit_SIZE_DATA28_SIZE_SHIFT5(i_shift_number, i_data,
     o_data);
  input [4:0] i_shift_number;
  input [27:0] i_data;
  output [27:0] o_data;
  wire [4:0] i_shift_number;
  wire [27:0] i_data;
  wire [27:0] o_data;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_43, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_102, n_103;
  wire n_104, n_109, n_110, n_111, n_112, n_124, n_125, n_128;
  OAI211X1HVT g3594(.A0 (i_shift_number[1]), .A1 (n_45), .B0 (n_104),
       .C0 (n_125), .Y (o_data[3]));
  OAI221X1HVT g3595(.A0 (n_83), .A1 (n_7), .B0 (n_73), .B1 (n_28), .C0
       (n_124), .Y (o_data[2]));
  OAI221X1HVT g3596(.A0 (n_67), .A1 (n_28), .B0 (n_36), .B1 (n_32), .C0
       (n_128), .Y (o_data[1]));
  AOI22X1HVT g3597(.A0 (i_shift_number[4]), .A1 (n_112), .B0 (n_80),
       .B1 (n_6), .Y (n_128));
  OAI22X1HVT g3598(.A0 (n_102), .A1 (i_shift_number[4]), .B0 (n_63),
       .B1 (n_0), .Y (o_data[9]));
  OAI22X1HVT g3599(.A0 (i_shift_number[3]), .A1 (n_103), .B0 (n_94),
       .B1 (n_7), .Y (o_data[5]));
  AOI22X1HVT g3600(.A0 (i_shift_number[4]), .A1 (n_110), .B0 (n_2), .B1
       (n_46), .Y (n_125));
  AOI22X1HVT g3601(.A0 (i_shift_number[4]), .A1 (n_111), .B0 (n_2), .B1
       (n_43), .Y (n_124));
  OAI222X1HVT g3602(.A0 (n_4), .A1 (n_109), .B0 (n_79), .B1 (n_7), .C0
       (n_57), .C1 (n_28), .Y (o_data[0]));
  AND2X1HVT g3603(.A (n_111), .B (n_4), .Y (o_data[18]));
  NOR2X1HVT g3604(.A (i_shift_number[4]), .B (n_109), .Y (o_data[16]));
  AND2X1HVT g3605(.A (n_112), .B (n_4), .Y (o_data[17]));
  AND2X1HVT g3606(.A (n_110), .B (n_4), .Y (o_data[19]));
  OAI221X1HVT g3607(.A0 (n_96), .A1 (n_7), .B0 (n_92), .B1 (n_8), .C0
       (n_91), .Y (o_data[6]));
  OAI221X1HVT g3608(.A0 (n_97), .A1 (n_7), .B0 (n_78), .B1 (n_8), .C0
       (n_90), .Y (o_data[7]));
  OAI222X1HVT g3609(.A0 (n_95), .A1 (n_7), .B0 (n_85), .B1 (n_11), .C0
       (n_33), .C1 (n_8), .Y (o_data[11]));
  OAI222X1HVT g3610(.A0 (n_93), .A1 (n_8), .B0 (n_88), .B1 (n_11), .C0
       (n_87), .C1 (n_7), .Y (o_data[4]));
  OAI222X1HVT g3611(.A0 (n_86), .A1 (n_7), .B0 (n_83), .B1 (n_11), .C0
       (n_31), .C1 (n_0), .Y (o_data[10]));
  OAI222X1HVT g3612(.A0 (n_84), .A1 (n_7), .B0 (n_79), .B1 (n_11), .C0
       (n_48), .C1 (n_0), .Y (o_data[8]));
  OAI22X1HVT g3613(.A0 (n_97), .A1 (n_11), .B0 (n_78), .B1 (n_7), .Y
       (o_data[15]));
  OAI22XLHVT g3614(.A0 (i_shift_number[3]), .A1 (n_81), .B0 (n_63), .B1
       (n_9), .Y (n_112));
  OAI22X1HVT g3615(.A0 (i_shift_number[3]), .A1 (n_86), .B0 (n_31), .B1
       (n_9), .Y (n_111));
  OAI22X1HVT g3616(.A0 (i_shift_number[3]), .A1 (n_95), .B0 (n_5), .B1
       (n_33), .Y (n_110));
  OA22X1HVT g3617(.A0 (i_shift_number[3]), .A1 (n_84), .B0 (n_48), .B1
       (n_9), .Y (n_109));
  OAI22X1HVT g3618(.A0 (n_96), .A1 (n_11), .B0 (n_92), .B1 (n_7), .Y
       (o_data[14]));
  OAI22X1HVT g3619(.A0 (n_94), .A1 (n_11), .B0 (n_77), .B1 (n_7), .Y
       (o_data[13]));
  OAI22X1HVT g3620(.A0 (n_87), .A1 (n_11), .B0 (n_93), .B1 (n_7), .Y
       (o_data[12]));
  OA22X1HVT g3621(.A0 (n_85), .A1 (n_7), .B0 (n_55), .B1 (n_28), .Y
       (n_104));
  MX2XLHVT g3622(.A (n_89), .B (n_77), .S0 (i_shift_number[4]), .Y
       (n_103));
  AOI22X1HVT g3623(.A0 (n_5), .A1 (n_80), .B0 (i_shift_number[3]), .B1
       (n_82), .Y (n_102));
  NOR2X1HVT g3624(.A (n_92), .B (n_11), .Y (o_data[22]));
  NOR2X1HVT g3625(.A (n_93), .B (n_11), .Y (o_data[20]));
  NOR2X1HVT g3626(.A (n_77), .B (n_11), .Y (o_data[21]));
  NOR2X1HVT g3627(.A (n_78), .B (n_11), .Y (o_data[23]));
  OA22X1HVT g3628(.A0 (n_73), .A1 (n_29), .B0 (n_59), .B1 (n_28), .Y
       (n_91));
  OA22X1HVT g3629(.A0 (n_55), .A1 (n_29), .B0 (n_54), .B1 (n_28), .Y
       (n_90));
  AOI22XLHVT g3630(.A0 (n_2), .A1 (n_66), .B0 (i_shift_number[2]), .B1
       (n_52), .Y (n_89));
  AOI22X1HVT g3631(.A0 (n_56), .A1 (n_2), .B0 (i_shift_number[2]), .B1
       (n_50), .Y (n_88));
  AOI22X1HVT g3632(.A0 (n_71), .A1 (n_2), .B0 (i_shift_number[2]), .B1
       (n_68), .Y (n_97));
  AOI22X1HVT g3633(.A0 (n_74), .A1 (n_2), .B0 (i_shift_number[2]), .B1
       (n_60), .Y (n_96));
  AOI22X1HVT g3634(.A0 (n_68), .A1 (n_2), .B0 (i_shift_number[2]), .B1
       (n_70), .Y (n_95));
  AOI22X1HVT g3635(.A0 (n_69), .A1 (n_2), .B0 (n_61), .B1
       (i_shift_number[2]), .Y (n_94));
  AOI22X1HVT g3636(.A0 (n_72), .A1 (n_2), .B0 (i_shift_number[2]), .B1
       (n_47), .Y (n_93));
  AOI22X1HVT g3637(.A0 (n_64), .A1 (n_2), .B0 (n_30), .B1
       (i_shift_number[2]), .Y (n_92));
  INVX1HVT g3638(.A (n_81), .Y (n_82));
  AOI22X1HVT g3639(.A0 (n_65), .A1 (n_2), .B0 (i_shift_number[2]), .B1
       (n_49), .Y (n_87));
  AOI22X1HVT g3640(.A0 (n_60), .A1 (n_2), .B0 (i_shift_number[2]), .B1
       (n_64), .Y (n_86));
  AOI22X1HVT g3641(.A0 (n_53), .A1 (n_2), .B0 (i_shift_number[2]), .B1
       (n_71), .Y (n_85));
  AOI22X1HVT g3642(.A0 (n_49), .A1 (n_2), .B0 (n_72), .B1
       (i_shift_number[2]), .Y (n_84));
  AOI22X1HVT g3643(.A0 (n_58), .A1 (n_2), .B0 (n_74), .B1
       (i_shift_number[2]), .Y (n_83));
  AOI22X1HVT g3644(.A0 (n_61), .A1 (n_2), .B0 (i_shift_number[2]), .B1
       (n_51), .Y (n_81));
  MX2X1HVT g3645(.A (n_52), .B (n_69), .S0 (i_shift_number[2]), .Y
       (n_80));
  AOI22X1HVT g3646(.A0 (n_50), .A1 (n_2), .B0 (n_65), .B1
       (i_shift_number[2]), .Y (n_79));
  AOI32X1HVT g3647(.A0 (n_3), .A1 (n_1), .A2 (i_shift_number[2]), .B0
       (n_70), .B1 (n_2), .Y (n_78));
  AOI22X1HVT g3648(.A0 (n_51), .A1 (n_2), .B0 (i_shift_number[2]), .B1
       (n_62), .Y (n_77));
  NOR2X1HVT g3649(.A (n_48), .B (n_29), .Y (o_data[24]));
  NOR2X1HVT g3650(.A (n_63), .B (n_29), .Y (o_data[25]));
  INVX1HVT g3651(.A (n_66), .Y (n_67));
  INVX1HVT g3652(.A (n_62), .Y (n_63));
  OAI22XLHVT g3653(.A0 (n_38), .A1 (i_shift_number[1]), .B0 (n_34), .B1
       (n_1), .Y (n_74));
  OA22X1HVT g3654(.A0 (n_20), .A1 (i_shift_number[1]), .B0 (n_13), .B1
       (n_1), .Y (n_73));
  OAI22X1HVT g3655(.A0 (n_15), .A1 (i_shift_number[1]), .B0 (n_24), .B1
       (n_1), .Y (n_72));
  OAI22XLHVT g3656(.A0 (n_17), .A1 (i_shift_number[1]), .B0 (n_16), .B1
       (n_1), .Y (n_71));
  OAI22X1HVT g3657(.A0 (n_14), .A1 (i_shift_number[1]), .B0 (n_26), .B1
       (n_1), .Y (n_70));
  OAI22X1HVT g3658(.A0 (n_39), .A1 (i_shift_number[1]), .B0 (n_17), .B1
       (n_1), .Y (n_69));
  OAI22XLHVT g3659(.A0 (n_40), .A1 (i_shift_number[1]), .B0 (n_22), .B1
       (n_1), .Y (n_68));
  OAI22X1HVT g3660(.A0 (n_37), .A1 (i_shift_number[1]), .B0 (n_35), .B1
       (n_1), .Y (n_66));
  OAI22XLHVT g3661(.A0 (n_25), .A1 (i_shift_number[1]), .B0 (n_38), .B1
       (n_1), .Y (n_65));
  OAI22XLHVT g3662(.A0 (n_24), .A1 (i_shift_number[1]), .B0 (n_19), .B1
       (n_1), .Y (n_64));
  OAI22X1HVT g3663(.A0 (n_26), .A1 (i_shift_number[1]), .B0
       (i_shift_number[0]), .B1 (n_1), .Y (n_62));
  INVX1HVT g3664(.A (n_58), .Y (n_59));
  INVX1HVT g3665(.A (n_56), .Y (n_57));
  INVX1HVT g3666(.A (n_53), .Y (n_54));
  INVX1HVT g3667(.A (n_47), .Y (n_48));
  OAI22X1HVT g3668(.A0 (n_16), .A1 (i_shift_number[1]), .B0 (n_40), .B1
       (n_1), .Y (n_61));
  OAI22XLHVT g3669(.A0 (n_23), .A1 (i_shift_number[1]), .B0 (n_15), .B1
       (n_1), .Y (n_60));
  OAI22XLHVT g3670(.A0 (n_41), .A1 (i_shift_number[1]), .B0 (n_25), .B1
       (n_1), .Y (n_58));
  OAI22XLHVT g3671(.A0 (n_21), .A1 (i_shift_number[1]), .B0 (n_20), .B1
       (n_1), .Y (n_56));
  OA22X1HVT g3672(.A0 (n_35), .A1 (i_shift_number[1]), .B0 (n_27), .B1
       (n_1), .Y (n_55));
  OAI22XLHVT g3673(.A0 (n_18), .A1 (i_shift_number[1]), .B0 (n_39), .B1
       (n_1), .Y (n_53));
  OAI22X1HVT g3674(.A0 (n_27), .A1 (i_shift_number[1]), .B0 (n_18), .B1
       (n_1), .Y (n_52));
  OAI22X1HVT g3675(.A0 (n_22), .A1 (i_shift_number[1]), .B0 (n_14), .B1
       (n_1), .Y (n_51));
  OAI22X1HVT g3676(.A0 (n_13), .A1 (i_shift_number[1]), .B0 (n_41), .B1
       (n_1), .Y (n_50));
  OAI22X1HVT g3677(.A0 (n_34), .A1 (i_shift_number[1]), .B0 (n_23), .B1
       (n_1), .Y (n_49));
  OAI22XLHVT g3678(.A0 (n_19), .A1 (i_shift_number[1]), .B0 (n_12), .B1
       (n_1), .Y (n_47));
  NOR2XLHVT g3679(.A (n_37), .B (n_32), .Y (n_46));
  OR2XLHVT g3680(.A (n_36), .B (n_11), .Y (n_45));
  NOR2X1HVT g3681(.A (n_31), .B (n_29), .Y (o_data[26]));
  NOR2XLHVT g3682(.A (n_21), .B (n_32), .Y (n_43));
  NOR2X1HVT g3683(.A (n_33), .B (n_11), .Y (o_data[27]));
  INVX1HVT g3684(.A (n_30), .Y (n_31));
  AOI22X1HVT g3685(.A0 (i_data[10]), .A1 (n_3), .B0 (i_data[11]), .B1
       (i_shift_number[0]), .Y (n_41));
  AOI22XLHVT g3686(.A0 (i_data[19]), .A1 (n_3), .B0 (i_data[20]), .B1
       (i_shift_number[0]), .Y (n_40));
  AOI22XLHVT g3687(.A0 (i_data[13]), .A1 (n_3), .B0 (i_data[14]), .B1
       (i_shift_number[0]), .Y (n_39));
  AOI22X1HVT g3688(.A0 (i_data[14]), .A1 (n_3), .B0 (i_data[15]), .B1
       (i_shift_number[0]), .Y (n_38));
  AOI22XLHVT g3689(.A0 (i_data[5]), .A1 (n_3), .B0 (i_data[6]), .B1
       (i_shift_number[0]), .Y (n_37));
  NAND3BXLHVT g3690(.AN (n_3), .B (i_data[4]), .C (n_2), .Y (n_36));
  AOI22X1HVT g3691(.A0 (i_data[7]), .A1 (n_3), .B0 (i_data[8]), .B1
       (i_shift_number[0]), .Y (n_35));
  AOI22X1HVT g3692(.A0 (i_data[16]), .A1 (n_3), .B0 (i_data[17]), .B1
       (i_shift_number[0]), .Y (n_34));
  NAND3X1HVT g3693(.A (n_3), .B (n_1), .C (n_2), .Y (n_33));
  NAND2XLHVT g3695(.A (i_shift_number[1]), .B (n_10), .Y (n_32));
  NOR2XLHVT g3696(.A (n_12), .B (i_shift_number[1]), .Y (n_30));
  NAND2X1HVT g3697(.A (n_2), .B (n_10), .Y (n_29));
  NAND2X1HVT g3698(.A (i_shift_number[2]), .B (n_10), .Y (n_28));
  AOI22XLHVT g3699(.A0 (i_data[9]), .A1 (n_3), .B0 (i_data[10]), .B1
       (i_shift_number[0]), .Y (n_27));
  AOI22X1HVT g3700(.A0 (i_data[25]), .A1 (n_3), .B0 (i_data[26]), .B1
       (i_shift_number[0]), .Y (n_26));
  AOI22X1HVT g3701(.A0 (i_data[12]), .A1 (n_3), .B0 (i_data[13]), .B1
       (i_shift_number[0]), .Y (n_25));
  AOI22X1HVT g3702(.A0 (i_data[22]), .A1 (n_3), .B0 (i_data[23]), .B1
       (i_shift_number[0]), .Y (n_24));
  AOI22X1HVT g3703(.A0 (i_data[18]), .A1 (n_3), .B0 (i_data[19]), .B1
       (i_shift_number[0]), .Y (n_23));
  AOI22XLHVT g3704(.A0 (i_data[21]), .A1 (n_3), .B0 (i_data[22]), .B1
       (i_shift_number[0]), .Y (n_22));
  AOI22X1HVT g3705(.A0 (i_data[4]), .A1 (n_3), .B0 (i_data[5]), .B1
       (i_shift_number[0]), .Y (n_21));
  AOI22X1HVT g3706(.A0 (i_data[6]), .A1 (n_3), .B0 (i_data[7]), .B1
       (i_shift_number[0]), .Y (n_20));
  AOI22X1HVT g3707(.A0 (i_data[24]), .A1 (n_3), .B0 (i_data[25]), .B1
       (i_shift_number[0]), .Y (n_19));
  AOI22X1HVT g3708(.A0 (i_data[11]), .A1 (n_3), .B0 (i_data[12]), .B1
       (i_shift_number[0]), .Y (n_18));
  AOI22XLHVT g3709(.A0 (i_data[15]), .A1 (n_3), .B0 (i_data[16]), .B1
       (i_shift_number[0]), .Y (n_17));
  AOI22XLHVT g3710(.A0 (i_data[17]), .A1 (n_3), .B0 (i_data[18]), .B1
       (i_shift_number[0]), .Y (n_16));
  AOI22X1HVT g3711(.A0 (i_data[20]), .A1 (n_3), .B0 (i_data[21]), .B1
       (i_shift_number[0]), .Y (n_15));
  AOI22X1HVT g3712(.A0 (i_data[23]), .A1 (n_3), .B0 (i_data[24]), .B1
       (i_shift_number[0]), .Y (n_14));
  AOI22X1HVT g3713(.A0 (i_data[8]), .A1 (n_3), .B0 (i_data[9]), .B1
       (i_shift_number[0]), .Y (n_13));
  INVX1HVT g3714(.A (n_11), .Y (n_10));
  NOR2XLHVT g3715(.A (i_data[26]), .B (i_shift_number[0]), .Y (n_12));
  NAND2X1HVT g3716(.A (n_5), .B (n_4), .Y (n_11));
  INVX1HVT g3718(.A (n_7), .Y (n_6));
  NAND2X1HVT g3719(.A (n_2), .B (i_shift_number[3]), .Y (n_9));
  NAND2X1HVT g3720(.A (n_5), .B (i_shift_number[4]), .Y (n_8));
  NAND2X1HVT g3721(.A (i_shift_number[3]), .B (n_4), .Y (n_7));
  INVX1HVT g3722(.A (i_shift_number[3]), .Y (n_5));
  INVX1HVT g3723(.A (i_shift_number[4]), .Y (n_4));
  INVX2HVT g3724(.A (i_shift_number[0]), .Y (n_3));
  INVX2HVT g3725(.A (i_shift_number[2]), .Y (n_2));
  INVX2HVT g3726(.A (i_shift_number[1]), .Y (n_1));
  NAND2BX1HVT g2(.AN (n_8), .B (n_2), .Y (n_0));
endmodule

module SIGN_unit(i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b,
     o_sign_s);
  input i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b;
  output o_sign_s;
  wire i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b;
  wire o_sign_s;
  wire n_0;
  MX2XLHVT g53(.A (i_sign_man_a), .B (n_0), .S0 (i_comp_man), .Y
       (o_sign_s));
  XOR2XLHVT g54(.A (i_sign_man_b), .B (i_add_sub), .Y (n_0));
endmodule

module FPU_unit(i_add_sub, i_32_a, i_32_b, o_32_s, o_ov_flag,
     o_un_flag);
  input [0:0] i_add_sub;
  input [31:0] i_32_a, i_32_b;
  output [31:0] o_32_s;
  output o_ov_flag, o_un_flag;
  wire [0:0] i_add_sub;
  wire [31:0] i_32_a, i_32_b;
  wire [31:0] o_32_s;
  wire o_ov_flag, o_un_flag;
  wire [27:0] w_MAN_ALU_man;
  wire [4:0] w_LOPD_24BIT_one_position;
  wire [7:0] w_EXPSWAP_max;
  wire [7:0] w_EXP_ADJUST_result;
  wire [7:0] w_EXP_ROUNDING;
  wire [7:0] w_EXPSWAP_min;
  wire [7:0] w_EXPSUB_diff_value;
  wire [27:0] w_MAN_PRE_SWAP_BY_MAN_max;
  wire [27:0] w_MAN_PRE_SWAP_BY_MAN_min;
  wire [23:0] w_MAN_SWAP1_max;
  wire [27:0] w_MAN_SHF_RIGHT_min;
  wire [23:0] w_MAN_SWAP1_min;
  wire [27:0] w_NORMALIZATION_man;
  wire [1:0] PSC_o_sel_man;
  wire [23:0] w_ROUNDING_man;
  wire [23:0] w_mantissa_result;
  wire PSC_o_sel_exp, UNCONNECTED1, UNCONNECTED2, n_4,
       w_EXPSWAP_compare, w_LOPD_24BIT_zero_flag, w_MAN_ALU_overflow,
       w_MAN_PRE_SWAP_BY_MAN_compara;
  wire w_ROUNDING_ov_flow;
  EXP_adjust_SIZE_EXP8_SIZE_LOPD8 EXP_ADJUST_UNIT(.i_overflow
       (w_MAN_ALU_overflow), .i_underflow (w_MAN_ALU_man[27]),
       .i_zero_flag (w_LOPD_24BIT_zero_flag), .i_lopd_value ({3'b000,
       w_LOPD_24BIT_one_position}), .i_exp_value (w_EXPSWAP_max),
       .o_exp_result (w_EXP_ADJUST_result));
  EXP_rounding_SIZE_DATA8 EXP_ROUNDING(.i_carry_rounding
       (w_ROUNDING_ov_flow), .i_exp_result (w_EXP_ADJUST_result),
       .o_exp_result (w_EXP_ROUNDING));
  EXP_sub_SIZE_EXP_SUB8 EXP_SUB_UNIT(.i_data_a ({3'b000,
       w_EXPSWAP_max[4:0]}), .i_data_b ({3'b000, w_EXPSWAP_min[4:0]}),
       .o_sub (w_EXPSUB_diff_value));
  EXP_swap_SIZE_DATA8 EXP_SWAP_UNIT(.i_data_a (i_32_a[30:23]),
       .i_data_b (i_32_b[30:23]), .o_compare (w_EXPSWAP_compare),
       .o_less_data (w_EXPSWAP_min), .o_greater_data (w_EXPSWAP_max));
  LOPD_24bit_SIZE_DATA24_SIZE_LOPD5 LOPD_24BIT_UNIT(.i_data
       (w_MAN_ALU_man[27:4]), .o_one_position
       (w_LOPD_24BIT_one_position), .o_zero_flag
       (w_LOPD_24BIT_zero_flag));
  MAN_ALU_NUM_OP1_SIZE_MAN28 MAN_ALU_UNIT(.i_fpu_op (i_add_sub),
       .i_sign_a (i_32_a[31]), .i_sign_b (i_32_b[31]), .i_man_max
       (w_MAN_PRE_SWAP_BY_MAN_max), .i_man_min
       (w_MAN_PRE_SWAP_BY_MAN_min), .o_man_alu (w_MAN_ALU_man),
       .o_overflow (w_MAN_ALU_overflow));
  COMP_28bit_SIZE_DATA28 MAN_COMP_28BIT_UNIT(.i_data_a ({1'b1,
       w_MAN_SWAP1_max[22:0], 4'b0000}), .i_data_b
       (w_MAN_SHF_RIGHT_min), .o_less (w_MAN_PRE_SWAP_BY_MAN_compara));
  MAN_swap_SIZE_MAN24 MAN_PRE_SWAP_BY_EXPONENT_UNIT(.i_man_a ({1'b1,
       i_32_a[22:0]}), .i_man_b ({1'b1, i_32_b[22:0]}), .i_compare
       (w_EXPSWAP_compare), .o_man_max ({UNCONNECTED1,
       w_MAN_SWAP1_max[22:0]}), .o_man_min ({UNCONNECTED2,
       w_MAN_SWAP1_min[22:0]}));
  MAN_swap_SIZE_MAN28 MAN_PRE_SWAP_BY_MAN_UNIT(.i_man_a ({1'b1,
       w_MAN_SWAP1_max[22:0], 4'b0000}), .i_man_b
       (w_MAN_SHF_RIGHT_min), .i_compare
       (w_MAN_PRE_SWAP_BY_MAN_compara), .o_man_max
       (w_MAN_PRE_SWAP_BY_MAN_max), .o_man_min
       (w_MAN_PRE_SWAP_BY_MAN_min));
  NORMALIZATION_unit_SIZE_LOPD5_SIZE_DATA28
       NORMALIZATION_UNIT(.i_overflow (w_MAN_ALU_overflow),
       .i_zero_flag (w_LOPD_24BIT_zero_flag), .i_one_position
       (w_LOPD_24BIT_one_position), .i_mantissa (w_MAN_ALU_man),
       .o_mantissa (w_NORMALIZATION_man));
  PSC_unit PSC_UNIT(.i_add_sub (i_add_sub), .i_sign_a (i_32_a[31]),
       .i_exp_a (i_32_a[30:23]), .i_man_a ({1'b1, i_32_a[22:0]}),
       .i_sign_b (i_32_b[31]), .i_exp_b (i_32_b[30:23]), .i_man_b
       ({1'b1, i_32_b[22:0]}), .o_sel_exp (PSC_o_sel_exp), .o_sel_man
       (PSC_o_sel_man));
  ROUNDING_unit_SIZE_MAN28_SIZE_MAN_RESULT24 ROUNDING_UNIT(.i_man
       (w_NORMALIZATION_man), .o_man_result (w_ROUNDING_man),
       .o_ov_flow (w_ROUNDING_ov_flow));
  Mux_4_to_1_SIZE_DATA24 SEL_MANTISSA_FOR_RESULT(.i_sel
       (PSC_o_sel_man), .i_data_00 (24'b000000000000000000000000),
       .i_data_01 ({1'b0, w_ROUNDING_man[22:0]}), .i_data_10
       (24'b000000000000000000000000), .i_data_11
       (24'b110000000000000000000000), .o_data ({w_mantissa_result[23],
       o_32_s[22:0]}));
  SHF_right_28bit_SIZE_DATA28_SIZE_SHIFT5
       SHF_RIGHT_28BIT_UNIT(.i_shift_number (w_EXPSUB_diff_value[4:0]),
       .i_data ({1'b1, w_MAN_SWAP1_min[22:0], 4'b0000}), .o_data
       (w_MAN_SHF_RIGHT_min));
  SIGN_unit SIGN_OUT(.i_add_sub (i_add_sub), .i_comp_man (n_4),
       .i_sign_man_a (i_32_a[31]), .i_sign_man_b (i_32_b[31]),
       .o_sign_s (o_32_s[31]));
  INVXLHVT g31(.A (w_MAN_ALU_man[27]), .Y (o_un_flag));
  OR2XLHVT g32(.A (w_EXPSWAP_compare), .B
       (w_MAN_PRE_SWAP_BY_MAN_compara), .Y (n_4));
  OR2XLHVT g33(.A (w_MAN_ALU_overflow), .B (w_ROUNDING_ov_flow), .Y
       (o_ov_flag));
  OR2XLHVT g34(.A (PSC_o_sel_exp), .B (w_EXP_ROUNDING[4]), .Y
       (o_32_s[27]));
  OR2XLHVT g35(.A (PSC_o_sel_exp), .B (w_EXP_ROUNDING[6]), .Y
       (o_32_s[29]));
  OR2XLHVT g36(.A (PSC_o_sel_exp), .B (w_EXP_ROUNDING[7]), .Y
       (o_32_s[30]));
  OR2XLHVT g37(.A (PSC_o_sel_exp), .B (w_EXP_ROUNDING[0]), .Y
       (o_32_s[23]));
  OR2XLHVT g38(.A (PSC_o_sel_exp), .B (w_EXP_ROUNDING[2]), .Y
       (o_32_s[25]));
  OR2XLHVT g39(.A (PSC_o_sel_exp), .B (w_EXP_ROUNDING[5]), .Y
       (o_32_s[28]));
  OR2XLHVT g40(.A (PSC_o_sel_exp), .B (w_EXP_ROUNDING[3]), .Y
       (o_32_s[26]));
  OR2XLHVT g41(.A (PSC_o_sel_exp), .B (w_EXP_ROUNDING[1]), .Y
       (o_32_s[24]));
endmodule

