// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_FPU_unit.h for the primary calling header

#ifndef VERILATED_VTB_FPU_UNIT___024ROOT_H_
#define VERILATED_VTB_FPU_UNIT___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_FPU_unit__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_FPU_unit___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_FPU_unit__DOT__i_clk;
        VL_IN8(COMP_2bit__02Ei_data_a,1,0);
        VL_IN8(COMP_2bit__02Ei_data_b,1,0);
        VL_OUT8(o_less,0,0);
        VL_OUT8(o_equal,0,0);
        VL_IN8(i_data,3,0);
        VL_OUT8(o_pos_one,1,0);
        VL_OUT8(o_zero_flag,0,0);
        VL_IN8(CLA_24bit__02Ei_carry,0,0);
        VL_OUT8(CLA_24bit__02Eo_carry,0,0);
        VL_IN8(CKSA_28bit__02Ei_carry,0,0);
        VL_OUT8(CKSA_28bit__02Eo_carry,0,0);
        CData/*0:0*/ tb_FPU_unit__DOT__i_rst_n;
        CData/*0:0*/ tb_FPU_unit__DOT__i_add_sub;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__w_sign_result;
        CData/*7:0*/ tb_FPU_unit__DOT__DUT__DOT__w_exponent_result;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__w_EXPSWAP_compare;
        CData/*7:0*/ tb_FPU_unit__DOT__DUT__DOT__w_EXPSWAP_max;
        CData/*7:0*/ tb_FPU_unit__DOT__DUT__DOT__w_EXPSWAP_min;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__w_MAN_COMP_28BIT_less;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__w_MAN_ALU_overflow;
        CData/*4:0*/ tb_FPU_unit__DOT__DUT__DOT__w_LOPD_24BIT_one_position;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__w_LOPD_24BIT_zero_flag;
        CData/*7:0*/ tb_FPU_unit__DOT__DUT__DOT__w_EXP_ADJUST_result;
        CData/*1:0*/ tb_FPU_unit__DOT__DUT__DOT__PSC_o_sel_man;
        CData/*4:0*/ tb_FPU_unit__DOT__DUT__DOT____Vcellinp__SHF_RIGHT_28BIT_UNIT__i_shift_number;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT____Vcellinp__SIGN_OUT__i_comp_man;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SWAP_UNIT__DOT__COMP_LESS_UNIT__DOT__w_less_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SWAP_UNIT__DOT__COMP_LESS_UNIT__DOT__w_less_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SWAP_UNIT__DOT__COMP_LESS_UNIT__DOT__u_low__DOT__w_less_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SWAP_UNIT__DOT__COMP_LESS_UNIT__DOT__u_low__DOT__w_equal_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SWAP_UNIT__DOT__COMP_LESS_UNIT__DOT__u_low__DOT__w_less_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SWAP_UNIT__DOT__COMP_LESS_UNIT__DOT__u_low__DOT__w_equal_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SWAP_UNIT__DOT__COMP_LESS_UNIT__DOT__u_high__DOT__w_less_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SWAP_UNIT__DOT__COMP_LESS_UNIT__DOT__u_high__DOT__w_equal_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SWAP_UNIT__DOT__COMP_LESS_UNIT__DOT__u_high__DOT__w_less_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SWAP_UNIT__DOT__COMP_LESS_UNIT__DOT__u_high__DOT__w_equal_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__w_C;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT____Vcellout__CLA_4BIT_UNIT_0__o_g;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT____Vcellout__CLA_4BIT_UNIT_1__o_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__w_less_0_1;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__w_less_0_2;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__w_less_0_3;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__w_less_0_4;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__w_less_0_5;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__w_less_0_6;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__w_equal_0_6;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_0__DOT__w_less_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_0__DOT__w_equal_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_0__DOT__w_less_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_0__DOT__w_equal_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_0__DOT____VdfgTmp_h29946ca5__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_0__DOT____VdfgTmp_hd800da22__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_0__DOT____VdfgTmp_hdbd36c31__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_0__DOT____VdfgTmp_hfd7d5815__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT__w_less_low;
    };
    struct {
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT__w_equal_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT__w_less_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT__w_equal_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT____VdfgTmp_h7cce17c8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT____VdfgTmp_hca3231d2__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT____VdfgTmp_h29946ca5__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT____VdfgTmp_hc195ed0f__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT____VdfgTmp_hd800da22__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT____VdfgTmp_hdbd36c31__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT____VdfgTmp_hfd7d5815__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_1__DOT____VdfgTmp_hccfef1f8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT__w_less_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT__w_equal_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT__w_less_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT__w_equal_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT____VdfgTmp_h7cce17c8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT____VdfgTmp_hca3231d2__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT____VdfgTmp_h29946ca5__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT____VdfgTmp_hc195ed0f__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT____VdfgTmp_hd800da22__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT____VdfgTmp_hdbd36c31__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT____VdfgTmp_hfd7d5815__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_2__DOT____VdfgTmp_hccfef1f8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT__w_less_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT__w_equal_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT__w_less_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT__w_equal_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT____VdfgTmp_h7cce17c8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT____VdfgTmp_hca3231d2__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT____VdfgTmp_h29946ca5__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT____VdfgTmp_hc195ed0f__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT____VdfgTmp_hd800da22__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT____VdfgTmp_hdbd36c31__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT____VdfgTmp_hfd7d5815__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_3__DOT____VdfgTmp_hccfef1f8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT__w_less_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT__w_equal_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT__w_less_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT__w_equal_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT____VdfgTmp_h7cce17c8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT____VdfgTmp_hca3231d2__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT____VdfgTmp_h29946ca5__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT____VdfgTmp_hc195ed0f__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT____VdfgTmp_hd800da22__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT____VdfgTmp_hdbd36c31__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT____VdfgTmp_hfd7d5815__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_4__DOT____VdfgTmp_hccfef1f8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT__w_less_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT__w_equal_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT__w_less_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT__w_equal_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT____VdfgTmp_h7cce17c8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT____VdfgTmp_hca3231d2__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT____VdfgTmp_h29946ca5__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT____VdfgTmp_hc195ed0f__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT____VdfgTmp_hd800da22__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT____VdfgTmp_hdbd36c31__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT____VdfgTmp_hfd7d5815__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_5__DOT____VdfgTmp_hccfef1f8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT__w_less_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT__w_equal_low;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT__w_less_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT__w_equal_high;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT____VdfgTmp_h7cce17c8__0;
    };
    struct {
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT____VdfgTmp_hca3231d2__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT____VdfgTmp_h29946ca5__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT____VdfgTmp_hc195ed0f__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT____VdfgTmp_hd800da22__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT____VdfgTmp_hdbd36c31__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT____VdfgTmp_hfd7d5815__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_COMP_28BIT_UNIT__DOT__u_i_data_6__DOT____VdfgTmp_hccfef1f8__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__w_i_carry;
        CData/*7:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__w_c;
        CData/*6:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__w_p;
        CData/*6:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT____Vcellout__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__sum;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT____Vcellout__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__sum;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT____Vcellout__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__sum;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT____Vcellout__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__sum;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT____Vcellout__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__sum;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT____Vcellout__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__sum;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT____Vcellout__CLA_BLOCK_GEN__BRA__6__KET____DOT__CLA_4BIT_UNIT__sum;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__6__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__6__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__6__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__6__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD16_o_zero_flag;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_16bit_UNIT_MSB__DOT__LOPD_8bit_unit_0__DOT____VdfgTmp_h52be7c25__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_16bit_UNIT_MSB__DOT__LOPD_8bit_unit_0__DOT____VdfgTmp_h0bae4039__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_16bit_UNIT_MSB__DOT__LOPD_8bit_unit_0__DOT____VdfgTmp_hf8322e18__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_16bit_UNIT_MSB__DOT__LOPD_8bit_unit_0__DOT____VdfgTmp_h0bc27682__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_16bit_UNIT_MSB__DOT__LOPD_8bit_unit_1__DOT____VdfgTmp_h52be7c25__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_16bit_UNIT_MSB__DOT__LOPD_8bit_unit_1__DOT____VdfgTmp_h0bae4039__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_16bit_UNIT_MSB__DOT__LOPD_8bit_unit_1__DOT____VdfgTmp_hf8322e18__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_16bit_UNIT_MSB__DOT__LOPD_8bit_unit_1__DOT____VdfgTmp_h0bc27682__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_8bit_UNIT_LSB__DOT____VdfgTmp_h52be7c25__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_8bit_UNIT_LSB__DOT____VdfgTmp_h0bae4039__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_8bit_UNIT_LSB__DOT____VdfgTmp_hf8322e18__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__LOPD_24BIT_UNIT__DOT__LOPD_8bit_UNIT_LSB__DOT____VdfgTmp_h0bc27682__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__w_i_carry;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__w_C;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT____Vcellout__CLA_4BIT_UNIT_0__o_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT____Vcellinp__CLA_4BIT_UNIT_0__b;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT____Vcellout__CLA_4BIT_UNIT_1__o_g;
    };
    struct {
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT____Vcellinp__CLA_4BIT_UNIT_1__b;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT__w_g;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT__w_p;
        CData/*3:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT__w_c;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__ROUNDING_UNIT__DOT__w_round_bit;
        CData/*7:0*/ tb_FPU_unit__DOT__DUT__DOT__EXP_ROUNDING__DOT__w_carry;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__PSC_UNIT__DOT____VdfgTmp_hd789dadf__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__PSC_UNIT__DOT____VdfgTmp_h05bafb70__0;
        CData/*0:0*/ tb_FPU_unit__DOT__DUT__DOT__PSC_UNIT__DOT____VdfgTmp_h450ca397__0;
        CData/*6:0*/ CLA_24bit__DOT__w_c;
        CData/*5:0*/ CLA_24bit__DOT__w_p;
        CData/*5:0*/ CLA_24bit__DOT__w_g;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_g;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_p;
        CData/*3:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_c;
        CData/*0:0*/ CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT____VdfgTmp_h1c6e9cb3__0;
        CData/*6:0*/ CKSA_28bit__DOT__w_carry;
        CData/*6:0*/ CKSA_28bit__DOT__w_carry_0;
        CData/*6:0*/ CKSA_28bit__DOT__w_carry_1;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U0_0__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U0_1__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U1_0__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U1_1__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U2_0__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U2_1__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U3_0__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U3_1__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U4_0__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U4_1__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U5_0__sum;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U5_1__sum;
        CData/*0:0*/ CKSA_28bit__DOT____Vcellout__U6_0__cout;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U6_0__sum;
        CData/*0:0*/ CKSA_28bit__DOT____Vcellout__U6_1__cout;
        CData/*3:0*/ CKSA_28bit__DOT____Vcellout__U6_1__sum;
        CData/*3:0*/ CKSA_28bit__DOT__U0_0__DOT__w_g;
        CData/*3:0*/ CKSA_28bit__DOT__U0_0__DOT__w_p;
        CData/*3:0*/ CKSA_28bit__DOT__U0_0__DOT__w_c;
        CData/*3:0*/ CKSA_28bit__DOT__U0_1__DOT__w_c;
    };
    struct {
        CData/*0:0*/ CKSA_28bit__DOT__U0_1__DOT____VdfgTmp_h8a056683__0;
        CData/*3:0*/ CKSA_28bit__DOT__U1_0__DOT__w_g;
        CData/*3:0*/ CKSA_28bit__DOT__U1_0__DOT__w_p;
        CData/*3:0*/ CKSA_28bit__DOT__U1_0__DOT__w_c;
        CData/*3:0*/ CKSA_28bit__DOT__U1_1__DOT__w_c;
        CData/*0:0*/ CKSA_28bit__DOT__U1_1__DOT____VdfgTmp_h8a056683__0;
        CData/*3:0*/ CKSA_28bit__DOT__U2_0__DOT__w_g;
        CData/*3:0*/ CKSA_28bit__DOT__U2_0__DOT__w_p;
        CData/*3:0*/ CKSA_28bit__DOT__U2_0__DOT__w_c;
        CData/*3:0*/ CKSA_28bit__DOT__U2_1__DOT__w_c;
        CData/*0:0*/ CKSA_28bit__DOT__U2_1__DOT____VdfgTmp_h8a056683__0;
        CData/*3:0*/ CKSA_28bit__DOT__U3_0__DOT__w_g;
        CData/*3:0*/ CKSA_28bit__DOT__U3_0__DOT__w_p;
        CData/*3:0*/ CKSA_28bit__DOT__U3_0__DOT__w_c;
        CData/*3:0*/ CKSA_28bit__DOT__U3_1__DOT__w_c;
        CData/*0:0*/ CKSA_28bit__DOT__U3_1__DOT____VdfgTmp_h8a056683__0;
        CData/*3:0*/ CKSA_28bit__DOT__U4_0__DOT__w_g;
        CData/*3:0*/ CKSA_28bit__DOT__U4_0__DOT__w_p;
        CData/*3:0*/ CKSA_28bit__DOT__U4_0__DOT__w_c;
        CData/*3:0*/ CKSA_28bit__DOT__U4_1__DOT__w_c;
        CData/*0:0*/ CKSA_28bit__DOT__U4_1__DOT____VdfgTmp_h8a056683__0;
        CData/*3:0*/ CKSA_28bit__DOT__U5_0__DOT__w_g;
        CData/*3:0*/ CKSA_28bit__DOT__U5_0__DOT__w_p;
        CData/*3:0*/ CKSA_28bit__DOT__U5_0__DOT__w_c;
        CData/*3:0*/ CKSA_28bit__DOT__U5_1__DOT__w_c;
        CData/*0:0*/ CKSA_28bit__DOT__U5_1__DOT____VdfgTmp_h8a056683__0;
        CData/*3:0*/ CKSA_28bit__DOT__U6_0__DOT__w_g;
        CData/*3:0*/ CKSA_28bit__DOT__U6_0__DOT__w_p;
        CData/*3:0*/ CKSA_28bit__DOT__U6_0__DOT__w_c;
        CData/*3:0*/ CKSA_28bit__DOT__U6_1__DOT__w_c;
        CData/*0:0*/ CKSA_28bit__DOT__U6_1__DOT____VdfgTmp_h8a056683__0;
        CData/*0:0*/ __VdfgTmp_hda0dd4b2__0;
        CData/*0:0*/ __VdfgTmp_hb3ff7a59__0;
        CData/*0:0*/ __VdfgTmp_h7869d370__0;
        CData/*0:0*/ __VdfgTmp_h273692f9__0;
        CData/*0:0*/ __VdfgTmp_h530ef46a__0;
        CData/*0:0*/ __VdfgTmp_hc1e1e567__0;
        CData/*0:0*/ __VdfgTmp_hd23a05eb__0;
        CData/*0:0*/ __VdfgTmp_h572ecf81__0;
        CData/*0:0*/ __VdfgTmp_h50c41b4e__0;
        CData/*0:0*/ __VdfgTmp_h77199685__0;
        CData/*0:0*/ __VdfgTmp_h8285d4cf__0;
        CData/*0:0*/ __VdfgTmp_ha4d0f811__0;
        CData/*0:0*/ __VdfgTmp_hcfc94fdc__0;
        CData/*0:0*/ __VdfgTmp_he03e609b__0;
        CData/*0:0*/ __VdfgTmp_h8509e247__0;
        CData/*0:0*/ __VdfgTmp_hc7f773d5__0;
        CData/*0:0*/ __VdfgTmp_h8f5d8cbf__0;
        CData/*0:0*/ __VdfgTmp_he6032948__0;
        CData/*0:0*/ __VdfgTmp_h7de88dc3__0;
        CData/*0:0*/ __VdfgTmp_h1885aee4__0;
        CData/*0:0*/ __VdfgTmp_h207cfc3a__0;
        CData/*0:0*/ __VdfgTmp_he6ef3697__0;
        CData/*0:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__570__t_i_add_sub;
        CData/*0:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__570__t_o_ov_flow;
        CData/*0:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__570__t_o_un_flow;
        CData/*0:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_i_add_sub;
        CData/*0:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_o_ov_flow;
        CData/*0:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_o_un_flow;
        CData/*0:0*/ __Vfunc_tb_FPU_unit__DOT__cal_rounding_error__1161__s_is_nan;
        CData/*0:0*/ __Vfunc_tb_FPU_unit__DOT__cal_rounding_error__1161__e_is_nan;
        CData/*0:0*/ __Vfunc_tb_FPU_unit__DOT__cal_rounding_error__1161__s_is_inf;
        CData/*0:0*/ __Vfunc_tb_FPU_unit__DOT__cal_rounding_error__1161__e_is_inf;
        CData/*7:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__EXP_ROUNDING__DOT__w_carry__0;
    };
    struct {
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__6__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__0;
        CData/*6:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__w_c__0;
        CData/*6:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__w_carry__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U0_1__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U1_1__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U2_1__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U3_1__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U4_1__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U5_1__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U0_0__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U1_0__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U2_0__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U3_0__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U4_0__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U5_0__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U6_1__DOT__w_c__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U6_0__DOT__w_c__0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*6:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__w_c__1;
        CData/*6:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__w_carry__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U0_1__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U1_1__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U2_1__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U3_1__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U4_1__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U5_1__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U0_0__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U1_0__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U2_0__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U3_0__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U4_0__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U5_0__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U6_1__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U6_0__DOT__w_c__1;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*7:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__EXP_ROUNDING__DOT__w_carry__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__EXP_ADJUST_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__6__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
    };
    struct {
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__1;
        CData/*7:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__ALU_SUB_UNIT__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_1__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__EXP_SUB_UNIT__DOT__CLA_8BIT_UNIT__DOT__CLA_4BIT_UNIT_0__DOT__w_c__1;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__5__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__4__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__3__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__2__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__1__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__CLA_BLOCK_GEN__BRA__0__KET____DOT__CLA_4BIT_UNIT__DOT__w_c__2;
        CData/*6:0*/ __Vtrigprevexpr___TOP__CLA_24bit__DOT__w_c__2;
        CData/*6:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__w_carry__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U0_1__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U1_1__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U2_1__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U3_1__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U4_1__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U5_1__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U0_0__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U1_0__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U2_0__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U3_0__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U4_0__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U5_0__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U6_1__DOT__w_c__2;
        CData/*3:0*/ __Vtrigprevexpr___TOP__CKSA_28bit__DOT__U6_0__DOT__w_c__2;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__i_clk__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*10:0*/ tb_FPU_unit__DOT__w_i_addr;
        VL_IN(CLA_24bit__02Ei_data_a,23,0);
        VL_IN(CLA_24bit__02Ei_data_b,23,0);
        VL_OUT(CLA_24bit__02Eo_sum,23,0);
        VL_IN(CKSA_28bit__02Ei_data_a,27,0);
        VL_IN(CKSA_28bit__02Ei_data_b,27,0);
        VL_OUT(CKSA_28bit__02Eo_sum,27,0);
        IData/*31:0*/ tb_FPU_unit__DOT__i_32_a;
        IData/*31:0*/ tb_FPU_unit__DOT__i_32_b;
        IData/*31:0*/ tb_FPU_unit__DOT__w_o_data_rom_a;
        IData/*31:0*/ tb_FPU_unit__DOT__w_o_data_rom_b;
        IData/*31:0*/ tb_FPU_unit__DOT__test_count;
        IData/*31:0*/ tb_FPU_unit__DOT__test_pass;
        IData/*23:0*/ tb_FPU_unit__DOT__DUT__DOT__w_MAN_SWAP1_max;
        IData/*27:0*/ tb_FPU_unit__DOT__DUT__DOT__w_MAN_PRE_SWAP_BY_MAN_max;
        IData/*27:0*/ tb_FPU_unit__DOT__DUT__DOT__w_MAN_PRE_SWAP_BY_MAN_min;
        IData/*27:0*/ tb_FPU_unit__DOT__DUT__DOT__w_MAN_ALU_man;
        IData/*23:0*/ tb_FPU_unit__DOT__DUT__DOT__w_ROUNDING_man;
        IData/*27:0*/ tb_FPU_unit__DOT__DUT__DOT__MAN_ALU_UNIT__DOT__w_i_man_b;
        IData/*23:0*/ tb_FPU_unit__DOT__DUT__DOT__ROUNDING_UNIT__DOT__w_man_temp;
        IData/*23:0*/ tb_FPU_unit__DOT__DUT__DOT__ROUNDING_UNIT__DOT__INCREASE_ROUNDING__DOT__w_carry;
        IData/*27:0*/ __VdfgTmp_h090a2097__0;
        IData/*31:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__570__t_i_32_a;
        IData/*31:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__570__t_i_32_b;
        IData/*31:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__570__t_o_32_s;
        IData/*31:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_i_32_a;
        IData/*31:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_i_32_b;
        IData/*31:0*/ __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_o_32_s;
        IData/*23:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__ROUNDING_UNIT__DOT__INCREASE_ROUNDING__DOT__w_carry__0;
        IData/*23:0*/ __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__ROUNDING_UNIT__DOT__INCREASE_ROUNDING__DOT__w_carry__1;
    };
    struct {
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<IData/*27:0*/, 6> tb_FPU_unit__DOT__DUT__DOT__SHF_RIGHT_28BIT_UNIT__DOT__stage;
        VlUnpacked<IData/*27:0*/, 6> tb_FPU_unit__DOT__DUT__DOT__NORMALIZATION_UNIT__DOT__SHF_left_28bit_unit__DOT__stage;
        VlUnpacked<IData/*31:0*/, 2048> tb_FPU_unit__DOT__ROM_UNIT_A__DOT__rom;
        VlUnpacked<IData/*31:0*/, 2048> tb_FPU_unit__DOT__ROM_UNIT_B__DOT__rom;
        VlUnpacked<IData/*27:0*/, 6> __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__NORMALIZATION_UNIT__DOT__SHF_left_28bit_unit__DOT__stage__0;
        VlUnpacked<IData/*27:0*/, 6> __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__SHF_RIGHT_28BIT_UNIT__DOT__stage__0;
        VlUnpacked<IData/*27:0*/, 6> __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__NORMALIZATION_UNIT__DOT__SHF_left_28bit_unit__DOT__stage__1;
        VlUnpacked<IData/*27:0*/, 6> __Vtrigprevexpr___TOP__tb_FPU_unit__DOT__DUT__DOT__SHF_RIGHT_28BIT_UNIT__DOT__stage__1;
        VlUnpacked<CData/*0:0*/, 18> __Vm_traceActivity;
    };
    std::string __Vtask_tb_FPU_unit__DOT__Display_result__570__t_type;
    double __Vtask_tb_FPU_unit__DOT__Display_result__570__t_sr_32_a;
    double __Vtask_tb_FPU_unit__DOT__Display_result__570__t_sr_32_b;
    double __Vtask_tb_FPU_unit__DOT__Display_result__570__t_sr_32_s;
    double __Vtask_tb_FPU_unit__DOT__Display_result__570__t_sr_32_e;
    double __Vtask_tb_FPU_unit__DOT__Display_result__570__t_sr_rounding_error;
    double __Vtask_tb_FPU_unit__DOT__Display_result__570__t_error;
    std::string __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_type;
    double __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_sr_32_a;
    double __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_sr_32_b;
    double __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_sr_32_s;
    double __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_sr_32_e;
    double __Vtask_tb_FPU_unit__DOT__Display_result__1153__t_error;
    double __Vfunc_tb_FPU_unit__DOT__cal_rounding_error__1161__f_sr_32_s;
    double __Vfunc_tb_FPU_unit__DOT__cal_rounding_error__1161__f_sr_32_e;
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_hb41ccb8d__0;
    VlTriggerScheduler __VtrigSched_hb41ccc4c__0;
    VlTriggerVec<52> __VstlTriggered;
    VlTriggerVec<26> __VicoTriggered;
    VlTriggerVec<54> __VactTriggered;
    VlTriggerVec<54> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_FPU_unit__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_FPU_unit___024root(Vtb_FPU_unit__Syms* symsp, const char* v__name);
    ~Vtb_FPU_unit___024root();
    VL_UNCOPYABLE(Vtb_FPU_unit___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
