/* Generated by Yosys 0.58+84 (git sha1 f5c9e122d, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module \$paramod$838eca7e11edbbe4133b9d4b805df76569a77db5\SHF_left_28bit (i_shift_number, i_data, o_data);
  input [4:0] i_shift_number;
  wire [4:0] i_shift_number;
  input [27:0] i_data;
  wire [27:0] i_data;
  output [27:0] o_data;
  wire [27:0] o_data;
  wire [27:0] \stage[0] ;
  wire [27:0] \stage[1] ;
  wire [27:0] \stage[2] ;
  wire [27:0] \stage[3] ;
  wire [27:0] \stage[4] ;
  wire [27:0] \stage[5] ;
  assign o_data = i_shift_number[4] ? { \stage[4] [11:0], 16'h0000 } : \stage[4] ;
  assign \stage[4]  = i_shift_number[3] ? { \stage[3] [19:0], 8'h00 } : \stage[3] ;
  assign \stage[3]  = i_shift_number[2] ? { \stage[2] [23:0], 4'h0 } : \stage[2] ;
  assign \stage[2]  = i_shift_number[1] ? { \stage[1] [25:0], 2'h0 } : \stage[1] ;
  assign \stage[1]  = i_shift_number[0] ? { i_data[26:0], 1'h0 } : i_data;
  assign \stage[0]  = i_data;
  assign \stage[5]  = o_data;
endmodule

module \$paramod$838eca7e11edbbe4133b9d4b805df76569a77db5\SHF_right_28bit (i_shift_number, i_data, o_data);
  input [4:0] i_shift_number;
  wire [4:0] i_shift_number;
  input [27:0] i_data;
  wire [27:0] i_data;
  output [27:0] o_data;
  wire [27:0] o_data;
  wire [27:0] \stage[0] ;
  wire [27:0] \stage[1] ;
  wire [27:0] \stage[2] ;
  wire [27:0] \stage[3] ;
  wire [27:0] \stage[4] ;
  wire [27:0] \stage[5] ;
  assign o_data = i_shift_number[4] ? { 16'h0000, \stage[4] [27:16] } : \stage[4] ;
  assign \stage[4]  = i_shift_number[3] ? { 8'h00, \stage[3] [27:8] } : \stage[3] ;
  assign \stage[3]  = i_shift_number[2] ? { 4'h0, \stage[2] [27:4] } : \stage[2] ;
  assign \stage[2]  = i_shift_number[1] ? { 2'h0, \stage[1] [27:2] } : \stage[1] ;
  assign \stage[1]  = i_shift_number[0] ? { 1'h0, i_data[27:1] } : i_data;
  assign \stage[0]  = i_data;
  assign \stage[5]  = o_data;
endmodule

module \$paramod$86e2ecc188db999b02eea494903b0b71b5611749\NORMALIZATION_unit (i_overflow, i_zero_flag, i_one_position, i_mantissa, o_mantissa);
  input i_overflow;
  wire i_overflow;
  input i_zero_flag;
  wire i_zero_flag;
  input [4:0] i_one_position;
  wire [4:0] i_one_position;
  input [27:0] i_mantissa;
  wire [27:0] i_mantissa;
  output [27:0] o_mantissa;
  wire [27:0] o_mantissa;
  wire [27:0] _0_;
  wire [27:0] _1_;
  wire [27:0] w_shift_left;
  assign _0_ = i_mantissa[27] ? { 1'h1, i_mantissa[26:0] } : w_shift_left;
  assign _1_ = i_overflow ? { 1'h1, i_mantissa[27:1] } : _0_;
  assign o_mantissa = i_zero_flag ? 28'h0000000 : _1_;
  \$paramod$838eca7e11edbbe4133b9d4b805df76569a77db5\SHF_left_28bit  SHF_left_28bit_unit (
    .i_data(i_mantissa),
    .i_shift_number(i_one_position),
    .o_data(w_shift_left)
  );
endmodule

module \$paramod$9d66fedbd2a12621ad7dd441d4f641513cea53cc\ROUNDING_unit (i_man, o_man_result, o_ov_flow);
  input [27:0] i_man;
  wire [27:0] i_man;
  output [23:0] o_man_result;
  wire [23:0] o_man_result;
  output o_ov_flow;
  wire o_ov_flow;
  wire _0_;
  wire _1_;
  wire w_guard_bit;
  wire [23:0] w_man_temp;
  wire w_round_bit;
  wire w_rounding_result;
  wire w_sticky_bit;
  assign _0_ = i_man[3] & i_man[2];
  assign _1_ = i_man[2] & w_sticky_bit;
  assign w_sticky_bit = i_man[1] | i_man[0];
  assign w_rounding_result = _0_ | _1_;
  \$paramod\RND_add\SIZE_DATA=s32'00000000000000000000000000011000  INCREASE_ROUNDING (
    .i_carry(w_rounding_result),
    .i_data(i_man[27:4]),
    .o_carry(o_ov_flow),
    .o_data(o_man_result)
  );
  assign w_guard_bit = i_man[3];
  assign w_man_temp = i_man[27:4];
  assign w_round_bit = i_man[2];
endmodule

module \$paramod$c4a789d13c6a51d42abff3e6c08b9ac15000ef29\MAN_ALU (i_fpu_op, i_sign_a, i_sign_b, i_man_max, i_man_min, o_man_alu, o_overflow);
  input [0:0] i_fpu_op;
  wire [0:0] i_fpu_op;
  input i_sign_a;
  wire i_sign_a;
  input i_sign_b;
  wire i_sign_b;
  input [27:0] i_man_max;
  wire [27:0] i_man_max;
  input [27:0] i_man_min;
  wire [27:0] i_man_min;
  output [27:0] o_man_alu;
  wire [27:0] o_man_alu;
  output o_overflow;
  wire o_overflow;
  wire _0_;
  wire _1_;
  wire w_i_carry;
  wire [27:0] w_i_man_b;
  wire [27:0] w_n_man_b;
  wire w_overflow;
  assign _0_ = ~ _1_;
  assign w_n_man_b = ~ i_man_min;
  assign w_i_carry = i_fpu_op ? _0_ : _1_;
  assign w_i_man_b = w_i_carry ? w_n_man_b : i_man_min;
  assign o_overflow = w_i_carry ? 1'h0 : w_overflow;
  assign _1_ = i_sign_a ^ i_sign_b;
  CLA_28bit ALU_SUB_UNIT (
    .i_carry(w_i_carry),
    .i_data_a(i_man_max),
    .i_data_b(w_i_man_b),
    .o_carry(w_overflow),
    .o_sum(o_man_alu)
  );
endmodule

module \$paramod$ddb12a396591830656c1cd6f172018da8b53bbff\LOPD_24bit (i_data, o_one_position, o_zero_flag);
  input [23:0] i_data;
  wire [23:0] i_data;
  output [4:0] o_one_position;
  wire [4:0] o_one_position;
  output o_zero_flag;
  wire o_zero_flag;
  wire [15:0] LOPD16_i_data;
  wire [3:0] LOPD16_o_pos_one;
  wire LOPD16_o_zero_flag;
  wire [7:0] LOPD8_i_data;
  wire [2:0] LOPD8_o_pos_one;
  wire LOPD8_o_zero_flag;
  wire [4:0] w_o_one_position;
  assign o_zero_flag = LOPD16_o_zero_flag & LOPD8_o_zero_flag;
  assign w_o_one_position[3] = LOPD16_o_zero_flag ? 1'h0 : LOPD16_o_pos_one[3];
  assign w_o_one_position[2] = LOPD16_o_zero_flag ? LOPD8_o_pos_one[2] : LOPD16_o_pos_one[2];
  assign w_o_one_position[1] = LOPD16_o_zero_flag ? LOPD8_o_pos_one[1] : LOPD16_o_pos_one[1];
  assign w_o_one_position[0] = LOPD16_o_zero_flag ? LOPD8_o_pos_one[0] : LOPD16_o_pos_one[0];
  assign o_one_position = o_zero_flag ? 5'h1f : { LOPD16_o_zero_flag, w_o_one_position[3:0] };
  LOPD_16bit LOPD_16bit_UNIT_MSB (
    .i_data(i_data[23:8]),
    .o_pos_one(LOPD16_o_pos_one),
    .o_zero_flag(LOPD16_o_zero_flag)
  );
  LOPD_8bit LOPD_8bit_UNIT_LSB (
    .i_data(i_data[7:0]),
    .o_pos_one(LOPD8_o_pos_one),
    .o_zero_flag(LOPD8_o_zero_flag)
  );
  assign LOPD16_i_data = i_data[23:8];
  assign LOPD8_i_data = i_data[7:0];
  assign w_o_one_position[4] = LOPD16_o_zero_flag;
endmodule

module \$paramod$e3033cb942ab349c2c8c9f2494da147b64d93cde\EXP_adjust (i_overflow, i_underflow, i_zero_flag, i_lopd_value, i_exp_value, o_exp_result);
  input i_overflow;
  wire i_overflow;
  input i_underflow;
  wire i_underflow;
  input i_zero_flag;
  wire i_zero_flag;
  input [7:0] i_lopd_value;
  wire [7:0] i_lopd_value;
  input [7:0] i_exp_value;
  wire [7:0] i_exp_value;
  output [7:0] o_exp_result;
  wire [7:0] o_exp_result;
  wire [7:0] _0_;
  wire _1_;
  wire [7:0] _2_;
  wire [7:0] w_data_b;
  wire [7:0] w_exp_result;
  wire w_i_carry;
  assign w_i_carry = ~ _1_;
  assign _0_ = ~ i_lopd_value;
  assign _1_ = i_overflow | i_underflow;
  assign _2_ = i_underflow ? 8'h00 : _0_;
  assign w_data_b = i_overflow ? 8'h01 : _2_;
  assign o_exp_result = i_zero_flag ? 8'h00 : w_exp_result;
  CLA_8bit CLA_8BIT_UNIT (
    .i_carry(w_i_carry),
    .i_data_a(i_exp_value),
    .i_data_b(w_data_b),
    .o_sum(w_exp_result)
  );
endmodule

module \$paramod\COMP_28bit\SIZE_DATA=s32'00000000000000000000000000011100 (i_data_a, i_data_b, o_less);
  input [27:0] i_data_a;
  wire [27:0] i_data_a;
  input [27:0] i_data_b;
  wire [27:0] i_data_b;
  output o_less;
  wire o_less;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire w_equal_0_0;
  wire w_equal_0_1;
  wire w_equal_0_2;
  wire w_equal_0_3;
  wire w_equal_0_4;
  wire w_equal_0_5;
  wire w_equal_0_6;
  wire w_less_0_0;
  wire w_less_0_1;
  wire w_less_0_2;
  wire w_less_0_3;
  wire w_less_0_4;
  wire w_less_0_5;
  wire w_less_0_6;
  assign _00_ = w_equal_0_6 & w_less_0_5;
  assign _02_ = _01_ & w_less_0_4;
  assign _04_ = _03_ & w_less_0_3;
  assign _06_ = _05_ & w_less_0_2;
  assign _05_ = _03_ & w_equal_0_3;
  assign _07_ = _05_ & w_equal_0_2;
  assign _08_ = _07_ & w_less_0_1;
  assign _01_ = w_equal_0_6 & w_equal_0_5;
  assign _03_ = _01_ & w_equal_0_4;
  assign _09_ = _07_ & w_equal_0_1;
  assign _10_ = _09_ & w_less_0_0;
  assign _11_ = w_less_0_6 | _00_;
  assign _12_ = _11_ | _02_;
  assign _13_ = _12_ | _04_;
  assign _14_ = _13_ | _06_;
  assign _15_ = _14_ | _08_;
  assign o_less = _15_ | _10_;
  COMP_4bit u_i_data_0 (
    .i_data_a(i_data_a[3:0]),
    .i_data_b(i_data_b[3:0]),
    .o_equal(w_equal_0_0),
    .o_less(w_less_0_0)
  );
  COMP_4bit u_i_data_1 (
    .i_data_a(i_data_a[7:4]),
    .i_data_b(i_data_b[7:4]),
    .o_equal(w_equal_0_1),
    .o_less(w_less_0_1)
  );
  COMP_4bit u_i_data_2 (
    .i_data_a(i_data_a[11:8]),
    .i_data_b(i_data_b[11:8]),
    .o_equal(w_equal_0_2),
    .o_less(w_less_0_2)
  );
  COMP_4bit u_i_data_3 (
    .i_data_a(i_data_a[15:12]),
    .i_data_b(i_data_b[15:12]),
    .o_equal(w_equal_0_3),
    .o_less(w_less_0_3)
  );
  COMP_4bit u_i_data_4 (
    .i_data_a(i_data_a[19:16]),
    .i_data_b(i_data_b[19:16]),
    .o_equal(w_equal_0_4),
    .o_less(w_less_0_4)
  );
  COMP_4bit u_i_data_5 (
    .i_data_a(i_data_a[23:20]),
    .i_data_b(i_data_b[23:20]),
    .o_equal(w_equal_0_5),
    .o_less(w_less_0_5)
  );
  COMP_4bit u_i_data_6 (
    .i_data_a(i_data_a[27:24]),
    .i_data_b(i_data_b[27:24]),
    .o_equal(w_equal_0_6),
    .o_less(w_less_0_6)
  );
endmodule

module \$paramod\COMP_8bit\SIZE_DATA=s32'00000000000000000000000000001000 (i_data_a, i_data_b, o_less);
  input [7:0] i_data_a;
  wire [7:0] i_data_a;
  input [7:0] i_data_b;
  wire [7:0] i_data_b;
  output o_less;
  wire o_less;
  wire _0_;
  wire w_equal_high;
  wire w_equal_low;
  wire w_less_high;
  wire w_less_low;
  assign _0_ = w_equal_high & w_less_low;
  assign o_less = w_less_high | _0_;
  COMP_4bit u_high (
    .i_data_a(i_data_a[7:4]),
    .i_data_b(i_data_b[7:4]),
    .o_equal(w_equal_high),
    .o_less(w_less_high)
  );
  COMP_4bit u_low (
    .i_data_a(i_data_a[3:0]),
    .i_data_b(i_data_b[3:0]),
    .o_equal(w_equal_low),
    .o_less(w_less_low)
  );
endmodule

module \$paramod\EXP_rounding\SIZE_DATA=s32'00000000000000000000000000001000 (i_carry_rounding, i_exp_result, o_exp_result);
  input i_carry_rounding;
  wire i_carry_rounding;
  input [7:0] i_exp_result;
  wire [7:0] i_exp_result;
  output [7:0] o_exp_result;
  wire [7:0] o_exp_result;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire [7:0] w_carry;
  assign w_carry[1] = i_exp_result[0] & i_carry_rounding;
  assign w_carry[2] = _00_ & i_carry_rounding;
  assign w_carry[3] = _01_ & i_carry_rounding;
  assign w_carry[4] = _02_ & i_carry_rounding;
  assign w_carry[5] = _03_ & i_carry_rounding;
  assign w_carry[6] = _04_ & i_carry_rounding;
  assign w_carry[7] = _05_ & i_carry_rounding;
  assign _00_ = & i_exp_result[1:0];
  assign _01_ = & i_exp_result[2:0];
  assign _02_ = & i_exp_result[3:0];
  assign _03_ = & i_exp_result[4:0];
  assign _04_ = & i_exp_result[5:0];
  assign _05_ = & i_exp_result[6:0];
  assign o_exp_result = i_exp_result ^ { w_carry[7:1], i_carry_rounding };
  assign w_carry[0] = i_carry_rounding;
endmodule

module \$paramod\EXP_sub\SIZE_EXP_SUB=s32'00000000000000000000000000001000 (i_data_a, i_data_b, o_sub);
  input [7:0] i_data_a;
  wire [7:0] i_data_a;
  input [7:0] i_data_b;
  wire [7:0] i_data_b;
  output [7:0] o_sub;
  wire [7:0] o_sub;
  wire [7:0] w_data_b;
  assign w_data_b = ~ i_data_b;
  CLA_8bit CLA_8BIT_UNIT (
    .i_carry(1'h1),
    .i_data_a(i_data_a),
    .i_data_b(w_data_b),
    .o_sum(o_sub)
  );
endmodule

module \$paramod\EXP_swap\SIZE_DATA=s32'00000000000000000000000000001000 (i_data_a, i_data_b, o_compare, o_less_data, o_greater_data);
  input [7:0] i_data_a;
  wire [7:0] i_data_a;
  input [7:0] i_data_b;
  wire [7:0] i_data_b;
  output o_compare;
  wire o_compare;
  output [7:0] o_less_data;
  wire [7:0] o_less_data;
  output [7:0] o_greater_data;
  wire [7:0] o_greater_data;
  assign o_greater_data = o_compare ? i_data_b : i_data_a;
  assign o_less_data = o_compare ? i_data_a : i_data_b;
  \$paramod\COMP_8bit\SIZE_DATA=s32'00000000000000000000000000001000  COMP_LESS_UNIT (
    .i_data_a(i_data_a),
    .i_data_b(i_data_b),
    .o_less(o_compare)
  );
endmodule

module \$paramod\MAN_swap\SIZE_MAN=s32'00000000000000000000000000011000 (i_man_a, i_man_b, i_compare, o_man_max, o_man_min);
  input [23:0] i_man_a;
  wire [23:0] i_man_a;
  input [23:0] i_man_b;
  wire [23:0] i_man_b;
  input i_compare;
  wire i_compare;
  output [23:0] o_man_max;
  wire [23:0] o_man_max;
  output [23:0] o_man_min;
  wire [23:0] o_man_min;
  assign o_man_max = i_compare ? i_man_b : i_man_a;
  assign o_man_min = i_compare ? i_man_a : i_man_b;
endmodule

module \$paramod\MAN_swap\SIZE_MAN=s32'00000000000000000000000000011100 (i_man_a, i_man_b, i_compare, o_man_max, o_man_min);
  input [27:0] i_man_a;
  wire [27:0] i_man_a;
  input [27:0] i_man_b;
  wire [27:0] i_man_b;
  input i_compare;
  wire i_compare;
  output [27:0] o_man_max;
  wire [27:0] o_man_max;
  output [27:0] o_man_min;
  wire [27:0] o_man_min;
  assign o_man_max = i_compare ? i_man_b : i_man_a;
  assign o_man_min = i_compare ? i_man_a : i_man_b;
endmodule

module \$paramod\Mux_4_to_1\SIZE_DATA=s32'00000000000000000000000000011000 (i_sel, i_data_00, i_data_01, i_data_10, i_data_11, o_data);
  input [1:0] i_sel;
  wire [1:0] i_sel;
  input [23:0] i_data_00;
  wire [23:0] i_data_00;
  input [23:0] i_data_01;
  wire [23:0] i_data_01;
  input [23:0] i_data_10;
  wire [23:0] i_data_10;
  input [23:0] i_data_11;
  wire [23:0] i_data_11;
  output [23:0] o_data;
  wire [23:0] o_data;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire [23:0] w_o_data;
  function [23:0] _4_;
    input [23:0] a;
    input [95:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _4_ = b[23:0];
      4'b??1?:
        _4_ = b[47:24];
      4'b?1??:
        _4_ = b[71:48];
      4'b1???:
        _4_ = b[95:72];
      default:
        _4_ = a;
    endcase
  endfunction
  assign o_data = _4_(24'hxxxxxx, { i_data_00, i_data_01, i_data_10, i_data_11 }, { _3_, _2_, _1_, _0_ });
  assign _0_ = i_sel == 2'h3;
  assign _1_ = i_sel == 2'h2;
  assign _2_ = i_sel == 2'h1;
  assign _3_ = ! i_sel;
  assign w_o_data = o_data;
endmodule

module \$paramod\RND_add\SIZE_DATA=s32'00000000000000000000000000011000 (i_data, i_carry, o_data, o_carry);
  input [23:0] i_data;
  wire [23:0] i_data;
  input i_carry;
  wire i_carry;
  output [23:0] o_data;
  wire [23:0] o_data;
  output o_carry;
  wire o_carry;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire [23:0] w_carry;
  assign w_carry[1] = i_data[0] & i_carry;
  assign w_carry[2] = _00_ & i_carry;
  assign w_carry[3] = _01_ & i_carry;
  assign w_carry[4] = _02_ & i_carry;
  assign w_carry[5] = _03_ & i_carry;
  assign w_carry[6] = _04_ & i_carry;
  assign w_carry[7] = _05_ & i_carry;
  assign w_carry[8] = _06_ & i_carry;
  assign w_carry[9] = _07_ & i_carry;
  assign w_carry[10] = _08_ & i_carry;
  assign w_carry[11] = _09_ & i_carry;
  assign w_carry[12] = _10_ & i_carry;
  assign w_carry[13] = _11_ & i_carry;
  assign w_carry[14] = _12_ & i_carry;
  assign w_carry[15] = _13_ & i_carry;
  assign w_carry[16] = _14_ & i_carry;
  assign w_carry[17] = _15_ & i_carry;
  assign w_carry[18] = _16_ & i_carry;
  assign w_carry[19] = _17_ & i_carry;
  assign w_carry[20] = _18_ & i_carry;
  assign w_carry[21] = _19_ & i_carry;
  assign w_carry[22] = _20_ & i_carry;
  assign w_carry[23] = _21_ & i_carry;
  assign o_carry = _22_ & i_carry;
  assign _00_ = & i_data[1:0];
  assign _01_ = & i_data[2:0];
  assign _02_ = & i_data[3:0];
  assign _03_ = & i_data[4:0];
  assign _04_ = & i_data[5:0];
  assign _05_ = & i_data[6:0];
  assign _06_ = & i_data[7:0];
  assign _07_ = & i_data[8:0];
  assign _08_ = & i_data[9:0];
  assign _09_ = & i_data[10:0];
  assign _10_ = & i_data[11:0];
  assign _11_ = & i_data[12:0];
  assign _12_ = & i_data[13:0];
  assign _13_ = & i_data[14:0];
  assign _14_ = & i_data[15:0];
  assign _15_ = & i_data[16:0];
  assign _16_ = & i_data[17:0];
  assign _17_ = & i_data[18:0];
  assign _18_ = & i_data[19:0];
  assign _19_ = & i_data[20:0];
  assign _20_ = & i_data[21:0];
  assign _21_ = & i_data[22:0];
  assign _22_ = & i_data;
  assign o_data = i_data ^ { w_carry[23:1], i_carry };
  assign w_carry[0] = i_carry;
endmodule

module CLA_28bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  wire i_carry;
  input [27:0] i_data_a;
  wire [27:0] i_data_a;
  input [27:0] i_data_b;
  wire [27:0] i_data_b;
  output [27:0] o_sum;
  wire [27:0] o_sum;
  output o_carry;
  wire o_carry;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire [7:0] w_c;
  wire [6:0] w_g;
  wire [6:0] w_p;
  assign _000_ = w_p[0] & i_carry;
  assign _001_ = w_p[1] & w_g[0];
  assign _002_ = w_p[1] & w_p[0];
  assign _003_ = _002_ & i_carry;
  assign _004_ = w_p[2] & w_g[1];
  assign _006_ = _005_ & w_g[0];
  assign _005_ = w_p[2] & w_p[1];
  assign _007_ = _005_ & w_p[0];
  assign _008_ = _007_ & i_carry;
  assign _009_ = w_p[3] & w_g[2];
  assign _011_ = _010_ & w_g[1];
  assign _013_ = _012_ & w_g[0];
  assign _010_ = w_p[3] & w_p[2];
  assign _012_ = _010_ & w_p[1];
  assign _014_ = _012_ & w_p[0];
  assign _015_ = _014_ & i_carry;
  assign _016_ = w_p[4] & w_g[3];
  assign _018_ = _017_ & w_g[2];
  assign _020_ = _019_ & w_g[1];
  assign _022_ = _021_ & w_g[0];
  assign _017_ = w_p[4] & w_p[3];
  assign _019_ = _017_ & w_p[2];
  assign _021_ = _019_ & w_p[1];
  assign _023_ = _021_ & w_p[0];
  assign _024_ = _023_ & i_carry;
  assign _025_ = w_p[5] & w_g[4];
  assign _027_ = _026_ & w_g[3];
  assign _029_ = _028_ & w_g[2];
  assign _031_ = _030_ & w_g[1];
  assign _033_ = _032_ & w_g[0];
  assign _026_ = w_p[5] & w_p[4];
  assign _028_ = _026_ & w_p[3];
  assign _030_ = _028_ & w_p[2];
  assign _032_ = _030_ & w_p[1];
  assign _034_ = _032_ & w_p[0];
  assign _035_ = _034_ & i_carry;
  assign _036_ = w_p[6] & w_g[5];
  assign _038_ = _037_ & w_g[4];
  assign _040_ = _039_ & w_g[3];
  assign _042_ = _041_ & w_g[2];
  assign _041_ = _039_ & w_p[3];
  assign _044_ = _043_ & w_g[1];
  assign _039_ = _037_ & w_p[4];
  assign _043_ = _041_ & w_p[2];
  assign _045_ = _043_ & w_p[1];
  assign _046_ = _045_ & w_g[0];
  assign _037_ = w_p[6] & w_p[5];
  assign _047_ = _045_ & w_p[0];
  assign _048_ = _047_ & i_carry;
  assign w_c[1] = w_g[0] | _000_;
  assign _049_ = w_g[1] | _001_;
  assign w_c[2] = _049_ | _003_;
  assign _050_ = w_g[2] | _004_;
  assign _051_ = _050_ | _006_;
  assign w_c[3] = _051_ | _008_;
  assign _052_ = w_g[3] | _009_;
  assign _053_ = _052_ | _011_;
  assign _054_ = _053_ | _013_;
  assign w_c[4] = _054_ | _015_;
  assign _055_ = w_g[4] | _016_;
  assign _056_ = _055_ | _018_;
  assign _057_ = _056_ | _020_;
  assign _058_ = _057_ | _022_;
  assign w_c[5] = _058_ | _024_;
  assign _059_ = w_g[5] | _025_;
  assign _060_ = _059_ | _027_;
  assign _061_ = _060_ | _029_;
  assign _062_ = _061_ | _031_;
  assign _063_ = _062_ | _033_;
  assign w_c[6] = _063_ | _035_;
  assign _064_ = w_g[6] | _036_;
  assign _065_ = _064_ | _038_;
  assign _066_ = _065_ | _040_;
  assign _067_ = _066_ | _042_;
  assign _068_ = _067_ | _044_;
  assign _069_ = _068_ | _046_;
  assign o_carry = _069_ | _048_;
  CLA_4bit \CLA_BLOCK_GEN[0].CLA_4BIT_UNIT  (
    .a(i_data_a[3:0]),
    .b(i_data_b[3:0]),
    .cin(i_carry),
    .o_g(w_g[0]),
    .o_p(w_p[0]),
    .sum(o_sum[3:0])
  );
  CLA_4bit \CLA_BLOCK_GEN[1].CLA_4BIT_UNIT  (
    .a(i_data_a[7:4]),
    .b(i_data_b[7:4]),
    .cin(w_c[1]),
    .o_g(w_g[1]),
    .o_p(w_p[1]),
    .sum(o_sum[7:4])
  );
  CLA_4bit \CLA_BLOCK_GEN[2].CLA_4BIT_UNIT  (
    .a(i_data_a[11:8]),
    .b(i_data_b[11:8]),
    .cin(w_c[2]),
    .o_g(w_g[2]),
    .o_p(w_p[2]),
    .sum(o_sum[11:8])
  );
  CLA_4bit \CLA_BLOCK_GEN[3].CLA_4BIT_UNIT  (
    .a(i_data_a[15:12]),
    .b(i_data_b[15:12]),
    .cin(w_c[3]),
    .o_g(w_g[3]),
    .o_p(w_p[3]),
    .sum(o_sum[15:12])
  );
  CLA_4bit \CLA_BLOCK_GEN[4].CLA_4BIT_UNIT  (
    .a(i_data_a[19:16]),
    .b(i_data_b[19:16]),
    .cin(w_c[4]),
    .o_g(w_g[4]),
    .o_p(w_p[4]),
    .sum(o_sum[19:16])
  );
  CLA_4bit \CLA_BLOCK_GEN[5].CLA_4BIT_UNIT  (
    .a(i_data_a[23:20]),
    .b(i_data_b[23:20]),
    .cin(w_c[5]),
    .o_g(w_g[5]),
    .o_p(w_p[5]),
    .sum(o_sum[23:20])
  );
  CLA_4bit \CLA_BLOCK_GEN[6].CLA_4BIT_UNIT  (
    .a(i_data_a[27:24]),
    .b(i_data_b[27:24]),
    .cin(w_c[6]),
    .o_g(w_g[6]),
    .o_p(w_p[6]),
    .sum(o_sum[27:24])
  );
  assign { w_c[7], w_c[0] } = { o_carry, i_carry };
endmodule

module CLA_4bit(a, b, cin, sum, o_p, o_g);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input cin;
  wire cin;
  output [3:0] sum;
  wire [3:0] sum;
  output o_p;
  wire o_p;
  output o_g;
  wire o_g;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [3:0] w_c;
  wire [3:0] w_g;
  wire [3:0] w_p;
  assign w_g = a & b;
  assign _00_ = w_p[0] & cin;
  assign _01_ = w_p[1] & w_g[0];
  assign _02_ = w_p[1] & w_p[0];
  assign _03_ = _02_ & cin;
  assign _04_ = w_p[2] & w_g[1];
  assign _06_ = _05_ & w_g[0];
  assign _05_ = w_p[2] & w_p[1];
  assign _07_ = _05_ & w_p[0];
  assign _08_ = _07_ & cin;
  assign _09_ = w_p[3] & w_g[2];
  assign _11_ = _10_ & w_g[1];
  assign _13_ = _12_ & w_g[0];
  assign _10_ = w_p[3] & w_p[2];
  assign _12_ = _10_ & w_p[1];
  assign _14_ = _12_ & w_p[0];
  assign _15_ = _14_ & cin;
  assign w_c[1] = w_g[0] | _00_;
  assign _16_ = w_g[1] | _01_;
  assign w_c[2] = _16_ | _03_;
  assign _17_ = w_g[2] | _04_;
  assign _18_ = _17_ | _06_;
  assign w_c[3] = _18_ | _08_;
  assign _19_ = w_g[3] | _09_;
  assign _20_ = _19_ | _11_;
  assign _21_ = _20_ | _13_;
  assign o_g = _21_ | _15_;
  assign o_p = & w_p;
  assign w_p = a ^ b;
  assign sum = w_p ^ { w_c[3:1], cin };
  assign w_c[0] = cin;
endmodule

module CLA_8bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  wire i_carry;
  input [7:0] i_data_a;
  wire [7:0] i_data_a;
  input [7:0] i_data_b;
  wire [7:0] i_data_b;
  output [7:0] o_sum;
  wire [7:0] o_sum;
  output o_carry;
  wire o_carry;
  wire _0_;
  wire _1_;
  wire w_C;
  wire [1:0] w_G;
  wire [1:0] w_P;
  assign _0_ = w_P[0] & i_carry;
  assign _1_ = w_P[1] & w_C;
  assign w_C = w_G[0] | _0_;
  assign o_carry = w_G[1] | _1_;
  CLA_4bit CLA_4BIT_UNIT_0 (
    .a(i_data_a[3:0]),
    .b(i_data_b[3:0]),
    .cin(i_carry),
    .o_g(w_G[0]),
    .o_p(w_P[0]),
    .sum(o_sum[3:0])
  );
  CLA_4bit CLA_4BIT_UNIT_1 (
    .a(i_data_a[7:4]),
    .b(i_data_b[7:4]),
    .cin(w_C),
    .o_g(w_G[1]),
    .o_p(w_P[1]),
    .sum(o_sum[7:4])
  );
endmodule

module COMP_4bit(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a;
  wire [3:0] i_data_a;
  input [3:0] i_data_b;
  wire [3:0] i_data_b;
  output o_less;
  wire o_less;
  output o_equal;
  wire o_equal;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire [3:0] _061_;
  assign _002_ = _001_ & _046_;
  assign _003_ = _002_ & i_data_b[0];
  assign _001_ = _000_ & _045_;
  assign _004_ = _001_ & i_data_b[1];
  assign _005_ = _000_ & i_data_b[2];
  assign _006_ = _043_ & i_data_b[3];
  assign _000_ = _043_ & _044_;
  assign _007_ = _000_ & _046_;
  assign _008_ = _007_ & i_data_b[1];
  assign _009_ = _008_ & i_data_b[0];
  assign _011_ = _010_ & _046_;
  assign _012_ = _011_ & i_data_b[2];
  assign _013_ = _012_ & i_data_b[0];
  assign _010_ = _043_ & _045_;
  assign _014_ = _010_ & i_data_b[2];
  assign _015_ = _014_ & i_data_b[1];
  assign _016_ = _043_ & _046_;
  assign _017_ = _016_ & i_data_b[2];
  assign _018_ = _017_ & i_data_b[1];
  assign _019_ = _018_ & i_data_b[0];
  assign _021_ = _020_ & _046_;
  assign _022_ = _021_ & i_data_b[3];
  assign _023_ = _022_ & i_data_b[0];
  assign _020_ = _044_ & _045_;
  assign _024_ = _020_ & i_data_b[3];
  assign _025_ = _024_ & i_data_b[1];
  assign _026_ = _044_ & i_data_b[3];
  assign _027_ = _026_ & i_data_b[2];
  assign _028_ = _044_ & _046_;
  assign _029_ = _028_ & i_data_b[3];
  assign _030_ = _029_ & i_data_b[1];
  assign _031_ = _030_ & i_data_b[0];
  assign _032_ = _045_ & _046_;
  assign _033_ = _032_ & i_data_b[3];
  assign _034_ = _033_ & i_data_b[2];
  assign _035_ = _034_ & i_data_b[0];
  assign _036_ = _045_ & i_data_b[3];
  assign _037_ = _036_ & i_data_b[2];
  assign _038_ = _037_ & i_data_b[1];
  assign _039_ = _046_ & i_data_b[3];
  assign _040_ = _039_ & i_data_b[2];
  assign _041_ = _040_ & i_data_b[1];
  assign _042_ = _041_ & i_data_b[0];
  assign o_equal = ! _060_;
  assign _043_ = ~ i_data_a[3];
  assign _044_ = ~ i_data_a[2];
  assign _045_ = ~ i_data_a[1];
  assign _046_ = ~ i_data_a[0];
  assign _047_ = _003_ | _004_;
  assign _048_ = _047_ | _005_;
  assign _049_ = _048_ | _006_;
  assign _050_ = _049_ | _009_;
  assign _051_ = _050_ | _013_;
  assign _052_ = _051_ | _015_;
  assign _053_ = _052_ | _019_;
  assign _054_ = _053_ | _023_;
  assign _055_ = _054_ | _025_;
  assign _056_ = _055_ | _027_;
  assign _057_ = _056_ | _031_;
  assign _058_ = _057_ | _035_;
  assign _059_ = _058_ | _038_;
  assign o_less = _059_ | _042_;
  assign _060_ = | _061_;
  assign _061_ = i_data_a ^ i_data_b;
endmodule

module FPU_unit(i_add_sub, i_32_a, i_32_b, o_32_s, o_ov_flag, o_un_flag);
  input [0:0] i_add_sub;
  wire [0:0] i_add_sub;
  input [31:0] i_32_a;
  wire [31:0] i_32_a;
  input [31:0] i_32_b;
  wire [31:0] i_32_b;
  output [31:0] o_32_s;
  wire [31:0] o_32_s;
  output o_ov_flag;
  wire o_ov_flag;
  output o_un_flag;
  wire o_un_flag;
  wire _0_;
  wire PSC_o_sel_exp;
  wire [1:0] PSC_o_sel_man;
  wire [7:0] w_EXPSUB_diff_value;
  wire w_EXPSWAP_compare;
  wire [7:0] w_EXPSWAP_max;
  wire [7:0] w_EXPSWAP_min;
  wire [7:0] w_EXP_ADJUST_result;
  wire [7:0] w_EXP_ROUNDING;
  wire [4:0] w_LOPD_24BIT_one_position;
  wire w_LOPD_24BIT_zero_flag;
  wire [27:0] w_MAN_ALU_man;
  wire w_MAN_ALU_overflow;
  wire w_MAN_COMP_28BIT_less;
  wire w_MAN_PRE_SWAP_BY_MAN_compara;
  wire [27:0] w_MAN_PRE_SWAP_BY_MAN_max;
  wire [27:0] w_MAN_PRE_SWAP_BY_MAN_min;
  wire [27:0] w_MAN_SHF_RIGHT_max;
  wire [27:0] w_MAN_SHF_RIGHT_min;
  wire [23:0] w_MAN_SWAP1_max;
  wire [23:0] w_MAN_SWAP1_min;
  wire [27:0] w_NORMALIZATION_man;
  wire [23:0] w_ROUNDING_man;
  wire w_ROUNDING_ov_flow;
  wire [7:0] w_exponent_a;
  wire [7:0] w_exponent_b;
  wire [7:0] w_exponent_result;
  wire [23:0] w_mantissa_a;
  wire [23:0] w_mantissa_b;
  wire [23:0] w_mantissa_result;
  wire w_sign_a;
  wire w_sign_b;
  wire w_sign_result;
  assign o_un_flag = ~ w_MAN_ALU_man[27];
  assign _0_ = w_MAN_COMP_28BIT_less | w_EXPSWAP_compare;
  assign o_ov_flag = w_MAN_ALU_overflow | w_ROUNDING_ov_flow;
  assign w_exponent_result = PSC_o_sel_exp ? 8'hff : w_EXP_ROUNDING;
  \$paramod$e3033cb942ab349c2c8c9f2494da147b64d93cde\EXP_adjust  EXP_ADJUST_UNIT (
    .i_exp_value(w_EXPSWAP_max),
    .i_lopd_value({ 3'h0, w_LOPD_24BIT_one_position }),
    .i_overflow(w_MAN_ALU_overflow),
    .i_underflow(w_MAN_ALU_man[27]),
    .i_zero_flag(w_LOPD_24BIT_zero_flag),
    .o_exp_result(w_EXP_ADJUST_result)
  );
  \$paramod\EXP_rounding\SIZE_DATA=s32'00000000000000000000000000001000  EXP_ROUNDING (
    .i_carry_rounding(w_ROUNDING_ov_flow),
    .i_exp_result(w_EXP_ADJUST_result),
    .o_exp_result(w_EXP_ROUNDING)
  );
  \$paramod\EXP_sub\SIZE_EXP_SUB=s32'00000000000000000000000000001000  EXP_SUB_UNIT (
    .i_data_a(w_EXPSWAP_max),
    .i_data_b(w_EXPSWAP_min),
    .o_sub(w_EXPSUB_diff_value)
  );
  \$paramod\EXP_swap\SIZE_DATA=s32'00000000000000000000000000001000  EXP_SWAP_UNIT (
    .i_data_a(i_32_a[30:23]),
    .i_data_b(i_32_b[30:23]),
    .o_compare(w_EXPSWAP_compare),
    .o_greater_data(w_EXPSWAP_max),
    .o_less_data(w_EXPSWAP_min)
  );
  \$paramod$ddb12a396591830656c1cd6f172018da8b53bbff\LOPD_24bit  LOPD_24BIT_UNIT (
    .i_data(w_MAN_ALU_man[27:4]),
    .o_one_position(w_LOPD_24BIT_one_position),
    .o_zero_flag(w_LOPD_24BIT_zero_flag)
  );
  \$paramod$c4a789d13c6a51d42abff3e6c08b9ac15000ef29\MAN_ALU  MAN_ALU_UNIT (
    .i_fpu_op(i_add_sub),
    .i_man_max(w_MAN_PRE_SWAP_BY_MAN_max),
    .i_man_min(w_MAN_PRE_SWAP_BY_MAN_min),
    .i_sign_a(i_32_a[31]),
    .i_sign_b(i_32_b[31]),
    .o_man_alu(w_MAN_ALU_man),
    .o_overflow(w_MAN_ALU_overflow)
  );
  \$paramod\COMP_28bit\SIZE_DATA=s32'00000000000000000000000000011100  MAN_COMP_28BIT_UNIT (
    .i_data_a({ w_MAN_SWAP1_max, 4'h0 }),
    .i_data_b(w_MAN_SHF_RIGHT_min),
    .o_less(w_MAN_COMP_28BIT_less)
  );
  \$paramod\MAN_swap\SIZE_MAN=s32'00000000000000000000000000011000  MAN_PRE_SWAP_BY_EXPONENT_UNIT (
    .i_compare(w_EXPSWAP_compare),
    .i_man_a({ 1'h1, i_32_a[22:0] }),
    .i_man_b({ 1'h1, i_32_b[22:0] }),
    .o_man_max(w_MAN_SWAP1_max),
    .o_man_min(w_MAN_SWAP1_min)
  );
  \$paramod\MAN_swap\SIZE_MAN=s32'00000000000000000000000000011100  MAN_PRE_SWAP_BY_MAN_UNIT (
    .i_compare(w_MAN_COMP_28BIT_less),
    .i_man_a({ w_MAN_SWAP1_max, 4'h0 }),
    .i_man_b(w_MAN_SHF_RIGHT_min),
    .o_man_max(w_MAN_PRE_SWAP_BY_MAN_max),
    .o_man_min(w_MAN_PRE_SWAP_BY_MAN_min)
  );
  \$paramod$86e2ecc188db999b02eea494903b0b71b5611749\NORMALIZATION_unit  NORMALIZATION_UNIT (
    .i_mantissa(w_MAN_ALU_man),
    .i_one_position(w_LOPD_24BIT_one_position),
    .i_overflow(w_MAN_ALU_overflow),
    .i_zero_flag(w_LOPD_24BIT_zero_flag),
    .o_mantissa(w_NORMALIZATION_man)
  );
  PSC_unit PSC_UNIT (
    .i_add_sub(i_add_sub),
    .i_exp_a(i_32_a[30:23]),
    .i_exp_b(i_32_b[30:23]),
    .i_man_a({ 1'h1, i_32_a[22:0] }),
    .i_man_b({ 1'h1, i_32_b[22:0] }),
    .i_sign_a(i_32_a[31]),
    .i_sign_b(i_32_b[31]),
    .o_sel_exp(PSC_o_sel_exp),
    .o_sel_man(PSC_o_sel_man)
  );
  \$paramod$9d66fedbd2a12621ad7dd441d4f641513cea53cc\ROUNDING_unit  ROUNDING_UNIT (
    .i_man(w_NORMALIZATION_man),
    .o_man_result(w_ROUNDING_man),
    .o_ov_flow(w_ROUNDING_ov_flow)
  );
  \$paramod\Mux_4_to_1\SIZE_DATA=s32'00000000000000000000000000011000  SEL_MANTISSA_FOR_RESULT (
    .i_data_00(w_ROUNDING_man),
    .i_data_01(24'h000000),
    .i_data_10(24'h000001),
    .i_data_11(w_ROUNDING_man),
    .i_sel(PSC_o_sel_man),
    .o_data(w_mantissa_result)
  );
  \$paramod$838eca7e11edbbe4133b9d4b805df76569a77db5\SHF_right_28bit  SHF_RIGHT_28BIT_UNIT (
    .i_data({ w_MAN_SWAP1_min, 4'h0 }),
    .i_shift_number(w_EXPSUB_diff_value[4:0]),
    .o_data(w_MAN_SHF_RIGHT_min)
  );
  SIGN_unit SIGN_OUT (
    .i_add_sub(i_add_sub),
    .i_comp_man(_0_),
    .i_sign_man_a(i_32_a[31]),
    .i_sign_man_b(i_32_b[31]),
    .o_sign_s(w_sign_result)
  );
  assign o_32_s = { w_sign_result, w_exponent_result, w_mantissa_result[22:0] };
  assign w_MAN_PRE_SWAP_BY_MAN_compara = w_MAN_COMP_28BIT_less;
  assign w_MAN_SHF_RIGHT_max = { w_MAN_SWAP1_max, 4'h0 };
  assign w_exponent_a = i_32_a[30:23];
  assign w_exponent_b = i_32_b[30:23];
  assign w_mantissa_a = { 1'h1, i_32_a[22:0] };
  assign w_mantissa_b = { 1'h1, i_32_b[22:0] };
  assign w_sign_a = i_32_a[31];
  assign w_sign_b = i_32_b[31];
endmodule

module LOPD_16bit(i_data, o_pos_one, o_zero_flag);
  input [15:0] i_data;
  wire [15:0] i_data;
  output [3:0] o_pos_one;
  wire [3:0] o_pos_one;
  output o_zero_flag;
  wire o_zero_flag;
  wire [3:0] w_o_pos_one;
  wire [2:0] w_pos_one_0;
  wire [2:0] w_pos_one_1;
  wire w_zero_flag_0;
  wire w_zero_flag_1;
  assign o_zero_flag = w_zero_flag_0 & w_zero_flag_1;
  assign o_pos_one[2] = w_zero_flag_1 ? w_pos_one_0[2] : w_pos_one_1[2];
  assign o_pos_one[1] = w_zero_flag_1 ? w_pos_one_0[1] : w_pos_one_1[1];
  assign o_pos_one[0] = w_zero_flag_1 ? w_pos_one_0[0] : w_pos_one_1[0];
  LOPD_8bit LOPD_8bit_unit_0 (
    .i_data(i_data[7:0]),
    .o_pos_one(w_pos_one_0),
    .o_zero_flag(w_zero_flag_0)
  );
  LOPD_8bit LOPD_8bit_unit_1 (
    .i_data(i_data[15:8]),
    .o_pos_one(w_pos_one_1),
    .o_zero_flag(w_zero_flag_1)
  );
  assign o_pos_one[3] = w_zero_flag_1;
  assign w_o_pos_one = { w_zero_flag_1, o_pos_one[2:0] };
endmodule

module LOPD_8bit(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  wire [7:0] i_data;
  output [2:0] o_pos_one;
  wire [2:0] o_pos_one;
  output o_zero_flag;
  wire o_zero_flag;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire [2:0] w_o_pos_one;
  assign _02_ = _01_ & _23_;
  assign _03_ = _02_ & i_data[0];
  assign _01_ = _00_ & _22_;
  assign _04_ = _01_ & i_data[2];
  assign _00_ = _20_ & _21_;
  assign _05_ = _00_ & i_data[4];
  assign _06_ = _20_ & i_data[6];
  assign _10_ = _09_ & i_data[0];
  assign _08_ = _07_ & _22_;
  assign _09_ = _08_ & _25_;
  assign _11_ = _09_ & i_data[1];
  assign _12_ = _07_ & i_data[4];
  assign _13_ = _07_ & i_data[5];
  assign _16_ = _15_ & i_data[0];
  assign _07_ = _20_ & _24_;
  assign _17_ = _15_ & i_data[1];
  assign _15_ = _14_ & _26_;
  assign _18_ = _15_ & i_data[2];
  assign _14_ = _07_ & _21_;
  assign _19_ = _15_ & i_data[3];
  assign _23_ = ~ i_data[1];
  assign _22_ = ~ i_data[3];
  assign _25_ = ~ i_data[2];
  assign _20_ = ~ i_data[7];
  assign _24_ = ~ i_data[6];
  assign _21_ = ~ i_data[5];
  assign _26_ = ~ i_data[4];
  assign o_zero_flag = ~ _39_;
  assign _27_ = _03_ | _04_;
  assign _28_ = _27_ | _05_;
  assign o_pos_one[0] = _28_ | _06_;
  assign _29_ = _10_ | _11_;
  assign _30_ = _29_ | _12_;
  assign o_pos_one[1] = _30_ | _13_;
  assign _31_ = _16_ | _17_;
  assign _32_ = _31_ | _18_;
  assign o_pos_one[2] = _32_ | _19_;
  assign _33_ = i_data[7] | i_data[6];
  assign _34_ = _33_ | i_data[5];
  assign _35_ = _34_ | i_data[4];
  assign _36_ = _35_ | i_data[3];
  assign _37_ = _36_ | i_data[2];
  assign _38_ = _37_ | i_data[1];
  assign _39_ = _38_ | i_data[0];
  assign w_o_pos_one = o_pos_one;
endmodule

module PSC_unit(i_add_sub, i_sign_a, i_exp_a, i_man_a, i_sign_b, i_exp_b, i_man_b, o_sel_exp, o_sel_man);
  input i_add_sub;
  wire i_add_sub;
  input i_sign_a;
  wire i_sign_a;
  input [7:0] i_exp_a;
  wire [7:0] i_exp_a;
  input [23:0] i_man_a;
  wire [23:0] i_man_a;
  input i_sign_b;
  wire i_sign_b;
  input [7:0] i_exp_b;
  wire [7:0] i_exp_b;
  input [23:0] i_man_b;
  wire [23:0] i_man_b;
  output o_sel_exp;
  wire o_sel_exp;
  output [1:0] o_sel_man;
  wire [1:0] o_sel_man;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire w_E_one_A;
  wire w_E_one_B;
  wire w_M_zero_A;
  wire w_M_zero_B;
  assign _004_ = w_E_one_A & w_M_zero_A;
  assign _005_ = _004_ & w_E_one_B;
  assign _006_ = _005_ & w_M_zero_B;
  assign _000_ = _042_ & w_E_one_B;
  assign _001_ = _000_ & _043_;
  assign _007_ = _003_ & _042_;
  assign _010_ = _009_ & _045_;
  assign _011_ = _010_ & _043_;
  assign _009_ = _008_ & w_E_one_A;
  assign _012_ = _009_ & w_E_one_B;
  assign _013_ = _012_ & w_M_zero_B;
  assign _003_ = _002_ & _045_;
  assign _014_ = _003_ & w_E_one_B;
  assign _002_ = _044_ & w_E_one_A;
  assign _015_ = _002_ & _042_;
  assign _016_ = _015_ & w_E_one_B;
  assign _018_ = _017_ & w_E_one_A;
  assign _019_ = _018_ & w_M_zero_A;
  assign _020_ = _019_ & i_sign_b;
  assign _021_ = _020_ & w_E_one_B;
  assign _022_ = _021_ & w_M_zero_B;
  assign _023_ = _019_ & _042_;
  assign _024_ = _023_ & w_E_one_B;
  assign _025_ = _024_ & w_M_zero_B;
  assign _008_ = _046_ & _044_;
  assign _026_ = _009_ & w_M_zero_A;
  assign _027_ = _026_ & _042_;
  assign _028_ = _027_ & w_E_one_B;
  assign _029_ = _028_ & w_M_zero_B;
  assign _030_ = _046_ & i_sign_a;
  assign _031_ = _030_ & w_E_one_A;
  assign _032_ = _031_ & w_M_zero_A;
  assign _033_ = _032_ & i_sign_b;
  assign _034_ = _033_ & w_E_one_B;
  assign _035_ = _034_ & w_M_zero_B;
  assign _036_ = i_add_sub & _044_;
  assign _037_ = _036_ & w_E_one_A;
  assign _038_ = _037_ & w_M_zero_A;
  assign _039_ = _038_ & i_sign_b;
  assign _040_ = _039_ & w_E_one_B;
  assign _041_ = _040_ & w_M_zero_B;
  assign _017_ = i_add_sub & i_sign_a;
  assign w_M_zero_A = ! _045_;
  assign w_M_zero_B = ! _043_;
  assign _042_ = ~ i_sign_b;
  assign _046_ = ~ i_add_sub;
  assign _044_ = ~ i_sign_a;
  assign _047_ = _001_ | _003_;
  assign o_sel_exp = _047_ | _006_;
  assign _048_ = _001_ | _007_;
  assign _049_ = _048_ | _011_;
  assign _050_ = _049_ | _013_;
  assign _051_ = _050_ | _014_;
  assign _052_ = _051_ | _016_;
  assign o_sel_man[1] = _052_ | _022_;
  assign o_sel_man[0] = _054_ | _025_;
  assign _053_ = _029_ | _035_;
  assign _054_ = _053_ | _041_;
  assign w_E_one_A = & i_exp_a;
  assign w_E_one_B = & i_exp_b;
  assign _045_ = | i_man_a[22:0];
  assign _043_ = | i_man_b[22:0];
endmodule

module SIGN_unit(i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b, o_sign_s);
  input i_add_sub;
  wire i_add_sub;
  input i_comp_man;
  wire i_comp_man;
  input i_sign_man_a;
  wire i_sign_man_a;
  input i_sign_man_b;
  wire i_sign_man_b;
  output o_sign_s;
  wire o_sign_s;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  assign _00_ = _05_ & i_sign_man_b;
  assign _01_ = _00_ & i_comp_man;
  assign _02_ = i_add_sub & _06_;
  assign _03_ = _02_ & i_comp_man;
  assign _04_ = i_sign_man_a & _07_;
  assign _05_ = ~ i_add_sub;
  assign _06_ = ~ i_sign_man_b;
  assign _07_ = ~ i_comp_man;
  assign _08_ = _01_ | _03_;
  assign o_sign_s = _08_ | _04_;
endmodule
