
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 22 2025 13:22:33 +07 (Nov 22 2025 06:22:33 UTC)

// Verification Directory fv/FPU_unit 

module xor_op(A, B, Z);
  input [3:0] A, B;
  output [3:0] Z;
  wire [3:0] A, B;
  wire [3:0] Z;
  xor g1 (Z[0], A[0], B[0]);
  xor g2 (Z[1], A[1], B[1]);
  xor g3 (Z[2], A[2], B[2]);
  xor g4 (Z[3], A[3], B[3]);
endmodule

module COMP_4bit(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_3, n_4, n_6, n_7, n_9, n_10, n_11, n_16;
  wire n_17, n_21, n_24, n_29, n_30, n_34, n_36, n_38;
  wire n_43, n_44, n_48, n_50, n_52, n_53, n_55, n_60;
  wire n_65, n_69, n_74, n_75, n_76, n_77, n_78, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  xor_op g68(.A (i_data_a), .B (i_data_b), .Z ({n_78, n_77, n_76,
       n_75}));
  not g1 (n_3, i_data_a[3]);
  not g2 (n_4, i_data_a[2]);
  and g3 (n_6, n_3, n_4);
  not g4 (n_7, i_data_a[1]);
  and g5 (n_9, n_6, n_7);
  not g6 (n_10, i_data_a[0]);
  and g7 (n_11, n_9, n_10);
  and g8 (n_16, n_11, i_data_b[0]);
  and g11 (n_17, n_9, i_data_b[1]);
  and g14 (n_21, n_6, i_data_b[2]);
  and g16 (n_24, n_3, i_data_b[3]);
  and g23 (n_30, n_3, n_7);
  and g29 (n_36, n_30, i_data_b[2]);
  and g30 (n_38, n_36, i_data_b[1]);
  and g37 (n_44, n_4, n_7);
  and g43 (n_50, n_44, i_data_b[3]);
  and g44 (n_52, n_50, i_data_b[1]);
  and g46 (n_53, n_4, i_data_b[3]);
  and g47 (n_55, n_53, i_data_b[2]);
  nor g70 (o_equal, n_78, n_77, n_76, n_75);
  or g71 (n_81, n_16, n_17, n_21, n_24);
  or g72 (n_82, n_29, n_34, n_38, n_43);
  or g73 (n_83, n_48, n_52, n_55, n_60);
  or g74 (n_84, n_65, n_69, n_74);
  or g75 (o_less, n_81, n_82, n_83, n_84);
  and g76 (n_29, n_6, n_10, i_data_b[1], i_data_b[0]);
  and g77 (n_34, n_30, n_10, i_data_b[2], i_data_b[0]);
  and g78 (n_85, n_3, n_10);
  and g79 (n_43, i_data_b[2], i_data_b[1], i_data_b[0], n_85);
  and g80 (n_48, n_44, n_10, i_data_b[3], i_data_b[0]);
  and g81 (n_86, n_4, n_10);
  and g82 (n_60, i_data_b[3], i_data_b[1], i_data_b[0], n_86);
  and g83 (n_87, n_7, n_10);
  and g84 (n_65, i_data_b[3], i_data_b[2], i_data_b[0], n_87);
  and g85 (n_69, n_7, i_data_b[3], i_data_b[2], i_data_b[1]);
  and g86 (n_88, n_10, i_data_b[3]);
  and g87 (n_74, i_data_b[2], i_data_b[1], i_data_b[0], n_88);
endmodule

module COMP_8bit_SIZE_DATA8(i_data_a, i_data_b, o_less);
  input [7:0] i_data_a, i_data_b;
  output o_less;
  wire [7:0] i_data_a, i_data_b;
  wire o_less;
  wire n_17, w_equal_high, w_equal_low, w_less_high, w_less_low;
  COMP_4bit u_low(.i_data_a (i_data_a[3:0]), .i_data_b (i_data_b[3:0]),
       .o_less (w_less_low), .o_equal (w_equal_low));
  COMP_4bit u_high(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_high), .o_equal (w_equal_high));
  and g1 (n_17, w_equal_high, w_less_low);
  or g2 (o_less, w_less_high, n_17);
endmodule

module bmux(ctl, in_0, in_1, z);
  input ctl;
  input [7:0] in_0, in_1;
  output [7:0] z;
  wire ctl;
  wire [7:0] in_0, in_1;
  wire [7:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module EXP_swap_SIZE_DATA8(i_data_a, i_data_b, o_compare, o_less_data,
     o_greater_data);
  input [7:0] i_data_a, i_data_b;
  output o_compare;
  output [7:0] o_less_data, o_greater_data;
  wire [7:0] i_data_a, i_data_b;
  wire o_compare;
  wire [7:0] o_less_data, o_greater_data;
  COMP_8bit_SIZE_DATA8 COMP_LESS_UNIT(.i_data_a (i_data_a), .i_data_b
       (i_data_b), .o_less (o_compare));
  bmux mux_21_24(.ctl (o_compare), .in_0 (i_data_a), .in_1 (i_data_b),
       .z (o_greater_data));
  bmux mux_22_24(.ctl (o_compare), .in_0 (i_data_b), .in_1 (i_data_a),
       .z (o_less_data));
endmodule

module and_op(A, B, Z);
  input [3:0] A, B;
  output [3:0] Z;
  wire [3:0] A, B;
  wire [3:0] Z;
  and g1 (Z[0], A[0], B[0]);
  and g2 (Z[1], A[1], B[1]);
  and g3 (Z[2], A[2], B[2]);
  and g4 (Z[3], A[3], B[3]);
endmodule

module xor_op_2(A, B, Z);
  input [3:0] A, B;
  output [3:0] Z;
  wire [3:0] A, B;
  wire [3:0] Z;
  xor g1 (Z[0], A[0], B[0]);
  xor g2 (Z[1], A[1], B[1]);
  xor g3 (Z[2], A[2], B[2]);
  xor g4 (Z[3], A[3], B[3]);
endmodule

module xor_op_3(A, B, Z);
  input [3:0] A, B;
  output [3:0] Z;
  wire [3:0] A, B;
  wire [3:0] Z;
  xor g1 (Z[0], A[0], B[0]);
  xor g2 (Z[1], A[1], B[1]);
  xor g3 (Z[2], A[2], B[2]);
  xor g4 (Z[3], A[3], B[3]);
endmodule

module and_op_4(A, Z);
  input [3:0] A;
  output Z;
  wire [3:0] A;
  wire Z;
  wire n_5;
  nand g1 (n_5, A[3], A[2], A[1], A[0]);
  not g2 (Z, n_5);
endmodule

module CLA_4bit(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire [3:0] w_g;
  wire [3:0] w_p;
  wire [3:0] w_c;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_18;
  wire n_20, n_22, n_23, n_24, n_26, n_28, n_30, n_33;
  wire n_35, n_42;
  and_op g1(.A (a), .B (b), .Z (w_g));
  xor_op_2 g2(.A (a), .B (b), .Z (w_p));
  xor_op_3 g19(.A (w_p), .B ({w_c[3:1], cin}), .Z (sum));
  and_op_4 g20(.A (w_p), .Z (o_p));
  and g3 (n_10, w_p[0], cin);
  or g4 (w_c[1], w_g[0], n_10);
  and g5 (n_11, w_p[1], w_g[0]);
  or g6 (n_13, w_g[1], n_11);
  and g7 (n_12, w_p[1], w_p[0]);
  and g8 (n_14, n_12, cin);
  or g9 (w_c[2], n_13, n_14);
  and g10 (n_15, w_p[2], w_g[1]);
  and g12 (n_16, w_p[2], w_p[1]);
  and g13 (n_18, n_16, w_g[0]);
  and g16 (n_20, n_16, w_p[0]);
  and g17 (n_22, n_20, cin);
  and g21 (n_23, w_p[3], w_g[2]);
  and g23 (n_24, w_p[3], w_p[2]);
  and g24 (n_26, n_24, w_g[1]);
  and g27 (n_28, n_24, w_p[1]);
  and g28 (n_30, n_28, w_g[0]);
  and g32 (n_33, n_28, w_p[0]);
  and g33 (n_35, n_33, cin);
  or g35 (w_c[3], w_g[2], n_15, n_18, n_22);
  or g36 (n_42, w_g[3], n_23);
  or g37 (o_g, n_26, n_30, n_35, n_42);
endmodule

module CLA_8bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire [1:0] w_P;
  wire [1:0] w_G;
  wire n_20, n_25, w_C;
  CLA_4bit CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]), .cin
       (i_carry), .sum (o_sum[3:0]), .o_p (w_P[0]), .o_g (w_G[0]));
  CLA_4bit CLA_4BIT_UNIT_1(.a (i_data_a[7:4]), .b (i_data_b[7:4]), .cin
       (w_C), .sum (o_sum[7:4]), .o_p (w_P[1]), .o_g (w_G[1]));
  and g1 (n_20, w_P[0], i_carry);
  or g2 (w_C, w_G[0], n_20);
  and g5 (n_25, w_P[1], w_C);
  or g6 (o_carry, w_G[1], n_25);
endmodule

module not_op(A, Z);
  input [7:0] A;
  output [7:0] Z;
  wire [7:0] A;
  wire [7:0] Z;
  not g1 (Z[7], A[7]);
  not g2 (Z[6], A[6]);
  not g3 (Z[5], A[5]);
  not g4 (Z[4], A[4]);
  not g5 (Z[3], A[3]);
  not g6 (Z[2], A[2]);
  not g7 (Z[1], A[1]);
  not g8 (Z[0], A[0]);
endmodule

module EXP_sub_SIZE_EXP_SUB8(i_data_a, i_data_b, o_sub);
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sub;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sub;
  wire [7:0] w_data_b;
  wire UNCONNECTED;
  CLA_8bit CLA_8BIT_UNIT(.i_carry (1'b1), .i_data_a (i_data_a),
       .i_data_b (w_data_b), .o_sum (o_sub), .o_carry (UNCONNECTED));
  not_op g1(.A (i_data_b), .Z (w_data_b));
endmodule

module bmux_2(ctl, in_0, in_1, z);
  input ctl;
  input [23:0] in_0, in_1;
  output [23:0] z;
  wire ctl;
  wire [23:0] in_0, in_1;
  wire [23:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[23]), .data1 (in_1[23]), .z
       (z[23]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[22]), .data1 (in_1[22]), .z
       (z[22]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[21]), .data1 (in_1[21]), .z
       (z[21]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[20]), .data1 (in_1[20]), .z
       (z[20]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[19]), .data1 (in_1[19]), .z
       (z[19]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[18]), .data1 (in_1[18]), .z
       (z[18]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[17]), .data1 (in_1[17]), .z
       (z[17]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[16]), .data1 (in_1[16]), .z
       (z[16]));
  CDN_bmux2 g9(.sel0 (ctl), .data0 (in_0[15]), .data1 (in_1[15]), .z
       (z[15]));
  CDN_bmux2 g10(.sel0 (ctl), .data0 (in_0[14]), .data1 (in_1[14]), .z
       (z[14]));
  CDN_bmux2 g11(.sel0 (ctl), .data0 (in_0[13]), .data1 (in_1[13]), .z
       (z[13]));
  CDN_bmux2 g12(.sel0 (ctl), .data0 (in_0[12]), .data1 (in_1[12]), .z
       (z[12]));
  CDN_bmux2 g13(.sel0 (ctl), .data0 (in_0[11]), .data1 (in_1[11]), .z
       (z[11]));
  CDN_bmux2 g14(.sel0 (ctl), .data0 (in_0[10]), .data1 (in_1[10]), .z
       (z[10]));
  CDN_bmux2 g15(.sel0 (ctl), .data0 (in_0[9]), .data1 (in_1[9]), .z
       (z[9]));
  CDN_bmux2 g16(.sel0 (ctl), .data0 (in_0[8]), .data1 (in_1[8]), .z
       (z[8]));
  CDN_bmux2 g17(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g18(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g19(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g20(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g21(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g22(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g23(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g24(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module MAN_swap_SIZE_MAN24(i_man_a, i_man_b, i_compare, o_man_max,
     o_man_min);
  input [23:0] i_man_a, i_man_b;
  input i_compare;
  output [23:0] o_man_max, o_man_min;
  wire [23:0] i_man_a, i_man_b;
  wire i_compare;
  wire [23:0] o_man_max, o_man_min;
  bmux_2 mux_24_23(.ctl (i_compare), .in_0 (i_man_b), .in_1 (i_man_a),
       .z (o_man_min));
  bmux_2 mux_23_23(.ctl (i_compare), .in_0 (i_man_a), .in_1 (i_man_b),
       .z (o_man_max));
endmodule

module bmux_4(ctl, in_0, in_1, z);
  input ctl;
  input [27:0] in_0, in_1;
  output [27:0] z;
  wire ctl;
  wire [27:0] in_0, in_1;
  wire [27:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[27]), .data1 (in_1[27]), .z
       (z[27]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[26]), .data1 (in_1[26]), .z
       (z[26]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[25]), .data1 (in_1[25]), .z
       (z[25]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[24]), .data1 (in_1[24]), .z
       (z[24]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[23]), .data1 (in_1[23]), .z
       (z[23]));
  CDN_bmux2 g6(.sel0 (ctl), .data0 (in_0[22]), .data1 (in_1[22]), .z
       (z[22]));
  CDN_bmux2 g7(.sel0 (ctl), .data0 (in_0[21]), .data1 (in_1[21]), .z
       (z[21]));
  CDN_bmux2 g8(.sel0 (ctl), .data0 (in_0[20]), .data1 (in_1[20]), .z
       (z[20]));
  CDN_bmux2 g9(.sel0 (ctl), .data0 (in_0[19]), .data1 (in_1[19]), .z
       (z[19]));
  CDN_bmux2 g10(.sel0 (ctl), .data0 (in_0[18]), .data1 (in_1[18]), .z
       (z[18]));
  CDN_bmux2 g11(.sel0 (ctl), .data0 (in_0[17]), .data1 (in_1[17]), .z
       (z[17]));
  CDN_bmux2 g12(.sel0 (ctl), .data0 (in_0[16]), .data1 (in_1[16]), .z
       (z[16]));
  CDN_bmux2 g13(.sel0 (ctl), .data0 (in_0[15]), .data1 (in_1[15]), .z
       (z[15]));
  CDN_bmux2 g14(.sel0 (ctl), .data0 (in_0[14]), .data1 (in_1[14]), .z
       (z[14]));
  CDN_bmux2 g15(.sel0 (ctl), .data0 (in_0[13]), .data1 (in_1[13]), .z
       (z[13]));
  CDN_bmux2 g16(.sel0 (ctl), .data0 (in_0[12]), .data1 (in_1[12]), .z
       (z[12]));
  CDN_bmux2 g17(.sel0 (ctl), .data0 (in_0[11]), .data1 (in_1[11]), .z
       (z[11]));
  CDN_bmux2 g18(.sel0 (ctl), .data0 (in_0[10]), .data1 (in_1[10]), .z
       (z[10]));
  CDN_bmux2 g19(.sel0 (ctl), .data0 (in_0[9]), .data1 (in_1[9]), .z
       (z[9]));
  CDN_bmux2 g20(.sel0 (ctl), .data0 (in_0[8]), .data1 (in_1[8]), .z
       (z[8]));
  CDN_bmux2 g21(.sel0 (ctl), .data0 (in_0[7]), .data1 (in_1[7]), .z
       (z[7]));
  CDN_bmux2 g22(.sel0 (ctl), .data0 (in_0[6]), .data1 (in_1[6]), .z
       (z[6]));
  CDN_bmux2 g23(.sel0 (ctl), .data0 (in_0[5]), .data1 (in_1[5]), .z
       (z[5]));
  CDN_bmux2 g24(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g25(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g26(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g27(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g28(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module SHF_right_28bit_SIZE_DATA28_SIZE_SHIFT5(i_shift_number, i_data,
     o_data);
  input [4:0] i_shift_number;
  input [27:0] i_data;
  output [27:0] o_data;
  wire [4:0] i_shift_number;
  wire [27:0] i_data;
  wire [27:0] o_data;
  wire [27:0] \stage[1] ;
  wire [27:0] \stage[2] ;
  wire [27:0] \stage[3] ;
  wire [27:0] \stage[4] ;
  bmux_4 \mux_stage[1]_18_21 (.ctl (i_shift_number[0]), .in_0 (i_data),
       .in_1 ({1'b0, i_data[27:1]}), .z (\stage[1] ));
  bmux_4 \mux_stage[2]_18_21 (.ctl (i_shift_number[1]), .in_0
       (\stage[1] ), .in_1 ({2'b0, \stage[1] [27:2]}), .z (\stage[2] ));
  bmux_4 \mux_stage[3]_18_21 (.ctl (i_shift_number[2]), .in_0
       (\stage[2] ), .in_1 ({4'b0, \stage[2] [27:4]}), .z (\stage[3] ));
  bmux_4 \mux_stage[4]_18_21 (.ctl (i_shift_number[3]), .in_0
       (\stage[3] ), .in_1 ({8'b0, \stage[3] [27:8]}), .z (\stage[4] ));
  bmux_4 \mux_stage[5]_18_21 (.ctl (i_shift_number[4]), .in_0
       (\stage[4] ), .in_1 ({16'b0, \stage[4] [27:16]}), .z (o_data));
endmodule

module COMP_28bit_SIZE_DATA28(i_data_a, i_data_b, o_less);
  input [27:0] i_data_a, i_data_b;
  output o_less;
  wire [27:0] i_data_a, i_data_b;
  wire o_less;
  wire n_57, n_58, n_60, n_62, n_64, n_67, n_69, n_73;
  wire n_75, n_80, n_82, n_84, n_85, n_86, w_equal_0_0, w_equal_0_1;
  wire w_equal_0_2, w_equal_0_3, w_equal_0_4, w_equal_0_5, w_equal_0_6,
       w_less_0_0, w_less_0_1, w_less_0_2;
  wire w_less_0_3, w_less_0_4, w_less_0_5, w_less_0_6;
  COMP_4bit u_i_data_0(.i_data_a (i_data_a[3:0]), .i_data_b
       (i_data_b[3:0]), .o_less (w_less_0_0), .o_equal (w_equal_0_0));
  COMP_4bit u_i_data_1(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_0_1), .o_equal (w_equal_0_1));
  COMP_4bit u_i_data_2(.i_data_a (i_data_a[11:8]), .i_data_b
       (i_data_b[11:8]), .o_less (w_less_0_2), .o_equal (w_equal_0_2));
  COMP_4bit u_i_data_3(.i_data_a (i_data_a[15:12]), .i_data_b
       (i_data_b[15:12]), .o_less (w_less_0_3), .o_equal (w_equal_0_3));
  COMP_4bit u_i_data_4(.i_data_a (i_data_a[19:16]), .i_data_b
       (i_data_b[19:16]), .o_less (w_less_0_4), .o_equal (w_equal_0_4));
  COMP_4bit u_i_data_5(.i_data_a (i_data_a[23:20]), .i_data_b
       (i_data_b[23:20]), .o_less (w_less_0_5), .o_equal (w_equal_0_5));
  COMP_4bit u_i_data_6(.i_data_a (i_data_a[27:24]), .i_data_b
       (i_data_b[27:24]), .o_less (w_less_0_6), .o_equal (w_equal_0_6));
  and g1 (n_57, w_equal_0_6, w_less_0_5);
  and g3 (n_58, w_equal_0_6, w_equal_0_5);
  and g4 (n_60, n_58, w_less_0_4);
  and g7 (n_62, n_58, w_equal_0_4);
  and g8 (n_64, n_62, w_less_0_3);
  and g12 (n_67, n_62, w_equal_0_3);
  and g13 (n_69, n_67, w_less_0_2);
  and g18 (n_73, n_67, w_equal_0_2);
  and g19 (n_75, n_73, w_less_0_1);
  and g25 (n_80, n_73, w_equal_0_1);
  and g26 (n_82, n_80, w_less_0_0);
  or g28 (n_84, w_less_0_6, n_57);
  or g29 (n_85, n_60, n_64);
  or g30 (n_86, n_69, n_75);
  or g31 (o_less, n_82, n_84, n_85, n_86);
endmodule

module MAN_swap_SIZE_MAN28(i_man_a, i_man_b, i_compare, o_man_max,
     o_man_min);
  input [27:0] i_man_a, i_man_b;
  input i_compare;
  output [27:0] o_man_max, o_man_min;
  wire [27:0] i_man_a, i_man_b;
  wire i_compare;
  wire [27:0] o_man_max, o_man_min;
  bmux_4 mux_24_23(.ctl (i_compare), .in_0 (i_man_b), .in_1 (i_man_a),
       .z (o_man_min));
  bmux_4 mux_23_23(.ctl (i_compare), .in_0 (i_man_a), .in_1 (i_man_b),
       .z (o_man_max));
endmodule

module SIGN_unit(i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b,
     o_sign_s);
  input i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b;
  output o_sign_s;
  wire i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b;
  wire o_sign_s;
  wire n_2, n_4, n_6, n_7, n_8, n_9, n_11, n_12;
  wire n_13;
  not g1 (n_2, i_add_sub);
  and g2 (n_4, n_2, i_sign_man_b);
  and g3 (n_8, n_4, i_comp_man);
  not g4 (n_6, i_sign_man_b);
  and g5 (n_7, i_add_sub, n_6);
  and g6 (n_9, n_7, i_comp_man);
  or g7 (n_12, n_8, n_9);
  not g8 (n_11, i_comp_man);
  and g9 (n_13, i_sign_man_a, n_11);
  or g10 (o_sign_s, n_12, n_13);
endmodule

module CLA_28bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [27:0] i_data_a, i_data_b;
  output [27:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [27:0] i_data_a, i_data_b;
  wire [27:0] o_sum;
  wire o_carry;
  wire [6:0] w_p;
  wire [6:0] w_g;
  wire [7:0] w_c;
  wire n_59, n_62, n_63, n_64, n_65, n_68, n_69, n_71;
  wire n_73, n_75, n_78, n_79, n_81, n_83, n_85, n_88;
  wire n_90, n_93, n_94, n_96, n_98, n_100, n_103, n_105;
  wire n_109, n_111, n_114, n_115, n_117, n_119, n_121, n_124;
  wire n_126, n_130, n_132, n_137, n_139, n_142, n_143, n_145;
  wire n_147, n_149, n_152, n_154, n_158, n_160, n_165, n_167;
  wire n_173, n_175, n_205, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_212, n_213, n_214;
  CLA_4bit \CLA_BLOCK_GEN[0].CLA_4BIT_UNIT (.a (i_data_a[3:0]), .b
       (i_data_b[3:0]), .cin (i_carry), .sum (o_sum[3:0]), .o_p
       (w_p[0]), .o_g (w_g[0]));
  CLA_4bit \CLA_BLOCK_GEN[1].CLA_4BIT_UNIT (.a (i_data_a[7:4]), .b
       (i_data_b[7:4]), .cin (w_c[1]), .sum (o_sum[7:4]), .o_p
       (w_p[1]), .o_g (w_g[1]));
  CLA_4bit \CLA_BLOCK_GEN[2].CLA_4BIT_UNIT (.a (i_data_a[11:8]), .b
       (i_data_b[11:8]), .cin (w_c[2]), .sum (o_sum[11:8]), .o_p
       (w_p[2]), .o_g (w_g[2]));
  CLA_4bit \CLA_BLOCK_GEN[3].CLA_4BIT_UNIT (.a (i_data_a[15:12]), .b
       (i_data_b[15:12]), .cin (w_c[3]), .sum (o_sum[15:12]), .o_p
       (w_p[3]), .o_g (w_g[3]));
  CLA_4bit \CLA_BLOCK_GEN[4].CLA_4BIT_UNIT (.a (i_data_a[19:16]), .b
       (i_data_b[19:16]), .cin (w_c[4]), .sum (o_sum[19:16]), .o_p
       (w_p[4]), .o_g (w_g[4]));
  CLA_4bit \CLA_BLOCK_GEN[5].CLA_4BIT_UNIT (.a (i_data_a[23:20]), .b
       (i_data_b[23:20]), .cin (w_c[5]), .sum (o_sum[23:20]), .o_p
       (w_p[5]), .o_g (w_g[5]));
  CLA_4bit \CLA_BLOCK_GEN[6].CLA_4BIT_UNIT (.a (i_data_a[27:24]), .b
       (i_data_b[27:24]), .cin (w_c[6]), .sum (o_sum[27:24]), .o_p
       (w_p[6]), .o_g (w_g[6]));
  and g1 (n_59, w_p[0], i_carry);
  or g2 (w_c[1], w_g[0], n_59);
  and g3 (n_62, w_p[1], w_g[0]);
  or g4 (n_64, w_g[1], n_62);
  and g5 (n_63, w_p[1], w_p[0]);
  and g6 (n_65, n_63, i_carry);
  or g7 (w_c[2], n_64, n_65);
  and g8 (n_68, w_p[2], w_g[1]);
  and g10 (n_69, w_p[2], w_p[1]);
  and g11 (n_71, n_69, w_g[0]);
  and g14 (n_73, n_69, w_p[0]);
  and g15 (n_75, n_73, i_carry);
  and g17 (n_78, w_p[3], w_g[2]);
  and g19 (n_79, w_p[3], w_p[2]);
  and g20 (n_81, n_79, w_g[1]);
  and g23 (n_83, n_79, w_p[1]);
  and g24 (n_85, n_83, w_g[0]);
  and g28 (n_88, n_83, w_p[0]);
  and g29 (n_90, n_88, i_carry);
  and g31 (n_93, w_p[4], w_g[3]);
  and g33 (n_94, w_p[4], w_p[3]);
  and g34 (n_96, n_94, w_g[2]);
  and g37 (n_98, n_94, w_p[2]);
  and g38 (n_100, n_98, w_g[1]);
  and g42 (n_103, n_98, w_p[1]);
  and g43 (n_105, n_103, w_g[0]);
  and g48 (n_109, n_103, w_p[0]);
  and g49 (n_111, n_109, i_carry);
  and g51 (n_114, w_p[5], w_g[4]);
  and g53 (n_115, w_p[5], w_p[4]);
  and g54 (n_117, n_115, w_g[3]);
  and g57 (n_119, n_115, w_p[3]);
  and g58 (n_121, n_119, w_g[2]);
  and g62 (n_124, n_119, w_p[2]);
  and g63 (n_126, n_124, w_g[1]);
  and g68 (n_130, n_124, w_p[1]);
  and g69 (n_132, n_130, w_g[0]);
  and g75 (n_137, n_130, w_p[0]);
  and g76 (n_139, n_137, i_carry);
  and g78 (n_142, w_p[6], w_g[5]);
  and g80 (n_143, w_p[6], w_p[5]);
  and g81 (n_145, n_143, w_g[4]);
  and g84 (n_147, n_143, w_p[4]);
  and g85 (n_149, n_147, w_g[3]);
  and g89 (n_152, n_147, w_p[3]);
  and g90 (n_154, n_152, w_g[2]);
  and g95 (n_158, n_152, w_p[2]);
  and g96 (n_160, n_158, w_g[1]);
  and g102 (n_165, n_158, w_p[1]);
  and g103 (n_167, n_165, w_g[0]);
  and g110 (n_173, n_165, w_p[0]);
  and g111 (n_175, n_173, i_carry);
  or g113 (n_205, w_g[5], n_114);
  or g114 (n_206, n_117, n_121);
  or g115 (n_207, n_126, n_132);
  or g116 (w_c[6], n_139, n_205, n_206, n_207);
  or g117 (n_208, w_g[4], n_93);
  or g118 (n_209, n_96, n_100);
  or g119 (w_c[5], n_105, n_111, n_208, n_209);
  or g120 (n_210, w_g[3], n_78);
  or g121 (w_c[4], n_81, n_85, n_90, n_210);
  or g122 (w_c[3], w_g[2], n_68, n_71, n_75);
  or g123 (n_211, w_g[6], n_142);
  or g124 (n_212, n_145, n_149);
  or g125 (n_213, n_154, n_160);
  or g126 (n_214, n_167, n_175);
  or g127 (o_carry, n_211, n_212, n_213, n_214);
endmodule

module not_op_5(A, Z);
  input [27:0] A;
  output [27:0] Z;
  wire [27:0] A;
  wire [27:0] Z;
  not g1 (Z[27], A[27]);
  not g2 (Z[26], A[26]);
  not g3 (Z[25], A[25]);
  not g4 (Z[24], A[24]);
  not g5 (Z[23], A[23]);
  not g6 (Z[22], A[22]);
  not g7 (Z[21], A[21]);
  not g8 (Z[20], A[20]);
  not g9 (Z[19], A[19]);
  not g10 (Z[18], A[18]);
  not g11 (Z[17], A[17]);
  not g12 (Z[16], A[16]);
  not g13 (Z[15], A[15]);
  not g14 (Z[14], A[14]);
  not g15 (Z[13], A[13]);
  not g16 (Z[12], A[12]);
  not g17 (Z[11], A[11]);
  not g18 (Z[10], A[10]);
  not g19 (Z[9], A[9]);
  not g20 (Z[8], A[8]);
  not g21 (Z[7], A[7]);
  not g22 (Z[6], A[6]);
  not g23 (Z[5], A[5]);
  not g24 (Z[4], A[4]);
  not g25 (Z[3], A[3]);
  not g26 (Z[2], A[2]);
  not g27 (Z[1], A[1]);
  not g28 (Z[0], A[0]);
endmodule

module bmux_11(ctl, in_0, in_1, z);
  input ctl, in_0, in_1;
  output z;
  wire ctl, in_0, in_1;
  wire z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0), .data1 (in_1), .z (z));
endmodule

module MAN_ALU_NUM_OP1_SIZE_MAN28(i_fpu_op, i_sign_a, i_sign_b,
     i_man_max, i_man_min, o_man_alu, o_overflow);
  input [0:0] i_fpu_op;
  input i_sign_a, i_sign_b;
  input [27:0] i_man_max, i_man_min;
  output [27:0] o_man_alu;
  output o_overflow;
  wire [0:0] i_fpu_op;
  wire i_sign_a, i_sign_b;
  wire [27:0] i_man_max, i_man_min;
  wire [27:0] o_man_alu;
  wire o_overflow;
  wire [27:0] w_i_man_b;
  wire [27:0] w_n_man_b;
  wire n_3, n_4, w_i_carry, w_overflow;
  CLA_28bit ALU_SUB_UNIT(.i_carry (w_i_carry), .i_data_a (i_man_max),
       .i_data_b (w_i_man_b), .o_sum (o_man_alu), .o_carry
       (w_overflow));
  not_op_5 g4(.A (i_man_min), .Z (w_n_man_b));
  bmux_11 mux_19_20(.ctl (i_fpu_op), .in_0 (n_4), .in_1 (n_3), .z
       (w_i_carry));
  bmux_4 mux_21_20(.ctl (w_i_carry), .in_0 (i_man_min), .in_1
       (w_n_man_b), .z (w_i_man_b));
  bmux_11 mux_33_21(.ctl (w_i_carry), .in_0 (w_overflow), .in_1 (1'b0),
       .z (o_overflow));
  xor g1 (n_4, i_sign_a, i_sign_b);
  not g2 (n_3, n_4);
endmodule

module LOPD_8bit(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire n_3, n_4, n_6, n_7, n_9, n_10, n_11, n_16;
  wire n_17, n_21, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_33, n_34, n_37, n_40, n_42, n_43, n_44, n_48;
  wire n_49, n_54, n_59, n_66, n_68, n_69, n_70, n_71;
  not g1 (n_3, i_data[7]);
  not g2 (n_4, i_data[5]);
  and g3 (n_6, n_3, n_4);
  not g4 (n_7, i_data[3]);
  and g5 (n_9, n_6, n_7);
  not g6 (n_10, i_data[1]);
  and g7 (n_11, n_9, n_10);
  and g8 (n_16, n_11, i_data[0]);
  and g11 (n_17, n_9, i_data[2]);
  and g14 (n_21, n_6, i_data[4]);
  and g16 (n_24, n_3, i_data[6]);
  not g18 (n_25, i_data[6]);
  and g19 (n_26, n_3, n_25);
  and g20 (n_27, n_26, n_7);
  not g21 (n_28, i_data[2]);
  and g22 (n_29, n_27, n_28);
  and g23 (n_33, n_29, i_data[0]);
  and g27 (n_34, n_29, i_data[1]);
  and g30 (n_37, n_26, i_data[4]);
  and g33 (n_40, n_26, i_data[5]);
  and g36 (n_42, n_26, n_4);
  not g37 (n_43, i_data[4]);
  and g38 (n_44, n_42, n_43);
  and g39 (n_48, n_44, i_data[0]);
  and g43 (n_49, n_44, i_data[1]);
  and g48 (n_54, n_44, i_data[2]);
  and g53 (n_59, n_44, i_data[3]);
  not g62 (o_zero_flag, n_66);
  or g63 (o_pos_one[2], n_48, n_49, n_54, n_59);
  or g64 (o_pos_one[1], n_33, n_34, n_37, n_40);
  or g65 (o_pos_one[0], n_16, n_17, n_21, n_24);
  or g66 (n_68, i_data[7], i_data[6]);
  or g67 (n_69, i_data[5], i_data[4]);
  or g68 (n_70, i_data[3], i_data[2]);
  or g69 (n_71, i_data[1], i_data[0]);
  or g70 (n_66, n_68, n_69, n_70, n_71);
endmodule

module LOPD_16bit(i_data, o_pos_one, o_zero_flag);
  input [15:0] i_data;
  output [3:0] o_pos_one;
  output o_zero_flag;
  wire [15:0] i_data;
  wire [3:0] o_pos_one;
  wire o_zero_flag;
  wire [2:0] w_pos_one_0;
  wire [2:0] w_pos_one_1;
  wire w_zero_flag_0;
  LOPD_8bit LOPD_8bit_unit_0(.i_data (i_data[7:0]), .o_pos_one
       (w_pos_one_0), .o_zero_flag (w_zero_flag_0));
  LOPD_8bit LOPD_8bit_unit_1(.i_data (i_data[15:8]), .o_pos_one
       (w_pos_one_1), .o_zero_flag (o_pos_one[3]));
  bmux_11 mux_34_25(.ctl (o_pos_one[3]), .in_0 (w_pos_one_1[2]), .in_1
       (w_pos_one_0[2]), .z (o_pos_one[2]));
  bmux_11 mux_35_25(.ctl (o_pos_one[3]), .in_0 (w_pos_one_1[1]), .in_1
       (w_pos_one_0[1]), .z (o_pos_one[1]));
  bmux_11 mux_36_25(.ctl (o_pos_one[3]), .in_0 (w_pos_one_1[0]), .in_1
       (w_pos_one_0[0]), .z (o_pos_one[0]));
  and g1 (o_zero_flag, w_zero_flag_0, o_pos_one[3]);
endmodule

module bmux_21(ctl, in_0, in_1, z);
  input ctl;
  input [4:0] in_0, in_1;
  output [4:0] z;
  wire ctl;
  wire [4:0] in_0, in_1;
  wire [4:0] z;
  CDN_bmux2 g1(.sel0 (ctl), .data0 (in_0[4]), .data1 (in_1[4]), .z
       (z[4]));
  CDN_bmux2 g2(.sel0 (ctl), .data0 (in_0[3]), .data1 (in_1[3]), .z
       (z[3]));
  CDN_bmux2 g3(.sel0 (ctl), .data0 (in_0[2]), .data1 (in_1[2]), .z
       (z[2]));
  CDN_bmux2 g4(.sel0 (ctl), .data0 (in_0[1]), .data1 (in_1[1]), .z
       (z[1]));
  CDN_bmux2 g5(.sel0 (ctl), .data0 (in_0[0]), .data1 (in_1[0]), .z
       (z[0]));
endmodule

module LOPD_24bit_SIZE_DATA24_SIZE_LOPD5(i_data, o_one_position,
     o_zero_flag);
  input [23:0] i_data;
  output [4:0] o_one_position;
  output o_zero_flag;
  wire [23:0] i_data;
  wire [4:0] o_one_position;
  wire o_zero_flag;
  wire [3:0] LOPD16_o_pos_one;
  wire [2:0] LOPD8_o_pos_one;
  wire [4:0] w_o_one_position;
  wire LOPD8_o_zero_flag, LOPD16_o_zero_flag;
  LOPD_16bit LOPD_16bit_UNIT_MSB(.i_data (i_data[23:8]), .o_pos_one
       (LOPD16_o_pos_one), .o_zero_flag (LOPD16_o_zero_flag));
  LOPD_8bit LOPD_8bit_UNIT_LSB(.i_data (i_data[7:0]), .o_pos_one
       (LOPD8_o_pos_one), .o_zero_flag (LOPD8_o_zero_flag));
  bmux_11 mux_33_30(.ctl (LOPD16_o_zero_flag), .in_0
       (LOPD16_o_pos_one[3]), .in_1 (1'b0), .z (w_o_one_position[3]));
  bmux_11 mux_34_30(.ctl (LOPD16_o_zero_flag), .in_0
       (LOPD16_o_pos_one[2]), .in_1 (LOPD8_o_pos_one[2]), .z
       (w_o_one_position[2]));
  bmux_11 mux_35_30(.ctl (LOPD16_o_zero_flag), .in_0
       (LOPD16_o_pos_one[1]), .in_1 (LOPD8_o_pos_one[1]), .z
       (w_o_one_position[1]));
  bmux_11 mux_36_30(.ctl (LOPD16_o_zero_flag), .in_0
       (LOPD16_o_pos_one[0]), .in_1 (LOPD8_o_pos_one[0]), .z
       (w_o_one_position[0]));
  bmux_21 mux_37_25(.ctl (o_zero_flag), .in_0 ({LOPD16_o_zero_flag,
       w_o_one_position[3:0]}), .in_1 (5'b11111), .z (o_one_position));
  and g1 (o_zero_flag, LOPD16_o_zero_flag, LOPD8_o_zero_flag);
endmodule

module not_op_6(A, Z);
  input [7:0] A;
  output [7:0] Z;
  wire [7:0] A;
  wire [7:0] Z;
  not g1 (Z[7], A[7]);
  not g2 (Z[6], A[6]);
  not g3 (Z[5], A[5]);
  not g4 (Z[4], A[4]);
  not g5 (Z[3], A[3]);
  not g6 (Z[2], A[2]);
  not g7 (Z[1], A[1]);
  not g8 (Z[0], A[0]);
endmodule

module EXP_adjust_SIZE_EXP8_SIZE_LOPD8(i_overflow, i_underflow,
     i_zero_flag, i_lopd_value, i_exp_value, o_exp_result);
  input i_overflow, i_underflow, i_zero_flag;
  input [7:0] i_lopd_value, i_exp_value;
  output [7:0] o_exp_result;
  wire i_overflow, i_underflow, i_zero_flag;
  wire [7:0] i_lopd_value, i_exp_value;
  wire [7:0] o_exp_result;
  wire [7:0] w_data_b;
  wire [7:0] w_exp_result;
  wire UNCONNECTED0, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_52, w_i_carry;
  CLA_8bit CLA_8BIT_UNIT(.i_carry (w_i_carry), .i_data_a (i_exp_value),
       .i_data_b (w_data_b), .o_sum (w_exp_result), .o_carry
       (UNCONNECTED0));
  not_op_6 g3(.A (i_lopd_value), .Z ({n_35, n_34, n_33, n_32, n_31,
       n_30, n_29, n_28}));
  bmux mux_21_48(.ctl (i_underflow), .in_0 ({n_35, n_34, n_33, n_32,
       n_31, n_30, n_29, n_28}), .in_1 (8'b0), .z ({n_43, n_42, n_41,
       n_40, n_39, n_38, n_37, n_36}));
  bmux mux_21_19(.ctl (i_overflow), .in_0 ({n_43, n_42, n_41, n_40,
       n_39, n_38, n_37, n_36}), .in_1 (8'b1), .z (w_data_b));
  bmux mux_33_23(.ctl (i_zero_flag), .in_0 (w_exp_result), .in_1
       (8'b0), .z (o_exp_result));
  or g1 (n_52, i_overflow, i_underflow);
  not g2 (w_i_carry, n_52);
endmodule

module SHF_left_28bit_SIZE_DATA28_SIZE_SHIFT5(i_shift_number, i_data,
     o_data);
  input [4:0] i_shift_number;
  input [27:0] i_data;
  output [27:0] o_data;
  wire [4:0] i_shift_number;
  wire [27:0] i_data;
  wire [27:0] o_data;
  wire [27:0] \stage[1] ;
  wire [27:0] \stage[2] ;
  wire [27:0] \stage[3] ;
  wire [27:0] \stage[4] ;
  bmux_4 \mux_stage[1]_18_21 (.ctl (i_shift_number[0]), .in_0 (i_data),
       .in_1 ({i_data[26:0], 1'b0}), .z (\stage[1] ));
  bmux_4 \mux_stage[2]_18_21 (.ctl (i_shift_number[1]), .in_0
       (\stage[1] ), .in_1 ({\stage[1] [25:0], 2'b0}), .z (\stage[2] ));
  bmux_4 \mux_stage[3]_18_21 (.ctl (i_shift_number[2]), .in_0
       (\stage[2] ), .in_1 ({\stage[2] [23:0], 4'b0}), .z (\stage[3] ));
  bmux_4 \mux_stage[4]_18_21 (.ctl (i_shift_number[3]), .in_0
       (\stage[3] ), .in_1 ({\stage[3] [19:0], 8'b0}), .z (\stage[4] ));
  bmux_4 \mux_stage[5]_18_21 (.ctl (i_shift_number[4]), .in_0
       (\stage[4] ), .in_1 ({\stage[4] [11:0], 16'b0}), .z (o_data));
endmodule

module NORMALIZATION_unit_SIZE_LOPD5_SIZE_DATA28(i_overflow,
     i_zero_flag, i_one_position, i_mantissa, o_mantissa);
  input i_overflow, i_zero_flag;
  input [4:0] i_one_position;
  input [27:0] i_mantissa;
  output [27:0] o_mantissa;
  wire i_overflow, i_zero_flag;
  wire [4:0] i_one_position;
  wire [27:0] i_mantissa;
  wire [27:0] o_mantissa;
  wire [27:0] w_shift_left;
  wire n_32, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116;
  SHF_left_28bit_SIZE_DATA28_SIZE_SHIFT5
       SHF_left_28bit_unit(.i_shift_number (i_one_position), .i_data
       (i_mantissa), .o_data (w_shift_left));
  bmux_4 mux_23_91(.ctl (n_32), .in_0 (i_mantissa), .in_1
       (w_shift_left), .z ({n_88, n_87, n_86, n_85, n_84, n_83, n_82,
       n_81, n_80, n_79, n_78, n_77, n_76, n_75, n_74, n_73, n_72,
       n_71, n_70, n_69, n_68, n_67, n_66, n_65, n_64, n_63, n_62,
       n_61}));
  bmux_4 mux_23_41(.ctl (i_overflow), .in_0 ({n_88, n_87, n_86, n_85,
       n_84, n_83, n_82, n_81, n_80, n_79, n_78, n_77, n_76, n_75,
       n_74, n_73, n_72, n_71, n_70, n_69, n_68, n_67, n_66, n_65,
       n_64, n_63, n_62, n_61}), .in_1 ({1'b1, i_mantissa[27:1]}), .z
       ({n_116, n_115, n_114, n_113, n_112, n_111, n_110, n_109, n_108,
       n_107, n_106, n_105, n_104, n_103, n_102, n_101, n_100, n_99,
       n_98, n_97, n_96, n_95, n_94, n_93, n_92, n_91, n_90, n_89}));
  bmux_4 mux_23_21(.ctl (i_zero_flag), .in_0 ({n_116, n_115, n_114,
       n_113, n_112, n_111, n_110, n_109, n_108, n_107, n_106, n_105,
       n_104, n_103, n_102, n_101, n_100, n_99, n_98, n_97, n_96, n_95,
       n_94, n_93, n_92, n_91, n_90, n_89}), .in_1 (28'b0), .z
       (o_mantissa));
  not g1 (n_32, i_mantissa[27]);
endmodule

module and_op_14(A, Z);
  input [2:0] A;
  output Z;
  wire [2:0] A;
  wire Z;
  wire n_4;
  nand g1 (n_4, A[2], A[1], A[0]);
  not g2 (Z, n_4);
endmodule

module and_op_15(A, Z);
  input [3:0] A;
  output Z;
  wire [3:0] A;
  wire Z;
  wire n_5;
  nand g1 (n_5, A[3], A[2], A[1], A[0]);
  not g2 (Z, n_5);
endmodule

module and_op_16(A, Z);
  input [4:0] A;
  output Z;
  wire [4:0] A;
  wire Z;
  wire n_6, n_7;
  nand g1 (n_6, A[4], A[3], A[2], A[1]);
  not g2 (n_7, A[0]);
  nor g3 (Z, n_6, n_7);
endmodule

module and_op_17(A, Z);
  input [5:0] A;
  output Z;
  wire [5:0] A;
  wire Z;
  wire n_7, n_8;
  nand g1 (n_8, A[5], A[4], A[3], A[2]);
  nand g2 (n_7, A[1], A[0]);
  nor g3 (Z, n_7, n_8);
endmodule

module and_op_18(A, Z);
  input [6:0] A;
  output Z;
  wire [6:0] A;
  wire Z;
  wire n_8, n_9;
  nand g1 (n_9, A[6], A[5], A[4], A[3]);
  nand g2 (n_8, A[2], A[1], A[0]);
  nor g3 (Z, n_8, n_9);
endmodule

module and_op_19(A, Z);
  input [7:0] A;
  output Z;
  wire [7:0] A;
  wire Z;
  wire n_9, n_10;
  nand g1 (n_10, A[7], A[6], A[5], A[4]);
  nand g2 (n_9, A[3], A[2], A[1], A[0]);
  nor g3 (Z, n_9, n_10);
endmodule

module and_op_20(A, Z);
  input [8:0] A;
  output Z;
  wire [8:0] A;
  wire Z;
  wire n_10, n_11, n_12;
  nand g1 (n_11, A[8], A[7], A[6], A[5]);
  nand g2 (n_12, A[4], A[3], A[2], A[1]);
  not g3 (n_10, A[0]);
  nor g4 (Z, n_10, n_11, n_12);
endmodule

module and_op_21(A, Z);
  input [9:0] A;
  output Z;
  wire [9:0] A;
  wire Z;
  wire n_11, n_12, n_13;
  nand g1 (n_11, A[9], A[8], A[7], A[6]);
  nand g2 (n_12, A[5], A[4], A[3], A[2]);
  nand g3 (n_13, A[1], A[0]);
  nor g4 (Z, n_11, n_12, n_13);
endmodule

module and_op_22(A, Z);
  input [10:0] A;
  output Z;
  wire [10:0] A;
  wire Z;
  wire n_12, n_13, n_14;
  nand g1 (n_12, A[10], A[9], A[8], A[7]);
  nand g2 (n_13, A[6], A[5], A[4], A[3]);
  nand g3 (n_14, A[2], A[1], A[0]);
  nor g4 (Z, n_12, n_13, n_14);
endmodule

module and_op_23(A, Z);
  input [11:0] A;
  output Z;
  wire [11:0] A;
  wire Z;
  wire n_13, n_14, n_15;
  nand g1 (n_13, A[11], A[10], A[9], A[8]);
  nand g2 (n_14, A[7], A[6], A[5], A[4]);
  nand g3 (n_15, A[3], A[2], A[1], A[0]);
  nor g4 (Z, n_13, n_14, n_15);
endmodule

module and_op_24(A, Z);
  input [12:0] A;
  output Z;
  wire [12:0] A;
  wire Z;
  wire n_14, n_15, n_16, n_17;
  nand g1 (n_15, A[12], A[11], A[10], A[9]);
  nand g2 (n_16, A[8], A[7], A[6], A[5]);
  nand g3 (n_17, A[4], A[3], A[2], A[1]);
  not g4 (n_14, A[0]);
  nor g5 (Z, n_14, n_15, n_16, n_17);
endmodule

module and_op_25(A, Z);
  input [13:0] A;
  output Z;
  wire [13:0] A;
  wire Z;
  wire n_15, n_16, n_17, n_18;
  nand g1 (n_15, A[13], A[12], A[11], A[10]);
  nand g2 (n_16, A[9], A[8], A[7], A[6]);
  nand g3 (n_17, A[5], A[4], A[3], A[2]);
  nand g4 (n_18, A[1], A[0]);
  nor g5 (Z, n_15, n_16, n_17, n_18);
endmodule

module and_op_26(A, Z);
  input [14:0] A;
  output Z;
  wire [14:0] A;
  wire Z;
  wire n_16, n_17, n_18, n_19;
  nand g1 (n_16, A[14], A[13], A[12], A[11]);
  nand g2 (n_17, A[10], A[9], A[8], A[7]);
  nand g3 (n_18, A[6], A[5], A[4], A[3]);
  nand g4 (n_19, A[2], A[1], A[0]);
  nor g5 (Z, n_16, n_17, n_18, n_19);
endmodule

module and_op_27(A, Z);
  input [15:0] A;
  output Z;
  wire [15:0] A;
  wire Z;
  wire n_17, n_18, n_19, n_20;
  nand g1 (n_17, A[15], A[14], A[13], A[12]);
  nand g2 (n_18, A[11], A[10], A[9], A[8]);
  nand g3 (n_19, A[7], A[6], A[5], A[4]);
  nand g4 (n_20, A[3], A[2], A[1], A[0]);
  nor g5 (Z, n_17, n_18, n_19, n_20);
endmodule

module and_op_28(A, Z);
  input [16:0] A;
  output Z;
  wire [16:0] A;
  wire Z;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  nand g1 (n_19, A[16], A[15], A[14], A[13]);
  nand g2 (n_20, A[12], A[11], A[10], A[9]);
  nand g3 (n_21, A[8], A[7], A[6], A[5]);
  nand g4 (n_22, A[4], A[3], A[2], A[1]);
  not g5 (n_18, A[0]);
  nor g6 (n_23, n_18, n_19, n_20, n_21);
  not g7 (n_24, n_22);
  nand g8 (n_25, n_23, n_24);
  not g9 (Z, n_25);
endmodule

module and_op_29(A, Z);
  input [17:0] A;
  output Z;
  wire [17:0] A;
  wire Z;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  nand g1 (n_19, A[17], A[16], A[15], A[14]);
  nand g2 (n_20, A[13], A[12], A[11], A[10]);
  nand g3 (n_21, A[9], A[8], A[7], A[6]);
  nand g4 (n_22, A[5], A[4], A[3], A[2]);
  nand g5 (n_23, A[1], A[0]);
  nor g6 (n_24, n_19, n_20, n_21, n_22);
  not g7 (n_25, n_23);
  nand g8 (n_26, n_24, n_25);
  not g9 (Z, n_26);
endmodule

module and_op_30(A, Z);
  input [18:0] A;
  output Z;
  wire [18:0] A;
  wire Z;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  nand g1 (n_20, A[18], A[17], A[16], A[15]);
  nand g2 (n_21, A[14], A[13], A[12], A[11]);
  nand g3 (n_22, A[10], A[9], A[8], A[7]);
  nand g4 (n_23, A[6], A[5], A[4], A[3]);
  nand g5 (n_24, A[2], A[1], A[0]);
  nor g6 (n_25, n_20, n_21, n_22, n_23);
  not g7 (n_26, n_24);
  nand g8 (n_27, n_25, n_26);
  not g9 (Z, n_27);
endmodule

module and_op_31(A, Z);
  input [19:0] A;
  output Z;
  wire [19:0] A;
  wire Z;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  nand g1 (n_21, A[19], A[18], A[17], A[16]);
  nand g2 (n_22, A[15], A[14], A[13], A[12]);
  nand g3 (n_23, A[11], A[10], A[9], A[8]);
  nand g4 (n_24, A[7], A[6], A[5], A[4]);
  nand g5 (n_25, A[3], A[2], A[1], A[0]);
  nor g6 (n_26, n_21, n_22, n_23, n_24);
  not g7 (n_27, n_25);
  nand g8 (n_28, n_26, n_27);
  not g9 (Z, n_28);
endmodule

module and_op_32(A, Z);
  input [20:0] A;
  output Z;
  wire [20:0] A;
  wire Z;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30;
  nand g1 (n_23, A[20], A[19], A[18], A[17]);
  nand g2 (n_24, A[16], A[15], A[14], A[13]);
  nand g3 (n_25, A[12], A[11], A[10], A[9]);
  nand g4 (n_26, A[8], A[7], A[6], A[5]);
  nand g5 (n_27, A[4], A[3], A[2], A[1]);
  not g6 (n_22, A[0]);
  nor g7 (n_29, n_22, n_23, n_24, n_25);
  nor g8 (n_28, n_26, n_27);
  nand g9 (n_30, n_28, n_29);
  not g10 (Z, n_30);
endmodule

module and_op_33(A, Z);
  input [21:0] A;
  output Z;
  wire [21:0] A;
  wire Z;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31;
  nand g1 (n_23, A[21], A[20], A[19], A[18]);
  nand g2 (n_24, A[17], A[16], A[15], A[14]);
  nand g3 (n_25, A[13], A[12], A[11], A[10]);
  nand g4 (n_26, A[9], A[8], A[7], A[6]);
  nand g5 (n_27, A[5], A[4], A[3], A[2]);
  nand g6 (n_28, A[1], A[0]);
  nor g7 (n_30, n_23, n_24, n_25, n_26);
  nor g8 (n_29, n_27, n_28);
  nand g9 (n_31, n_29, n_30);
  not g10 (Z, n_31);
endmodule

module and_op_34(A, Z);
  input [22:0] A;
  output Z;
  wire [22:0] A;
  wire Z;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32;
  nand g1 (n_24, A[22], A[21], A[20], A[19]);
  nand g2 (n_25, A[18], A[17], A[16], A[15]);
  nand g3 (n_26, A[14], A[13], A[12], A[11]);
  nand g4 (n_27, A[10], A[9], A[8], A[7]);
  nand g5 (n_28, A[6], A[5], A[4], A[3]);
  nand g6 (n_29, A[2], A[1], A[0]);
  nor g7 (n_31, n_24, n_25, n_26, n_27);
  nor g8 (n_30, n_28, n_29);
  nand g9 (n_32, n_30, n_31);
  not g10 (Z, n_32);
endmodule

module xor_op_35(A, B, Z);
  input [23:0] A, B;
  output [23:0] Z;
  wire [23:0] A, B;
  wire [23:0] Z;
  xor g1 (Z[0], A[0], B[0]);
  xor g2 (Z[1], A[1], B[1]);
  xor g3 (Z[2], A[2], B[2]);
  xor g4 (Z[3], A[3], B[3]);
  xor g5 (Z[4], A[4], B[4]);
  xor g6 (Z[5], A[5], B[5]);
  xor g7 (Z[6], A[6], B[6]);
  xor g8 (Z[7], A[7], B[7]);
  xor g9 (Z[8], A[8], B[8]);
  xor g10 (Z[9], A[9], B[9]);
  xor g11 (Z[10], A[10], B[10]);
  xor g12 (Z[11], A[11], B[11]);
  xor g13 (Z[12], A[12], B[12]);
  xor g14 (Z[13], A[13], B[13]);
  xor g15 (Z[14], A[14], B[14]);
  xor g16 (Z[15], A[15], B[15]);
  xor g17 (Z[16], A[16], B[16]);
  xor g18 (Z[17], A[17], B[17]);
  xor g19 (Z[18], A[18], B[18]);
  xor g20 (Z[19], A[19], B[19]);
  xor g21 (Z[20], A[20], B[20]);
  xor g22 (Z[21], A[21], B[21]);
  xor g23 (Z[22], A[22], B[22]);
  xor g24 (Z[23], A[23], B[23]);
endmodule

module and_op_36(A, Z);
  input [23:0] A;
  output Z;
  wire [23:0] A;
  wire Z;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33;
  nand g1 (n_25, A[23], A[22], A[21], A[20]);
  nand g2 (n_26, A[19], A[18], A[17], A[16]);
  nand g3 (n_27, A[15], A[14], A[13], A[12]);
  nand g4 (n_28, A[11], A[10], A[9], A[8]);
  nand g5 (n_29, A[7], A[6], A[5], A[4]);
  nand g6 (n_30, A[3], A[2], A[1], A[0]);
  nor g7 (n_32, n_25, n_26, n_27, n_28);
  nor g8 (n_31, n_29, n_30);
  nand g9 (n_33, n_31, n_32);
  not g10 (Z, n_33);
endmodule

module RND_add_SIZE_DATA24(i_data, i_carry, o_data, o_carry);
  input [23:0] i_data;
  input i_carry;
  output [23:0] o_data;
  output o_carry;
  wire [23:0] i_data;
  wire i_carry;
  wire [23:0] o_data;
  wire o_carry;
  wire [23:0] w_carry;
  wire n_5, n_7, n_9, n_11, n_13, n_15, n_17, n_19;
  wire n_21, n_23, n_25, n_27, n_29, n_31, n_33, n_35;
  wire n_37, n_39, n_41, n_43, n_45, n_47, n_49, n_75;
  and_op_14 g5(.A (i_data[2:0]), .Z (n_7));
  and_op_15 g7(.A (i_data[3:0]), .Z (n_9));
  and_op_16 g9(.A (i_data[4:0]), .Z (n_11));
  and_op_17 g11(.A (i_data[5:0]), .Z (n_13));
  and_op_18 g13(.A (i_data[6:0]), .Z (n_15));
  and_op_19 g15(.A (i_data[7:0]), .Z (n_17));
  and_op_20 g17(.A (i_data[8:0]), .Z (n_19));
  and_op_21 g19(.A (i_data[9:0]), .Z (n_21));
  and_op_22 g21(.A (i_data[10:0]), .Z (n_23));
  and_op_23 g23(.A (i_data[11:0]), .Z (n_25));
  and_op_24 g25(.A (i_data[12:0]), .Z (n_27));
  and_op_25 g27(.A (i_data[13:0]), .Z (n_29));
  and_op_26 g29(.A (i_data[14:0]), .Z (n_31));
  and_op_27 g31(.A (i_data[15:0]), .Z (n_33));
  and_op_28 g33(.A (i_data[16:0]), .Z (n_35));
  and_op_29 g35(.A (i_data[17:0]), .Z (n_37));
  and_op_30 g37(.A (i_data[18:0]), .Z (n_39));
  and_op_31 g39(.A (i_data[19:0]), .Z (n_41));
  and_op_32 g41(.A (i_data[20:0]), .Z (n_43));
  and_op_33 g43(.A (i_data[21:0]), .Z (n_45));
  and_op_34 g45(.A (i_data[22:0]), .Z (n_47));
  xor_op_35 g47(.A (i_data), .B ({w_carry[23:1], i_carry}), .Z
       (o_data));
  and_op_36 g48(.A (i_data), .Z (n_49));
  and g2 (w_carry[1], i_data[0], i_carry);
  and g4 (w_carry[2], n_5, i_carry);
  and g6 (w_carry[3], n_7, i_carry);
  and g8 (w_carry[4], n_9, i_carry);
  and g10 (w_carry[5], n_11, i_carry);
  and g12 (w_carry[6], n_13, i_carry);
  and g14 (w_carry[7], n_15, i_carry);
  and g16 (w_carry[8], n_17, i_carry);
  and g18 (w_carry[9], n_19, i_carry);
  and g20 (w_carry[10], n_21, i_carry);
  and g22 (w_carry[11], n_23, i_carry);
  and g24 (w_carry[12], n_25, i_carry);
  and g26 (w_carry[13], n_27, i_carry);
  and g28 (w_carry[14], n_29, i_carry);
  and g30 (w_carry[15], n_31, i_carry);
  and g32 (w_carry[16], n_33, i_carry);
  and g34 (w_carry[17], n_35, i_carry);
  and g36 (w_carry[18], n_37, i_carry);
  and g38 (w_carry[19], n_39, i_carry);
  and g40 (w_carry[20], n_41, i_carry);
  and g42 (w_carry[21], n_43, i_carry);
  and g44 (w_carry[22], n_45, i_carry);
  and g46 (w_carry[23], n_47, i_carry);
  and g49 (o_carry, n_49, i_carry);
  nand g1 (n_75, i_data[0], i_data[1]);
  not g50 (n_5, n_75);
endmodule

module ROUNDING_unit_SIZE_MAN28_SIZE_MAN_RESULT24(i_man, o_man_result,
     o_ov_flow);
  input [27:0] i_man;
  output [23:0] o_man_result;
  output o_ov_flow;
  wire [27:0] i_man;
  wire [23:0] o_man_result;
  wire o_ov_flow;
  wire n_3, n_4, w_rounding_result, w_sticky_bit;
  RND_add_SIZE_DATA24 INCREASE_ROUNDING(.i_data (i_man[27:4]), .i_carry
       (w_rounding_result), .o_data (o_man_result), .o_carry
       (o_ov_flow));
  or g1 (w_sticky_bit, i_man[1], i_man[0]);
  and g2 (n_3, i_man[3], i_man[2]);
  and g3 (n_4, i_man[2], w_sticky_bit);
  or g4 (w_rounding_result, n_3, n_4);
endmodule

module and_op_39(A, Z);
  input [2:0] A;
  output Z;
  wire [2:0] A;
  wire Z;
  wire n_4;
  nand g1 (n_4, A[2], A[1], A[0]);
  not g2 (Z, n_4);
endmodule

module and_op_40(A, Z);
  input [3:0] A;
  output Z;
  wire [3:0] A;
  wire Z;
  wire n_5;
  nand g1 (n_5, A[3], A[2], A[1], A[0]);
  not g2 (Z, n_5);
endmodule

module and_op_41(A, Z);
  input [4:0] A;
  output Z;
  wire [4:0] A;
  wire Z;
  wire n_6, n_7;
  nand g1 (n_6, A[4], A[3], A[2], A[1]);
  not g2 (n_7, A[0]);
  nor g3 (Z, n_6, n_7);
endmodule

module and_op_42(A, Z);
  input [5:0] A;
  output Z;
  wire [5:0] A;
  wire Z;
  wire n_7, n_8;
  nand g1 (n_8, A[5], A[4], A[3], A[2]);
  nand g2 (n_7, A[1], A[0]);
  nor g3 (Z, n_7, n_8);
endmodule

module and_op_43(A, Z);
  input [6:0] A;
  output Z;
  wire [6:0] A;
  wire Z;
  wire n_8, n_9;
  nand g1 (n_9, A[6], A[5], A[4], A[3]);
  nand g2 (n_8, A[2], A[1], A[0]);
  nor g3 (Z, n_8, n_9);
endmodule

module xor_op_44(A, B, Z);
  input [7:0] A, B;
  output [7:0] Z;
  wire [7:0] A, B;
  wire [7:0] Z;
  xor g1 (Z[0], A[0], B[0]);
  xor g2 (Z[1], A[1], B[1]);
  xor g3 (Z[2], A[2], B[2]);
  xor g4 (Z[3], A[3], B[3]);
  xor g5 (Z[4], A[4], B[4]);
  xor g6 (Z[5], A[5], B[5]);
  xor g7 (Z[6], A[6], B[6]);
  xor g8 (Z[7], A[7], B[7]);
endmodule

module EXP_rounding_SIZE_DATA8(i_carry_rounding, i_exp_result,
     o_exp_result);
  input i_carry_rounding;
  input [7:0] i_exp_result;
  output [7:0] o_exp_result;
  wire i_carry_rounding;
  wire [7:0] i_exp_result;
  wire [7:0] o_exp_result;
  wire [7:0] w_carry;
  wire n_4, n_6, n_8, n_10, n_12, n_14, n_24;
  and_op_39 g5(.A (i_exp_result[2:0]), .Z (n_6));
  and_op_40 g7(.A (i_exp_result[3:0]), .Z (n_8));
  and_op_41 g9(.A (i_exp_result[4:0]), .Z (n_10));
  and_op_42 g11(.A (i_exp_result[5:0]), .Z (n_12));
  and_op_43 g13(.A (i_exp_result[6:0]), .Z (n_14));
  xor_op_44 g15(.A (i_exp_result), .B ({w_carry[7:1],
       i_carry_rounding}), .Z (o_exp_result));
  and g2 (w_carry[1], i_exp_result[0], i_carry_rounding);
  and g4 (w_carry[2], n_4, i_carry_rounding);
  and g6 (w_carry[3], n_6, i_carry_rounding);
  and g8 (w_carry[4], n_8, i_carry_rounding);
  and g10 (w_carry[5], n_10, i_carry_rounding);
  and g12 (w_carry[6], n_12, i_carry_rounding);
  and g14 (w_carry[7], n_14, i_carry_rounding);
  nand g1 (n_24, i_exp_result[0], i_exp_result[1]);
  not g16 (n_4, n_24);
endmodule

module and_op_45(A, Z);
  input [7:0] A;
  output Z;
  wire [7:0] A;
  wire Z;
  wire n_9, n_10;
  nand g1 (n_10, A[7], A[6], A[5], A[4]);
  nand g2 (n_9, A[3], A[2], A[1], A[0]);
  nor g3 (Z, n_9, n_10);
endmodule

module and_op_46(A, Z);
  input [7:0] A;
  output Z;
  wire [7:0] A;
  wire Z;
  wire n_9, n_10;
  nand g1 (n_10, A[7], A[6], A[5], A[4]);
  nand g2 (n_9, A[3], A[2], A[1], A[0]);
  nor g3 (Z, n_9, n_10);
endmodule

module PSC_unit(i_add_sub, i_sign_a, i_exp_a, i_man_a, i_sign_b,
     i_exp_b, i_man_b, o_sel_exp, o_sel_man);
  input i_add_sub, i_sign_a, i_sign_b;
  input [7:0] i_exp_a, i_exp_b;
  input [23:0] i_man_a, i_man_b;
  output o_sel_exp;
  output [1:0] o_sel_man;
  wire i_add_sub, i_sign_a, i_sign_b;
  wire [7:0] i_exp_a, i_exp_b;
  wire [23:0] i_man_a, i_man_b;
  wire o_sel_exp;
  wire [1:0] o_sel_man;
  wire n_64, n_65, n_66, n_68, n_69, n_70, n_71, n_72;
  wire n_75, n_76, n_77, n_78, n_80, n_85, n_90, n_95;
  wire n_100, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, w_E_one_A;
  wire w_E_one_B, w_M_zero_A, w_M_zero_B;
  and_op_45 g1(.A (i_exp_a), .Z (w_E_one_A));
  and_op_46 g2(.A (i_exp_b), .Z (w_E_one_B));
  not g5 (n_64, i_sign_b);
  and g6 (n_65, n_64, w_E_one_B);
  not g7 (n_66, w_M_zero_B);
  and g8 (n_71, n_65, n_66);
  not g9 (n_68, i_sign_a);
  and g10 (n_69, n_68, w_E_one_A);
  not g11 (n_70, w_M_zero_A);
  and g12 (n_72, n_69, n_70);
  or g13 (n_75, n_71, n_72);
  or g17 (o_sel_exp, n_75, n_76);
  or g18 (o_sel_man[1], w_E_one_A, w_E_one_B);
  and g19 (n_77, w_E_one_B, n_66);
  and g20 (n_78, w_E_one_A, n_70);
  not g22 (n_80, i_add_sub);
  nor g43 (n_104, i_man_a[22], i_man_a[21], i_man_a[20], i_man_a[19]);
  nor g44 (n_105, i_man_a[18], i_man_a[17], i_man_a[16], i_man_a[15]);
  nor g3 (n_106, i_man_a[14], i_man_a[13], i_man_a[12], i_man_a[11]);
  nor g45 (n_107, i_man_a[10], i_man_a[9], i_man_a[8], i_man_a[7]);
  nor g46 (n_108, i_man_a[6], i_man_a[5], i_man_a[4], i_man_a[3]);
  nor g47 (n_109, i_man_a[2], i_man_a[1], i_man_a[0]);
  nand g48 (n_111, n_104, n_105, n_106, n_107);
  nand g49 (n_110, n_108, n_109);
  nor g50 (w_M_zero_A, n_110, n_111);
  nor g51 (n_112, i_man_b[22], i_man_b[21], i_man_b[20], i_man_b[19]);
  nor g52 (n_113, i_man_b[18], i_man_b[17], i_man_b[16], i_man_b[15]);
  nor g53 (n_114, i_man_b[14], i_man_b[13], i_man_b[12], i_man_b[11]);
  nor g4 (n_115, i_man_b[10], i_man_b[9], i_man_b[8], i_man_b[7]);
  nor g54 (n_116, i_man_b[6], i_man_b[5], i_man_b[4], i_man_b[3]);
  nor g55 (n_117, i_man_b[2], i_man_b[1], i_man_b[0]);
  nand g56 (n_119, n_112, n_113, n_114, n_115);
  nand g57 (n_118, n_116, n_117);
  nor g58 (w_M_zero_B, n_118, n_119);
  and g59 (n_76, w_E_one_A, w_M_zero_A, w_E_one_B, w_M_zero_B);
  or g60 (n_120, n_77, n_78);
  or g61 (n_121, n_85, n_90);
  or g62 (o_sel_man[0], n_95, n_100, n_120, n_121);
  and g63 (n_122, n_80, n_68);
  and g64 (n_85, w_E_one_A, i_sign_b, w_E_one_B, n_122);
  and g65 (n_123, n_80, i_sign_a);
  and g66 (n_90, w_E_one_A, n_64, w_E_one_B, n_123);
  and g67 (n_124, i_add_sub, n_68);
  and g68 (n_95, w_E_one_A, n_64, w_E_one_B, n_124);
  and g69 (n_125, i_add_sub, i_sign_a);
  and g70 (n_100, w_E_one_A, i_sign_b, w_E_one_B, n_125);
endmodule

module bmux_33(ctl, in_0, in_1, in_2, in_3, z);
  input [1:0] ctl;
  input [23:0] in_0, in_1, in_2, in_3;
  output [23:0] z;
  wire [1:0] ctl;
  wire [23:0] in_0, in_1, in_2, in_3;
  wire [23:0] z;
  CDN_bmux4 g1(.sel0 (ctl[0]), .data0 (in_0[23]), .data1 (in_1[23]),
       .sel1 (ctl[1]), .data2 (in_2[23]), .data3 (in_3[23]), .z
       (z[23]));
  CDN_bmux4 g2(.sel0 (ctl[0]), .data0 (in_0[22]), .data1 (in_1[22]),
       .sel1 (ctl[1]), .data2 (in_2[22]), .data3 (in_3[22]), .z
       (z[22]));
  CDN_bmux4 g3(.sel0 (ctl[0]), .data0 (in_0[21]), .data1 (in_1[21]),
       .sel1 (ctl[1]), .data2 (in_2[21]), .data3 (in_3[21]), .z
       (z[21]));
  CDN_bmux4 g4(.sel0 (ctl[0]), .data0 (in_0[20]), .data1 (in_1[20]),
       .sel1 (ctl[1]), .data2 (in_2[20]), .data3 (in_3[20]), .z
       (z[20]));
  CDN_bmux4 g5(.sel0 (ctl[0]), .data0 (in_0[19]), .data1 (in_1[19]),
       .sel1 (ctl[1]), .data2 (in_2[19]), .data3 (in_3[19]), .z
       (z[19]));
  CDN_bmux4 g6(.sel0 (ctl[0]), .data0 (in_0[18]), .data1 (in_1[18]),
       .sel1 (ctl[1]), .data2 (in_2[18]), .data3 (in_3[18]), .z
       (z[18]));
  CDN_bmux4 g7(.sel0 (ctl[0]), .data0 (in_0[17]), .data1 (in_1[17]),
       .sel1 (ctl[1]), .data2 (in_2[17]), .data3 (in_3[17]), .z
       (z[17]));
  CDN_bmux4 g8(.sel0 (ctl[0]), .data0 (in_0[16]), .data1 (in_1[16]),
       .sel1 (ctl[1]), .data2 (in_2[16]), .data3 (in_3[16]), .z
       (z[16]));
  CDN_bmux4 g9(.sel0 (ctl[0]), .data0 (in_0[15]), .data1 (in_1[15]),
       .sel1 (ctl[1]), .data2 (in_2[15]), .data3 (in_3[15]), .z
       (z[15]));
  CDN_bmux4 g10(.sel0 (ctl[0]), .data0 (in_0[14]), .data1 (in_1[14]),
       .sel1 (ctl[1]), .data2 (in_2[14]), .data3 (in_3[14]), .z
       (z[14]));
  CDN_bmux4 g11(.sel0 (ctl[0]), .data0 (in_0[13]), .data1 (in_1[13]),
       .sel1 (ctl[1]), .data2 (in_2[13]), .data3 (in_3[13]), .z
       (z[13]));
  CDN_bmux4 g12(.sel0 (ctl[0]), .data0 (in_0[12]), .data1 (in_1[12]),
       .sel1 (ctl[1]), .data2 (in_2[12]), .data3 (in_3[12]), .z
       (z[12]));
  CDN_bmux4 g13(.sel0 (ctl[0]), .data0 (in_0[11]), .data1 (in_1[11]),
       .sel1 (ctl[1]), .data2 (in_2[11]), .data3 (in_3[11]), .z
       (z[11]));
  CDN_bmux4 g14(.sel0 (ctl[0]), .data0 (in_0[10]), .data1 (in_1[10]),
       .sel1 (ctl[1]), .data2 (in_2[10]), .data3 (in_3[10]), .z
       (z[10]));
  CDN_bmux4 g15(.sel0 (ctl[0]), .data0 (in_0[9]), .data1 (in_1[9]),
       .sel1 (ctl[1]), .data2 (in_2[9]), .data3 (in_3[9]), .z (z[9]));
  CDN_bmux4 g16(.sel0 (ctl[0]), .data0 (in_0[8]), .data1 (in_1[8]),
       .sel1 (ctl[1]), .data2 (in_2[8]), .data3 (in_3[8]), .z (z[8]));
  CDN_bmux4 g17(.sel0 (ctl[0]), .data0 (in_0[7]), .data1 (in_1[7]),
       .sel1 (ctl[1]), .data2 (in_2[7]), .data3 (in_3[7]), .z (z[7]));
  CDN_bmux4 g18(.sel0 (ctl[0]), .data0 (in_0[6]), .data1 (in_1[6]),
       .sel1 (ctl[1]), .data2 (in_2[6]), .data3 (in_3[6]), .z (z[6]));
  CDN_bmux4 g19(.sel0 (ctl[0]), .data0 (in_0[5]), .data1 (in_1[5]),
       .sel1 (ctl[1]), .data2 (in_2[5]), .data3 (in_3[5]), .z (z[5]));
  CDN_bmux4 g20(.sel0 (ctl[0]), .data0 (in_0[4]), .data1 (in_1[4]),
       .sel1 (ctl[1]), .data2 (in_2[4]), .data3 (in_3[4]), .z (z[4]));
  CDN_bmux4 g21(.sel0 (ctl[0]), .data0 (in_0[3]), .data1 (in_1[3]),
       .sel1 (ctl[1]), .data2 (in_2[3]), .data3 (in_3[3]), .z (z[3]));
  CDN_bmux4 g22(.sel0 (ctl[0]), .data0 (in_0[2]), .data1 (in_1[2]),
       .sel1 (ctl[1]), .data2 (in_2[2]), .data3 (in_3[2]), .z (z[2]));
  CDN_bmux4 g23(.sel0 (ctl[0]), .data0 (in_0[1]), .data1 (in_1[1]),
       .sel1 (ctl[1]), .data2 (in_2[1]), .data3 (in_3[1]), .z (z[1]));
  CDN_bmux4 g24(.sel0 (ctl[0]), .data0 (in_0[0]), .data1 (in_1[0]),
       .sel1 (ctl[1]), .data2 (in_2[0]), .data3 (in_3[0]), .z (z[0]));
endmodule

module Mux_4_to_1_SIZE_DATA24(i_sel, i_data_00, i_data_01, i_data_10,
     i_data_11, o_data);
  input [1:0] i_sel;
  input [23:0] i_data_00, i_data_01, i_data_10, i_data_11;
  output [23:0] o_data;
  wire [1:0] i_sel;
  wire [23:0] i_data_00, i_data_01, i_data_10, i_data_11;
  wire [23:0] o_data;
  bmux_33 mux_w_o_data_254_11(.ctl (i_sel), .in_0 (i_data_00), .in_1
       (i_data_01), .in_2 (i_data_10), .in_3 (i_data_11), .z (o_data));
endmodule

module FPU_unit(i_add_sub, i_32_a, i_32_b, o_32_s, o_ov_flag,
     o_un_flag);
  input [0:0] i_add_sub;
  input [31:0] i_32_a, i_32_b;
  output [31:0] o_32_s;
  output o_ov_flag, o_un_flag;
  wire [0:0] i_add_sub;
  wire [31:0] i_32_a, i_32_b;
  wire [31:0] o_32_s;
  wire o_ov_flag, o_un_flag;
  wire [7:0] w_EXPSWAP_min;
  wire [7:0] w_EXPSWAP_max;
  wire [7:0] w_EXPSUB_diff_value;
  wire [23:0] w_MAN_SWAP1_max;
  wire [23:0] w_MAN_SWAP1_min;
  wire [27:0] w_MAN_SHF_RIGHT_min;
  wire [27:0] w_MAN_PRE_SWAP_BY_MAN_max;
  wire [27:0] w_MAN_PRE_SWAP_BY_MAN_min;
  wire [27:0] w_MAN_ALU_man;
  wire [4:0] w_LOPD_24BIT_one_position;
  wire [7:0] w_EXP_ADJUST_result;
  wire [27:0] w_NORMALIZATION_man;
  wire [23:0] w_ROUNDING_man;
  wire [7:0] w_EXP_ROUNDING;
  wire [1:0] PSC_o_sel_man;
  wire [23:0] w_mantissa_result;
  wire PSC_o_sel_exp, n_71, w_EXPSWAP_compare, w_LOPD_24BIT_zero_flag,
       \w_MAN_ALU_man[0]_72 , \w_MAN_ALU_man[1]_73 ,
       \w_MAN_ALU_man[2]_74 , \w_MAN_ALU_man[3]_75 ;
  wire w_MAN_ALU_overflow, w_MAN_COMP_28BIT_less, w_ROUNDING_ov_flow;
  EXP_swap_SIZE_DATA8 EXP_SWAP_UNIT(.i_data_a (i_32_a[30:23]),
       .i_data_b (i_32_b[30:23]), .o_compare (w_EXPSWAP_compare),
       .o_less_data (w_EXPSWAP_min), .o_greater_data (w_EXPSWAP_max));
  EXP_sub_SIZE_EXP_SUB8 EXP_SUB_UNIT(.i_data_a (w_EXPSWAP_max),
       .i_data_b (w_EXPSWAP_min), .o_sub (w_EXPSUB_diff_value));
  MAN_swap_SIZE_MAN24 MAN_PRE_SWAP_BY_EXPONENT_UNIT(.i_man_a ({1'b1,
       i_32_a[22:0]}), .i_man_b ({1'b1, i_32_b[22:0]}), .i_compare
       (w_EXPSWAP_compare), .o_man_max (w_MAN_SWAP1_max), .o_man_min
       (w_MAN_SWAP1_min));
  SHF_right_28bit_SIZE_DATA28_SIZE_SHIFT5
       SHF_RIGHT_28BIT_UNIT(.i_shift_number (w_EXPSUB_diff_value[4:0]),
       .i_data ({w_MAN_SWAP1_min, 4'b0}), .o_data
       (w_MAN_SHF_RIGHT_min));
  COMP_28bit_SIZE_DATA28 MAN_COMP_28BIT_UNIT(.i_data_a
       ({w_MAN_SWAP1_max, 4'b0}), .i_data_b (w_MAN_SHF_RIGHT_min),
       .o_less (w_MAN_COMP_28BIT_less));
  MAN_swap_SIZE_MAN28 MAN_PRE_SWAP_BY_MAN_UNIT(.i_man_a
       ({w_MAN_SWAP1_max, 4'b0}), .i_man_b (w_MAN_SHF_RIGHT_min),
       .i_compare (w_MAN_COMP_28BIT_less), .o_man_max
       (w_MAN_PRE_SWAP_BY_MAN_max), .o_man_min
       (w_MAN_PRE_SWAP_BY_MAN_min));
  SIGN_unit SIGN_OUT(.i_add_sub (i_add_sub), .i_comp_man (n_71),
       .i_sign_man_a (i_32_a[31]), .i_sign_man_b (i_32_b[31]),
       .o_sign_s (o_32_s[31]));
  MAN_ALU_NUM_OP1_SIZE_MAN28 MAN_ALU_UNIT(.i_fpu_op (i_add_sub),
       .i_sign_a (i_32_a[31]), .i_sign_b (i_32_b[31]), .i_man_max
       (w_MAN_PRE_SWAP_BY_MAN_max), .i_man_min
       (w_MAN_PRE_SWAP_BY_MAN_min), .o_man_alu ({w_MAN_ALU_man[23:0],
       \w_MAN_ALU_man[3]_75 , \w_MAN_ALU_man[2]_74 ,
       \w_MAN_ALU_man[1]_73 , \w_MAN_ALU_man[0]_72 }), .o_overflow
       (w_MAN_ALU_overflow));
  LOPD_24bit_SIZE_DATA24_SIZE_LOPD5 LOPD_24BIT_UNIT(.i_data
       (w_MAN_ALU_man[23:0]), .o_one_position
       (w_LOPD_24BIT_one_position), .o_zero_flag
       (w_LOPD_24BIT_zero_flag));
  EXP_adjust_SIZE_EXP8_SIZE_LOPD8 EXP_ADJUST_UNIT(.i_overflow
       (w_MAN_ALU_overflow), .i_underflow (w_MAN_ALU_man[23]),
       .i_zero_flag (w_LOPD_24BIT_zero_flag), .i_lopd_value ({3'b0,
       w_LOPD_24BIT_one_position}), .i_exp_value (w_EXPSWAP_max),
       .o_exp_result (w_EXP_ADJUST_result));
  NORMALIZATION_unit_SIZE_LOPD5_SIZE_DATA28
       NORMALIZATION_UNIT(.i_overflow (w_MAN_ALU_overflow),
       .i_zero_flag (w_LOPD_24BIT_zero_flag), .i_one_position
       (w_LOPD_24BIT_one_position), .i_mantissa ({w_MAN_ALU_man[23:0],
       \w_MAN_ALU_man[3]_75 , \w_MAN_ALU_man[2]_74 ,
       \w_MAN_ALU_man[1]_73 , \w_MAN_ALU_man[0]_72 }), .o_mantissa
       (w_NORMALIZATION_man));
  ROUNDING_unit_SIZE_MAN28_SIZE_MAN_RESULT24 ROUNDING_UNIT(.i_man
       (w_NORMALIZATION_man), .o_man_result (w_ROUNDING_man),
       .o_ov_flow (w_ROUNDING_ov_flow));
  EXP_rounding_SIZE_DATA8 EXP_ROUNDING(.i_carry_rounding
       (w_ROUNDING_ov_flow), .i_exp_result (w_EXP_ADJUST_result),
       .o_exp_result (w_EXP_ROUNDING));
  PSC_unit PSC_UNIT(.i_add_sub (i_add_sub), .i_sign_a (i_32_a[31]),
       .i_exp_a (i_32_a[30:23]), .i_man_a ({1'b1, i_32_a[22:0]}),
       .i_sign_b (i_32_b[31]), .i_exp_b (i_32_b[30:23]), .i_man_b
       ({1'b1, i_32_b[22:0]}), .o_sel_exp (PSC_o_sel_exp), .o_sel_man
       (PSC_o_sel_man));
  Mux_4_to_1_SIZE_DATA24 SEL_MANTISSA_FOR_RESULT(.i_sel
       (PSC_o_sel_man), .i_data_00 (w_ROUNDING_man), .i_data_01
       (w_ROUNDING_man), .i_data_10 (24'b0), .i_data_11
       (24'b110000000000000000000000), .o_data ({w_mantissa_result[23],
       o_32_s[22:0]}));
  bmux mux_222_28(.ctl (PSC_o_sel_exp), .in_0 (w_EXP_ROUNDING), .in_1
       (8'b11111111), .z (o_32_s[30:23]));
  or g1 (n_71, w_MAN_COMP_28BIT_less, w_EXPSWAP_compare);
  or g2 (o_ov_flag, w_MAN_ALU_overflow, w_ROUNDING_ov_flow);
  not g3 (o_un_flag, w_MAN_ALU_man[23]);
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  reg  z;
  always 
    @(sel0 or data0 or data1) 
      case ({sel0})
       1'b0: z = data0;
       1'b1: z = data1;
      endcase
endmodule
`else
module CDN_bmux2(sel0, data0, data1, z);
  input sel0, data0, data1;
  output z;
  wire sel0, data0, data1;
  wire z;
  wire inv_sel0, w_0, w_1;
  not i_0 (inv_sel0, sel0);
  and a_0 (w_0, inv_sel0, data0);
  and a_1 (w_1, sel0, data1);
  or org (z, w_0, w_1);
endmodule
`endif // ONE_HOT_MUX
`endif
`ifdef RC_CDN_GENERIC_GATE
`else
`ifdef ONE_HOT_MUX
module CDN_bmux4(sel0, data0, data1, sel1, data2, data3, z);
  input sel0, data0, data1, sel1, data2, data3;
  output z;
  wire sel0, data0, data1, sel1, data2, data3;
  reg  z;
  always 
    @(sel0 or sel1 or data0 or data1 or data2 or data3) 
      case ({sel0, sel1})
       2'b00: z = data0;
       2'b10: z = data1;
       2'b01: z = data2;
       2'b11: z = data3;
      endcase
endmodule
`else
module CDN_bmux4(sel0, data0, data1, sel1, data2, data3, z);
  input sel0, data0, data1, sel1, data2, data3;
  output z;
  wire sel0, data0, data1, sel1, data2, data3;
  wire z;
  wire inv_sel0, inv_sel1, w_0, w_1, w_2, w_3;
  not i_0 (inv_sel0, sel0);
  not i_1 (inv_sel1, sel1);
  and a_0 (w_0, inv_sel1, inv_sel0, data0);
  and a_1 (w_1, inv_sel1, sel0, data1);
  and a_2 (w_2, sel1, inv_sel0, data2);
  and a_3 (w_3, sel1, sel0, data3);
  or org (z, w_0, w_1, w_2, w_3);
endmodule
`endif // ONE_HOT_MUX
`endif
