
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: Nov 27 2025 02:54:43

// Verification Directory fv/FPU_unit 

module CLA_4bit_8(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_13, n_15;
  OAI21X1HVT g471(.A0 (n_6), .A1 (n_15), .B0 (n_1), .Y (o_g));
  XOR2XLHVT g472(.A (n_6), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g473(.A0 (n_7), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  XOR2XLHVT g474(.A (n_7), .B (n_13), .Y (sum[2]));
  OAI21X1HVT g475(.A0 (n_5), .A1 (n_10), .B0 (n_4), .Y (n_13));
  XNOR2X1HVT g476(.A (n_9), .B (n_10), .Y (sum[1]));
  XNOR2X1HVT g478(.A (cin), .B (n_8), .Y (sum[0]));
  AOI21X1HVT g479(.A0 (cin), .A1 (n_3), .B0 (n_2), .Y (n_10));
  NOR2BX1HVT g481(.AN (n_4), .B (n_5), .Y (n_9));
  NAND2BX1HVT g482(.AN (n_2), .B (n_3), .Y (n_8));
  XOR2XLHVT g483(.A (a[2]), .B (b[2]), .Y (n_7));
  XNOR2X1HVT g484(.A (a[3]), .B (b[3]), .Y (n_6));
  NOR2X1HVT g485(.A (a[1]), .B (b[1]), .Y (n_5));
  NAND2X1HVT g486(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2XLHVT g487(.A (a[3]), .B (b[3]), .Y (n_1));
  OR2X1HVT g488(.A (a[0]), .B (b[0]), .Y (n_3));
  AND2XLHVT g489(.A (a[0]), .B (b[0]), .Y (n_2));
  NOR4BBX1HVT g2(.AN (n_9), .BN (n_7), .C (n_6), .D (n_8), .Y (o_p));
endmodule

module CLA_4bit_9(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_8, n_10;
  wire n_11, n_12;
  assign o_g = 1'b0;
  assign o_p = 1'b0;
  XNOR2X1HVT g217(.A (n_5), .B (n_12), .Y (sum[3]));
  XNOR2X1HVT g218(.A (n_4), .B (n_11), .Y (sum[2]));
  OAI2BB1X1HVT g219(.A0N (n_4), .A1N (n_10), .B0 (n_6), .Y (n_12));
  AOI21X1HVT g220(.A0 (a[1]), .A1 (b[1]), .B0 (n_10), .Y (n_11));
  ADDHX1HVT g221(.A (n_2), .B (n_8), .CO (n_10), .S (sum[1]));
  AO22XLHVT g222(.A0 (n_3), .A1 (cin), .B0 (a[0]), .B1 (b[0]), .Y
       (n_8));
  XOR2XLHVT g223(.A (n_3), .B (cin), .Y (sum[0]));
  OAI21XLHVT g224(.A0 (a[1]), .A1 (a[2]), .B0 (b[1]), .Y (n_6));
  XNOR2X1HVT g225(.A (a[3]), .B (b[1]), .Y (n_5));
  MXI2XLHVT g226(.A (n_1), .B (b[1]), .S0 (a[2]), .Y (n_4));
  MXI2XLHVT g227(.A (n_1), .B (b[1]), .S0 (a[1]), .Y (n_2));
  XOR2XLHVT g228(.A (a[0]), .B (b[0]), .Y (n_3));
  INVX1HVT g229(.A (b[1]), .Y (n_1));
endmodule

module CLA_8bit_1(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire w_C, w_G, w_G_22, w_P, w_P_20;
  assign o_carry = 1'b0;
  CLA_4bit_8 CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]),
       .cin (i_data_b[5]), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
  CLA_4bit_9 CLA_4BIT_UNIT_1(.a (i_data_a[7:4]), .b ({2'b00,
       i_data_b[5:4]}), .cin (w_C), .sum (o_sum[7:4]), .o_p (w_P_20),
       .o_g (w_G_22));
  AO21XLHVT g20(.A0 (i_data_b[5]), .A1 (w_P), .B0 (w_G), .Y (w_C));
endmodule

module EXP_adjust_SIZE_EXP8_SIZE_LOPD8(i_overflow, i_underflow,
     i_zero_flag, i_lopd_value, i_exp_value, o_exp_result);
  input i_overflow, i_underflow, i_zero_flag;
  input [7:0] i_lopd_value, i_exp_value;
  output [7:0] o_exp_result;
  wire i_overflow, i_underflow, i_zero_flag;
  wire [7:0] i_lopd_value, i_exp_value;
  wire [7:0] o_exp_result;
  wire [7:0] w_data_b;
  wire [7:0] w_exp_result;
  wire UNCONNECTED, n_0, w_i_carry;
  CLA_8bit_1 CLA_8BIT_UNIT(.i_carry (1'b0), .i_data_a (i_exp_value),
       .i_data_b ({2'b00, w_i_carry, w_data_b[4:0]}), .o_sum
       (w_exp_result), .o_carry (UNCONNECTED));
  NOR2BX1HVT g150(.AN (w_i_carry), .B (i_lopd_value[4]), .Y
       (w_data_b[4]));
  NOR2BX1HVT g151(.AN (w_i_carry), .B (i_lopd_value[2]), .Y
       (w_data_b[2]));
  NOR2BX1HVT g152(.AN (w_i_carry), .B (i_lopd_value[1]), .Y
       (w_data_b[1]));
  NOR2BX1HVT g153(.AN (w_i_carry), .B (i_lopd_value[3]), .Y
       (w_data_b[3]));
  OAI21X1HVT g154(.A0 (i_underflow), .A1 (i_lopd_value[0]), .B0 (n_0),
       .Y (w_data_b[0]));
  NOR2X1HVT g155(.A (i_underflow), .B (i_overflow), .Y (w_i_carry));
  INVX1HVT g156(.A (i_overflow), .Y (n_0));
  NOR2BX1HVT g157(.AN (w_exp_result[4]), .B (i_zero_flag), .Y
       (o_exp_result[4]));
  NOR2BX1HVT g158(.AN (w_exp_result[6]), .B (i_zero_flag), .Y
       (o_exp_result[6]));
  NOR2BX1HVT g159(.AN (w_exp_result[7]), .B (i_zero_flag), .Y
       (o_exp_result[7]));
  NOR2BX1HVT g160(.AN (w_exp_result[0]), .B (i_zero_flag), .Y
       (o_exp_result[0]));
  NOR2BX1HVT g161(.AN (w_exp_result[2]), .B (i_zero_flag), .Y
       (o_exp_result[2]));
  NOR2BX1HVT g162(.AN (w_exp_result[5]), .B (i_zero_flag), .Y
       (o_exp_result[5]));
  NOR2BX1HVT g163(.AN (w_exp_result[3]), .B (i_zero_flag), .Y
       (o_exp_result[3]));
  NOR2BX1HVT g164(.AN (w_exp_result[1]), .B (i_zero_flag), .Y
       (o_exp_result[1]));
endmodule

module COMP_4bit_1(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12;
  OAI21X1HVT g326(.A0 (i_data_a[3]), .A1 (n_11), .B0 (n_12), .Y
       (o_less));
  OAI2BB1X1HVT g327(.A0N (i_data_a[3]), .A1N (n_11), .B0 (i_data_b[3]),
       .Y (n_12));
  AOI22X1HVT g328(.A0 (n_3), .A1 (n_10), .B0 (i_data_b[2]), .B1 (n_2),
       .Y (n_11));
  OAI32X1HVT g329(.A0 (n_1), .A1 (i_data_a[0]), .A2 (n_7), .B0 (n_0),
       .B1 (i_data_a[1]), .Y (n_10));
  AND4XLHVT g330(.A (n_6), .B (n_8), .C (n_4), .D (n_5), .Y (o_equal));
  ADDHX1HVT g331(.A (i_data_a[1]), .B (n_0), .CO (n_7), .S (n_8));
  MX2XLHVT g332(.A (n_1), .B (i_data_b[0]), .S0 (i_data_a[0]), .Y
       (n_6));
  XNOR2X1HVT g333(.A (i_data_b[3]), .B (i_data_a[3]), .Y (n_5));
  MX2XLHVT g334(.A (n_2), .B (i_data_a[2]), .S0 (i_data_b[2]), .Y
       (n_4));
  OR2XLHVT g335(.A (i_data_b[2]), .B (n_2), .Y (n_3));
  INVX1HVT g336(.A (i_data_a[2]), .Y (n_2));
  INVX1HVT g337(.A (i_data_b[0]), .Y (n_1));
  INVX1HVT g338(.A (i_data_b[1]), .Y (n_0));
endmodule

module COMP_4bit(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  assign o_equal = 1'b0;
  OAI22X1HVT g253(.A0 (n_4), .A1 (n_8), .B0 (n_2), .B1 (i_data_a[3]),
       .Y (o_less));
  AOI22X1HVT g254(.A0 (n_5), .A1 (n_7), .B0 (i_data_b[2]), .B1 (n_0),
       .Y (n_8));
  OAI32X1HVT g255(.A0 (n_3), .A1 (i_data_a[0]), .A2 (n_6), .B0 (n_1),
       .B1 (i_data_a[1]), .Y (n_7));
  AND2XLHVT g256(.A (i_data_a[1]), .B (n_1), .Y (n_6));
  OR2XLHVT g257(.A (i_data_b[2]), .B (n_0), .Y (n_5));
  AND2XLHVT g258(.A (i_data_a[3]), .B (n_2), .Y (n_4));
  INVX1HVT g259(.A (i_data_b[0]), .Y (n_3));
  INVX1HVT g260(.A (i_data_b[3]), .Y (n_2));
  INVX1HVT g261(.A (i_data_b[1]), .Y (n_1));
  INVX1HVT g262(.A (i_data_a[2]), .Y (n_0));
endmodule

module COMP_8bit_SIZE_DATA8(i_data_a, i_data_b, o_less);
  input [7:0] i_data_a, i_data_b;
  output o_less;
  wire [7:0] i_data_a, i_data_b;
  wire o_less;
  wire w_equal_high, w_equal_low, w_less_high, w_less_low;
  COMP_4bit_1 u_high(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_high), .o_equal (w_equal_high));
  COMP_4bit u_low(.i_data_a (i_data_a[3:0]), .i_data_b (i_data_b[3:0]),
       .o_less (w_less_low), .o_equal (w_equal_low));
  AO21X2HVT g16(.A0 (w_equal_high), .A1 (w_less_low), .B0
       (w_less_high), .Y (o_less));
endmodule

module EXP_comp_SIZE_DATA8(i_data_a, i_data_b, o_compare);
  input [7:0] i_data_a, i_data_b;
  output o_compare;
  wire [7:0] i_data_a, i_data_b;
  wire o_compare;
  COMP_8bit_SIZE_DATA8 COMP_LESS_UNIT(.i_data_a (i_data_a), .i_data_b
       (i_data_b), .o_less (o_compare));
endmodule

module EXP_rounding_SIZE_DATA8(i_carry_rounding, i_exp_result,
     o_exp_result);
  input i_carry_rounding;
  input [7:0] i_exp_result;
  output [7:0] o_exp_result;
  wire i_carry_rounding;
  wire [7:0] i_exp_result;
  wire [7:0] o_exp_result;
  wire n_0, n_2, n_4, n_6, n_8, n_10, n_12;
  XNOR2X1HVT g173(.A (i_exp_result[7]), .B (n_12), .Y
       (o_exp_result[7]));
  XNOR2X1HVT g174(.A (i_exp_result[6]), .B (n_10), .Y
       (o_exp_result[6]));
  NAND2BXLHVT g175(.AN (n_10), .B (i_exp_result[6]), .Y (n_12));
  XNOR2X1HVT g176(.A (i_exp_result[5]), .B (n_8), .Y (o_exp_result[5]));
  NAND2BX1HVT g177(.AN (n_8), .B (i_exp_result[5]), .Y (n_10));
  XNOR2X1HVT g178(.A (i_exp_result[4]), .B (n_6), .Y (o_exp_result[4]));
  NAND2BX1HVT g179(.AN (n_6), .B (i_exp_result[4]), .Y (n_8));
  XNOR2X1HVT g180(.A (i_exp_result[3]), .B (n_4), .Y (o_exp_result[3]));
  NAND2BX1HVT g181(.AN (n_4), .B (i_exp_result[3]), .Y (n_6));
  XNOR2X1HVT g182(.A (i_exp_result[2]), .B (n_2), .Y (o_exp_result[2]));
  NAND2BX1HVT g183(.AN (n_2), .B (i_exp_result[2]), .Y (n_4));
  XNOR2X1HVT g184(.A (i_exp_result[1]), .B (n_0), .Y (o_exp_result[1]));
  NAND2BX1HVT g185(.AN (n_0), .B (i_exp_result[1]), .Y (n_2));
  XOR2XLHVT g186(.A (i_exp_result[0]), .B (i_carry_rounding), .Y
       (o_exp_result[0]));
  NAND2X1HVT g187(.A (i_exp_result[0]), .B (i_carry_rounding), .Y
       (n_0));
endmodule

module CLA_4bit(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_10, n_12, n_13, n_16;
  XNOR2X1HVT g263(.A (n_2), .B (n_16), .Y (sum[3]));
  AOI21X1HVT g264(.A0 (n_6), .A1 (n_12), .B0 (n_5), .Y (n_16));
  NAND2BX1HVT g265(.AN (o_p), .B (n_13), .Y (o_g));
  CLKXOR2X1HVT g266(.A (n_6), .B (n_12), .Y (sum[2]));
  AOI222X1HVT g267(.A0 (a[3]), .A1 (b[3]), .B0 (n_10), .B1 (n_8), .C0
       (n_5), .C1 (n_2), .Y (n_13));
  OAI21X1HVT g268(.A0 (n_7), .A1 (n_4), .B0 (n_0), .Y (n_12));
  NOR3BX1HVT g269(.AN (n_8), .B (n_7), .C (sum[0]), .Y (o_p));
  OAI2BB1X1HVT g270(.A0N (b[0]), .A1N (n_1), .B0 (n_0), .Y (n_10));
  XNOR2X1HVT g271(.A (n_1), .B (n_4), .Y (sum[1]));
  AND2XLHVT g272(.A (n_6), .B (n_2), .Y (n_8));
  INVX1HVT g273(.A (n_1), .Y (n_7));
  ADDHX1HVT g274(.A (a[2]), .B (b[2]), .CO (n_5), .S (n_6));
  NOR2BX1HVT g275(.AN (sum[0]), .B (b[0]), .Y (n_4));
  XNOR2X1HVT g276(.A (a[0]), .B (b[0]), .Y (sum[0]));
  XOR2XLHVT g277(.A (a[3]), .B (b[3]), .Y (n_2));
  XOR2XLHVT g278(.A (a[1]), .B (b[1]), .Y (n_1));
  NAND2X1HVT g279(.A (a[1]), .B (b[1]), .Y (n_0));
endmodule

module CLA_4bit_1(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1;
  assign o_g = 1'b0;
  assign o_p = 1'b0;
  assign sum[1] = 1'b0;
  assign sum[2] = 1'b0;
  assign sum[3] = 1'b0;
  XNOR2X1HVT g68(.A (n_1), .B (cin), .Y (sum[0]));
  XNOR2X1HVT g69(.A (a[0]), .B (b[0]), .Y (n_1));
endmodule

module CLA_8bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sum;
  wire o_carry;
  wire n_6, n_7, n_9, w_C, w_G, w_G_22, w_P, w_P_20;
  assign o_carry = 1'b0;
  assign o_sum[5] = 1'b0;
  assign o_sum[6] = 1'b0;
  assign o_sum[7] = 1'b0;
  CLA_4bit CLA_4BIT_UNIT_0(.a (i_data_a[3:0]), .b (i_data_b[3:0]), .cin
       (1'b1), .sum (o_sum[3:0]), .o_p (w_P), .o_g (w_G));
  CLA_4bit_1 CLA_4BIT_UNIT_1(.a ({3'b000, i_data_a[4]}), .b ({3'b000,
       i_data_b[4]}), .cin (w_C), .sum ({n_6, n_7, n_9, o_sum[4]}),
       .o_p (w_P_20), .o_g (w_G_22));
  OR2XLHVT g7(.A (w_P), .B (w_G), .Y (w_C));
endmodule

module EXP_sub_SIZE_EXP_SUB8(i_data_a, i_data_b, o_sub);
  input [7:0] i_data_a, i_data_b;
  output [7:0] o_sub;
  wire [7:0] i_data_a, i_data_b;
  wire [7:0] o_sub;
  wire UNCONNECTED0, n_0, n_1, n_2, n_3, n_4, n_13, n_14;
  wire n_15;
  assign o_sub[5] = 1'b0;
  assign o_sub[6] = 1'b0;
  assign o_sub[7] = 1'b0;
  CLA_8bit CLA_8BIT_UNIT(.i_carry (1'b1), .i_data_a ({3'b000,
       i_data_a[4:0]}), .i_data_b ({3'b000, n_1, n_4, n_3, n_0, n_2}),
       .o_sum ({n_13, n_14, n_15, o_sub[4:0]}), .o_carry
       (UNCONNECTED0));
  INVX1HVT g11(.A (i_data_b[3]), .Y (n_4));
  INVX1HVT g12(.A (i_data_b[2]), .Y (n_3));
  INVX1HVT g13(.A (i_data_b[0]), .Y (n_2));
  INVX1HVT g9(.A (i_data_b[4]), .Y (n_1));
  INVX1HVT g10(.A (i_data_b[1]), .Y (n_0));
endmodule

module EXP_swap_SIZE_DATA8(i_data_a, i_data_b, i_compare, o_less_data,
     o_greater_data);
  input [7:0] i_data_a, i_data_b;
  input i_compare;
  output [7:0] o_less_data, o_greater_data;
  wire [7:0] i_data_a, i_data_b;
  wire i_compare;
  wire [7:0] o_less_data, o_greater_data;
  assign o_less_data[5] = 1'b0;
  assign o_less_data[6] = 1'b0;
  assign o_less_data[7] = 1'b0;
  MX2XLHVT g217(.A (i_data_b[4]), .B (i_data_a[4]), .S0 (i_compare), .Y
       (o_less_data[4]));
  MX2XLHVT g218(.A (i_data_b[3]), .B (i_data_a[3]), .S0 (i_compare), .Y
       (o_less_data[3]));
  MX2XLHVT g219(.A (i_data_b[1]), .B (i_data_a[1]), .S0 (i_compare), .Y
       (o_less_data[1]));
  MX2XLHVT g220(.A (i_data_a[6]), .B (i_data_b[6]), .S0 (i_compare), .Y
       (o_greater_data[6]));
  MX2X1HVT g221(.A (i_data_a[5]), .B (i_data_b[5]), .S0 (i_compare), .Y
       (o_greater_data[5]));
  MX2XLHVT g222(.A (i_data_b[0]), .B (i_data_a[0]), .S0 (i_compare), .Y
       (o_less_data[0]));
  MX2XLHVT g223(.A (i_data_a[7]), .B (i_data_b[7]), .S0 (i_compare), .Y
       (o_greater_data[7]));
  MX2X1HVT g224(.A (i_data_a[3]), .B (i_data_b[3]), .S0 (i_compare), .Y
       (o_greater_data[3]));
  MX2XLHVT g225(.A (i_data_b[2]), .B (i_data_a[2]), .S0 (i_compare), .Y
       (o_less_data[2]));
  MX2X1HVT g226(.A (i_data_a[2]), .B (i_data_b[2]), .S0 (i_compare), .Y
       (o_greater_data[2]));
  MX2X1HVT g227(.A (i_data_a[1]), .B (i_data_b[1]), .S0 (i_compare), .Y
       (o_greater_data[1]));
  MX2XLHVT g228(.A (i_data_a[0]), .B (i_data_b[0]), .S0 (i_compare), .Y
       (o_greater_data[0]));
  MX2XLHVT g229(.A (i_data_a[4]), .B (i_data_b[4]), .S0 (i_compare), .Y
       (o_greater_data[4]));
endmodule

module LOPD_8bit(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_12;
  AOI2BB1XLHVT g263(.A0N (n_12), .A1N (i_data[6]), .B0 (i_data[7]), .Y
       (o_pos_one[0]));
  AOI2BB1XLHVT g264(.A0N (n_7), .A1N (i_data[4]), .B0 (i_data[5]), .Y
       (n_12));
  AOI21X1HVT g265(.A0 (n_5), .A1 (n_1), .B0 (n_0), .Y (o_pos_one[1]));
  NOR2X1HVT g266(.A (n_8), .B (n_0), .Y (o_pos_one[2]));
  NOR3BX1HVT g267(.AN (n_1), .B (n_6), .C (n_0), .Y (o_zero_flag));
  NAND2X1HVT g268(.A (n_6), .B (n_1), .Y (n_8));
  AOI2BB1XLHVT g269(.A0N (n_3), .A1N (i_data[2]), .B0 (i_data[3]), .Y
       (n_7));
  NAND2X1HVT g270(.A (n_2), .B (n_4), .Y (n_6));
  NAND2BX1HVT g271(.AN (n_2), .B (n_4), .Y (n_5));
  NOR2BX1HVT g272(.AN (i_data[0]), .B (i_data[1]), .Y (n_3));
  NOR2X1HVT g273(.A (i_data[2]), .B (i_data[3]), .Y (n_4));
  NOR2X1HVT g274(.A (i_data[0]), .B (i_data[1]), .Y (n_2));
  NOR2X1HVT g275(.A (i_data[4]), .B (i_data[5]), .Y (n_1));
  OR2X1HVT g276(.A (i_data[6]), .B (i_data[7]), .Y (n_0));
endmodule

module LOPD_8bit_1(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_12;
  AOI2BB1XLHVT g263(.A0N (n_12), .A1N (i_data[6]), .B0 (i_data[7]), .Y
       (o_pos_one[0]));
  AOI2BB1XLHVT g264(.A0N (n_7), .A1N (i_data[4]), .B0 (i_data[5]), .Y
       (n_12));
  AOI21X1HVT g265(.A0 (n_5), .A1 (n_1), .B0 (n_0), .Y (o_pos_one[1]));
  NOR2X1HVT g266(.A (n_8), .B (n_0), .Y (o_pos_one[2]));
  NOR3BX1HVT g267(.AN (n_1), .B (n_6), .C (n_0), .Y (o_zero_flag));
  NAND2X1HVT g268(.A (n_6), .B (n_1), .Y (n_8));
  AOI2BB1XLHVT g269(.A0N (n_3), .A1N (i_data[2]), .B0 (i_data[3]), .Y
       (n_7));
  NAND2X1HVT g270(.A (n_2), .B (n_4), .Y (n_6));
  NAND2BX1HVT g271(.AN (n_2), .B (n_4), .Y (n_5));
  NOR2BX1HVT g272(.AN (i_data[0]), .B (i_data[1]), .Y (n_3));
  NOR2X1HVT g273(.A (i_data[2]), .B (i_data[3]), .Y (n_4));
  NOR2X1HVT g274(.A (i_data[0]), .B (i_data[1]), .Y (n_2));
  NOR2X1HVT g275(.A (i_data[4]), .B (i_data[5]), .Y (n_1));
  OR2XLHVT g276(.A (i_data[6]), .B (i_data[7]), .Y (n_0));
endmodule

module LOPD_16bit(i_data, o_pos_one, o_zero_flag);
  input [15:0] i_data;
  output [3:0] o_pos_one;
  output o_zero_flag;
  wire [15:0] i_data;
  wire [3:0] o_pos_one;
  wire o_zero_flag;
  wire [2:0] w_pos_one_0;
  wire [2:0] w_pos_one_1;
  wire w_zero_flag_0;
  LOPD_8bit LOPD_8bit_unit_0(.i_data (i_data[7:0]), .o_pos_one
       (w_pos_one_0), .o_zero_flag (w_zero_flag_0));
  LOPD_8bit_1 LOPD_8bit_unit_1(.i_data (i_data[15:8]), .o_pos_one
       (w_pos_one_1), .o_zero_flag (o_pos_one[3]));
  MX2XLHVT g62(.A (w_pos_one_1[2]), .B (w_pos_one_0[2]), .S0
       (o_pos_one[3]), .Y (o_pos_one[2]));
  MX2XLHVT g63(.A (w_pos_one_1[1]), .B (w_pos_one_0[1]), .S0
       (o_pos_one[3]), .Y (o_pos_one[1]));
  MX2XLHVT g64(.A (w_pos_one_1[0]), .B (w_pos_one_0[0]), .S0
       (o_pos_one[3]), .Y (o_pos_one[0]));
  AND2X1HVT g65(.A (o_pos_one[3]), .B (w_zero_flag_0), .Y
       (o_zero_flag));
endmodule

module LOPD_8bit_2(i_data, o_pos_one, o_zero_flag);
  input [7:0] i_data;
  output [2:0] o_pos_one;
  output o_zero_flag;
  wire [7:0] i_data;
  wire [2:0] o_pos_one;
  wire o_zero_flag;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_12;
  AOI2BB1X1HVT g263(.A0N (n_12), .A1N (i_data[6]), .B0 (i_data[7]), .Y
       (o_pos_one[0]));
  AOI2BB1XLHVT g264(.A0N (n_7), .A1N (i_data[4]), .B0 (i_data[5]), .Y
       (n_12));
  AOI21X1HVT g265(.A0 (n_5), .A1 (n_1), .B0 (n_0), .Y (o_pos_one[1]));
  NOR2X1HVT g266(.A (n_8), .B (n_0), .Y (o_pos_one[2]));
  NOR3BX1HVT g267(.AN (n_1), .B (n_6), .C (n_0), .Y (o_zero_flag));
  NAND2X1HVT g268(.A (n_6), .B (n_1), .Y (n_8));
  AOI2BB1XLHVT g269(.A0N (n_3), .A1N (i_data[2]), .B0 (i_data[3]), .Y
       (n_7));
  NAND2X1HVT g270(.A (n_2), .B (n_4), .Y (n_6));
  NAND2BX1HVT g271(.AN (n_2), .B (n_4), .Y (n_5));
  NOR2BX1HVT g272(.AN (i_data[0]), .B (i_data[1]), .Y (n_3));
  NOR2X1HVT g273(.A (i_data[2]), .B (i_data[3]), .Y (n_4));
  NOR2X1HVT g274(.A (i_data[0]), .B (i_data[1]), .Y (n_2));
  NOR2X1HVT g275(.A (i_data[4]), .B (i_data[5]), .Y (n_1));
  OR2X1HVT g276(.A (i_data[6]), .B (i_data[7]), .Y (n_0));
endmodule

module LOPD_24bit_SIZE_DATA24_SIZE_LOPD5(i_data, o_one_position,
     o_zero_flag);
  input [23:0] i_data;
  output [4:0] o_one_position;
  output o_zero_flag;
  wire [23:0] i_data;
  wire [4:0] o_one_position;
  wire o_zero_flag;
  wire [3:0] LOPD16_o_pos_one;
  wire [2:0] LOPD8_o_pos_one;
  wire LOPD8_o_zero_flag, n_0, n_1, n_2, n_3, n_4;
  LOPD_16bit LOPD_16bit_UNIT_MSB(.i_data (i_data[23:8]), .o_pos_one
       (LOPD16_o_pos_one), .o_zero_flag (o_one_position[4]));
  LOPD_8bit_2 LOPD_8bit_UNIT_LSB(.i_data (i_data[7:0]), .o_pos_one
       (LOPD8_o_pos_one), .o_zero_flag (LOPD8_o_zero_flag));
  NAND2X1HVT g124(.A (n_1), .B (n_4), .Y (o_one_position[2]));
  NAND2X1HVT g125(.A (n_1), .B (n_3), .Y (o_one_position[0]));
  NAND2X1HVT g126(.A (n_1), .B (n_2), .Y (o_one_position[1]));
  OAI2BB1X1HVT g127(.A0N (LOPD16_o_pos_one[3]), .A1N (n_0), .B0 (n_1),
       .Y (o_one_position[3]));
  AOI22X1HVT g128(.A0 (n_0), .A1 (LOPD16_o_pos_one[2]), .B0
       (LOPD8_o_pos_one[2]), .B1 (o_one_position[4]), .Y (n_4));
  AOI22X1HVT g129(.A0 (n_0), .A1 (LOPD16_o_pos_one[0]), .B0
       (LOPD8_o_pos_one[0]), .B1 (o_one_position[4]), .Y (n_3));
  AOI22X1HVT g130(.A0 (n_0), .A1 (LOPD16_o_pos_one[1]), .B0
       (LOPD8_o_pos_one[1]), .B1 (o_one_position[4]), .Y (n_2));
  INVX1HVT g131(.A (o_zero_flag), .Y (n_1));
  NOR2BX1HVT g132(.AN (LOPD8_o_zero_flag), .B (n_0), .Y (o_zero_flag));
  INVX1HVT g133(.A (o_one_position[4]), .Y (n_0));
endmodule

module CLA_4bit_2(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9, n_11, n_12, n_14, n_16, n_18;
  XNOR2X1HVT g306(.A (n_2), .B (n_18), .Y (sum[3]));
  AOI21X1HVT g307(.A0 (n_7), .A1 (n_16), .B0 (n_6), .Y (n_18));
  CLKXOR2X1HVT g308(.A (n_7), .B (n_16), .Y (sum[2]));
  OAI21X1HVT g309(.A0 (n_5), .A1 (n_11), .B0 (n_0), .Y (n_16));
  OAI2BB1X1HVT g310(.A0N (cin), .A1N (o_p), .B0 (n_14), .Y (o_g));
  AOI22X1HVT g311(.A0 (n_2), .A1 (n_12), .B0 (a[3]), .B1 (b[3]), .Y
       (n_14));
  CLKXOR2X1HVT g312(.A (n_5), .B (n_11), .Y (sum[1]));
  AO21XLHVT g313(.A0 (n_7), .A1 (n_9), .B0 (n_6), .Y (n_12));
  AOI21X1HVT g314(.A0 (cin), .A1 (n_4), .B0 (n_3), .Y (n_11));
  AND4XLHVT g315(.A (n_4), .B (n_2), .C (n_1), .D (n_7), .Y (o_p));
  OAI2BB1X1HVT g316(.A0N (n_3), .A1N (n_1), .B0 (n_0), .Y (n_9));
  CLKXOR2X1HVT g317(.A (cin), .B (n_4), .Y (sum[0]));
  INVX1HVT g318(.A (n_1), .Y (n_5));
  ADDHX1HVT g319(.A (a[2]), .B (b[2]), .CO (n_6), .S (n_7));
  ADDHX1HVT g320(.A (a[0]), .B (b[0]), .CO (n_3), .S (n_4));
  XOR2XLHVT g321(.A (a[3]), .B (b[3]), .Y (n_2));
  XOR2XLHVT g322(.A (a[1]), .B (b[1]), .Y (n_1));
  NAND2X1HVT g323(.A (a[1]), .B (b[1]), .Y (n_0));
endmodule

module CLA_4bit_3(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_13, n_15;
  OAI21X1HVT g441(.A0 (n_5), .A1 (n_15), .B0 (n_0), .Y (o_g));
  CLKXOR2X1HVT g442(.A (n_5), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g443(.A0 (n_6), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  CLKXOR2X1HVT g444(.A (n_6), .B (n_13), .Y (sum[2]));
  OAI2BB1X1HVT g445(.A0N (n_4), .A1N (n_9), .B0 (n_3), .Y (n_13));
  XNOR2X1HVT g446(.A (n_8), .B (n_9), .Y (sum[1]));
  NOR4BX1HVT g447(.AN (n_6), .B (n_7), .C (n_8), .D (n_5), .Y (o_p));
  XNOR2X1HVT g448(.A (n_7), .B (cin), .Y (sum[0]));
  OAI2BB1X1HVT g449(.A0N (n_2), .A1N (cin), .B0 (n_1), .Y (n_9));
  NAND2X1HVT g450(.A (n_3), .B (n_4), .Y (n_8));
  NAND2X1HVT g451(.A (n_1), .B (n_2), .Y (n_7));
  XOR2XLHVT g452(.A (a[2]), .B (b[2]), .Y (n_6));
  XNOR2X1HVT g453(.A (a[3]), .B (b[3]), .Y (n_5));
  OR2XLHVT g454(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2X1HVT g455(.A (a[1]), .B (b[1]), .Y (n_3));
  NAND2XLHVT g456(.A (a[3]), .B (b[3]), .Y (n_0));
  OR2XLHVT g457(.A (a[0]), .B (b[0]), .Y (n_2));
  NAND2X1HVT g458(.A (a[0]), .B (b[0]), .Y (n_1));
endmodule

module CLA_4bit_4(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_13, n_15;
  OAI21X1HVT g441(.A0 (n_6), .A1 (n_15), .B0 (n_1), .Y (o_g));
  CLKXOR2X1HVT g442(.A (n_6), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g443(.A0 (n_7), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  CLKXOR2X1HVT g444(.A (n_7), .B (n_13), .Y (sum[2]));
  OAI21X1HVT g445(.A0 (n_5), .A1 (n_10), .B0 (n_4), .Y (n_13));
  NOR4BX1HVT g447(.AN (n_7), .B (n_9), .C (n_8), .D (n_6), .Y (o_p));
  XNOR2X1HVT g448(.A (n_8), .B (cin), .Y (sum[0]));
  AOI21X1HVT g449(.A0 (n_3), .A1 (cin), .B0 (n_2), .Y (n_10));
  NAND2BX1HVT g451(.AN (n_5), .B (n_4), .Y (n_9));
  NAND2BX1HVT g452(.AN (n_2), .B (n_3), .Y (n_8));
  XOR2XLHVT g453(.A (a[2]), .B (b[2]), .Y (n_7));
  XNOR2X1HVT g454(.A (a[3]), .B (b[3]), .Y (n_6));
  NOR2X1HVT g455(.A (a[1]), .B (b[1]), .Y (n_5));
  NAND2X1HVT g456(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2XLHVT g457(.A (a[3]), .B (b[3]), .Y (n_1));
  OR2XLHVT g458(.A (a[0]), .B (b[0]), .Y (n_3));
  AND2XLHVT g459(.A (a[0]), .B (b[0]), .Y (n_2));
  XOR2XLHVT g2(.A (n_9), .B (n_10), .Y (sum[1]));
endmodule

module CLA_4bit_5(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_13, n_15;
  OAI21X1HVT g441(.A0 (n_6), .A1 (n_15), .B0 (n_1), .Y (o_g));
  XOR2XLHVT g442(.A (n_6), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g443(.A0 (n_7), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  CLKXOR2X1HVT g444(.A (n_7), .B (n_13), .Y (sum[2]));
  OAI21X1HVT g445(.A0 (n_5), .A1 (n_10), .B0 (n_4), .Y (n_13));
  NOR4BX1HVT g447(.AN (n_7), .B (n_9), .C (n_8), .D (n_6), .Y (o_p));
  XNOR2X1HVT g448(.A (n_8), .B (cin), .Y (sum[0]));
  AOI21X1HVT g449(.A0 (n_3), .A1 (cin), .B0 (n_2), .Y (n_10));
  NAND2BX1HVT g451(.AN (n_5), .B (n_4), .Y (n_9));
  NAND2BX1HVT g452(.AN (n_2), .B (n_3), .Y (n_8));
  XOR2XLHVT g453(.A (a[2]), .B (b[2]), .Y (n_7));
  XNOR2X1HVT g454(.A (a[3]), .B (b[3]), .Y (n_6));
  NOR2X1HVT g455(.A (a[1]), .B (b[1]), .Y (n_5));
  NAND2X1HVT g456(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2XLHVT g457(.A (a[3]), .B (b[3]), .Y (n_1));
  OR2XLHVT g458(.A (a[0]), .B (b[0]), .Y (n_3));
  AND2XLHVT g459(.A (a[0]), .B (b[0]), .Y (n_2));
  XOR2XLHVT g2(.A (n_9), .B (n_10), .Y (sum[1]));
endmodule

module CLA_4bit_6(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_8, n_10;
  wire n_12;
  OAI21X1HVT g367(.A0 (n_4), .A1 (n_12), .B0 (n_1), .Y (o_g));
  CLKXOR2X1HVT g368(.A (n_4), .B (n_12), .Y (sum[3]));
  AOI22X1HVT g369(.A0 (n_3), .A1 (n_10), .B0 (a[2]), .B1 (b[2]), .Y
       (n_12));
  CLKXOR2X1HVT g370(.A (n_3), .B (n_10), .Y (sum[2]));
  OAI21X1HVT g371(.A0 (n_5), .A1 (n_8), .B0 (n_0), .Y (n_10));
  CLKXOR2X1HVT g372(.A (n_5), .B (n_8), .Y (sum[1]));
  AOI22X1HVT g373(.A0 (n_2), .A1 (cin), .B0 (a[0]), .B1 (b[0]), .Y
       (n_8));
  NOR4BBX1HVT g374(.AN (n_3), .BN (n_2), .C (n_4), .D (n_5), .Y (o_p));
  CLKXOR2X1HVT g375(.A (n_2), .B (cin), .Y (sum[0]));
  XNOR2X1HVT g376(.A (a[1]), .B (b[1]), .Y (n_5));
  XNOR2X1HVT g377(.A (a[3]), .B (b[3]), .Y (n_4));
  XOR2XLHVT g378(.A (a[2]), .B (b[2]), .Y (n_3));
  XOR2XLHVT g379(.A (a[0]), .B (b[0]), .Y (n_2));
  NAND2XLHVT g380(.A (a[3]), .B (b[3]), .Y (n_1));
  NAND2XLHVT g381(.A (a[1]), .B (b[1]), .Y (n_0));
endmodule

module CLA_4bit_7(a, b, cin, sum, o_p, o_g);
  input [3:0] a, b;
  input cin;
  output [3:0] sum;
  output o_p, o_g;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] sum;
  wire o_p, o_g;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_13, n_15;
  OAI21X1HVT g499(.A0 (n_5), .A1 (n_15), .B0 (n_0), .Y (o_g));
  CLKXOR2X1HVT g500(.A (n_5), .B (n_15), .Y (sum[3]));
  AOI22X1HVT g501(.A0 (n_6), .A1 (n_13), .B0 (a[2]), .B1 (b[2]), .Y
       (n_15));
  CLKXOR2X1HVT g502(.A (n_6), .B (n_13), .Y (sum[2]));
  OAI2BB1X1HVT g503(.A0N (n_4), .A1N (n_9), .B0 (n_3), .Y (n_13));
  XNOR2X1HVT g504(.A (n_8), .B (n_9), .Y (sum[1]));
  NOR4BX1HVT g505(.AN (n_6), .B (n_5), .C (n_8), .D (n_7), .Y (o_p));
  XNOR2X1HVT g506(.A (n_7), .B (cin), .Y (sum[0]));
  OAI2BB1X1HVT g507(.A0N (n_2), .A1N (cin), .B0 (n_1), .Y (n_9));
  NAND2X1HVT g508(.A (n_3), .B (n_4), .Y (n_8));
  NAND2X1HVT g509(.A (n_1), .B (n_2), .Y (n_7));
  XOR2XLHVT g510(.A (a[2]), .B (b[2]), .Y (n_6));
  XNOR2X1HVT g511(.A (a[3]), .B (b[3]), .Y (n_5));
  OR2XLHVT g512(.A (a[1]), .B (b[1]), .Y (n_4));
  NAND2X1HVT g513(.A (a[1]), .B (b[1]), .Y (n_3));
  NAND2XLHVT g514(.A (a[3]), .B (b[3]), .Y (n_0));
  OR2XLHVT g515(.A (a[0]), .B (b[0]), .Y (n_2));
  NAND2X1HVT g516(.A (a[0]), .B (b[0]), .Y (n_1));
endmodule

module CLA_24bit(i_carry, i_data_a, i_data_b, o_sum, o_carry);
  input i_carry;
  input [23:0] i_data_a, i_data_b;
  output [23:0] o_sum;
  output o_carry;
  wire i_carry;
  wire [23:0] i_data_a, i_data_b;
  wire [23:0] o_sum;
  wire o_carry;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, \w_c[1] , \w_c[2] , \w_c[3] , \w_c[4] ;
  wire \w_c[5] , w_g, w_g_51, w_g_57, w_g_67, w_g_82, w_g_103, w_p;
  wire w_p_50, w_p_56, w_p_66, w_p_81, w_p_102;
  CLA_4bit_2 \CLA_BLOCK_GEN[0].CLA_4BIT_UNIT (.a (i_data_a[3:0]), .b
       (i_data_b[3:0]), .cin (i_carry), .sum (o_sum[3:0]), .o_p (w_p),
       .o_g (w_g));
  CLA_4bit_3 \CLA_BLOCK_GEN[1].CLA_4BIT_UNIT (.a (i_data_a[7:4]), .b
       (i_data_b[7:4]), .cin (\w_c[1] ), .sum (o_sum[7:4]), .o_p
       (w_p_50), .o_g (w_g_51));
  CLA_4bit_4 \CLA_BLOCK_GEN[2].CLA_4BIT_UNIT (.a (i_data_a[11:8]), .b
       (i_data_b[11:8]), .cin (\w_c[2] ), .sum (o_sum[11:8]), .o_p
       (w_p_56), .o_g (w_g_57));
  CLA_4bit_5 \CLA_BLOCK_GEN[3].CLA_4BIT_UNIT (.a (i_data_a[15:12]), .b
       (i_data_b[15:12]), .cin (\w_c[3] ), .sum (o_sum[15:12]), .o_p
       (w_p_66), .o_g (w_g_67));
  CLA_4bit_6 \CLA_BLOCK_GEN[4].CLA_4BIT_UNIT (.a (i_data_a[19:16]), .b
       (i_data_b[19:16]), .cin (\w_c[4] ), .sum (o_sum[19:16]), .o_p
       (w_p_81), .o_g (w_g_82));
  CLA_4bit_7 \CLA_BLOCK_GEN[5].CLA_4BIT_UNIT (.a (i_data_a[23:20]), .b
       (i_data_b[23:20]), .cin (\w_c[5] ), .sum (o_sum[23:20]), .o_p
       (w_p_102), .o_g (w_g_103));
  AO21XLHVT g101(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (\w_c[1] ));
  OR2XLHVT g119(.A (n_19), .B (w_g_51), .Y (\w_c[2] ));
  NOR2BX1HVT g120(.AN (w_p_50), .B (n_18), .Y (n_19));
  AOI21XLHVT g121(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_18));
  NAND2BX1HVT g146(.AN (w_g_57), .B (n_17), .Y (\w_c[3] ));
  OAI21X1HVT g147(.A0 (n_16), .A1 (w_g_51), .B0 (w_p_56), .Y (n_17));
  NOR2BX1HVT g148(.AN (w_p_50), .B (n_15), .Y (n_16));
  AOI21XLHVT g149(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_15));
  NAND2BX1HVT g181(.AN (w_g_67), .B (n_14), .Y (\w_c[4] ));
  OAI21X1HVT g182(.A0 (n_13), .A1 (w_g_57), .B0 (w_p_66), .Y (n_14));
  OA21X1HVT g183(.A0 (n_12), .A1 (w_g_51), .B0 (w_p_56), .Y (n_13));
  NOR2BX1HVT g184(.AN (w_p_50), .B (n_11), .Y (n_12));
  AOI21XLHVT g185(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_11));
  NAND2BX1HVT g213(.AN (w_g_82), .B (n_10), .Y (\w_c[5] ));
  OAI21X1HVT g214(.A0 (n_9), .A1 (w_g_67), .B0 (w_p_81), .Y (n_10));
  OA21X1HVT g215(.A0 (n_8), .A1 (w_g_57), .B0 (w_p_66), .Y (n_9));
  OA21X1HVT g216(.A0 (n_7), .A1 (w_g_51), .B0 (w_p_56), .Y (n_8));
  NOR2BX1HVT g217(.AN (w_p_50), .B (n_6), .Y (n_7));
  AOI21XLHVT g218(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_6));
  NAND2BXLHVT g219(.AN (w_g_103), .B (n_5), .Y (o_carry));
  OAI21X1HVT g220(.A0 (n_4), .A1 (w_g_82), .B0 (w_p_102), .Y (n_5));
  OA21X1HVT g221(.A0 (n_3), .A1 (w_g_67), .B0 (w_p_81), .Y (n_4));
  OA21X1HVT g222(.A0 (n_2), .A1 (w_g_57), .B0 (w_p_66), .Y (n_3));
  OA21X1HVT g223(.A0 (n_1), .A1 (w_g_51), .B0 (w_p_56), .Y (n_2));
  NOR2BX1HVT g224(.AN (w_p_50), .B (n_0), .Y (n_1));
  AOI21XLHVT g225(.A0 (i_carry), .A1 (w_p), .B0 (w_g), .Y (n_0));
endmodule

module MAN_ALU_NUM_OP1_SIZE_MAN24(i_fpu_op, i_sign_a, i_sign_b,
     i_carry, i_man_max, i_man_min, o_man_alu, o_overflow);
  input [0:0] i_fpu_op;
  input i_sign_a, i_sign_b, i_carry;
  input [23:0] i_man_max, i_man_min;
  output [23:0] o_man_alu;
  output o_overflow;
  wire [0:0] i_fpu_op;
  wire i_sign_a, i_sign_b, i_carry;
  wire [23:0] i_man_max, i_man_min;
  wire [23:0] o_man_alu;
  wire o_overflow;
  wire [23:0] w_i_man_b;
  wire n_0, w_i_carry_alu, w_i_fpu_op, w_overflow;
  CLA_24bit ALU_SUB_UNIT(.i_carry (w_i_carry_alu), .i_data_a
       (i_man_max), .i_data_b (w_i_man_b), .o_sum (o_man_alu), .o_carry
       (w_overflow));
  AND2X1HVT g62(.A (w_overflow), .B (w_i_fpu_op), .Y (o_overflow));
  XNOR2X1HVT g271(.A (w_i_fpu_op), .B (i_man_min[7]), .Y
       (w_i_man_b[7]));
  XNOR2X1HVT g272(.A (w_i_fpu_op), .B (i_man_min[21]), .Y
       (w_i_man_b[21]));
  XNOR2X1HVT g273(.A (w_i_fpu_op), .B (i_man_min[17]), .Y
       (w_i_man_b[17]));
  XNOR2X1HVT g274(.A (w_i_fpu_op), .B (i_man_min[9]), .Y
       (w_i_man_b[9]));
  XNOR2X1HVT g275(.A (w_i_fpu_op), .B (i_man_min[8]), .Y
       (w_i_man_b[8]));
  XNOR2X1HVT g276(.A (w_i_fpu_op), .B (i_man_min[16]), .Y
       (w_i_man_b[16]));
  XNOR2X1HVT g277(.A (w_i_fpu_op), .B (i_man_min[23]), .Y
       (w_i_man_b[23]));
  XNOR2X1HVT g278(.A (w_i_fpu_op), .B (i_man_min[6]), .Y
       (w_i_man_b[6]));
  XNOR2X1HVT g279(.A (w_i_fpu_op), .B (i_man_min[20]), .Y
       (w_i_man_b[20]));
  XNOR2X1HVT g280(.A (w_i_fpu_op), .B (i_man_min[15]), .Y
       (w_i_man_b[15]));
  XNOR2X1HVT g281(.A (w_i_fpu_op), .B (i_man_min[5]), .Y
       (w_i_man_b[5]));
  XNOR2X1HVT g282(.A (w_i_fpu_op), .B (i_man_min[4]), .Y
       (w_i_man_b[4]));
  XNOR2X1HVT g283(.A (w_i_fpu_op), .B (i_man_min[1]), .Y
       (w_i_man_b[1]));
  XNOR2X1HVT g284(.A (w_i_fpu_op), .B (i_man_min[3]), .Y
       (w_i_man_b[3]));
  XNOR2X1HVT g285(.A (w_i_fpu_op), .B (i_man_min[2]), .Y
       (w_i_man_b[2]));
  XNOR2X1HVT g286(.A (w_i_fpu_op), .B (i_man_min[22]), .Y
       (w_i_man_b[22]));
  XNOR2X1HVT g287(.A (w_i_fpu_op), .B (i_man_min[19]), .Y
       (w_i_man_b[19]));
  XNOR2X1HVT g288(.A (w_i_fpu_op), .B (i_man_min[13]), .Y
       (w_i_man_b[13]));
  XNOR2X1HVT g289(.A (w_i_fpu_op), .B (i_man_min[14]), .Y
       (w_i_man_b[14]));
  XNOR2X1HVT g290(.A (w_i_fpu_op), .B (i_man_min[0]), .Y
       (w_i_man_b[0]));
  XNOR2X1HVT g291(.A (w_i_fpu_op), .B (i_man_min[12]), .Y
       (w_i_man_b[12]));
  XNOR2X1HVT g292(.A (w_i_fpu_op), .B (i_man_min[18]), .Y
       (w_i_man_b[18]));
  XNOR2X1HVT g293(.A (w_i_fpu_op), .B (i_man_min[11]), .Y
       (w_i_man_b[11]));
  XNOR2X1HVT g294(.A (w_i_fpu_op), .B (i_man_min[10]), .Y
       (w_i_man_b[10]));
  NOR2X1HVT g295(.A (w_i_fpu_op), .B (i_carry), .Y (w_i_carry_alu));
  CLKXOR2X1HVT g296(.A (i_fpu_op), .B (n_0), .Y (w_i_fpu_op));
  XNOR2X1HVT g297(.A (i_sign_b), .B (i_sign_a), .Y (n_0));
endmodule

module CLS_4bit(A, B, Bin, SUB, Bout);
  input [3:0] A, B;
  input Bin;
  output [3:0] SUB;
  output Bout;
  wire [3:0] A, B;
  wire Bin;
  wire [3:0] SUB;
  wire Bout;
  wire n_0, n_1, n_2, n_3, n_6;
  assign SUB[0] = 1'b0;
  XNOR2X1HVT g38(.A (B[3]), .B (n_6), .Y (SUB[3]));
  NAND2BX1HVT g39(.AN (B[3]), .B (n_6), .Y (Bout));
  ADDHX1HVT g40(.A (n_1), .B (n_3), .CO (n_6), .S (SUB[2]));
  ADDHX1HVT g41(.A (n_0), .B (n_2), .CO (n_3), .S (SUB[1]));
  INVX1HVT g42(.A (B[1]), .Y (n_2));
  INVX1HVT g43(.A (B[2]), .Y (n_1));
  INVX1HVT g44(.A (B[0]), .Y (n_0));
endmodule

module COMP_4bit_2(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  assign o_equal = 1'b0;
  OAI22X1HVT g247(.A0 (n_4), .A1 (n_8), .B0 (i_data_a[3]), .B1 (n_2),
       .Y (o_less));
  AOI22X1HVT g248(.A0 (n_5), .A1 (n_7), .B0 (n_0), .B1 (i_data_b[2]),
       .Y (n_8));
  OAI32X1HVT g249(.A0 (i_data_a[0]), .A1 (n_3), .A2 (n_6), .B0
       (i_data_a[1]), .B1 (n_1), .Y (n_7));
  NOR2BX1HVT g250(.AN (i_data_a[1]), .B (i_data_b[1]), .Y (n_6));
  OR2XLHVT g251(.A (n_0), .B (i_data_b[2]), .Y (n_5));
  NOR2BX1HVT g252(.AN (i_data_a[3]), .B (i_data_b[3]), .Y (n_4));
  INVX1HVT g253(.A (i_data_b[0]), .Y (n_3));
  INVX1HVT g254(.A (i_data_b[3]), .Y (n_2));
  INVX1HVT g255(.A (i_data_b[1]), .Y (n_1));
  INVX1HVT g256(.A (i_data_a[2]), .Y (n_0));
endmodule

module COMP_4bit_6(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12;
  OAI21X1HVT g320(.A0 (i_data_a[3]), .A1 (n_11), .B0 (n_12), .Y
       (o_less));
  OAI2BB1X1HVT g321(.A0N (i_data_a[3]), .A1N (n_11), .B0 (i_data_b[3]),
       .Y (n_12));
  AOI22X1HVT g322(.A0 (n_3), .A1 (n_10), .B0 (n_2), .B1 (i_data_b[2]),
       .Y (n_11));
  OAI32X1HVT g323(.A0 (i_data_a[0]), .A1 (n_1), .A2 (n_7), .B0
       (i_data_a[1]), .B1 (n_0), .Y (n_10));
  AND4XLHVT g324(.A (n_5), .B (n_6), .C (n_8), .D (n_4), .Y (o_equal));
  ADDHX1HVT g325(.A (i_data_a[1]), .B (n_0), .CO (n_7), .S (n_8));
  XNOR2X1HVT g326(.A (i_data_a[0]), .B (i_data_b[0]), .Y (n_6));
  XNOR2X1HVT g327(.A (i_data_a[3]), .B (i_data_b[3]), .Y (n_5));
  MXI2XLHVT g328(.A (i_data_a[2]), .B (n_2), .S0 (i_data_b[2]), .Y
       (n_4));
  OR2XLHVT g329(.A (n_2), .B (i_data_b[2]), .Y (n_3));
  INVX1HVT g330(.A (i_data_a[2]), .Y (n_2));
  INVX1HVT g331(.A (i_data_b[0]), .Y (n_1));
  INVX1HVT g332(.A (i_data_b[1]), .Y (n_0));
endmodule

module COMP_4bit_7(i_data_a, i_data_b, o_less, o_equal);
  input [3:0] i_data_a, i_data_b;
  output o_less, o_equal;
  wire [3:0] i_data_a, i_data_b;
  wire o_less, o_equal;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_9;
  OAI2BB1X1HVT g323(.A0N (i_data_b[3]), .A1N (n_9), .B0 (n_6), .Y
       (o_less));
  AOI221X1HVT g324(.A0 (i_data_a[2]), .A1 (n_0), .B0 (i_data_a[1]), .B1
       (n_1), .C0 (n_7), .Y (n_9));
  AND4XLHVT g325(.A (i_data_b[3]), .B (n_3), .C (n_4), .D (n_5), .Y
       (o_equal));
  AOI21XLHVT g326(.A0 (n_2), .A1 (i_data_b[0]), .B0 (i_data_b[1]), .Y
       (n_7));
  NAND3BXLHVT g327(.AN (i_data_a[2]), .B (i_data_b[3]), .C
       (i_data_b[2]), .Y (n_6));
  XNOR2X1HVT g328(.A (i_data_a[2]), .B (i_data_b[2]), .Y (n_5));
  XNOR2X1HVT g329(.A (i_data_a[1]), .B (i_data_b[1]), .Y (n_4));
  XNOR2X1HVT g330(.A (i_data_a[0]), .B (i_data_b[0]), .Y (n_3));
  NOR2XLHVT g331(.A (i_data_a[1]), .B (i_data_a[0]), .Y (n_2));
  NAND2BXLHVT g332(.AN (i_data_a[0]), .B (i_data_b[0]), .Y (n_1));
  INVX1HVT g333(.A (i_data_b[2]), .Y (n_0));
endmodule

module COMP_24bit_SIZE_DATA24(i_data_a, i_data_b, o_less);
  input [23:0] i_data_a, i_data_b;
  output o_less;
  wire [23:0] i_data_a, i_data_b;
  wire o_less;
  wire n_0, n_1, n_2, n_3, n_4, w_equal_0_0, w_equal_0_1, w_equal_0_2;
  wire w_equal_0_3, w_equal_0_4, w_equal_0_5, w_less_0_0, w_less_0_1,
       w_less_0_2, w_less_0_3, w_less_0_4;
  wire w_less_0_5;
  COMP_4bit_2 u_i_data_0(.i_data_a (i_data_a[3:0]), .i_data_b
       (i_data_b[3:0]), .o_less (w_less_0_0), .o_equal (w_equal_0_0));
  COMP_4bit_6 u_i_data_1(.i_data_a (i_data_a[7:4]), .i_data_b
       (i_data_b[7:4]), .o_less (w_less_0_1), .o_equal (w_equal_0_1));
  COMP_4bit_6 u_i_data_2(.i_data_a (i_data_a[11:8]), .i_data_b
       (i_data_b[11:8]), .o_less (w_less_0_2), .o_equal (w_equal_0_2));
  COMP_4bit_6 u_i_data_3(.i_data_a (i_data_a[15:12]), .i_data_b
       (i_data_b[15:12]), .o_less (w_less_0_3), .o_equal (w_equal_0_3));
  COMP_4bit_6 u_i_data_4(.i_data_a (i_data_a[19:16]), .i_data_b
       (i_data_b[19:16]), .o_less (w_less_0_4), .o_equal (w_equal_0_4));
  COMP_4bit_7 u_i_data_5(.i_data_a ({1'b1, i_data_a[22:20]}), .i_data_b
       (i_data_b[23:20]), .o_less (w_less_0_5), .o_equal (w_equal_0_5));
  AO21X1HVT g140(.A0 (w_equal_0_5), .A1 (n_4), .B0 (w_less_0_5), .Y
       (o_less));
  NAND2BX1HVT g141(.AN (w_less_0_4), .B (n_3), .Y (n_4));
  OAI21X1HVT g142(.A0 (w_less_0_3), .A1 (n_2), .B0 (w_equal_0_4), .Y
       (n_3));
  OA21X1HVT g143(.A0 (w_less_0_2), .A1 (n_1), .B0 (w_equal_0_3), .Y
       (n_2));
  NOR2BX1HVT g144(.AN (w_equal_0_2), .B (n_0), .Y (n_1));
  AOI21X1HVT g145(.A0 (w_equal_0_1), .A1 (w_less_0_0), .B0
       (w_less_0_1), .Y (n_0));
endmodule

module MAN_rounding_SIZE_MAN32_SIZE_MAN_RESULT24(i_man, o_man_result,
     o_ov_flow);
  input [31:0] i_man;
  output [23:0] o_man_result;
  output o_ov_flow;
  wire [31:0] i_man;
  wire [23:0] o_man_result;
  wire o_ov_flow;
  wire n_0, n_1, n_2, n_4, n_6, n_8, n_10, n_12;
  wire n_14, n_16, n_18, n_20, n_22, n_24, n_26, n_28;
  wire n_30, n_32, n_34, n_36, n_38, n_40, n_42, n_45;
  assign o_man_result[23] = 1'b0;
  AND3XLHVT g639(.A (i_man[30]), .B (i_man[31]), .C (n_45), .Y
       (o_ov_flow));
  XOR2XLHVT g640(.A (i_man[30]), .B (n_45), .Y (o_man_result[22]));
  ADDHX1HVT g641(.A (i_man[29]), .B (n_42), .CO (n_45), .S
       (o_man_result[21]));
  ADDHX1HVT g642(.A (i_man[28]), .B (n_40), .CO (n_42), .S
       (o_man_result[20]));
  ADDHX1HVT g643(.A (i_man[27]), .B (n_38), .CO (n_40), .S
       (o_man_result[19]));
  ADDHX1HVT g644(.A (i_man[26]), .B (n_36), .CO (n_38), .S
       (o_man_result[18]));
  ADDHX1HVT g645(.A (i_man[25]), .B (n_34), .CO (n_36), .S
       (o_man_result[17]));
  ADDHX1HVT g646(.A (i_man[24]), .B (n_32), .CO (n_34), .S
       (o_man_result[16]));
  ADDHX1HVT g647(.A (i_man[23]), .B (n_30), .CO (n_32), .S
       (o_man_result[15]));
  ADDHX1HVT g648(.A (i_man[22]), .B (n_28), .CO (n_30), .S
       (o_man_result[14]));
  ADDHX1HVT g649(.A (i_man[21]), .B (n_26), .CO (n_28), .S
       (o_man_result[13]));
  ADDHX1HVT g650(.A (i_man[20]), .B (n_24), .CO (n_26), .S
       (o_man_result[12]));
  ADDHX1HVT g651(.A (i_man[19]), .B (n_22), .CO (n_24), .S
       (o_man_result[11]));
  ADDHX1HVT g652(.A (i_man[18]), .B (n_20), .CO (n_22), .S
       (o_man_result[10]));
  ADDHX1HVT g653(.A (i_man[17]), .B (n_18), .CO (n_20), .S
       (o_man_result[9]));
  ADDHX1HVT g654(.A (i_man[16]), .B (n_16), .CO (n_18), .S
       (o_man_result[8]));
  ADDHX1HVT g655(.A (i_man[15]), .B (n_14), .CO (n_16), .S
       (o_man_result[7]));
  ADDHX1HVT g656(.A (i_man[14]), .B (n_12), .CO (n_14), .S
       (o_man_result[6]));
  ADDHX1HVT g657(.A (i_man[13]), .B (n_10), .CO (n_12), .S
       (o_man_result[5]));
  ADDHX1HVT g658(.A (i_man[12]), .B (n_8), .CO (n_10), .S
       (o_man_result[4]));
  ADDHX1HVT g659(.A (i_man[11]), .B (n_6), .CO (n_8), .S
       (o_man_result[3]));
  ADDHX1HVT g660(.A (i_man[10]), .B (n_4), .CO (n_6), .S
       (o_man_result[2]));
  ADDHX1HVT g661(.A (i_man[9]), .B (n_2), .CO (n_4), .S
       (o_man_result[1]));
  ADDHX1HVT g662(.A (n_1), .B (i_man[8]), .CO (n_2), .S
       (o_man_result[0]));
  NOR2BX1HVT g663(.AN (i_man[6]), .B (n_0), .Y (n_1));
  NOR4X1HVT g664(.A (i_man[3]), .B (i_man[4]), .C (i_man[5]), .D
       (i_man[7]), .Y (n_0));
endmodule

module MAN_swap_SIZE_MAN24_1(i_man_a, i_man_b, i_compare, o_man_max,
     o_man_min);
  input [23:0] i_man_a, i_man_b;
  input i_compare;
  output [23:0] o_man_max, o_man_min;
  wire [23:0] i_man_a, i_man_b;
  wire i_compare;
  wire [23:0] o_man_max, o_man_min;
  MX2XLHVT g764(.A (i_man_b[8]), .B (i_man_a[8]), .S0 (i_compare), .Y
       (o_man_min[8]));
  MX2XLHVT g765(.A (i_man_a[21]), .B (i_man_b[21]), .S0 (i_compare), .Y
       (o_man_max[21]));
  MX2XLHVT g766(.A (i_man_a[19]), .B (i_man_b[19]), .S0 (i_compare), .Y
       (o_man_max[19]));
  MX2XLHVT g767(.A (i_man_a[16]), .B (i_man_b[16]), .S0 (i_compare), .Y
       (o_man_max[16]));
  MX2XLHVT g768(.A (i_man_a[10]), .B (i_man_b[10]), .S0 (i_compare), .Y
       (o_man_max[10]));
  MX2XLHVT g769(.A (i_man_b[19]), .B (i_man_a[19]), .S0 (i_compare), .Y
       (o_man_min[19]));
  MX2XLHVT g770(.A (i_man_b[18]), .B (i_man_a[18]), .S0 (i_compare), .Y
       (o_man_min[18]));
  MX2XLHVT g771(.A (i_man_b[17]), .B (i_man_a[17]), .S0 (i_compare), .Y
       (o_man_min[17]));
  MX2XLHVT g772(.A (i_man_a[9]), .B (i_man_b[9]), .S0 (i_compare), .Y
       (o_man_max[9]));
  MX2XLHVT g773(.A (i_man_b[16]), .B (i_man_a[16]), .S0 (i_compare), .Y
       (o_man_min[16]));
  MX2XLHVT g774(.A (i_man_b[15]), .B (i_man_a[15]), .S0 (i_compare), .Y
       (o_man_min[15]));
  MX2XLHVT g775(.A (i_man_a[15]), .B (i_man_b[15]), .S0 (i_compare), .Y
       (o_man_max[15]));
  MX2XLHVT g776(.A (i_man_a[8]), .B (i_man_b[8]), .S0 (i_compare), .Y
       (o_man_max[8]));
  MX2XLHVT g777(.A (i_man_b[14]), .B (i_man_a[14]), .S0 (i_compare), .Y
       (o_man_min[14]));
  MX2XLHVT g778(.A (i_man_b[13]), .B (i_man_a[13]), .S0 (i_compare), .Y
       (o_man_min[13]));
  MX2XLHVT g779(.A (i_man_b[12]), .B (i_man_a[12]), .S0 (i_compare), .Y
       (o_man_min[12]));
  MX2XLHVT g780(.A (i_man_a[7]), .B (i_man_b[7]), .S0 (i_compare), .Y
       (o_man_max[7]));
  MX2XLHVT g781(.A (i_man_b[11]), .B (i_man_a[11]), .S0 (i_compare), .Y
       (o_man_min[11]));
  MX2XLHVT g782(.A (i_man_b[10]), .B (i_man_a[10]), .S0 (i_compare), .Y
       (o_man_min[10]));
  MX2XLHVT g783(.A (i_man_b[9]), .B (i_man_a[9]), .S0 (i_compare), .Y
       (o_man_min[9]));
  MX2XLHVT g784(.A (i_man_a[14]), .B (i_man_b[14]), .S0 (i_compare), .Y
       (o_man_max[14]));
  MX2XLHVT g785(.A (i_man_a[6]), .B (i_man_b[6]), .S0 (i_compare), .Y
       (o_man_max[6]));
  MX2XLHVT g786(.A (i_man_a[22]), .B (i_man_b[22]), .S0 (i_compare), .Y
       (o_man_max[22]));
  MX2XLHVT g787(.A (i_man_b[20]), .B (i_man_a[20]), .S0 (i_compare), .Y
       (o_man_min[20]));
  MX2XLHVT g788(.A (i_man_b[6]), .B (i_man_a[6]), .S0 (i_compare), .Y
       (o_man_min[6]));
  MX2XLHVT g789(.A (i_man_b[5]), .B (i_man_a[5]), .S0 (i_compare), .Y
       (o_man_min[5]));
  MX2XLHVT g790(.A (i_man_b[4]), .B (i_man_a[4]), .S0 (i_compare), .Y
       (o_man_min[4]));
  MX2XLHVT g791(.A (i_man_a[5]), .B (i_man_b[5]), .S0 (i_compare), .Y
       (o_man_max[5]));
  MX2XLHVT g792(.A (i_man_b[3]), .B (i_man_a[3]), .S0 (i_compare), .Y
       (o_man_min[3]));
  MX2XLHVT g793(.A (i_man_b[2]), .B (i_man_a[2]), .S0 (i_compare), .Y
       (o_man_min[2]));
  MX2XLHVT g794(.A (i_man_b[1]), .B (i_man_a[1]), .S0 (i_compare), .Y
       (o_man_min[1]));
  MX2XLHVT g795(.A (i_man_a[4]), .B (i_man_b[4]), .S0 (i_compare), .Y
       (o_man_max[4]));
  MX2XLHVT g796(.A (i_man_b[0]), .B (i_man_a[0]), .S0 (i_compare), .Y
       (o_man_min[0]));
  MX2XLHVT g797(.A (i_man_a[20]), .B (i_man_b[20]), .S0 (i_compare), .Y
       (o_man_max[20]));
  MX2XLHVT g798(.A (i_man_a[18]), .B (i_man_b[18]), .S0 (i_compare), .Y
       (o_man_max[18]));
  MX2XLHVT g799(.A (i_man_a[13]), .B (i_man_b[13]), .S0 (i_compare), .Y
       (o_man_max[13]));
  MX2XLHVT g800(.A (i_man_a[3]), .B (i_man_b[3]), .S0 (i_compare), .Y
       (o_man_max[3]));
  MX2XLHVT g801(.A (i_man_a[12]), .B (i_man_b[12]), .S0 (i_compare), .Y
       (o_man_max[12]));
  MX2XLHVT g802(.A (i_man_a[2]), .B (i_man_b[2]), .S0 (i_compare), .Y
       (o_man_max[2]));
  MX2XLHVT g803(.A (i_man_a[1]), .B (i_man_b[1]), .S0 (i_compare), .Y
       (o_man_max[1]));
  MX2XLHVT g804(.A (i_man_a[17]), .B (i_man_b[17]), .S0 (i_compare), .Y
       (o_man_max[17]));
  MX2XLHVT g805(.A (i_man_a[11]), .B (i_man_b[11]), .S0 (i_compare), .Y
       (o_man_max[11]));
  MX2XLHVT g806(.A (i_man_a[0]), .B (i_man_b[0]), .S0 (i_compare), .Y
       (o_man_max[0]));
  MX2XLHVT g807(.A (i_man_b[22]), .B (i_man_a[22]), .S0 (i_compare), .Y
       (o_man_min[22]));
  MX2XLHVT g808(.A (i_man_b[21]), .B (i_man_a[21]), .S0 (i_compare), .Y
       (o_man_min[21]));
  MX2XLHVT g809(.A (i_man_b[7]), .B (i_man_a[7]), .S0 (i_compare), .Y
       (o_man_min[7]));
  NAND2BXLHVT g810(.AN (i_man_b[23]), .B (i_compare), .Y
       (o_man_max[23]));
  OR2XLHVT g811(.A (i_man_b[23]), .B (i_compare), .Y (o_man_min[23]));
endmodule

module MAN_swap_SIZE_MAN24(i_man_a, i_man_b, i_compare, o_man_max,
     o_man_min);
  input [23:0] i_man_a, i_man_b;
  input i_compare;
  output [23:0] o_man_max, o_man_min;
  wire [23:0] i_man_a, i_man_b;
  wire i_compare;
  wire [23:0] o_man_max, o_man_min;
  assign o_man_min[23] = 1'b1;
  assign o_man_max[23] = 1'b1;
  MX2XLHVT g761(.A (i_man_b[7]), .B (i_man_a[7]), .S0 (i_compare), .Y
       (o_man_min[7]));
  MX2XLHVT g762(.A (i_man_a[21]), .B (i_man_b[21]), .S0 (i_compare), .Y
       (o_man_max[21]));
  MX2XLHVT g763(.A (i_man_a[19]), .B (i_man_b[19]), .S0 (i_compare), .Y
       (o_man_max[19]));
  MX2XLHVT g764(.A (i_man_a[16]), .B (i_man_b[16]), .S0 (i_compare), .Y
       (o_man_max[16]));
  MX2XLHVT g765(.A (i_man_b[18]), .B (i_man_a[18]), .S0 (i_compare), .Y
       (o_man_min[18]));
  MX2XLHVT g766(.A (i_man_b[17]), .B (i_man_a[17]), .S0 (i_compare), .Y
       (o_man_min[17]));
  MX2X1HVT g767(.A (i_man_a[9]), .B (i_man_b[9]), .S0 (i_compare), .Y
       (o_man_max[9]));
  MX2XLHVT g768(.A (i_man_b[16]), .B (i_man_a[16]), .S0 (i_compare), .Y
       (o_man_min[16]));
  MX2XLHVT g769(.A (i_man_b[15]), .B (i_man_a[15]), .S0 (i_compare), .Y
       (o_man_min[15]));
  MX2XLHVT g770(.A (i_man_b[14]), .B (i_man_a[14]), .S0 (i_compare), .Y
       (o_man_min[14]));
  MX2XLHVT g771(.A (i_man_a[15]), .B (i_man_b[15]), .S0 (i_compare), .Y
       (o_man_max[15]));
  MX2XLHVT g772(.A (i_man_a[8]), .B (i_man_b[8]), .S0 (i_compare), .Y
       (o_man_max[8]));
  MX2XLHVT g773(.A (i_man_b[13]), .B (i_man_a[13]), .S0 (i_compare), .Y
       (o_man_min[13]));
  MX2XLHVT g774(.A (i_man_b[12]), .B (i_man_a[12]), .S0 (i_compare), .Y
       (o_man_min[12]));
  MX2XLHVT g775(.A (i_man_b[11]), .B (i_man_a[11]), .S0 (i_compare), .Y
       (o_man_min[11]));
  MX2XLHVT g776(.A (i_man_a[7]), .B (i_man_b[7]), .S0 (i_compare), .Y
       (o_man_max[7]));
  MX2XLHVT g777(.A (i_man_b[10]), .B (i_man_a[10]), .S0 (i_compare), .Y
       (o_man_min[10]));
  MX2XLHVT g778(.A (i_man_b[9]), .B (i_man_a[9]), .S0 (i_compare), .Y
       (o_man_min[9]));
  MX2X1HVT g779(.A (i_man_a[18]), .B (i_man_b[18]), .S0 (i_compare), .Y
       (o_man_max[18]));
  MX2X1HVT g780(.A (i_man_a[14]), .B (i_man_b[14]), .S0 (i_compare), .Y
       (o_man_max[14]));
  MX2X1HVT g781(.A (i_man_a[6]), .B (i_man_b[6]), .S0 (i_compare), .Y
       (o_man_max[6]));
  MX2XLHVT g782(.A (i_man_b[8]), .B (i_man_a[8]), .S0 (i_compare), .Y
       (o_man_min[8]));
  MX2XLHVT g783(.A (i_man_a[22]), .B (i_man_b[22]), .S0 (i_compare), .Y
       (o_man_max[22]));
  MX2XLHVT g784(.A (i_man_b[19]), .B (i_man_a[19]), .S0 (i_compare), .Y
       (o_man_min[19]));
  MX2XLHVT g785(.A (i_man_b[5]), .B (i_man_a[5]), .S0 (i_compare), .Y
       (o_man_min[5]));
  MX2XLHVT g786(.A (i_man_b[4]), .B (i_man_a[4]), .S0 (i_compare), .Y
       (o_man_min[4]));
  MX2XLHVT g787(.A (i_man_b[3]), .B (i_man_a[3]), .S0 (i_compare), .Y
       (o_man_min[3]));
  MX2X1HVT g788(.A (i_man_a[5]), .B (i_man_b[5]), .S0 (i_compare), .Y
       (o_man_max[5]));
  MX2XLHVT g789(.A (i_man_b[2]), .B (i_man_a[2]), .S0 (i_compare), .Y
       (o_man_min[2]));
  MX2XLHVT g790(.A (i_man_b[1]), .B (i_man_a[1]), .S0 (i_compare), .Y
       (o_man_min[1]));
  MX2XLHVT g791(.A (i_man_a[4]), .B (i_man_b[4]), .S0 (i_compare), .Y
       (o_man_max[4]));
  MX2XLHVT g792(.A (i_man_b[0]), .B (i_man_a[0]), .S0 (i_compare), .Y
       (o_man_min[0]));
  MX2XLHVT g793(.A (i_man_a[20]), .B (i_man_b[20]), .S0 (i_compare), .Y
       (o_man_max[20]));
  MX2X1HVT g794(.A (i_man_a[13]), .B (i_man_b[13]), .S0 (i_compare), .Y
       (o_man_max[13]));
  MX2XLHVT g795(.A (i_man_a[3]), .B (i_man_b[3]), .S0 (i_compare), .Y
       (o_man_max[3]));
  MX2XLHVT g796(.A (i_man_a[2]), .B (i_man_b[2]), .S0 (i_compare), .Y
       (o_man_max[2]));
  MX2XLHVT g797(.A (i_man_a[12]), .B (i_man_b[12]), .S0 (i_compare), .Y
       (o_man_max[12]));
  MX2XLHVT g798(.A (i_man_a[1]), .B (i_man_b[1]), .S0 (i_compare), .Y
       (o_man_max[1]));
  MX2X1HVT g799(.A (i_man_a[17]), .B (i_man_b[17]), .S0 (i_compare), .Y
       (o_man_max[17]));
  MX2XLHVT g800(.A (i_man_a[11]), .B (i_man_b[11]), .S0 (i_compare), .Y
       (o_man_max[11]));
  MX2XLHVT g801(.A (i_man_a[0]), .B (i_man_b[0]), .S0 (i_compare), .Y
       (o_man_max[0]));
  MX2XLHVT g802(.A (i_man_b[22]), .B (i_man_a[22]), .S0 (i_compare), .Y
       (o_man_min[22]));
  MX2X1HVT g803(.A (i_man_a[10]), .B (i_man_b[10]), .S0 (i_compare), .Y
       (o_man_max[10]));
  MX2XLHVT g804(.A (i_man_b[21]), .B (i_man_a[21]), .S0 (i_compare), .Y
       (o_man_min[21]));
  MX2XLHVT g805(.A (i_man_b[20]), .B (i_man_a[20]), .S0 (i_compare), .Y
       (o_man_min[20]));
  MX2XLHVT g806(.A (i_man_b[6]), .B (i_man_a[6]), .S0 (i_compare), .Y
       (o_man_min[6]));
endmodule

module SHF_left_SIZE_DATA32_SIZE_SHIFT5(i_shift_number, i_data, o_data);
  input [4:0] i_shift_number;
  input [31:0] i_data;
  output [31:0] o_data;
  wire [4:0] i_shift_number;
  wire [31:0] i_data;
  wire [31:0] o_data;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_117, n_118, n_119, n_122, n_129, n_130, n_131, n_133;
  wire n_137, n_138;
  assign o_data[0] = 1'b0;
  assign o_data[1] = 1'b0;
  assign o_data[2] = 1'b0;
  assign o_data[3] = 1'b0;
  NAND2X1HVT g2849(.A (n_122), .B (n_138), .Y (o_data[31]));
  NAND2X1HVT g2850(.A (n_129), .B (n_137), .Y (o_data[30]));
  OAI221X1HVT g2851(.A0 (n_5), .A1 (n_119), .B0 (n_31), .B1 (n_64), .C0
       (n_131), .Y (o_data[29]));
  OAI211X1HVT g2852(.A0 (n_31), .A1 (n_49), .B0 (n_133), .C0 (n_130),
       .Y (o_data[28]));
  AOI32X1HVT g2853(.A0 (i_data[31]), .A1 (n_7), .A2 (n_29), .B0
       (i_shift_number[4]), .B1 (n_117), .Y (n_138));
  AOI32X1HVT g2854(.A0 (i_data[30]), .A1 (n_7), .A2 (n_29), .B0
       (i_shift_number[4]), .B1 (n_118), .Y (n_137));
  NOR2X1HVT g2855(.A (i_shift_number[4]), .B (n_119), .Y (o_data[13]));
  AND2XLHVT g2856(.A (n_5), .B (n_118), .Y (o_data[14]));
  AND2XLHVT g2857(.A (n_5), .B (n_111), .Y (o_data[12]));
  NAND2X1HVT g2858(.A (i_shift_number[4]), .B (n_111), .Y (n_133));
  AND2XLHVT g2859(.A (n_5), .B (n_117), .Y (o_data[15]));
  AOI31X1HVT g2860(.A0 (n_9), .A1 (n_8), .A2 (n_41), .B0 (n_112), .Y
       (n_131));
  AOI31X1HVT g2861(.A0 (n_9), .A1 (n_8), .A2 (n_43), .B0 (n_115), .Y
       (n_130));
  AOI221X1HVT g2862(.A0 (n_43), .A1 (n_45), .B0 (i_data[29]), .B1
       (n_80), .C0 (n_110), .Y (n_129));
  OAI222X1HVT g2863(.A0 (n_6), .A1 (n_94), .B0 (n_0), .B1 (n_90), .C0
       (n_34), .C1 (n_69), .Y (o_data[23]));
  OAI221X1HVT g2864(.A0 (n_6), .A1 (n_96), .B0 (n_31), .B1 (n_63), .C0
       (n_109), .Y (o_data[26]));
  OAI221X1HVT g2865(.A0 (n_6), .A1 (n_95), .B0 (n_31), .B1 (n_60), .C0
       (n_114), .Y (o_data[25]));
  OAI221X1HVT g2866(.A0 (n_6), .A1 (n_87), .B0 (n_31), .B1 (n_51), .C0
       (n_113), .Y (o_data[24]));
  OAI222X1HVT g2867(.A0 (n_6), .A1 (n_99), .B0 (n_0), .B1 (n_86), .C0
       (n_34), .C1 (n_32), .Y (o_data[20]));
  OAI222X1HVT g2868(.A0 (n_6), .A1 (n_97), .B0 (n_0), .B1 (n_89), .C0
       (n_34), .C1 (n_67), .Y (o_data[22]));
  AOI221X1HVT g2869(.A0 (n_41), .A1 (n_45), .B0 (i_data[30]), .B1
       (n_80), .C0 (n_107), .Y (n_122));
  OAI222X1HVT g2870(.A0 (n_6), .A1 (n_91), .B0 (n_0), .B1 (n_88), .C0
       (n_10), .C1 (n_47), .Y (o_data[21]));
  OAI221X1HVT g2871(.A0 (n_6), .A1 (n_98), .B0 (n_31), .B1 (n_57), .C0
       (n_108), .Y (o_data[27]));
  OAI22X1HVT g2872(.A0 (n_0), .A1 (n_98), .B0 (n_6), .B1 (n_92), .Y
       (o_data[19]));
  OAI22X1HVT g2873(.A0 (n_6), .A1 (n_86), .B0 (n_39), .B1 (n_46), .Y
       (n_115));
  OA22X1HVT g2874(.A0 (n_10), .A1 (n_85), .B0 (n_30), .B1 (n_64), .Y
       (n_114));
  OA22X1HVT g2875(.A0 (n_10), .A1 (n_93), .B0 (n_30), .B1 (n_49), .Y
       (n_113));
  OAI22X1HVT g2876(.A0 (n_6), .A1 (n_88), .B0 (n_26), .B1 (n_46), .Y
       (n_112));
  MX2XLHVT g2877(.A (n_91), .B (n_47), .S0 (i_shift_number[3]), .Y
       (n_119));
  OAI22X1HVT g2878(.A0 (i_shift_number[3]), .A1 (n_97), .B0 (n_12), .B1
       (n_67), .Y (n_118));
  OAI22X1HVT g2879(.A0 (i_shift_number[3]), .A1 (n_94), .B0 (n_12), .B1
       (n_69), .Y (n_117));
  OAI22X1HVT g2880(.A0 (n_6), .A1 (n_89), .B0 (n_31), .B1 (n_71), .Y
       (n_110));
  AOI22X1HVT g2881(.A0 (n_11), .A1 (n_83), .B0 (n_29), .B1 (n_70), .Y
       (n_109));
  OA22X1HVT g2882(.A0 (n_10), .A1 (n_92), .B0 (n_30), .B1 (n_72), .Y
       (n_108));
  OAI22X1HVT g2883(.A0 (n_6), .A1 (n_90), .B0 (n_31), .B1 (n_72), .Y
       (n_107));
  OAI22X1HVT g2884(.A0 (n_0), .A1 (n_87), .B0 (n_6), .B1 (n_93), .Y
       (o_data[16]));
  OAI22X1HVT g2885(.A0 (n_0), .A1 (n_96), .B0 (n_6), .B1 (n_84), .Y
       (o_data[18]));
  OAI22X1HVT g2886(.A0 (n_0), .A1 (n_95), .B0 (n_6), .B1 (n_85), .Y
       (o_data[17]));
  OAI22X1HVT g2887(.A0 (i_shift_number[3]), .A1 (n_99), .B0 (n_12), .B1
       (n_32), .Y (n_111));
  NOR2X1HVT g2888(.A (n_0), .B (n_92), .Y (o_data[11]));
  NOR2X1HVT g2889(.A (n_0), .B (n_85), .Y (o_data[9]));
  NOR2X1HVT g2890(.A (n_0), .B (n_93), .Y (o_data[8]));
  NOR2X1HVT g2891(.A (n_0), .B (n_84), .Y (o_data[10]));
  AOI22X1HVT g2892(.A0 (n_3), .A1 (n_76), .B0 (i_shift_number[2]), .B1
       (n_77), .Y (n_99));
  AOI22X1HVT g2893(.A0 (n_3), .A1 (n_55), .B0 (i_shift_number[2]), .B1
       (n_58), .Y (n_98));
  AOI22X1HVT g2894(.A0 (n_3), .A1 (n_73), .B0 (i_shift_number[2]), .B1
       (n_74), .Y (n_97));
  AOI22X1HVT g2895(.A0 (n_3), .A1 (n_79), .B0 (i_shift_number[2]), .B1
       (n_73), .Y (n_96));
  AOI22X1HVT g2896(.A0 (n_3), .A1 (n_61), .B0 (i_shift_number[2]), .B1
       (n_53), .Y (n_95));
  AOI22X1HVT g2897(.A0 (n_3), .A1 (n_58), .B0 (i_shift_number[2]), .B1
       (n_75), .Y (n_94));
  MX2XLHVT g2898(.A (n_78), .B (n_32), .S0 (i_shift_number[2]), .Y
       (n_93));
  AOI22X1HVT g2899(.A0 (n_3), .A1 (n_75), .B0 (i_shift_number[2]), .B1
       (n_68), .Y (n_92));
  INVX1HVT g2900(.A (n_84), .Y (n_83));
  AOI22X1HVT g2901(.A0 (n_3), .A1 (n_53), .B0 (i_shift_number[2]), .B1
       (n_54), .Y (n_91));
  AOI22X1HVT g2902(.A0 (n_3), .A1 (n_56), .B0 (i_shift_number[2]), .B1
       (n_55), .Y (n_90));
  AOI22X1HVT g2903(.A0 (n_3), .A1 (n_62), .B0 (i_shift_number[2]), .B1
       (n_79), .Y (n_89));
  AOI22X1HVT g2904(.A0 (n_3), .A1 (n_59), .B0 (i_shift_number[2]), .B1
       (n_61), .Y (n_88));
  AOI22X1HVT g2905(.A0 (n_3), .A1 (n_52), .B0 (i_shift_number[2]), .B1
       (n_76), .Y (n_87));
  AOI22X1HVT g2906(.A0 (n_3), .A1 (n_50), .B0 (i_shift_number[2]), .B1
       (n_52), .Y (n_86));
  AOI32X1HVT g2907(.A0 (i_shift_number[2]), .A1 (n_2), .A2 (n_33), .B0
       (n_3), .B1 (n_54), .Y (n_85));
  AOI22X1HVT g2908(.A0 (n_3), .A1 (n_74), .B0 (i_shift_number[2]), .B1
       (n_66), .Y (n_84));
  NOR2X1HVT g2909(.A (n_30), .B (n_67), .Y (o_data[6]));
  NOR2X1HVT g2910(.A (n_30), .B (n_69), .Y (o_data[7]));
  INVX1HVT g2911(.A (n_77), .Y (n_78));
  INVX1HVT g2912(.A (n_70), .Y (n_71));
  INVX1HVT g2913(.A (n_69), .Y (n_68));
  INVX1HVT g2914(.A (n_67), .Y (n_66));
  NOR2X1HVT g2915(.A (n_0), .B (n_47), .Y (o_data[5]));
  NOR3X1HVT g2916(.A (i_shift_number[1]), .B (n_4), .C (n_30), .Y
       (n_80));
  OAI22X1HVT g2917(.A0 (i_shift_number[1]), .A1 (n_25), .B0 (n_2), .B1
       (n_13), .Y (n_79));
  OAI22X1HVT g2918(.A0 (i_shift_number[1]), .A1 (n_38), .B0 (n_2), .B1
       (n_36), .Y (n_77));
  OAI22X1HVT g2919(.A0 (i_shift_number[1]), .A1 (n_42), .B0 (n_2), .B1
       (n_27), .Y (n_76));
  OAI22X1HVT g2920(.A0 (i_shift_number[1]), .A1 (n_35), .B0 (n_2), .B1
       (n_44), .Y (n_75));
  OAI22X1HVT g2921(.A0 (i_shift_number[1]), .A1 (n_27), .B0 (n_2), .B1
       (n_38), .Y (n_74));
  OAI22X1HVT g2922(.A0 (i_shift_number[1]), .A1 (n_17), .B0 (n_2), .B1
       (n_42), .Y (n_73));
  MX2XLHVT g2923(.A (n_40), .B (n_26), .S0 (n_2), .Y (n_72));
  OAI22X1HVT g2924(.A0 (i_shift_number[1]), .A1 (n_39), .B0 (n_2), .B1
       (n_21), .Y (n_70));
  AOI22X1HVT g2925(.A0 (n_2), .A1 (n_20), .B0 (i_shift_number[1]), .B1
       (n_33), .Y (n_69));
  AOI32X1HVT g2926(.A0 (i_data[4]), .A1 (i_shift_number[1]), .A2 (n_4),
       .B0 (n_2), .B1 (n_37), .Y (n_67));
  INVX1HVT g2927(.A (n_62), .Y (n_63));
  INVX1HVT g2928(.A (n_59), .Y (n_60));
  INVX1HVT g2929(.A (n_56), .Y (n_57));
  INVX1HVT g2930(.A (n_50), .Y (n_51));
  MX2XLHVT g2931(.A (n_40), .B (n_14), .S0 (i_shift_number[1]), .Y
       (n_64));
  OAI22X1HVT g2932(.A0 (i_shift_number[1]), .A1 (n_28), .B0 (n_2), .B1
       (n_24), .Y (n_62));
  OAI22X1HVT g2933(.A0 (i_shift_number[1]), .A1 (n_22), .B0 (n_2), .B1
       (n_15), .Y (n_61));
  OAI22X1HVT g2934(.A0 (i_shift_number[1]), .A1 (n_16), .B0 (n_2), .B1
       (n_23), .Y (n_59));
  OAI22X1HVT g2935(.A0 (i_shift_number[1]), .A1 (n_15), .B0 (n_2), .B1
       (n_18), .Y (n_58));
  OAI22X1HVT g2936(.A0 (i_shift_number[1]), .A1 (n_14), .B0 (n_2), .B1
       (n_16), .Y (n_56));
  OAI22X1HVT g2937(.A0 (i_shift_number[1]), .A1 (n_23), .B0 (n_2), .B1
       (n_22), .Y (n_55));
  OAI22X1HVT g2938(.A0 (i_shift_number[1]), .A1 (n_44), .B0 (n_2), .B1
       (n_19), .Y (n_54));
  OAI22X1HVT g2939(.A0 (i_shift_number[1]), .A1 (n_18), .B0 (n_2), .B1
       (n_35), .Y (n_53));
  OAI22X1HVT g2940(.A0 (i_shift_number[1]), .A1 (n_13), .B0 (n_2), .B1
       (n_17), .Y (n_52));
  OAI22X1HVT g2941(.A0 (i_shift_number[1]), .A1 (n_24), .B0 (n_2), .B1
       (n_25), .Y (n_50));
  MX2XLHVT g2942(.A (n_21), .B (n_28), .S0 (i_shift_number[1]), .Y
       (n_49));
  NOR2X1HVT g2943(.A (n_30), .B (n_32), .Y (o_data[4]));
  INVX1HVT g2944(.A (n_46), .Y (n_45));
  NAND2X1HVT g2945(.A (n_8), .B (n_33), .Y (n_47));
  NAND2X1HVT g2946(.A (i_shift_number[1]), .B (n_29), .Y (n_46));
  INVX1HVT g2947(.A (n_36), .Y (n_37));
  INVX1HVT g2948(.A (n_30), .Y (n_29));
  AOI22X1HVT g2949(.A0 (i_data[9]), .A1 (n_4), .B0 (i_data[8]), .B1
       (i_shift_number[0]), .Y (n_44));
  MX2XLHVT g2950(.A (i_data[27]), .B (i_data[28]), .S0 (n_4), .Y
       (n_43));
  AOI22X1HVT g2951(.A0 (i_data[12]), .A1 (n_4), .B0 (i_data[11]), .B1
       (i_shift_number[0]), .Y (n_42));
  MX2XLHVT g2952(.A (i_data[28]), .B (i_data[29]), .S0 (n_4), .Y
       (n_41));
  AOI22XLHVT g2953(.A0 (i_data[25]), .A1 (n_4), .B0 (i_data[24]), .B1
       (i_shift_number[0]), .Y (n_40));
  AOI22XLHVT g2954(.A0 (i_data[26]), .A1 (n_4), .B0 (i_data[25]), .B1
       (i_shift_number[0]), .Y (n_39));
  AOI22X1HVT g2955(.A0 (i_data[8]), .A1 (n_4), .B0 (i_data[7]), .B1
       (i_shift_number[0]), .Y (n_38));
  AOI22X1HVT g2956(.A0 (i_data[6]), .A1 (n_4), .B0 (i_data[5]), .B1
       (i_shift_number[0]), .Y (n_36));
  AOI22X1HVT g2957(.A0 (i_data[11]), .A1 (n_4), .B0 (i_data[10]), .B1
       (i_shift_number[0]), .Y (n_35));
  NAND2X1HVT g2958(.A (n_11), .B (n_3), .Y (n_34));
  MX2X1HVT g2959(.A (i_data[5]), .B (i_data[4]), .S0
       (i_shift_number[0]), .Y (n_33));
  NAND2X1HVT g2960(.A (i_data[4]), .B (n_7), .Y (n_32));
  NAND2X1HVT g2961(.A (i_shift_number[2]), .B (n_9), .Y (n_31));
  NAND2X1HVT g2962(.A (n_9), .B (n_3), .Y (n_30));
  INVX1HVT g2963(.A (n_19), .Y (n_20));
  AOI22XLHVT g2964(.A0 (i_data[22]), .A1 (n_4), .B0 (i_data[21]), .B1
       (i_shift_number[0]), .Y (n_28));
  AOI22X1HVT g2965(.A0 (i_data[10]), .A1 (n_4), .B0 (i_data[9]), .B1
       (i_shift_number[0]), .Y (n_27));
  AOI22XLHVT g2966(.A0 (i_data[27]), .A1 (n_4), .B0 (i_data[26]), .B1
       (i_shift_number[0]), .Y (n_26));
  AOI22XLHVT g2967(.A0 (i_data[18]), .A1 (n_4), .B0 (i_data[17]), .B1
       (i_shift_number[0]), .Y (n_25));
  AOI22XLHVT g2968(.A0 (i_data[20]), .A1 (n_4), .B0 (i_data[19]), .B1
       (i_shift_number[0]), .Y (n_24));
  AOI22XLHVT g2969(.A0 (i_data[19]), .A1 (n_4), .B0 (i_data[18]), .B1
       (i_shift_number[0]), .Y (n_23));
  AOI22XLHVT g2970(.A0 (i_data[17]), .A1 (n_4), .B0 (i_data[16]), .B1
       (i_shift_number[0]), .Y (n_22));
  AOI22XLHVT g2971(.A0 (i_data[24]), .A1 (n_4), .B0 (i_data[23]), .B1
       (i_shift_number[0]), .Y (n_21));
  AOI22X1HVT g2972(.A0 (i_data[7]), .A1 (n_4), .B0 (i_data[6]), .B1
       (i_shift_number[0]), .Y (n_19));
  AOI22X1HVT g2973(.A0 (i_data[13]), .A1 (n_4), .B0 (i_data[12]), .B1
       (i_shift_number[0]), .Y (n_18));
  AOI22X1HVT g2974(.A0 (i_data[14]), .A1 (n_4), .B0 (i_data[13]), .B1
       (i_shift_number[0]), .Y (n_17));
  AOI22XLHVT g2975(.A0 (i_data[21]), .A1 (n_4), .B0 (i_data[20]), .B1
       (i_shift_number[0]), .Y (n_16));
  AOI22X1HVT g2976(.A0 (i_data[15]), .A1 (n_4), .B0 (i_data[14]), .B1
       (i_shift_number[0]), .Y (n_15));
  AOI22XLHVT g2977(.A0 (i_data[23]), .A1 (n_4), .B0 (i_data[22]), .B1
       (i_shift_number[0]), .Y (n_14));
  AOI22X1HVT g2978(.A0 (i_data[16]), .A1 (n_4), .B0 (i_data[15]), .B1
       (i_shift_number[0]), .Y (n_13));
  INVX1HVT g2979(.A (n_11), .Y (n_10));
  INVX1HVT g2980(.A (n_0), .Y (n_9));
  NAND2X1HVT g2981(.A (i_shift_number[3]), .B (n_3), .Y (n_12));
  NOR2X1HVT g2982(.A (n_5), .B (i_shift_number[3]), .Y (n_11));
  NOR2X1HVT g2984(.A (i_shift_number[2]), .B (i_shift_number[1]), .Y
       (n_8));
  NOR2X1HVT g2985(.A (i_shift_number[1]), .B (i_shift_number[0]), .Y
       (n_7));
  NAND2X1HVT g2986(.A (n_5), .B (i_shift_number[3]), .Y (n_6));
  INVX1HVT g2988(.A (i_shift_number[4]), .Y (n_5));
  INVX2HVT g2989(.A (i_shift_number[0]), .Y (n_4));
  INVX1HVT g2990(.A (i_shift_number[2]), .Y (n_3));
  INVX2HVT g2991(.A (i_shift_number[1]), .Y (n_2));
  NAND2BX1HVT g2(.AN (i_shift_number[3]), .B (n_5), .Y (n_0));
endmodule

module NOR_unit_SIZE_LOPD5_SIZE_DATA32(i_overflow, i_zero_flag,
     i_one_position, i_mantissa, o_mantissa);
  input i_overflow, i_zero_flag;
  input [4:0] i_one_position;
  input [31:0] i_mantissa;
  output [31:0] o_mantissa;
  wire i_overflow, i_zero_flag;
  wire [4:0] i_one_position;
  wire [31:0] i_mantissa;
  wire [31:0] o_mantissa;
  wire [31:0] w_shift_left;
  wire UNCONNECTED1, UNCONNECTED2, UNCONNECTED3, UNCONNECTED4, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  assign o_mantissa[0] = 1'b0;
  assign o_mantissa[1] = 1'b0;
  assign o_mantissa[2] = 1'b0;
  SHF_left_SIZE_DATA32_SIZE_SHIFT5 SHF_left_unit(.i_shift_number
       (i_one_position), .i_data ({i_mantissa[31:4], 4'b0000}), .o_data
       ({w_shift_left[31:4], UNCONNECTED4, UNCONNECTED3, UNCONNECTED2,
       UNCONNECTED1}));
  OAI2BB1X1HVT g1425(.A0N (i_mantissa[30]), .A1N (n_2), .B0 (n_16), .Y
       (o_mantissa[30]));
  OAI2BB1X1HVT g1426(.A0N (i_mantissa[29]), .A1N (n_7), .B0 (n_25), .Y
       (o_mantissa[29]));
  OAI2BB1X1HVT g1427(.A0N (n_6), .A1N (w_shift_left[27]), .B0 (n_28),
       .Y (o_mantissa[27]));
  OAI2BB1X1HVT g1428(.A0N (n_6), .A1N (w_shift_left[22]), .B0 (n_30),
       .Y (o_mantissa[22]));
  OAI2BB1X1HVT g1429(.A0N (i_mantissa[13]), .A1N (n_7), .B0 (n_33), .Y
       (o_mantissa[13]));
  OAI2BB1X1HVT g1430(.A0N (n_6), .A1N (w_shift_left[12]), .B0 (n_31),
       .Y (o_mantissa[12]));
  OAI2BB1X1HVT g1431(.A0N (n_6), .A1N (w_shift_left[21]), .B0 (n_27),
       .Y (o_mantissa[21]));
  OAI2BB1X1HVT g1432(.A0N (n_6), .A1N (w_shift_left[11]), .B0 (n_29),
       .Y (o_mantissa[11]));
  OAI2BB1X1HVT g1433(.A0N (n_6), .A1N (w_shift_left[10]), .B0 (n_26),
       .Y (o_mantissa[10]));
  OAI2BB1X1HVT g1434(.A0N (n_6), .A1N (w_shift_left[26]), .B0 (n_20),
       .Y (o_mantissa[26]));
  OAI2BB1X1HVT g1435(.A0N (n_6), .A1N (w_shift_left[20]), .B0 (n_22),
       .Y (o_mantissa[20]));
  OAI2BB1X1HVT g1436(.A0N (n_6), .A1N (w_shift_left[9]), .B0 (n_24), .Y
       (o_mantissa[9]));
  OAI2BB1X1HVT g1437(.A0N (n_6), .A1N (w_shift_left[8]), .B0 (n_23), .Y
       (o_mantissa[8]));
  OAI2BB1X1HVT g1438(.A0N (n_6), .A1N (w_shift_left[14]), .B0 (n_34),
       .Y (o_mantissa[14]));
  OAI2BB1X1HVT g1439(.A0N (i_mantissa[19]), .A1N (n_7), .B0 (n_18), .Y
       (o_mantissa[19]));
  OAI2BB1X1HVT g1440(.A0N (n_6), .A1N (w_shift_left[6]), .B0 (n_19), .Y
       (o_mantissa[6]));
  OAI2BB1X1HVT g1441(.A0N (i_mantissa[5]), .A1N (n_7), .B0 (n_17), .Y
       (o_mantissa[5]));
  OAI2BB1X1HVT g1442(.A0N (n_6), .A1N (w_shift_left[28]), .B0 (n_21),
       .Y (o_mantissa[28]));
  OAI2BB1X1HVT g1443(.A0N (n_6), .A1N (w_shift_left[25]), .B0 (n_14),
       .Y (o_mantissa[25]));
  OAI2BB1X1HVT g1444(.A0N (i_mantissa[18]), .A1N (n_7), .B0 (n_13), .Y
       (o_mantissa[18]));
  OAI2BB1X1HVT g1445(.A0N (i_mantissa[4]), .A1N (n_7), .B0 (n_15), .Y
       (o_mantissa[4]));
  OAI2BB1X1HVT g1446(.A0N (i_mantissa[24]), .A1N (n_7), .B0 (n_10), .Y
       (o_mantissa[24]));
  OAI2BB1X1HVT g1447(.A0N (i_mantissa[17]), .A1N (n_7), .B0 (n_12), .Y
       (o_mantissa[17]));
  OAI2BB1X1HVT g1448(.A0N (n_6), .A1N (w_shift_left[16]), .B0 (n_11),
       .Y (o_mantissa[16]));
  OAI2BB1X1HVT g1449(.A0N (i_mantissa[23]), .A1N (n_7), .B0 (n_32), .Y
       (o_mantissa[23]));
  OAI2BB1X1HVT g1450(.A0N (n_6), .A1N (w_shift_left[15]), .B0 (n_9), .Y
       (o_mantissa[15]));
  OAI2BB1X1HVT g1451(.A0N (i_mantissa[7]), .A1N (n_7), .B0 (n_8), .Y
       (o_mantissa[7]));
  AOI22XLHVT g1452(.A0 (i_mantissa[14]), .A1 (n_7), .B0
       (i_mantissa[15]), .B1 (n_5), .Y (n_34));
  AOI22X1HVT g1453(.A0 (n_6), .A1 (w_shift_left[13]), .B0
       (i_mantissa[14]), .B1 (n_5), .Y (n_33));
  AOI22X1HVT g1454(.A0 (n_6), .A1 (w_shift_left[23]), .B0
       (i_mantissa[24]), .B1 (n_5), .Y (n_32));
  AOI22XLHVT g1455(.A0 (i_mantissa[12]), .A1 (n_7), .B0
       (i_mantissa[13]), .B1 (n_5), .Y (n_31));
  AOI22XLHVT g1456(.A0 (i_mantissa[22]), .A1 (n_7), .B0
       (i_mantissa[23]), .B1 (n_5), .Y (n_30));
  AOI22XLHVT g1457(.A0 (i_mantissa[11]), .A1 (n_7), .B0
       (i_mantissa[12]), .B1 (n_5), .Y (n_29));
  AOI22XLHVT g1458(.A0 (i_mantissa[27]), .A1 (n_7), .B0
       (i_mantissa[28]), .B1 (n_5), .Y (n_28));
  AOI22XLHVT g1459(.A0 (i_mantissa[21]), .A1 (n_7), .B0
       (i_mantissa[22]), .B1 (n_5), .Y (n_27));
  AOI22XLHVT g1460(.A0 (i_mantissa[10]), .A1 (n_7), .B0
       (i_mantissa[11]), .B1 (n_5), .Y (n_26));
  AOI22X1HVT g1461(.A0 (n_6), .A1 (w_shift_left[29]), .B0
       (i_mantissa[30]), .B1 (n_5), .Y (n_25));
  AOI22XLHVT g1462(.A0 (i_mantissa[9]), .A1 (n_7), .B0
       (i_mantissa[10]), .B1 (n_5), .Y (n_24));
  AOI22XLHVT g1463(.A0 (i_mantissa[8]), .A1 (n_7), .B0 (i_mantissa[9]),
       .B1 (n_5), .Y (n_23));
  AOI22XLHVT g1464(.A0 (i_mantissa[20]), .A1 (n_7), .B0
       (i_mantissa[21]), .B1 (n_5), .Y (n_22));
  AOI22XLHVT g1465(.A0 (i_mantissa[28]), .A1 (n_7), .B0
       (i_mantissa[29]), .B1 (n_5), .Y (n_21));
  AOI22XLHVT g1466(.A0 (i_mantissa[26]), .A1 (n_7), .B0
       (i_mantissa[27]), .B1 (n_5), .Y (n_20));
  AOI22X1HVT g1467(.A0 (i_mantissa[6]), .A1 (n_7), .B0 (i_mantissa[7]),
       .B1 (n_5), .Y (n_19));
  AOI22X1HVT g1468(.A0 (n_6), .A1 (w_shift_left[19]), .B0
       (i_mantissa[20]), .B1 (n_5), .Y (n_18));
  AOI22X1HVT g1469(.A0 (n_6), .A1 (w_shift_left[5]), .B0
       (i_mantissa[6]), .B1 (n_5), .Y (n_17));
  AOI22X1HVT g1470(.A0 (n_6), .A1 (w_shift_left[30]), .B0
       (i_mantissa[31]), .B1 (n_5), .Y (n_16));
  AOI22X1HVT g1471(.A0 (n_6), .A1 (w_shift_left[4]), .B0
       (i_mantissa[5]), .B1 (n_5), .Y (n_15));
  AOI22XLHVT g1472(.A0 (i_mantissa[25]), .A1 (n_7), .B0
       (i_mantissa[26]), .B1 (n_5), .Y (n_14));
  AOI22X1HVT g1473(.A0 (n_6), .A1 (w_shift_left[18]), .B0
       (i_mantissa[19]), .B1 (n_5), .Y (n_13));
  AOI22X1HVT g1474(.A0 (n_6), .A1 (w_shift_left[17]), .B0
       (i_mantissa[18]), .B1 (n_5), .Y (n_12));
  AOI22XLHVT g1475(.A0 (i_mantissa[16]), .A1 (n_7), .B0
       (i_mantissa[17]), .B1 (n_5), .Y (n_11));
  AOI22X1HVT g1476(.A0 (n_6), .A1 (w_shift_left[24]), .B0
       (i_mantissa[25]), .B1 (n_5), .Y (n_10));
  AOI22XLHVT g1477(.A0 (i_mantissa[15]), .A1 (n_7), .B0
       (i_mantissa[16]), .B1 (n_5), .Y (n_9));
  AOI22X1HVT g1478(.A0 (n_6), .A1 (w_shift_left[7]), .B0
       (i_mantissa[8]), .B1 (n_5), .Y (n_8));
  OAI211X1HVT g1479(.A0 (i_zero_flag), .A1 (n_0), .B0 (n_3), .C0 (n_4),
       .Y (o_mantissa[31]));
  AND2XLHVT g1480(.A (i_mantissa[4]), .B (n_5), .Y (o_mantissa[3]));
  NOR2X1HVT g1481(.A (i_overflow), .B (n_3), .Y (n_7));
  NOR2BX1HVT g1482(.AN (n_1), .B (i_zero_flag), .Y (n_6));
  INVX1HVT g1483(.A (n_5), .Y (n_4));
  NOR2BX1HVT g1484(.AN (i_overflow), .B (i_zero_flag), .Y (n_5));
  INVX1HVT g1485(.A (n_3), .Y (n_2));
  NOR2XLHVT g1486(.A (i_mantissa[31]), .B (i_overflow), .Y (n_1));
  NAND2BX1HVT g1487(.AN (i_zero_flag), .B (i_mantissa[31]), .Y (n_3));
  INVX1HVT g1488(.A (w_shift_left[31]), .Y (n_0));
endmodule

module PSC_unit(i_add_sub, i_sign_a, i_exp_a, i_man_a, i_sign_b,
     i_exp_b, i_man_b, o_sel_exp, o_sel_man);
  input i_add_sub, i_sign_a, i_sign_b;
  input [7:0] i_exp_a, i_exp_b;
  input [23:0] i_man_a, i_man_b;
  output o_sel_exp;
  output [1:0] o_sel_man;
  wire i_add_sub, i_sign_a, i_sign_b;
  wire [7:0] i_exp_a, i_exp_b;
  wire [23:0] i_man_a, i_man_b;
  wire o_sel_exp;
  wire [1:0] o_sel_man;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_31;
  OAI2BB1X1HVT g623(.A0N (n_21), .A1N (n_31), .B0 (n_29), .Y
       (o_sel_exp));
  OAI32X1HVT g624(.A0 (n_19), .A1 (n_26), .A2 (n_24), .B0 (i_sign_b),
       .B1 (n_25), .Y (n_31));
  OAI2BB1X1HVT g625(.A0N (n_21), .A1N (n_27), .B0 (n_28), .Y
       (o_sel_man[0]));
  NAND3BXLHVT g626(.AN (i_sign_a), .B (n_20), .C (n_26), .Y (n_29));
  NAND2X1HVT g627(.A (n_20), .B (n_26), .Y (n_28));
  OAI2BB1X1HVT g628(.A0N (n_20), .A1N (n_22), .B0 (n_25), .Y (n_27));
  NAND4XLHVT g629(.A (n_3), .B (n_7), .C (n_16), .D (n_18), .Y (n_26));
  INVX1HVT g630(.A (n_24), .Y (n_25));
  NAND4XLHVT g631(.A (n_14), .B (n_6), .C (n_15), .D (n_17), .Y (n_24));
  NAND2BX1HVT g632(.AN (n_21), .B (n_19), .Y (o_sel_man[1]));
  XNOR2X1HVT g633(.A (i_add_sub), .B (n_8), .Y (n_22));
  INVX1HVT g634(.A (n_20), .Y (n_19));
  AND2XLHVT g635(.A (n_2), .B (n_5), .Y (n_18));
  NOR2X1HVT g636(.A (n_10), .B (n_12), .Y (n_21));
  NOR2X1HVT g637(.A (n_13), .B (n_11), .Y (n_20));
  AND2XLHVT g638(.A (n_0), .B (n_1), .Y (n_17));
  NOR4X1HVT g639(.A (i_man_a[10]), .B (i_man_a[15]), .C (i_man_a[4]),
       .D (n_9), .Y (n_16));
  NOR4X1HVT g640(.A (i_man_b[3]), .B (i_man_b[18]), .C (i_man_b[13]),
       .D (n_4), .Y (n_15));
  NOR4X1HVT g641(.A (i_man_b[14]), .B (i_man_b[19]), .C (i_man_b[20]),
       .D (i_man_b[21]), .Y (n_14));
  NAND4XLHVT g642(.A (i_exp_a[4]), .B (i_exp_a[7]), .C (i_exp_a[5]), .D
       (i_exp_a[6]), .Y (n_13));
  NAND4XLHVT g643(.A (i_exp_b[0]), .B (i_exp_b[3]), .C (i_exp_b[1]), .D
       (i_exp_b[2]), .Y (n_12));
  NAND4XLHVT g644(.A (i_exp_a[0]), .B (i_exp_a[3]), .C (i_exp_a[1]), .D
       (i_exp_a[2]), .Y (n_11));
  NAND4XLHVT g645(.A (i_exp_b[4]), .B (i_exp_b[7]), .C (i_exp_b[5]), .D
       (i_exp_b[6]), .Y (n_10));
  OR4X1HVT g646(.A (i_man_a[8]), .B (i_man_a[9]), .C (i_man_a[11]), .D
       (i_man_a[18]), .Y (n_9));
  XNOR2X1HVT g647(.A (i_sign_b), .B (i_sign_a), .Y (n_8));
  NOR4X1HVT g648(.A (i_man_a[0]), .B (i_man_a[1]), .C (i_man_a[5]), .D
       (i_man_a[6]), .Y (n_7));
  NOR4X1HVT g649(.A (i_man_b[1]), .B (i_man_b[2]), .C (i_man_b[15]), .D
       (i_man_b[22]), .Y (n_6));
  NOR4X1HVT g650(.A (i_man_a[16]), .B (i_man_a[17]), .C (i_man_a[20]),
       .D (i_man_a[21]), .Y (n_5));
  OR4X1HVT g651(.A (i_man_b[4]), .B (i_man_b[5]), .C (i_man_b[16]), .D
       (i_man_b[17]), .Y (n_4));
  NOR4X1HVT g652(.A (i_man_a[2]), .B (i_man_a[7]), .C (i_man_a[12]), .D
       (i_man_a[13]), .Y (n_3));
  NOR4X1HVT g653(.A (i_man_a[3]), .B (i_man_a[22]), .C (i_man_a[14]),
       .D (i_man_a[19]), .Y (n_2));
  NOR4X1HVT g654(.A (i_man_b[7]), .B (i_man_b[8]), .C (i_man_b[9]), .D
       (i_man_b[10]), .Y (n_1));
  NOR4X1HVT g655(.A (i_man_b[0]), .B (i_man_b[6]), .C (i_man_b[11]), .D
       (i_man_b[12]), .Y (n_0));
endmodule

module SHF_right_SIZE_DATA32_SIZE_SHIFT5(i_shift_number, i_data,
     o_data);
  input [4:0] i_shift_number;
  input [31:0] i_data;
  output [31:0] o_data;
  wire [4:0] i_shift_number;
  wire [31:0] i_data;
  wire [31:0] o_data;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_44, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_98, n_99, n_100, n_101, n_104, n_107, n_108;
  wire n_109, n_110, n_118, n_123;
  assign o_data[0] = 1'b0;
  assign o_data[1] = 1'b0;
  assign o_data[2] = 1'b0;
  assign o_data[3] = 1'b0;
  OAI221X1HVT g3642(.A0 (n_5), .A1 (n_109), .B0 (n_67), .B1 (n_28), .C0
       (n_118), .Y (o_data[7]));
  OAI221X1HVT g3643(.A0 (n_83), .A1 (n_6), .B0 (n_72), .B1 (n_28), .C0
       (n_123), .Y (o_data[6]));
  OAI222X1HVT g3644(.A0 (n_110), .A1 (n_5), .B0 (n_80), .B1 (n_6), .C0
       (n_49), .C1 (n_28), .Y (o_data[4]));
  OAI221X1HVT g3645(.A0 (n_107), .A1 (n_5), .B0 (n_3), .B1 (n_44), .C0
       (n_100), .Y (o_data[5]));
  OAI22X1HVT g3646(.A0 (i_shift_number[4]), .A1 (n_104), .B0 (n_62),
       .B1 (n_31), .Y (o_data[13]));
  AOI32X1HVT g3647(.A0 (n_36), .A1 (i_shift_number[1]), .A2 (n_26), .B0
       (i_shift_number[4]), .B1 (n_108), .Y (n_123));
  NOR2X1HVT g3648(.A (i_shift_number[4]), .B (n_107), .Y (o_data[21]));
  NOR2X1HVT g3649(.A (i_shift_number[4]), .B (n_110), .Y (o_data[20]));
  AND2X1HVT g3650(.A (n_108), .B (n_5), .Y (o_data[22]));
  NOR2X1HVT g3651(.A (i_shift_number[4]), .B (n_109), .Y (o_data[23]));
  AOI31X1HVT g3652(.A0 (n_39), .A1 (i_shift_number[1]), .A2 (n_26), .B0
       (n_98), .Y (n_118));
  OAI222X1HVT g3653(.A0 (n_83), .A1 (n_0), .B0 (n_30), .B1 (n_31), .C0
       (n_84), .C1 (n_6), .Y (o_data[14]));
  OAI222X1HVT g3654(.A0 (n_80), .A1 (n_0), .B0 (n_47), .B1 (n_31), .C0
       (n_79), .C1 (n_6), .Y (o_data[12]));
  OAI222X1HVT g3655(.A0 (n_32), .A1 (n_8), .B0 (n_78), .B1 (n_0), .C0
       (n_90), .C1 (n_6), .Y (o_data[15]));
  OAI221X1HVT g3656(.A0 (n_92), .A1 (n_6), .B0 (n_67), .B1 (n_27), .C0
       (n_99), .Y (o_data[11]));
  OAI222X1HVT g3657(.A0 (n_89), .A1 (n_6), .B0 (n_86), .B1 (n_0), .C0
       (n_76), .C1 (n_8), .Y (o_data[9]));
  OAI222X1HVT g3658(.A0 (n_93), .A1 (n_6), .B0 (n_85), .B1 (n_0), .C0
       (n_88), .C1 (n_8), .Y (o_data[8]));
  OAI221X1HVT g3659(.A0 (n_87), .A1 (n_8), .B0 (n_57), .B1 (n_28), .C0
       (n_101), .Y (o_data[10]));
  OAI22X1HVT g3660(.A0 (n_92), .A1 (n_0), .B0 (n_77), .B1 (n_6), .Y
       (o_data[19]));
  OAI22X1HVT g3661(.A0 (n_91), .A1 (n_0), .B0 (n_87), .B1 (n_6), .Y
       (o_data[18]));
  OA22X1HVT g3662(.A0 (i_shift_number[3]), .A1 (n_79), .B0 (n_47), .B1
       (n_9), .Y (n_110));
  MX2XLHVT g3663(.A (n_90), .B (n_32), .S0 (i_shift_number[3]), .Y
       (n_109));
  OAI22X1HVT g3664(.A0 (i_shift_number[3]), .A1 (n_84), .B0 (n_30), .B1
       (n_9), .Y (n_108));
  OA22X1HVT g3665(.A0 (i_shift_number[3]), .A1 (n_82), .B0 (n_62), .B1
       (n_9), .Y (n_107));
  MX2XLHVT g3666(.A (n_81), .B (n_82), .S0 (i_shift_number[3]), .Y
       (n_104));
  OAI22X1HVT g3667(.A0 (n_89), .A1 (n_0), .B0 (n_76), .B1 (n_6), .Y
       (o_data[17]));
  OAI22X1HVT g3668(.A0 (n_93), .A1 (n_0), .B0 (n_88), .B1 (n_6), .Y
       (o_data[16]));
  OA22X1HVT g3669(.A0 (n_91), .A1 (n_6), .B0 (n_72), .B1 (n_27), .Y
       (n_101));
  OA22X1HVT g3670(.A0 (n_81), .A1 (n_6), .B0 (n_68), .B1 (n_28), .Y
       (n_100));
  OA22X1HVT g3671(.A0 (n_77), .A1 (n_8), .B0 (n_54), .B1 (n_28), .Y
       (n_99));
  OAI22X1HVT g3672(.A0 (n_78), .A1 (n_6), .B0 (i_shift_number[1]), .B1
       (n_44), .Y (n_98));
  NOR2X1HVT g3673(.A (n_87), .B (n_0), .Y (o_data[26]));
  NOR2X1HVT g3674(.A (n_88), .B (n_0), .Y (o_data[24]));
  NOR2X1HVT g3675(.A (n_76), .B (n_0), .Y (o_data[25]));
  NOR2X1HVT g3676(.A (n_77), .B (n_0), .Y (o_data[27]));
  AOI22X1HVT g3677(.A0 (n_69), .A1 (n_4), .B0 (n_52), .B1
       (i_shift_number[2]), .Y (n_86));
  AOI22XLHVT g3678(.A0 (n_4), .A1 (n_48), .B0 (i_shift_number[2]), .B1
       (n_50), .Y (n_85));
  AOI22X1HVT g3679(.A0 (n_64), .A1 (n_4), .B0 (n_55), .B1
       (i_shift_number[2]), .Y (n_93));
  AOI22X1HVT g3680(.A0 (n_70), .A1 (n_4), .B0 (n_58), .B1
       (i_shift_number[2]), .Y (n_92));
  AOI22X1HVT g3681(.A0 (n_66), .A1 (n_4), .B0 (i_shift_number[2]), .B1
       (n_59), .Y (n_91));
  AOI22X1HVT g3682(.A0 (n_58), .A1 (n_4), .B0 (i_shift_number[2]), .B1
       (n_73), .Y (n_90));
  AOI22X1HVT g3683(.A0 (n_65), .A1 (n_4), .B0 (n_60), .B1
       (i_shift_number[2]), .Y (n_89));
  AOI22X1HVT g3684(.A0 (n_4), .A1 (n_71), .B0 (n_46), .B1
       (i_shift_number[2]), .Y (n_88));
  AOI22X1HVT g3685(.A0 (n_63), .A1 (n_4), .B0 (n_29), .B1
       (i_shift_number[2]), .Y (n_87));
  AOI22X1HVT g3686(.A0 (n_59), .A1 (n_4), .B0 (i_shift_number[2]), .B1
       (n_63), .Y (n_84));
  AOI22X1HVT g3687(.A0 (n_56), .A1 (n_4), .B0 (i_shift_number[2]), .B1
       (n_66), .Y (n_83));
  AOI22XLHVT g3688(.A0 (n_4), .A1 (n_60), .B0 (i_shift_number[2]), .B1
       (n_51), .Y (n_82));
  AOI22XLHVT g3689(.A0 (n_4), .A1 (n_52), .B0 (i_shift_number[2]), .B1
       (n_65), .Y (n_81));
  AOI22X1HVT g3690(.A0 (n_50), .A1 (n_4), .B0 (i_shift_number[2]), .B1
       (n_64), .Y (n_80));
  AOI22X1HVT g3691(.A0 (n_4), .A1 (n_55), .B0 (n_71), .B1
       (i_shift_number[2]), .Y (n_79));
  AOI22X1HVT g3692(.A0 (n_53), .A1 (n_4), .B0 (i_shift_number[2]), .B1
       (n_70), .Y (n_78));
  AOI32X1HVT g3693(.A0 (n_2), .A1 (n_3), .A2 (i_shift_number[2]), .B0
       (n_73), .B1 (n_4), .Y (n_77));
  AOI22X1HVT g3694(.A0 (n_51), .A1 (n_4), .B0 (n_61), .B1
       (i_shift_number[2]), .Y (n_76));
  NOR2X1HVT g3695(.A (n_47), .B (n_27), .Y (o_data[28]));
  NOR2X1HVT g3696(.A (n_62), .B (n_27), .Y (o_data[29]));
  INVX1HVT g3697(.A (n_68), .Y (n_69));
  INVX1HVT g3698(.A (n_61), .Y (n_62));
  OAI22X1HVT g3699(.A0 (n_22), .A1 (i_shift_number[1]), .B0 (n_12), .B1
       (n_3), .Y (n_73));
  OA22X1HVT g3700(.A0 (n_42), .A1 (i_shift_number[1]), .B0 (n_20), .B1
       (n_3), .Y (n_72));
  OAI22X1HVT g3701(.A0 (n_40), .A1 (i_shift_number[1]), .B0 (n_19), .B1
       (n_3), .Y (n_71));
  OAI22X1HVT g3702(.A0 (n_38), .A1 (i_shift_number[1]), .B0 (n_14), .B1
       (n_3), .Y (n_70));
  AOI22XLHVT g3703(.A0 (n_39), .A1 (n_3), .B0 (n_34), .B1
       (i_shift_number[1]), .Y (n_68));
  OA22X1HVT g3704(.A0 (n_33), .A1 (i_shift_number[1]), .B0 (n_37), .B1
       (n_3), .Y (n_67));
  OAI22X1HVT g3705(.A0 (n_15), .A1 (i_shift_number[1]), .B0 (n_18), .B1
       (n_3), .Y (n_66));
  OAI22X1HVT g3706(.A0 (n_41), .A1 (i_shift_number[1]), .B0 (n_38), .B1
       (n_3), .Y (n_65));
  OAI22X1HVT g3707(.A0 (n_21), .A1 (i_shift_number[1]), .B0 (n_15), .B1
       (n_3), .Y (n_64));
  OAI22X1HVT g3708(.A0 (n_19), .A1 (i_shift_number[1]), .B0 (n_16), .B1
       (n_3), .Y (n_63));
  OAI22X1HVT g3709(.A0 (n_12), .A1 (i_shift_number[1]), .B0
       (i_shift_number[0]), .B1 (n_3), .Y (n_61));
  INVX1HVT g3710(.A (n_56), .Y (n_57));
  INVX1HVT g3711(.A (n_53), .Y (n_54));
  INVX1HVT g3712(.A (n_48), .Y (n_49));
  INVX1HVT g3713(.A (n_46), .Y (n_47));
  OAI22X1HVT g3714(.A0 (n_14), .A1 (i_shift_number[1]), .B0 (n_23), .B1
       (n_3), .Y (n_60));
  OAI22X1HVT g3715(.A0 (n_17), .A1 (i_shift_number[1]), .B0 (n_40), .B1
       (n_3), .Y (n_59));
  OAI22X1HVT g3716(.A0 (n_23), .A1 (i_shift_number[1]), .B0 (n_13), .B1
       (n_3), .Y (n_58));
  OAI22X1HVT g3717(.A0 (n_24), .A1 (i_shift_number[1]), .B0 (n_21), .B1
       (n_3), .Y (n_56));
  OAI22X1HVT g3718(.A0 (n_18), .A1 (i_shift_number[1]), .B0 (n_17), .B1
       (n_3), .Y (n_55));
  OAI22X1HVT g3719(.A0 (n_25), .A1 (i_shift_number[1]), .B0 (n_41), .B1
       (n_3), .Y (n_53));
  OAI22X1HVT g3720(.A0 (n_37), .A1 (i_shift_number[1]), .B0 (n_25), .B1
       (n_3), .Y (n_52));
  OAI22X1HVT g3721(.A0 (n_13), .A1 (i_shift_number[1]), .B0 (n_22), .B1
       (n_3), .Y (n_51));
  OAI22XLHVT g3722(.A0 (n_20), .A1 (i_shift_number[1]), .B0 (n_24), .B1
       (n_3), .Y (n_50));
  OAI22XLHVT g3723(.A0 (n_35), .A1 (i_shift_number[1]), .B0 (n_42), .B1
       (n_3), .Y (n_48));
  OAI22X1HVT g3724(.A0 (n_16), .A1 (i_shift_number[1]), .B0 (n_11), .B1
       (n_3), .Y (n_46));
  NOR2X1HVT g3725(.A (n_30), .B (n_27), .Y (o_data[30]));
  NOR2X1HVT g3726(.A (n_32), .B (n_0), .Y (o_data[31]));
  NAND4XLHVT g3727(.A (i_data[8]), .B (i_shift_number[0]), .C (n_4), .D
       (n_10), .Y (n_44));
  INVX1HVT g3728(.A (n_35), .Y (n_36));
  INVX1HVT g3729(.A (n_33), .Y (n_34));
  INVX1HVT g3730(.A (n_29), .Y (n_30));
  INVX1HVT g3731(.A (n_27), .Y (n_26));
  AOI22XLHVT g3732(.A0 (i_data[10]), .A1 (n_2), .B0 (i_data[11]), .B1
       (i_shift_number[0]), .Y (n_42));
  AOI22X1HVT g3733(.A0 (i_data[17]), .A1 (n_2), .B0 (i_data[18]), .B1
       (i_shift_number[0]), .Y (n_41));
  AOI22X1HVT g3734(.A0 (i_data[24]), .A1 (n_2), .B0 (i_data[25]), .B1
       (i_shift_number[0]), .Y (n_40));
  MX2XLHVT g3735(.A (i_data[9]), .B (i_data[10]), .S0
       (i_shift_number[0]), .Y (n_39));
  AOI22X1HVT g3736(.A0 (i_data[19]), .A1 (n_2), .B0 (i_data[20]), .B1
       (i_shift_number[0]), .Y (n_38));
  AOI22XLHVT g3737(.A0 (i_data[13]), .A1 (n_2), .B0 (i_data[14]), .B1
       (i_shift_number[0]), .Y (n_37));
  AOI22XLHVT g3738(.A0 (i_data[8]), .A1 (n_2), .B0 (i_data[9]), .B1
       (i_shift_number[0]), .Y (n_35));
  AOI22X1HVT g3739(.A0 (i_data[11]), .A1 (n_2), .B0 (i_data[12]), .B1
       (i_shift_number[0]), .Y (n_33));
  NAND3X1HVT g3740(.A (n_2), .B (n_3), .C (n_4), .Y (n_32));
  NAND2X1HVT g3741(.A (n_4), .B (n_7), .Y (n_31));
  NOR2XLHVT g3742(.A (n_11), .B (i_shift_number[1]), .Y (n_29));
  NAND2X1HVT g3743(.A (i_shift_number[2]), .B (n_10), .Y (n_28));
  NAND2X1HVT g3744(.A (n_4), .B (n_10), .Y (n_27));
  AOI22X1HVT g3745(.A0 (i_data[15]), .A1 (n_2), .B0 (i_data[16]), .B1
       (i_shift_number[0]), .Y (n_25));
  AOI22X1HVT g3746(.A0 (i_data[14]), .A1 (n_2), .B0 (i_data[15]), .B1
       (i_shift_number[0]), .Y (n_24));
  AOI22X1HVT g3747(.A0 (i_data[23]), .A1 (n_2), .B0 (i_data[24]), .B1
       (i_shift_number[0]), .Y (n_23));
  AOI22X1HVT g3748(.A0 (i_data[27]), .A1 (n_2), .B0 (i_data[28]), .B1
       (i_shift_number[0]), .Y (n_22));
  AOI22X1HVT g3749(.A0 (i_data[16]), .A1 (n_2), .B0 (i_data[17]), .B1
       (i_shift_number[0]), .Y (n_21));
  AOI22XLHVT g3750(.A0 (i_data[12]), .A1 (n_2), .B0 (i_data[13]), .B1
       (i_shift_number[0]), .Y (n_20));
  AOI22X1HVT g3751(.A0 (i_data[26]), .A1 (n_2), .B0 (i_data[27]), .B1
       (i_shift_number[0]), .Y (n_19));
  AOI22X1HVT g3752(.A0 (i_data[20]), .A1 (n_2), .B0 (i_data[21]), .B1
       (i_shift_number[0]), .Y (n_18));
  AOI22X1HVT g3753(.A0 (i_data[22]), .A1 (n_2), .B0 (i_data[23]), .B1
       (i_shift_number[0]), .Y (n_17));
  AOI22X1HVT g3754(.A0 (i_data[28]), .A1 (n_2), .B0 (i_data[29]), .B1
       (i_shift_number[0]), .Y (n_16));
  AOI22X1HVT g3755(.A0 (i_data[18]), .A1 (n_2), .B0 (i_data[19]), .B1
       (i_shift_number[0]), .Y (n_15));
  AOI22X1HVT g3756(.A0 (i_data[21]), .A1 (n_2), .B0 (i_data[22]), .B1
       (i_shift_number[0]), .Y (n_14));
  AOI22X1HVT g3757(.A0 (i_data[25]), .A1 (n_2), .B0 (i_data[26]), .B1
       (i_shift_number[0]), .Y (n_13));
  AOI22X1HVT g3758(.A0 (i_data[29]), .A1 (n_2), .B0 (i_data[30]), .B1
       (i_shift_number[0]), .Y (n_12));
  INVX1HVT g3759(.A (n_0), .Y (n_10));
  NOR2XLHVT g3760(.A (i_data[30]), .B (i_shift_number[0]), .Y (n_11));
  INVX1HVT g3762(.A (n_7), .Y (n_8));
  NAND2X1HVT g3763(.A (n_4), .B (i_shift_number[3]), .Y (n_9));
  NOR2X1HVT g3764(.A (i_shift_number[3]), .B (n_5), .Y (n_7));
  NAND2X1HVT g3765(.A (i_shift_number[3]), .B (n_5), .Y (n_6));
  INVX1HVT g3766(.A (i_shift_number[4]), .Y (n_5));
  INVX2HVT g3767(.A (i_shift_number[2]), .Y (n_4));
  INVX2HVT g3768(.A (i_shift_number[1]), .Y (n_3));
  INVX2HVT g3770(.A (i_shift_number[0]), .Y (n_2));
  NAND2BX1HVT g2(.AN (i_shift_number[3]), .B (n_5), .Y (n_0));
endmodule

module SIGN_unit(i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b,
     o_sign_s);
  input i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b;
  output o_sign_s;
  wire i_add_sub, i_comp_man, i_sign_man_a, i_sign_man_b;
  wire o_sign_s;
  wire n_0;
  CLKMX2X6HVT g53(.A (i_sign_man_a), .B (n_0), .S0 (i_comp_man), .Y
       (o_sign_s));
  XOR2XLHVT g54(.A (i_sign_man_b), .B (i_add_sub), .Y (n_0));
endmodule

module FPU_unit(i_add_sub, i_32_a, i_32_b, o_32_s, o_ov_flag,
     o_un_flag);
  input [0:0] i_add_sub;
  input [31:0] i_32_a, i_32_b;
  output [31:0] o_32_s;
  output o_ov_flag, o_un_flag;
  wire [0:0] i_add_sub;
  wire [31:0] i_32_a, i_32_b;
  wire [31:0] o_32_s;
  wire o_ov_flag, o_un_flag;
  wire [23:0] MAN_ALU_man_alu;
  wire [4:0] LOPD_o_one_position;
  wire [7:0] EXP_SWAP_o_max;
  wire [7:0] EXP_ADJUST_exp_result;
  wire [7:0] EXP_RND_exp;
  wire [7:0] EXP_SWAP_o_min;
  wire [7:0] EXP_SUB_o_sub;
  wire [23:0] MAN_SWAP_max;
  wire [23:0] MAN_SWAP_min;
  wire [31:0] SHF_RIGHT_MAN_o_data;
  wire [3:0] CLS_MAN_ALU_o_data;
  wire [23:0] MAN_SWAP_PRE_man_max;
  wire [31:0] NOR_o_man;
  wire [23:0] MAN_RND_man;
  wire [23:0] MAN_SWAP_PRE_man_min;
  wire [1:0] PSC_sel_man;
  wire CLS_MAN_ALU_bout, EXP_COMP_o_compare, LOPD_o_zero_flag,
       MAN_ALU_ov_flag, MAN_COM_o_compare, MAN_RND_ov_flag,
       PSC_sel_exp, UNCONNECTED5;
  wire UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, UNCONNECTED9,
       UNCONNECTED10, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_92;
  EXP_adjust_SIZE_EXP8_SIZE_LOPD8 EXP_ADJUST(.i_overflow
       (MAN_ALU_ov_flag), .i_underflow (MAN_ALU_man_alu[23]),
       .i_zero_flag (LOPD_o_zero_flag), .i_lopd_value ({3'b000,
       LOPD_o_one_position}), .i_exp_value (EXP_SWAP_o_max),
       .o_exp_result (EXP_ADJUST_exp_result));
  EXP_comp_SIZE_DATA8 EXP_COM_8BIT(.i_data_a ({n_89, n_88, n_87, n_86,
       n_85, n_84, n_83, n_82}), .i_data_b ({n_81, n_80, n_79, n_78,
       n_77, n_76, n_75, n_74}), .o_compare (EXP_COMP_o_compare));
  EXP_rounding_SIZE_DATA8 EXP_RND(.i_carry_rounding (MAN_RND_ov_flag),
       .i_exp_result (EXP_ADJUST_exp_result), .o_exp_result
       (EXP_RND_exp));
  EXP_sub_SIZE_EXP_SUB8 EXP_SUB(.i_data_a ({3'b000,
       EXP_SWAP_o_max[4:0]}), .i_data_b ({3'b000,
       EXP_SWAP_o_min[4:0]}), .o_sub (EXP_SUB_o_sub));
  EXP_swap_SIZE_DATA8 EXP_SWAP(.i_data_a ({n_89, n_88, n_87, n_86,
       n_85, n_84, n_83, n_82}), .i_data_b ({n_81, n_80, n_79, n_78,
       n_77, n_76, n_75, n_74}), .i_compare (EXP_COMP_o_compare),
       .o_less_data (EXP_SWAP_o_min), .o_greater_data (EXP_SWAP_o_max));
  LOPD_24bit_SIZE_DATA24_SIZE_LOPD5 LOPD_24BIT(.i_data
       (MAN_ALU_man_alu), .o_one_position (LOPD_o_one_position),
       .o_zero_flag (LOPD_o_zero_flag));
  MAN_ALU_NUM_OP1_SIZE_MAN24 MAN_ALU(.i_fpu_op (n_72), .i_sign_a
       (n_71), .i_sign_b (n_47), .i_carry (CLS_MAN_ALU_bout),
       .i_man_max (MAN_SWAP_max), .i_man_min (MAN_SWAP_min), .o_man_alu
       (MAN_ALU_man_alu), .o_overflow (MAN_ALU_ov_flag));
  CLS_4bit MAN_ALU_PROC_RND(.A (4'b0000), .B
       (SHF_RIGHT_MAN_o_data[7:4]), .Bin (1'b0), .SUB
       ({CLS_MAN_ALU_o_data[3:1], UNCONNECTED5}), .Bout
       (CLS_MAN_ALU_bout));
  COMP_24bit_SIZE_DATA24 MAN_COMP_24BIT(.i_data_a ({1'b1,
       MAN_SWAP_PRE_man_max[22:0]}), .i_data_b
       (SHF_RIGHT_MAN_o_data[31:8]), .o_less (MAN_COM_o_compare));
  MAN_rounding_SIZE_MAN32_SIZE_MAN_RESULT24 MAN_RND(.i_man
       ({NOR_o_man[31:3], 3'b000}), .o_man_result (MAN_RND_man),
       .o_ov_flow (MAN_RND_ov_flag));
  MAN_swap_SIZE_MAN24_1 MAN_SWAP(.i_man_a ({1'b1,
       MAN_SWAP_PRE_man_max[22:0]}), .i_man_b
       (SHF_RIGHT_MAN_o_data[31:8]), .i_compare (MAN_COM_o_compare),
       .o_man_max (MAN_SWAP_max), .o_man_min (MAN_SWAP_min));
  MAN_swap_SIZE_MAN24 MAN_SWAP_PRE(.i_man_a ({1'b1, n_70, n_69, n_68,
       n_67, n_66, n_65, n_64, n_63, n_62, n_61, n_60, n_59, n_58,
       n_57, n_56, n_55, n_54, n_53, n_52, n_51, n_50, n_49, n_48}),
       .i_man_b ({1'b1, n_46, n_45, n_44, n_43, n_42, n_41, n_40, n_39,
       n_38, n_37, n_36, n_35, n_34, n_33, n_32, n_31, n_30, n_29,
       n_28, n_27, n_26, n_25, n_24}), .i_compare (EXP_COMP_o_compare),
       .o_man_max ({UNCONNECTED6, MAN_SWAP_PRE_man_max[22:0]}),
       .o_man_min ({UNCONNECTED7, MAN_SWAP_PRE_man_min[22:0]}));
  NOR_unit_SIZE_LOPD5_SIZE_DATA32 NOR_UNIT(.i_overflow
       (MAN_ALU_ov_flag), .i_zero_flag (LOPD_o_zero_flag),
       .i_one_position (LOPD_o_one_position), .i_mantissa
       ({MAN_ALU_man_alu, CLS_MAN_ALU_o_data[3:1],
       SHF_RIGHT_MAN_o_data[4], 4'b0000}), .o_mantissa
       ({NOR_o_man[31:3], UNCONNECTED10, UNCONNECTED9, UNCONNECTED8}));
  PSC_unit PSC_UNIT(.i_add_sub (n_72), .i_sign_a (n_71), .i_exp_a
       ({n_89, n_88, n_87, n_86, n_85, n_84, n_83, n_82}), .i_man_a
       ({1'b1, n_70, n_69, n_68, n_67, n_66, n_65, n_64, n_63, n_62,
       n_61, n_60, n_59, n_58, n_57, n_56, n_55, n_54, n_53, n_52,
       n_51, n_50, n_49, n_48}), .i_sign_b (n_47), .i_exp_b ({n_81,
       n_80, n_79, n_78, n_77, n_76, n_75, n_74}), .i_man_b ({1'b1,
       n_46, n_45, n_44, n_43, n_42, n_41, n_40, n_39, n_38, n_37,
       n_36, n_35, n_34, n_33, n_32, n_31, n_30, n_29, n_28, n_27,
       n_26, n_25, n_24}), .o_sel_exp (PSC_sel_exp), .o_sel_man
       (PSC_sel_man));
  SHF_right_SIZE_DATA32_SIZE_SHIFT5 SHF_RIGHT_MAN(.i_shift_number
       (EXP_SUB_o_sub[4:0]), .i_data ({1'b1,
       MAN_SWAP_PRE_man_min[22:0], 8'b00000000}), .o_data
       (SHF_RIGHT_MAN_o_data));
  SIGN_unit SIGN_UNIT(.i_add_sub (n_72), .i_comp_man (n_92),
       .i_sign_man_a (n_71), .i_sign_man_b (n_47), .o_sign_s
       (o_32_s[31]));
  CLKINVX6HVT g90(.A (MAN_ALU_man_alu[23]), .Y (o_un_flag));
  BUFX2HVT g135(.A (i_32_a[14]), .Y (n_62));
  BUFX2HVT g103(.A (i_32_b[12]), .Y (n_36));
  BUFX2HVT g98(.A (i_32_b[14]), .Y (n_38));
  BUFX2HVT g100(.A (i_32_b[17]), .Y (n_41));
  BUFX2HVT g130(.A (i_32_b[8]), .Y (n_32));
  BUFX2HVT g144(.A (i_32_a[10]), .Y (n_58));
  BUFX2HVT g96(.A (i_32_a[2]), .Y (n_50));
  BUFX2HVT g133(.A (i_32_a[21]), .Y (n_69));
  BUFX2HVT g95(.A (i_32_b[3]), .Y (n_27));
  BUFX2HVT g147(.A (i_32_b[18]), .Y (n_42));
  BUFX2HVT g97(.A (i_32_b[10]), .Y (n_34));
  BUFX2HVT g128(.A (i_32_b[5]), .Y (n_29));
  BUFX2HVT g136(.A (i_32_a[11]), .Y (n_59));
  BUFX2HVT g106(.A (i_32_a[12]), .Y (n_60));
  BUFX2HVT g91(.A (i_32_b[16]), .Y (n_40));
  BUFX2HVT g140(.A (i_32_a[9]), .Y (n_57));
  BUFX2HVT g101(.A (i_32_a[4]), .Y (n_52));
  BUFX2HVT g99(.A (i_32_a[16]), .Y (n_64));
  BUFX2HVT g129(.A (i_32_b[19]), .Y (n_43));
  BUFX2HVT g105(.A (i_32_b[4]), .Y (n_28));
  BUFX2HVT g134(.A (i_32_b[21]), .Y (n_45));
  BUFX2HVT g107(.A (i_32_b[2]), .Y (n_26));
  BUFX2HVT g124(.A (i_32_a[5]), .Y (n_53));
  BUFX2HVT g146(.A (i_32_b[1]), .Y (n_25));
  BUFX2HVT g119(.A (i_32_a[24]), .Y (n_83));
  BUFX2HVT g122(.A (i_32_a[27]), .Y (n_86));
  BUFX2HVT g154(.A (i_32_a[26]), .Y (n_85));
  BUFX2HVT g149(.A (i_32_b[28]), .Y (n_79));
  BUFX2HVT g148(.A (i_32_a[25]), .Y (n_84));
  BUFX2HVT g151(.A (i_32_b[31]), .Y (n_47));
  BUFX2HVT g155(.A (i_32_a[28]), .Y (n_87));
  BUFX2HVT g116(.A (i_32_b[29]), .Y (n_80));
  BUFX2HVT g131(.A (i_32_a[18]), .Y (n_66));
  BUFX2HVT g92(.A (i_32_a[22]), .Y (n_70));
  BUFX2HVT g137(.A (i_32_b[6]), .Y (n_30));
  BUFX2HVT g126(.A (i_32_a[8]), .Y (n_56));
  BUFX2HVT g139(.A (i_32_a[3]), .Y (n_51));
  BUFX2HVT g127(.A (i_32_a[0]), .Y (n_48));
  BUFX2HVT g145(.A (i_32_b[9]), .Y (n_33));
  BUFX2HVT g123(.A (i_32_b[22]), .Y (n_46));
  BUFX2HVT g94(.A (i_32_a[13]), .Y (n_61));
  BUFX2HVT g108(.A (i_32_a[17]), .Y (n_65));
  BUFX2HVT g141(.A (i_32_b[7]), .Y (n_31));
  BUFX2HVT g125(.A (i_32_b[11]), .Y (n_35));
  BUFX2HVT g142(.A (i_32_b[13]), .Y (n_37));
  BUFX2HVT g138(.A (i_32_a[20]), .Y (n_68));
  BUFX2HVT g110(.A (i_32_a[6]), .Y (n_54));
  BUFX2HVT g109(.A (i_32_a[1]), .Y (n_49));
  BUFX2HVT g93(.A (i_32_b[0]), .Y (n_24));
  BUFX2HVT g111(.A (i_32_b[15]), .Y (n_39));
  BUFX2HVT g132(.A (i_32_a[15]), .Y (n_63));
  BUFX2HVT g143(.A (i_32_b[20]), .Y (n_44));
  BUFX2HVT g104(.A (i_32_a[7]), .Y (n_55));
  BUFX2HVT g102(.A (i_32_a[19]), .Y (n_67));
  BUFX2HVT g113(.A (i_32_b[26]), .Y (n_77));
  BUFX2HVT g121(.A (i_32_b[23]), .Y (n_74));
  BUFX2HVT g115(.A (i_32_a[29]), .Y (n_88));
  BUFX2HVT g112(.A (i_32_b[25]), .Y (n_76));
  BUFX2HVT g118(.A (i_add_sub), .Y (n_72));
  BUFX2HVT g120(.A (i_32_a[23]), .Y (n_82));
  BUFX2HVT g117(.A (i_32_a[30]), .Y (n_89));
  BUFX2HVT g153(.A (i_32_b[30]), .Y (n_81));
  BUFX2HVT g114(.A (i_32_a[31]), .Y (n_71));
  BUFX2HVT g152(.A (i_32_b[27]), .Y (n_78));
  BUFX2HVT g150(.A (i_32_b[24]), .Y (n_75));
  CLKMX2X6HVT g261(.A (MAN_RND_man[22]), .B (PSC_sel_man[0]), .S0
       (PSC_sel_man[1]), .Y (o_32_s[22]));
  AND2X1HVT g262(.A (n_0), .B (MAN_RND_man[15]), .Y (n_22));
  AND2X1HVT g263(.A (n_0), .B (MAN_RND_man[16]), .Y (n_21));
  AND2X1HVT g264(.A (n_0), .B (MAN_RND_man[8]), .Y (n_20));
  AND2X1HVT g265(.A (n_0), .B (MAN_RND_man[1]), .Y (n_19));
  AND2X1HVT g266(.A (n_0), .B (MAN_RND_man[7]), .Y (n_18));
  AND2X1HVT g267(.A (n_0), .B (MAN_RND_man[20]), .Y (n_17));
  AND2X1HVT g268(.A (n_0), .B (MAN_RND_man[6]), .Y (n_16));
  AND2X1HVT g269(.A (n_0), .B (MAN_RND_man[5]), .Y (n_15));
  AND2X1HVT g270(.A (n_0), .B (MAN_RND_man[14]), .Y (n_14));
  AND2X1HVT g271(.A (n_0), .B (MAN_RND_man[4]), .Y (n_13));
  AND2X1HVT g272(.A (n_0), .B (MAN_RND_man[3]), .Y (n_12));
  AND2X1HVT g273(.A (n_0), .B (MAN_RND_man[12]), .Y (n_11));
  AND2X1HVT g274(.A (n_0), .B (MAN_RND_man[2]), .Y (n_10));
  AND2X1HVT g275(.A (n_0), .B (MAN_RND_man[13]), .Y (n_9));
  AND2X1HVT g276(.A (n_0), .B (MAN_RND_man[21]), .Y (n_8));
  AND2X1HVT g277(.A (n_0), .B (MAN_RND_man[18]), .Y (n_7));
  AND2X1HVT g278(.A (n_0), .B (MAN_RND_man[19]), .Y (n_6));
  AND2X1HVT g279(.A (n_0), .B (MAN_RND_man[0]), .Y (n_5));
  AND2X1HVT g280(.A (n_0), .B (MAN_RND_man[11]), .Y (n_4));
  AND2X1HVT g281(.A (n_0), .B (MAN_RND_man[17]), .Y (n_3));
  AND2X1HVT g282(.A (n_0), .B (MAN_RND_man[10]), .Y (n_2));
  AND2X1HVT g283(.A (n_0), .B (MAN_RND_man[9]), .Y (n_1));
  INVX2HVT g284(.A (PSC_sel_man[1]), .Y (n_0));
  BUFX6HVT drc_bufs(.A (n_22), .Y (o_32_s[15]));
  BUFX6HVT drc_bufs285(.A (n_1), .Y (o_32_s[9]));
  BUFX6HVT drc_bufs286(.A (n_2), .Y (o_32_s[10]));
  BUFX6HVT drc_bufs287(.A (n_3), .Y (o_32_s[17]));
  BUFX6HVT drc_bufs288(.A (n_4), .Y (o_32_s[11]));
  BUFX6HVT drc_bufs289(.A (n_5), .Y (o_32_s[0]));
  BUFX6HVT drc_bufs290(.A (n_6), .Y (o_32_s[19]));
  BUFX6HVT drc_bufs291(.A (n_7), .Y (o_32_s[18]));
  BUFX6HVT drc_bufs292(.A (n_8), .Y (o_32_s[21]));
  BUFX6HVT drc_bufs293(.A (n_9), .Y (o_32_s[13]));
  BUFX6HVT drc_bufs294(.A (n_10), .Y (o_32_s[2]));
  BUFX6HVT drc_bufs295(.A (n_11), .Y (o_32_s[12]));
  BUFX6HVT drc_bufs296(.A (n_12), .Y (o_32_s[3]));
  BUFX6HVT drc_bufs297(.A (n_13), .Y (o_32_s[4]));
  BUFX6HVT drc_bufs298(.A (n_14), .Y (o_32_s[14]));
  BUFX6HVT drc_bufs299(.A (n_15), .Y (o_32_s[5]));
  BUFX6HVT drc_bufs300(.A (n_16), .Y (o_32_s[6]));
  BUFX6HVT drc_bufs301(.A (n_17), .Y (o_32_s[20]));
  BUFX6HVT drc_bufs302(.A (n_18), .Y (o_32_s[7]));
  BUFX6HVT drc_bufs303(.A (n_19), .Y (o_32_s[1]));
  BUFX6HVT drc_bufs304(.A (n_20), .Y (o_32_s[8]));
  BUFX6HVT drc_bufs305(.A (n_21), .Y (o_32_s[16]));
  OR2XLHVT g89(.A (EXP_COMP_o_compare), .B (MAN_COM_o_compare), .Y
       (n_92));
  OR2X6HVT g306(.A (MAN_ALU_ov_flag), .B (MAN_RND_ov_flag), .Y
       (o_ov_flag));
  OR2X6HVT g307(.A (PSC_sel_exp), .B (EXP_RND_exp[4]), .Y (o_32_s[27]));
  OR2X6HVT g308(.A (PSC_sel_exp), .B (EXP_RND_exp[6]), .Y (o_32_s[29]));
  OR2X6HVT g309(.A (PSC_sel_exp), .B (EXP_RND_exp[7]), .Y (o_32_s[30]));
  OR2X6HVT g310(.A (PSC_sel_exp), .B (EXP_RND_exp[0]), .Y (o_32_s[23]));
  OR2X6HVT g311(.A (PSC_sel_exp), .B (EXP_RND_exp[2]), .Y (o_32_s[25]));
  OR2X6HVT g312(.A (PSC_sel_exp), .B (EXP_RND_exp[5]), .Y (o_32_s[28]));
  OR2X6HVT g313(.A (PSC_sel_exp), .B (EXP_RND_exp[3]), .Y (o_32_s[26]));
  OR2X6HVT g314(.A (PSC_sel_exp), .B (EXP_RND_exp[1]), .Y (o_32_s[24]));
endmodule

