/home/noname/Documents/project_tiny/Floating_point/Temp_Code/03_verif/Topmodule/tb_FPU_unit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/FPU_unit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/CLA_4bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/CLA_8bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/CLA_28bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/COMP_2bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/COMP_4bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/COMP_8bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/COMP_28bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/EXP_adjust.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/EXP_sub.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/EXP_swap.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/LOPD_4bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/LOPD_8bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/LOPD_16bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/LOPD_24bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/MAN_ALU.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/MAN_swap.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/NORMALIZATION_unit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/ROUNDING_unit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/SHF_left_28bit.sv
/home/noname/Documents/project_tiny/Floating_point/Temp_Code/02_rtl/SHF_right_28bit.sv